### ISSUE TITLE
Associating multiple public keys to one listener socket in CurveZMQ

### ISSUE THREAD

**Issue by lovesh** [zeromq/pyzmq#1007]
Right now while using CurveZMQ, client needs to know the server public key and server can have only one public key.
Sample server code
```
listener = ctx.socket(zmq.ROUTER)
publicServer, secretServer = get_keys()
listener.curve_secretkey = secretServer
listener.curve_publickey = publicServer
listener.curve_server = True
```

Sample client code
```
sock = context.socket(DEALER)
sock.curve_publickey = localPubKey
sock.curve_secretkey = localSecKey
sock.curve_serverkey = publicServer
```

But what if we needed the server to have a unique public key for each client, i know it does not make sense in a client server pattern, but consider a peer to peer communication where peers have pairwise connection and each peer has a unique keypair for another peer, now we can have multiple listeners for each keypair (peer) but that restricts to 64K (since each listener binds to one port). Does CurveZMQ have a hook that i can use to check for the public key for any peer connection, its like plugging in a keystore in CurveZMQ. Thanks

**Comment by minrk** [comment]
Closing some old inactive issues. Since this is a question about libzmq behavior, it is not on the right repo. Feel free to open questions about Curve behavior on libzmq.
