### ISSUE TITLE
Invalid argument (bundled/zeromq/src/zmq.cpp:762)

### ISSUE THREAD

**Issue by f1401martin** [zeromq/pyzmq#1008]
I am experiencing crashes when the system's date/time is set back in time, we have a device that has 'sleep mode' and when it goes to sleep it loses the current time so when it wakes up it syncs from the real time clock, if the clock has an old setting, like year 2000, zmq/pyzmq crashes.

This can be reproduced on a mac by simply setting the date back in time (for example: sudo date 123122432000.55) when the script below is running (the crash doesn't happen 100% of the time but it does happen quite often so after a few tries it will show up)

This script contains minimal modifications from original downloaded from: https://gist.github.com/minrk/4667957

Environment:
>>> sys.version
'3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21) \n[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'
>>> zmq.zmq_version()
'4.1.6'
>>> zmq.pyzmq_version()
'16.0.2'

```python
"""
An XPUB/XSUB broker that forwards subscriptions

"""
import time
from threading import Thread, Event
from datetime import datetime

import zmq

xpub_url = "tcp://127.0.0.1:5555"
xsub_url = "tcp://127.0.0.1:5556"

def broker(ctx, end_event):
    xpub = ctx.socket(zmq.XPUB)
    xpub.bind(xpub_url)
    xsub = ctx.socket(zmq.XSUB)
    xsub.bind(xsub_url)

    poller = zmq.Poller()
    poller.register(xpub, zmq.POLLIN)
    poller.register(xsub, zmq.POLLIN)
    while not end_event.is_set():
        events = dict(poller.poll(10))
        if xpub in events:
            message = xpub.recv_string()
            print("[BROKER] subscription message: %r" % message[0])
            xsub.send_string(message)
        if xsub in events:
            message = xsub.recv_string()
            print("[BROKER] publishing message: %r" % message)
            xpub.send_string(message)
    xpub.close()
    xsub.close()
    print("EXIT broker")

MSG_COUNT = 1000


def publisher(ctx, end_event):
    pub = ctx.socket(zmq.PUB)
    pub.connect(xsub_url)
    for n in range(MSG_COUNT):
        time.sleep(1)
        message = "1-Update! >> {0}".format(datetime.now())
        pub.send_string(message)
    print("EXIT publisher")
    pub.close()
    time.sleep(0.1)
    end_event.set()


def subscriber(ctx, _):
    sub = ctx.socket(zmq.SUB)
    sub.connect(xpub_url)
    sub.setsockopt_string(zmq.SUBSCRIBE, '')
    msg_index = 0
    while True:
        message = sub.recv_string()
        print("Subscriber received message: {0}".format(message))
        msg_index += 1
        if msg_index == MSG_COUNT:
            break
    sub.close()
    print("EXIT subscriber")

if __name__ == '__main__':
    ctx = zmq.Context()
    end_event = Event()
    threads = [Thread(target=f, args=(ctx, end_event,))
               for f in (broker, publisher, subscriber)]
    [t.start() for t in threads]
    while not end_event.is_set():
        try:
            time.sleep(1)
        except KeyboardInterrupt:
            break
    time.sleep(0.2)
    print("terminating")
    ctx.term()
    print("terminated")
    [t.join() for t in threads]
```

**Comment by minrk** [comment]
If it's raising an assert in zmq.cpp, that generally means there is a bug in libzmq, and not something pyzmq can do anything about. [Here's the relevant code](https://github.com/zeromq/zeromq4-1/blob/v4.1.6/src/zmq.cpp#L762). Looking at it, I'm guessing it has to do with the `now` and `end` markers being confused by the time change, but it could also be something a bit lower level.

**Comment by f1401martin** [comment]
I agree this is a libzmq issue, the following issue (https://github.com/zeromq/libzmq/issues/2555) has been created.
