### ISSUE TITLE
DelayedCallback cannot be stopped

### ISSUE THREAD

**Issue by jferguson-gnubio** [zeromq/pyzmq#1010]
I know it's marked as deprecated for some reason, but nevertheless I think the fix is easy (?).

`DelayedCallback.start()` calls `add_timeout`, but doesn't set `self._timeout` with the result, so when you call `stop()` nothing is done, and your callback still happens.  I suspect that just assigning the result to `self._timeout` should fix it.

As a side note, I'm not sure why it should be deprecated - there's logic in there that's useful - it seems worth having to me.  Just using add_timeout is not enough and I'd just end up having to recreate much of what it does.

**Comment by minrk** [comment]
DelayedCallback is redundant with methods on IOLoop such as `call_later`, etc.:

```python
# call after a given delay
handle = loop.call_later(seconds_from_now, callback)
# cancel the callback for some reason
loop.remove_timeout(handle)
```

Is there other functionality that you are getting from the deprecated objects?

**Comment by jferguson-gnubio** [comment]
On reflection, there is very little useful functionality in there.  In the end, in our codebase, I just wrote our own, since we only use start() and stop().

But if it still exists I think it should work.  Right now if you call `stop()`, the callback will still happen.

**Comment by minrk** [comment]
Closing stale issue as DelayedCallback has been deprecated for ages and won't get any new features or fixes.
