### ISSUE TITLE
install pyzmq offline?

### ISSUE THREAD

**Issue by u1550** [zeromq/pyzmq#1012]
We are using an installer package (Inno Setup) for Windows containing Python 3.4 and some Python packages to provide all necessary programs for an offline installation on Windows systems that do not have a connection to the internet.
Now I need to include PyZmq.
I tried the suggested "pip install --wheel pyzmq", but, I did not figure out how to run it without internet access.
Is there any offline way to install PyZmq without using internet or compilers?

**Comment by minrk** [comment]
> Is there any offline way to install PyZmq without using internet or compilers?

Yes, it should be the same for pyzmq as any other Python package:

1. download the pyzmq wheel
2. move the wheel to the machine
3. `pip install /path/to/pyzmq.whl`

The best way I've found to do offline installation for Python packages is to make a `requirements.txt`, then do:

    pip wheel -r requirements.txt

This will download (and build if necessary) wheels for your packages and all of their dependencies in the current directory. Then you can relocate the wheels to your target machine, and install those wheels:

    pip install --no-index -f . -r requirements.txt

**Comment by u1550** [comment]
Thank you for your advice. It simplifies my scripts a lot.
My core problem was that I had a pip version 7.1.2 which was not able to process the format of the pyzmq-16.0.2 wheel but wanted to get some version data from the net. The messages were a bit confusing to me. Using pip 9.0.1 solved this problem ..
