### ISSUE TITLE
Cannot install pyzmq on Solaris

### ISSUE THREAD

**Issue by ksalman** [zeromq/pyzmq#1014]
I am trying to build pyzmq on Solaris (specifically OmniOS) but I am running into issues. I have tried to install it via pip
https://gist.github.com/ksalman/1228100eec753e2352a257ea27f578a3#file-pip-install-pyzmq

And I have also tried downloading the tarball and doing ```python setup.py install```
https://gist.github.com/ksalman/1228100eec753e2352a257ea27f578a3#file-python-setup-install

Any idea how I can build it? The pip version is 9.0.1 and the Python version is 2.7.11
```
root@testzone:/root/pyzmq-16.0.2# /opt/csw/bin/python -V
Python 2.7.11
root@testzone:/root/pyzmq-16.0.2# /opt/csw/bin/pip -V
pip 9.0.1 from /opt/csw/lib/python2.7/site-packages (python 2.7)
```

**Comment by erespaulo** [comment]
I am having the same issue, Any updates?
