### ISSUE TITLE
PAIR socket never becomes readable

### ISSUE THREAD

**Issue by lab313ru** [zeromq/pyzmq#1016]
```
poller = zmq.Poller()
poller.register(sock, zmq.POLLIN)

socks = dict(poller.poll(1000))

if sock not in socks:
  return False

return True
```
Data that was sended at this socket (successfully sended) never becomes readable at this socket.

Both bind and connect parts are using PAIR type and connected at the same ports.

But other part receives messages. So, maybe problem is that PAIR is one way connection?
I'm using C and Python connection.

**Comment by minrk** [comment]
Do you have a complete example that reproduces the issue?

**Comment by lab313ru** [comment]
Not yet publicly available, but I'll make it for you.

For now you may test such situation:
C side: Two pair sockets, different ports, the same context
Python side: Two pair sockets, the same ports as in C part, the same context.

One C socket waits for input messages, and other socket sends requests to the Python side, and waits for response. Both in different threads.

At the Python part the second socket waits for input messages, and depending on received data, responses to the first or to the second socket. One thread is used here.

**Comment by lab313ru** [comment]
Addition: Before waiting for input messages at the python side at the second socket, my example sends packet to the first C socket. Then in response the second C thread sends request to the second Python socket.
Problem is that everything works only with the first socket. Python successfully sends the data at the first socket, but data never becomes readable at the second socket at the Python side.

The same situation successfuly works with two C parts.

**Comment by minrk** [comment]
Closing old issues. Since this is a question about libzmq socket behavior, it can be reopened on the libzmq repo if it's still an issue.
