### ISSUE TITLE
why pyzmq don't have ZMQ_TCP_MAXRT?

### ISSUE THREAD

**Issue by xiaoanyunfei** [zeromq/pyzmq#1017]
when I use zmq.PUB send message to 12000 clients, there are always more than 1000 clients  failed.
then the server retry to send message to the failed clients automatically after about 120 seconds.
after repeating about three times , the failed client will also receive the message.

I want to shorten the retry time (120s), and I find ZMQ_TCP_MAXRT in libzmq, but pyzmq doesn't have

**Comment by guidog** [comment]
One reason could be: "On OSes where it is supported, sets ..."  (from http://api.zeromq.org/4-2:zmq-setsockopt)
Btw, this option is for the underlying TCP stack only, it has nothing to do w/ PUB sockets.

**Comment by minrk** [comment]
This was added in b8fde41d
