### ISSUE TITLE
Trouble with zmq.REP and zmq.REQ

### ISSUE THREAD

**Issue by Iflier** [zeromq/pyzmq#1019]
Hi, I am newer to pyzmq, the version of pyzmq I use is : 
![default](https://cloud.githubusercontent.com/assets/19361364/26586653/6b102c52-4582-11e7-82c8-0ebd5258aa06.PNG)
Today, when I try to do this: 
![default](https://cloud.githubusercontent.com/assets/19361364/26586890/370f9e78-4583-11e7-9a5e-6cd739b73176.PNG)
Something bad has happened.
I guess, it's wrong to create two sockets in just one Python script. 
Welcome to any helpful suggestions. Thank you first.

**Comment by guidog** [comment]
Given the error message I'd say you're doomed...

**Comment by minrk** [comment]
There's nothing wrong in the code you've presented, but it's also incomplete. Can you provide more detail about what you expect and what you see instead?

**Comment by Iflier** [comment]
@minrk ,Hi, thanks for you reply. In fact, I want to create 2 sockets with type of zmq.REP in one Python script, and another 2 Python script connect to this script with socket type of zmq.REQ.

**Comment by Iflier** [comment]
And, the result seems to be waiting forever, I got nothing from the zmq.REQ.

**Comment by minrk** [comment]
It's definitely fine to have multiple sockets in one process, and talking to them from req sockets in other processes is also fine. You probably want to only have one context in the process, though.

**Comment by Iflier** [comment]
The content of Relay.py as below:

[Relay.txt](https://github.com/zeromq/pyzmq/files/1039134/Relay.txt)

**Comment by Iflier** [comment]
@minrk , thanks, First, I have a try to use one zmq.Context() ,and bind to 2 port, but I think the last binded port may cover the former port, so I give up the idea.

**Comment by minrk** [comment]
You may still want to have two sockets. Each socket can bind to one or more ports. Subsequent binds do not replace previous ones. The contexts aren't related to ports. With REQ/REP, you need to be careful that every send is followed by a recv and vice versa. That's the main source of hangs in such things.

**Comment by Iflier** [comment]
Thank you, now, I will have a try to use 2 ports bind to one zmq.Context(). Thanks again.

**Comment by Iflier** [comment]
@minrk , Hi, now I have a question: does there any way can know the data I received from which one port?

**Comment by minrk** [comment]
> does there any way can know the data I received from which one port?

Are you using one socket on two ports, or two sockets each with one port?

**Comment by Iflier** [comment]
Sorry, I'm late. Duration of test, I use one socket on two ports.

**Comment by Iflier** [comment]
May I ask one more question, does there any difference between zmq.REQ/zmqREP and zmq.PAIR/zmq.PAIR  pattern?

**Comment by minrk** [comment]
REQ/REP enforce a lock-step send/recv/send/recv order. PAIR sockets have different restrictions: that only one connection is ever made per socket, but do not have send/recv order restrictions.

**Comment by Iflier** [comment]
Thanks, I think that I have understood your instruction. That is to say, In the PAIR/PAIR pattern, Only allow one to one, but there is no restriction on send/recv, one of them can send/recv many times. But, speaking of here, I have a question: in the PAIR/PAIR pattern,  there is still a constraint that the number of times accepted is equal to the number of times sent?Thank you first.

**Comment by Iflier** [comment]
The two scripts confused me: 
[pairclient.txt](https://github.com/zeromq/pyzmq/files/1043336/pairclient.txt)
[pairserver.txt](https://github.com/zeromq/pyzmq/files/1043337/pairserver.txt)
