### ISSUE TITLE
Why are zeroMQ IPC sockets slower than TCP loopback? 

### ISSUE THREAD

**Issue by snehamj** [zeromq/pyzmq#1022]
I performed the same test with same data size and same number of messages once with IPC endpoint and once with TCP loopback address and I saw a significant difference in the time for the data transport. 
1) Isn't TCP supposed to be slower because of the network stack? 
2) Does this have to do with pyzmq library?

**Comment by minrk** [comment]
1. not necessarily; loopback's pretty quick. It may depend on the message pattern.
2. probably not, but you can try a simple example in C. pyzmq doesn't have any logic related to the underlying libzmq transport for a given socket.
