### ISSUE TITLE
.unbind() not working = zmq.error.ZMQError: No such file or directory

### ISSUE THREAD

**Issue by franciscogmm** [zeromq/pyzmq#1025]
So, I'm trying to minimize the number of open ports as it's pretty bad for port management. I tried .unbind(address) on an open socket. Doing so is giving me an error of:

>  File "zmq_distributed_agents.py", line 77, in to_connect
    socket_pull.unbind('tcp://127.0.0.1:%s' % self.my_port) ### CHECKPOINT -- UNBIND NOT WORKING
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.unbind (zmq/backend/cython/socket.c:6290)
zmq.error.ZMQError: No such file or directory

I am not sure what's wrong. I'm running it using the python binding with versions:

> >>> print("Current libzmq version is %s" % zmq.zmq_version())
Current libzmq version is 4.1.6
>>> print("Current  pyzmq version is %s" % zmq.__version__)
Current  pyzmq version is 16.0.2

Hope you guys can help me out. thanks!

**Comment by minrk** [comment]
unbind will raise this error if the given socket is not bound on the given URL, such as if you call `unbind` with the wrong port or more than once:

```python
import zmq
ctx = zmq.Context()
s = ctx.socket(zmq.PUB)
url = 'tcp://127.0.0.1:5555'
s.bind(url)

s.unbind(url) # ok
s.unbind(url) # raises No such file...
```

**Comment by franciscogmm** [comment]
Good point.

If I bind to 'tcp://*:5555', what would be the unbind url?

Also, I found a way around this... not the most elegant ways, but it solved. What I did was I recreated the socket.

Initial socket:
> self.socket = zmq.Context().socket(zmq.PULL)
		self.socket.bind('tcp://*:%s' % self.my_port)

Unbind and rebind workaround:
> #repurpose socket to REP-REQ pattern
					self.socket = zmq.Context().socket(zmq.REP)
					self.socket.bind('tcp://*:%s' % self.my_port)

**Comment by bluca** [comment]
The last_endpoint socket option can be used to retrieve the actual endpoint when using wildcards
