### ISSUE TITLE
Documentation mismatch

### ISSUE THREAD

**Issue by oplatek** [zeromq/pyzmq#1027]
Hey,
I am exited by the new feature from MR https://github.com/zeromq/pyzmq/pull/1021
documented at https://pyzmq.readthedocs.io/en/latest/eventloop.html.

I installed the zmq via `pip3 install --no-cache-dir --install-option="--zmq=bundled" git+git://github.com/zeromq/pyzmq.git@702bb4168378b92a13b811f97b7bc1023fa5a362` (installing the commit of the MR)

The problem is that the version after importing is `16.1.0.dev`, but the documentation claims that one needs `17` and above to make it work.

I have following questions:
1) Will the code from master work without `zmq.asyncio.install()` ?
2) Can you please clarify the documentation?

Thank you

Ondra

**Comment by minrk** [comment]
You are on the right track, I just hadn't bumped the version string to 17 yet, but I just did in 2f077f7. It should work in master, please let me know if it doesn't.

**Comment by oplatek** [comment]
Now I get the right version 17.0.0.dev.

However, I hit annother issue #1028 
I think we can close this issue right now and continue in #1028
