### ISSUE TITLE
pub / sub vs. connect / bind unexpected behavior

### ISSUE THREAD

**Issue by FirefoxMetzger** [zeromq/pyzmq#1031]
I've read online multiple times now, that when setting up a PUB/SUB connection, the PUB should BIND and the SUB should CONNECT.

I tested the 4 cases: 
1) [PUB + connect - then - SUB + bind](https://gist.github.com/FirefoxMetzger/6d957681096a793b9e2cbc3acd1d6490)
2) [PUB + bind - then - SUB + connect](https://gist.github.com/FirefoxMetzger/c65c31a25889ff7e753cf53dae70954b)
3) [SUB + connect - then - PUB + bind](https://gist.github.com/FirefoxMetzger/8026d2d9b5ec97ef7f39844814d7ed06)
4) [SUB + bind - then - PUB + connect](https://gist.github.com/FirefoxMetzger/6910980f286e760e123f6fd531a041e0)

And case 1) - 3) deliver the messages as expected.

However, case 4) does not; instead the subscriber didn't receive anything. What is a bit unexpected, is that this [can be fixed](https://gist.github.com/FirefoxMetzger/883501b05120069f5fb6eb51ca012942) by adding a random `poller.poll()` before the messages are sent. The poll has to happen _before_ the publisher sends messages and _after_ the publisher has connected for this to work.

For me this is unexpected, but maybe someone more experienced has an explanation?
Also, I am not sure if this is pyzmq only or something related to libzmq.

**Comment by minrk** [comment]
This is a libzmq issue. It will work but it takes some time for subscriptions to propagate, which takes longer in that case. It's relatively rare that PUB sockets should connect, though. Usually PUSH/PULL is more likely to do what you want if you find your self calling connect on a PUB socket.
