### ISSUE TITLE
Resource temporarily unavailable (src/signaler.cpp:301)

### ISSUE THREAD

**Issue by JMurph2015** [zeromq/pyzmq#1033]
For some reason I consistently get an error using PyZMQ with the only error description being
``` shell
Resource temporarily unavailable (src/signaler.cpp:301)
```
What doesn't appear to be consistent is the time at which it happens in my program.  I'm using ZMQ in a Tornado app and PyZMQ is interfacing to Jupyter kernels.  The sockets are getting opened and closed in response to new websocket connections being opened and closed on my frontend.  Sometimes it gets through hundreds of requests and multiple startups and shutdowns and other times it will be like the second request or the first connect-disconnect lifecycle.

Anyone got an idea what I should be looking for?  (I'm not too familiar with ZMQ, so when I looked at that source file, it might as well have been gibberish)

Some useful details:
I'm using the zmq.eventloop.future variety of sockets, PyZMQ 16.0.2, and I am doing the:
``` python
import zmq.eventloop.ioloop
zmq.eventloop.ioloop.install()
```
rigamarole at the beginning of my files involving IOLoops.  Any help would be appreciated because these crashes are just sniping my app (not like I can catch C++ errors in Python?).

**Comment by JMurph2015** [comment]
Also another useful piece of info, I'm developing on macOS, and it happens both when I run it natively and when I'm running it in an Ubuntu docker image.

**Comment by JMurph2015** [comment]
Bump?  I wish I had more info, but that's all ZMQ/PyZMQ is giving me.

**Comment by JMurph2015** [comment]
Update, I think I fixed it for the most part.  I had needed to modify the jupyter_client.session to use eventloop sockets, and it took some tinkering to get things right.  

Essentially they were using zmq.NO_BLOCK by default and catching EAGIN's, but when used on a eventloop socket, that overwhelms the whole eventloop with the phony return value (because it is returning instantly).

My first solution was to take out that whole section of code and replace it with a default socket.recv_multipart call and it worked, most of the time, except when EAGIN's were sent.

Therefore the end solution was to use default options on the recv_multipart, but still try-except for EAGIN's.  This seems to work much better (can't say perfectly yet, not enough testing).

**Comment by ocehugo** [comment]
Hi @JMurph2015 ,

I'm finding the same problem with jupyter-console v5.1.0, python3.6.2, in OSX and running the console within a screen session.

I notice having this problem after typing import commands and requesting completions (with tab).
The entire session goes down the drain with ```Abort trap:6```.

Can you provide more detail on how did you solve ? Or should I report back to the console dev guys?

**Comment by JMurph2015** [comment]
Hi!
So this was a spectacularly specific problem that shouldn't have made it into any of the Jupyter mainline code.  Unless you are developing an alternative client (sounds like you're just using the console, so probably not?), I would open a new issue to track that an error like the one I made here made it into the actual Jupyter console, and reference this issue there.
Thanks,
Joseph Murphy

**Comment by ocehugo** [comment]
Yeap.
Not developing for jupyter or pyzmq, just normal use of the console. 

Thanks
