### ISSUE TITLE
zmq hang issue happen

### ISSUE THREAD

**Issue by hellonzx** [zeromq/pyzmq#1035]
Issue description: 
zmq/pyzmq hang in self.socket.recv() sometime, but this hung issue is not 100% reproduce, about 1% or more less. 

Environment: 
python version: 2.7.9
zmq version: 4.1.6
pyzmq version: 16.0.2

Backtrace: 
  File "/usr/lib/python2.7/site-packages/cli/debug_cli/debug_cli.py", line 221, in get_reg_dump_from_luoyang
    rsp = self.cli.hal_ipc.recvMsg()
  File "/usr/lib/python2.7/site-packages/cli/cmd_ios/cli_hal_ipc.py", line 167, in recvMsg
    bin = self.pullSock.recv()
  File "/usr/lib/python2.7/site-packages/rpd/hal/src/transport/HalTransport.py", line 187, in recv
    return self.socket.recv()
  File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
  File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9621)
KeyboardInterrupt

**Comment by hellonzx** [comment]
more information, for I already upgrade my pyzmq to 16.0.2,  which means that below overflow workarround  was already included in my code. but this issue seems still. 
https://github.com/jupyter/jupyter_console/issues/33

**Comment by minrk** [comment]
recv will block until a message is delivered. If recv is hanging, that probably means that a message is not being delivered. What socket types are you using, what transport, etc.?

**Comment by hellonzx** [comment]
@minrk  
kindly please check: 
contex = zmq.Context()

if mode == HalServerMode:   #in server mode
                self.socket = self.context.socket(zmq.REP) 
                self.binds()
else:       #in client mode
                self.socket = self.context.socket(zmq.REQ)
                self.connects()

#bind and connect for server and client mode
def binds(self):
        """Bind to an address."""
        self.socket.bind("ipc://" + self.path)
def connects(self):
        """Connect to an address."""
        self.socket.connect("ipc://" + self.path)

**Comment by minrk** [comment]
Thanks. There's nothing wrong with the sample, but it doesn't show any messages sending or receiving, which is presumably where the problem would be. Do you have an example that shows the problem?

**Comment by hellonzx** [comment]
@minrk 
Thanks for your quickly feedback. below is my send/recv logic. from above traceback, it should block/hung in the self.socket.recv(). 

def recv(self):
        """Receive a msg from a peer, please note that this should be a
        nonblcok peer."""
        return self.socket.recv()

 def send(self, msg):
        """Send a msg to a peer, BTW, this should be a nonblock send."""
        if msg is None or self.socket is None:
            msg = "Cannot send the msg since the msg is None, agent:%s" % self.path
            self.logger.error(msg)
            raise Exception(msg)
        self.logger.debug("agent[%s] sends a message to peer." % self.path)
        try:
            self.socket.send(msg, flags=zmq.NOBLOCK)
        except zmq.ZMQError as e:
            msg = "Got an error when trying with non-block send:" + str(e)
            self.logger.error(msg)
            import traceback
            self.logger.error(traceback.format_stack())
            HalGlobalStats.NrErrorMsgs += 1
            return False
        return True

**Comment by minrk** [comment]
`socket.recv()` will wait for a message to be available. If it's not returning, the odds are that there is no message waiting. You can use `socket.poll()` to check/wait for messages, or `recv(flags=zmq.NOBLOCK)` to raise `zmq.Again` if no message is available. If there's a problem, it's likely that a message you are expecting to send isn't sending, rather than a problem on the receiving side.

**Comment by hellonzx** [comment]
thanks @minrk. fix this issue, it's my code issue in upper application. thanks a lot.

**Comment by WangJiexin** [comment]
Hello,I also have the same issue.
How did you solve this problem?
