### ISSUE TITLE
DISH message group is a string instead of bytes

### ISSUE THREAD

**Issue by Busimus** [zeromq/pyzmq#1061]
I've been trying out RADIO-DISH pattern and noticed an inconsistency: `message.group` has a type `str` instead of usual `bytes`. At first I thought nothing of it, but it could cause an exception to arise if the group has non-decodable characters.

Reproduceable by running this code:
_bug.py:_
```python
import zmq

ctx = zmq.Context()

radio = ctx.socket(zmq.RADIO)
dish = ctx.socket(zmq.DISH)

radio.bind('inproc://radio')
dish.connect('inproc://radio')

dish.join(b'\xab')

radio.send(b'Hello', group=b'\xab')

msg = dish.recv(copy=False)

group = msg.group
```
_Output:_
```
Traceback (most recent call last):
  File "bug.py", line 17, in <module>
    group = msg.group
  File "/usr/lib/python3.6/site-packages/zmq/sugar/frame.py", line 30, in group
    return self.get('group')
  File "zmq/backend/cython/message.pyx", line 406, in zmq.backend.cython.message.Frame.get
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte
pyzmq-gc send failed: Socket operation on non-socket
```

**Comment by minrk** [comment]
The ZeroMQ API docs declare that groups are "strings" and the only other strings in the API are `zmq_msg_gets` which are already defined as UTF-8. For consistency with other string APIs in libzmq, I've updated the zmq API docs to declare that groups are also UTF-8, so non-UTF8 binary groups are invalid and thus would rightly raise.

**Comment by Busimus** [comment]
Huh.
Not sure why they decided to go with strings there, doesn't make much sense. 
I guess I can only hope that they change that before finalizing the spec.
