### ISSUE TITLE
send_pyobj deserialization 

### ISSUE THREAD

**Issue by daikaizoku** [zeromq/pyzmq#1077]
hello there,

don't know if this was mentioned in a previous issue. When checking the bindings examples, I found that for example gevents calls to send_pyobj which runs in the end: https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py#L565-L579 

send_pyobj doesn't do any checks as to what is receiving, thus allowing running untrusted code. is the user supposed to know this when calling send_pyobj? I don't see anything on the documentation that refers to that https://pyzmq.readthedocs.io/en/latest/serialization.html

**Comment by minrk** [comment]
Yup, using blind pickle isn't a good idea if untrusted peers can connect to your sockets and send you messages. A note about it in the docs would be appropriate.

To be clear, `send_pyobj` is perfectly safe. Only `recv_pyobj` has the potential to be unsafe *if* untrusted messages can be delivered to your socket. This can be addressed with message signatures / etc. I feel like this is a pretty standard issue when dealing with messages on an untrusted network - make sure you validate messages before doing anything potentially unsafe with them.

Personally, I wouldn't recommend anyone use `send_pyobj` (or any `send_foo` functions) in anything other than toy examples. It's a convenience function for a trivial case, and any production deployment should be writing their own multi-frame message serialization.
