### ISSUE TITLE
Impossible to compile on Windows 10 with Visual 2015

### ISSUE THREAD

**Issue by devGitHub48** [zeromq/pyzmq#1090]
Hi!

We need to use pyZMQ with Maya 2018. The Python version is 2.7.11 but it is compiled with VS2015.
So I have been able to build libZMQ.

Here is what I have
`"C:\Program Files\Autodesk\Maya2018\bin\mayapy.exe" setup.py -q bdist_egg configure --zmq=E:\zmq\zeromq-4.2.2\zeromq-4.2.2\
warning: no files found matching 'tox.ini'
no previously-included directories found matching 'docs\build'
no previously-included directories found matching 'docs\gh-pages'
warning: no files found matching 'bundled\zeromq\COPYING'
warning: no directories found matching 'bundled\zeromq\include'
warning: no directories found matching 'bundled\zeromq\src'
warning: no directories found matching 'bundled\zeromq\tweetnacl'
warning: no files found matching 'bundled\zeromq\builds\msvc\platform.hpp'
warning: no previously-included files found matching 'bundled\zeromq\src\Makefile*'
warning: no previously-included files found matching 'bundled\zeromq\src\platform.hpp'
warning: no previously-included files found matching 'setup.cfg'
warning: no previously-included files found matching 'zmq\libzmq*'
warning: no previously-included files matching '__pycache__\*' found anywhere in distribution
warning: no previously-included files matching '.deps\*' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '.mailmap' found anywhere in distribution
warning: no previously-included files matching 'Makefile.am' found anywhere in distribution
warning: no previously-included files matching 'Makefile.in' found anywhere in distribution
{'libraries': ['libzmq'], 'extra_link_args': [], 'runtime_library_dirs': [], 'library_dirs': ['E:\\zmq\\zeromq-4.2.2\\zeromq-4.2.2\\lib'], 'include_dirs': ['E:\\zmq\\zeromq-4.2.2\\zeromq-4.2.2\\include']}
************************************************
Configure: Autodetecting ZMQ settings...
    Custom ZMQ dir:       E:\zmq\zeromq-4.2.2\zeromq-4.2.2\
vers.c
buildutils\include_win32\stdint.h(6): warning C4005: 'UINT8_MAX': macro redefinition
e:\zmq\pyzmq-17.0.0b1\buildutils\include_win32\../../../zeromq-4.2.2\zeromq-4.2.2/src/stdint.hpp(71): note: see previous definition of 'UINT8_MAX'

build\temp.win-amd64-2.7\Release\scratch\vers.exe.manifest : general error c1010070: Failed to load and parse the manifest. The system cannot find the file specified.

error: command 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64\\mt.exe' failed with exit status 31

Fatal: Falling back on bundled libzmq, but config has explicitly prohibited building the libzmq extension.`

There is the issues : #643 and #1024.
But it doesn't seem that there are fixes.
Could you help me on this big journey!

Thanks

**Comment by iamsleepy** [comment]
I've built for Maya today.

It has two issues with current setup.py

1. Should add /MANIFEST flag with link.exe
2. stdint.h is included after VS2013, include_win32 shouldn't be added.

**Comment by minrk** [comment]
This is finally fixed by the latest changes in pyzmq 22. Delvewheel can be used to bundle libzmq, if needed.
