### ISSUE TITLE
Weird poller issues

### ISSUE THREAD

**Issue by benhoff** [zeromq/pyzmq#1091]
I'm not sure if I'm not using the lib correctly, but this behavior seems goofy.
On pyzmq 16.0.2, the below code causes my CPU to peg at 100% utilization

    import zmq
    from multiprocessing import Process
    import time

    context = zmq.Context()
    poller = zmq.Poller()
    socket = context.socket(zmq.SUB)
    socket.connect('tcp://127.0.0.1:4000')
    poller.register(socket, zmq.POLLIN)
    process = Process(target=poller.poll)
    process.start()
    while True:
        time.sleep(1)

Am I thinking about this incorrectly?

**Comment by minrk** [comment]
You can't run poll in a subprocess. `socket` only exists in the parent process. When you fork the subprocess to call poll, the subprocess doesn't have a socket to poll on anymore.

What is your ultimate goal?

**Comment by benhoff** [comment]
Ultimately have the application code run in it's own event loop and have the messaging run in another event loop, with the two loops running concurrently. If that makes sense.

I amusing the poller to control the messaging loop.

**Comment by minrk** [comment]
You can run an eventloop in the other thread and signal events that way, rather than run pollers yourself:

```python
from zmq.eventloop import IOLoop, ZMQStream

def handle_recv(msg):
    """I will be called whenever a message arrives on sock"""
    print(msg)

def handle_messages(socket):
    loop = IOLoop()
    loop.make_current()
    stream = ZMQStream(socket)
    stream.on_recv(handle_recv)
    loop.start()

ctx = zmq.Context()
sock = ctx.socket(zmq.SUB)
sock.connect('tcp://127.0.0.1:4000')
sock.subscribe(b'')
message_thread = Thread(target=handle_messages, args=(sock,))
message_thread.start()

```

Since pyzmq blocking methods release the GIL, it usually makes more sense to do these things with threads than processes. Do make sure to not use a socket simultaneously in multiple threads because zmq sockets are not threadsafe. If you put a thread on an IOLoop, then *all* operations on that socket should be called on that thread.

**Comment by benhoff** [comment]
Awesome! Thanks for the lib, and thanks for taking a second to educate me about the concurrency model!
