### ISSUE TITLE
cannot exit from a wrong address

### ISSUE THREAD

**Issue by sunhubs** [zeromq/pyzmq#1096]
my core code is below:

            context = zmq.Context()
            sender = context.socket(zmq.REQ)
            sender.setsockopt(zmq.RCVTIMEO,  3000)
            sender.connect('tcp://{}:{}'.format(self.ip, self.port))
            print msg
            sender.send_string(msg)
            print "sent: %s"%msg
            resp = sender.recv_string()
            print "received: %s"%resp

but when i use a not existed ip and port compose, it will throw exception "temporary resource unavailable" (i can accept this), but the script is hanging and cannot exit.  what is the reason and how to fix it (i need to let the script exit).
By the way, i think give a ret when connect failed is best to avoid this.

**Comment by minrk** [comment]
If it hangs, it could be because a socket still exists that isn't being garbage collected. You can try closing the socket manually, e.g. by using a `try:...finally:` block.
