### ISSUE TITLE
send dirty data to zmq in c

### ISSUE THREAD

**Issue by sunhubs** [zeromq/pyzmq#1097]
my core code is below:

```python
context = zmq.Context()
sender = context.socket(zmq.REQ)
sender.setsockopt(zmq.RCVTIMEO, 3000)
sender.connect('tcp://{}:{}'.format(self.ip, self.port))
print msg
sender.send_string(msg)
print "sent: %s"%msg
resp = sender.recv_string()
print "received: %s"%resp
```

when i send a long msg "123456789abcdefg"(a sample) then send a short one "123456789" i will got a content with dirty data("123456789bcdef" as an example)in server (this is written in c/c++) . how can i solve this?

**Comment by minrk** [comment]
Can you include your C/C++ code as well? My guess is that you aren't taking the `zmq_msg_size()` info about the length of the message into account. zmq messages are binary blobs, not null-terminated strings. So if you are using things like `printf('%s')` with the implicit assumption of null-terminated strings, then re-used memory (if it started out initialized to zero) will look like it always has data from longer messages from the past. But only the first `zmq_msg_size()` bytes contain valid data, the rest is undefined.
