### ISSUE TITLE
Wheels without bundled ZeroMQ

### ISSUE THREAD

**Issue by Kentzo** [zeromq/pyzmq#1099]
I apology in advance if question is lame as I'm not familiar with manylinux and cython to the bone.

Currently pyzmq wheels for Linux are shipped with pre-built zeromq. libzmq is available for the popular distributions either from the mainstream or from custom repositories. To my understanding the convenience of manylinux is to ship only essential binaries and allow the linker to resolve dependencies. That allows system administrator to independently update libraries.

In my case pyzmq, even 17.0.0b1, is still shipped with libzmq 4.1.6 while I'd like to use 4.2.2 (no draft) due to important bug fixes. My only options are to either build my own wheels or install everything required for a manual build right where I deploy.

**Comment by minrk** [comment]
The standard practice of manylinux wheels is to bundle any DLLs in the wheels themselves.

We can't upload to PyPI a relocatable wheel that don't bundle zeromq. That wouldn't work for any users who don't have libzmq, which would miss the point of the wheels.

If you want to use a wheel that depends on your chosen external libzmq, you are going to have to build your own wheels, which you can do with `pip wheel`.
