### ISSUE TITLE
pyzmq NOBLOCK recv() quite slow due to exception overhead

### ISSUE THREAD

**Issue by egnor** [zeromq/pyzmq#1101]
Hey, when zmq.Socket.recv() (and recv_multipart(), etc) is used in non blocking mode (flags=NOBLOCK), failure to read a message results in an exception being thrown (zmq.error.Again).

This is a little funny/nonpythonic because this isn't really an error condition, it's actually a very nominal condition with non-blocking I/O.

More significantly, however, throwing that exception is quite costly. On the Raspberry Pi I'm working on, for example, it ends up taking north of one millisecond to construct that exception, populate its stack trace (which means stat()'ing the backend module, etc), and generally perform related bookkeeping -- even though I'm just going to catch & throw away that exception and return to a polling loop.

That means if I have a 10msec polling loop (as part of a control system), and it checks zmq every time through that loop, pyzmq ends up burning *over 10% of the CPU* even when no messages are actually arriving.

It would be strongly desired to have some flag in the API which would allow non-blocking receive without throwing an exception when no messages are pending. (Or, equivalently, check to see if any messages are pending without performing an actual receive, or throwing an exception.)

**Comment by minrk** [comment]
> Or, equivalently, check to see if any messages are pending without performing an actual receive, or throwing an exception.

This is what `zmq.Poller` does. Is there a reason you aren't using polling to signal when events are available?

**Comment by egnor** [comment]
I suppose I can, @minrk -- I wasn't sure Poller's return would guarantee that an entire multipart message could be read without blocking, but it looks like it does. (And at least in the common case, the exception overhead would be avoided.)

There's still the case where I want to drain all pending messages, in case I'm under heavy load, and want to handle everything from zmq before returning to the polling loop, but that's arguably a special case.

Perhaps this whole issue could be resolved by just adding a see-also to the documentation for recv() and recv_multipart() as an alternative to NOBLOCK.

**Comment by minrk** [comment]
> I wasn't sure Poller's return would guarantee that an entire multipart message

Yup, zmq messages are atomic, so a socket won't register as readable (by any means) until at least one whole multipart message is available.

You can combine a poll with flushing:

```python
poller = zmq.Poller()
poller.register(sock, zmq.POLLIN)
while True:
    # wait for an event to process
    evts = dict(poller.poll())
    if sock in evts:
        while True:
            # process all available messages
            try:
                handle(sock.recv_multipart(zmq.NOBLOCK))
            except zmq.Again:
                break
```    

But that's only going to do anything if several messages are going to arrive during the interval of processing a single message. And it's only really helpful if you have other, lower-priority processing that you want to preempt that would also happen during the poll iteration. Processing one message per poll iteration ensures fair-queuing of multiple streams, which can prevent starvation.

So I would start with the simpler poll mechanism:

```python
while True:
    # wait for an event to process
    evts = dict(poller.poll())
    if sock in evts:
        # process one waiting message
        handle(sock.recv_multipart())
```    

and see how that performs.

> Perhaps this whole issue could be resolved by just adding a see-also to the documentation for recv() and recv_multipart() as an alternative to NOBLOCK.

That's a good idea. Would you like to make a PR adding to those docstrings?

**Comment by egnor** [comment]
I'd be happy to do that. I've made a stab at a set of changes. Can you point me to some directions for rebuilding the docs (to make sure I got the syntax right)? When I "cd docs; make html" I get this:

=====
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.5

Exception occurred:
  File "/home/egnor/source/pyzmq/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
The full traceback has been saved in /tmp/sphinx-err-wegddqq6.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:58: recipe for target 'html' failed
make: *** [html] Error 1
=====

The indicated logfile has this:
=====
# Sphinx version: 1.6.5
# Python version: 3.5.2 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/config.py", line 150, in __init__
    execfile_(filename, config)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 70, in <module>
  File "/home/egnor/source/pyzmq/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/egnor/source/pyzmq/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/egnor/source/pyzmq/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/egnor/source/pyzmq/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/egnor/source/pyzmq/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/egnor/source/pyzmq/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants'
=====

I'm sure I'm doing something trivial wrong? Running "python3 setup.py build" completes successfully...

**Comment by minrk** [comment]
It needs to be `--inplace` to be importable:

    python setup.py build_ext --inplace

or you can do a full dev installation, rather than just the build step:

    pip install -e .

**Comment by egnor** [comment]
Thanks! Sent https://github.com/zeromq/pyzmq/pull/1110.
