### ISSUE TITLE
Where is the api function of zmq.STREAMER?

### ISSUE THREAD

**Issue by yutiansut** [zeromq/pyzmq#1102]
I have looked for the api documents and I didn't find it https://pyzmq.readthedocs.io/en/latest/

however , learning-0mq-with-pyzmq gives an example of ZMQ.Device:

```python
import zmq

def main():

    try:
        context = zmq.Context(1)
        # Socket facing clients
        frontend = context.socket(zmq.PULL)
        frontend.bind("tcp://*:5559")
        
        # Socket facing services
        backend = context.socket(zmq.PUSH)
        backend.bind("tcp://*:5560")

        zmq.device(zmq.STREAMER, frontend, backend)
    except Exception as e:
        print (e)
        print ("bringing down zmq device")
    finally:
        pass
        frontend.close()
        backend.close()
        context.term()

if __name__ == "__main__":
    main()
```

and it really does work, so i am curious about where the **ZMQ.STREAMER** api is

**Comment by yutiansut** [comment]
https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/devices/streamer.html

**Comment by yutiansut** [comment]
got it , cause for libzmq has updated and in pyzmq 13,the pyzmq.device api has been deprecated

**Comment by minrk** [comment]
closing some old questions, especially those about libzmq and not pyzmq
