### ISSUE TITLE
Asyncio with request response message pattern?

### ISSUE THREAD

**Issue by lnunno** [zeromq/pyzmq#1104]
I've seen the example with [PUSH/PULL with coroutines here](https://github.com/zeromq/pyzmq/blob/v16.0.2/examples/asyncio/coroutines.py) is this possible while using the REQ/REP socket types? I tried modifying the example, however it seems to retrieve the first message from the REQ socket and hang. Is this supported? And do I need to change the Poller arguments with different socket flags?

**Comment by minrk** [comment]
The push/pull example works if you switch to any other socket type, as long as the send/recv pattern is appropriate. What version of zmq are you using? Can you share your example? REQ/REP aren't generally recommended for use in production. Instead, the more general ROUTER/DEALER sockets are preferred.

**Comment by lnunno** [comment]
I'm using pyzmq 16.0.2 from Anaconda. Below is the PUSH/PULL coroutines example with REQ/REP substituted.

```
"""Example using zmq with asyncio coroutines"""
# Copyright (c) PyZMQ Developers.
# This example is in the public domain (CC-0)

import time

import zmq
from zmq.asyncio import Context, Poller, ZMQEventLoop
import asyncio

url = 'tcp://127.0.0.1:5555'

loop = ZMQEventLoop()
asyncio.set_event_loop(loop)

ctx = Context()

@asyncio.coroutine
def ping():
    """print dots to indicate idleness"""
    while True:
        yield from asyncio.sleep(0.5)
        print('.')

@asyncio.coroutine
def receiver():
    """receive messages with polling"""
    pull = ctx.socket(zmq.REP)
    pull.connect(url)
    poller = Poller()
    poller.register(pull, zmq.POLLIN)
    while True:
        events = yield from poller.poll()
        if pull in dict(events):
            print("recving", events)
            msg = yield from pull.recv_multipart()
            print('recvd', msg)

@asyncio.coroutine
def sender():
    """send a message every second"""
    tic = time.time()
    push = ctx.socket(zmq.REQ)
    push.bind(url)
    while True:
        print("sending")
        yield from push.send_multipart([str(time.time() - tic).encode('ascii')])
        yield from asyncio.sleep(1)

loop.run_until_complete(asyncio.wait([
    ping(),
    receiver(),
    sender(),
]))

```

And below is the output, which is consistent with what I'm seeing in my production code.

```
➜ python coroutines.py
sending
recving [(<zmq.asyncio.Socket object at 0x7fc538360168>, 1)]
recvd [b'0.0015082359313964844']
.
sending
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
```

**Comment by lnunno** [comment]
However, if I change the receiver socket to ROUTER and the sender socket to DEALER it appears to work. Any additional clarification DEALER/ROUTER should be used over REQ/REP? I've read the ZMQ guide and is it because ROUTER/DEALER can work asynchronously and handle multiple connections?

Also I'm unclear what the role of the Poller is in this example and if it is necessary, I read the pyzmq docs, but it wasn't clear when it should/shouldn't be used.

**Comment by minrk** [comment]
REQ/REP sockets must always follow a recv with a send and vice versa. That's why your example is hanging:

1. `push` sends a message
2. `pull` receives the message
3. `push` will not be able to send until it has received a message.

This artificial limitation is all REQ/REP do on top of ROUTER/DEALER, which is why ROUTER/DEALER are recommended in general to use instead of REQ/REP.

> Also I'm unclear what the role of the Poller is in this example and if it is necessary

It's not strictly necessary in an example this simple. It's mainly there to showing how to use a Poller with asyncio. Usually, you wouldn't use a Poller unless you have multiple sockets on which events may arrive.

**Comment by lnunno** [comment]
Thanks, that helps. I was using REQ/REP incorrectly, but I'm able to use it with asyncio now.
