### ISSUE TITLE
pyinstaller pack zmq error

### ISSUE THREAD

**Issue by friddle** [zeromq/pyzmq#1105]
https://github.com/zeromq/pyzmq/blob/master/zmq/__init__.py

when i use pyinstaller to pack my source and I found this problem.
![image](https://user-images.githubusercontent.com/2897690/32366086-9e81dbce-c04a-11e7-8eed-f9745ea42f4c.png)
And I debug I found that
``` py
    try:
        from . import libzmq
    except ImportError:
        pass
```
In pyinstaller,import error when i execute the pyinstaller executable  file.
os.getcwd() is to my execute location,not include libzmq.so。
when I change the location to the folder where include libzmq.so..I  could not import libzmq.so ethir
when I copy libzmq.so to excutable root folder and import again.
it is ok,but stranger
this is fix code
```python
     try:
        from . import libzmq
    except ImportError as e:
        #for compatiable pyinstaller runner
        import os;os.chdir(os.path.join(os.path.dirname(__file__),"../"))
        import shutil;
        if os.path.exists("./zmq/libzmq.so"): shutil.copy('./zmq/libzmq.so','./');
        import libzmq
```
please fix this problem.

other information
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
pyinstaller 3.3
Darwin sckMacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
zmq:0.0.0

**Comment by minrk** [comment]
Is the libzmq.so included in the bundle, just not loaded?

**Comment by friddle** [comment]
Thanks for answer me.
Forgive my poor english.
I try pack using Pyinstaller in Linux is ok.failed in mac

In mac folder like(I have left my mac in offices,so i draw it)
[executable_folder]
----[zmq](folder)
-----[libzmq.so]
-----[zmq](folder)
-------[backend]
-------[python]
----[zmq.backend.*]
And when I debug .it into the zmq folder to import libzmq.so.but failed



I check it in Ubuntu.libzmq.so not in sub folder
![image](https://user-images.githubusercontent.com/2897690/32403109-fc9e13f8-c16c-11e7-8c1f-79aa9995428a.png)

thanks。
