### ISSUE TITLE
timer_createmSQbdX.c:2:5: warning: implicit declaration of function ‘timer_create’

### ISSUE THREAD

**Issue by garrymar** [zeromq/pyzmq#1118]
Hello,

During update of Gentoo GNU/Linux system I caught following compiler warnings:

/var/tmp/portage/dev-python/pyzmq-16.0.2/temp/timer_createmSQbdX.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
/var/tmp/portage/dev-python/pyzmq-16.0.2/temp/timer_create7sy0jdy2.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
/var/tmp/portage/dev-python/pyzmq-16.0.2/temp/timer_createoLn3Eu.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
/var/tmp/portage/dev-python/pyzmq-16.0.2/temp/timer_createkdmjr89_.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]

Thanks.

**Comment by minrk** [comment]
Are there any errors? Does pyzmq not work?

**Comment by garrymar** [comment]
I have not noticed any errors actually. Just proactive measures.

**Comment by minrk** [comment]
OK. There are compiler checks for the availability of timer_create during build time, which is probably what these are from.
