### ISSUE TITLE
Won't run "Hello World", hangs on internal tests; built all from source

### ISSUE THREAD

**Issue by bundito** [zeromq/pyzmq#1119]
Hi all. I'm having trouble using pyzmq. Yesterday, I built the entire zmq system from source, including tracking down arcane tools like automake and autoremake. I made sure it went into /usr/local. I compiled pyzmq from the latest source and used the `--with-zmq=/usr/local` option just for good measure. Today, I'm trying to run the internal tests that come with pyzmq and it's been hung on `zmq/tests/test_pubsub.py::TestPubSubGreen::test_sigabrt_issue` for the past 15 minutes. When I try to run the simple "Hello World" program:

`import time
import zmq

context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")

while True:
    #  Wait for next request from client
    message = socket.recv()
    print("Received request: %s" % message)

    #  Do some 'work'
    time.sleep(1)

    #  Send reply back to client
    socket.send(b"World")`

I get an error that reads 'Traceback (most recent call last):
 ` File "zmq.py", line 10, in <module>
    import zmq
  File "/Users/bundito/joe/joe/zmq.py", line 13, in <module>
    context = zmq.Context()
AttributeError: module 'zmq' has no attribute 'Context'`

I'm kind of frustrated. I've got a small task (part of a larger project) that I think ZMQ would be perfect for. But I can't even run the Page One sample. 

Here are my system specs:
`Python 3.6.3 (default, Oct  4 2017, 06:09:38) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin`

It's running on a brand-new MacBook Pro on macOS High Sierra 10.13.2

Any ideas? Anything else I can provide?

Thanks.

**Comment by minrk** [comment]
When you type `import zmq`, that looks for a `zmq.py` in the current directory first, before any zmq module that is installed. If your script is called something else (but not the same name as something else imported), you should be okay.

**Comment by sbraz** [comment]
Seeing as the failing test was removed in e9000fc82ca799f6de73573b51c6b73fb519b6f3, this can probably be closed.
