### ISSUE TITLE
pyzmq >= 16.0.3 make ipyparallel unstable

### ISSUE THREAD

**Issue by cyberwillis** [zeromq/pyzmq#1120]
I just got many issues last week when I had to reinstall ubuntu in my machine and the packages again.
My previous projects and code just stopped to work, as normally and sometimes just hanged or other times made my kernel in jupyter just get restarted.
I just found out that my problem was pyzmq 17.0.0b3 in my system causing many many troubles. 
That drove me crazy for a couple days because my code was working nicely before. 
Now that i get the last stable version everything is smooth again.

**Comment by minrk** [comment]
Do you have any examples where this is the case? More version and system info, perhaps?

**Comment by cyberwillis** [comment]
Sure, here it is:
I am in Ubuntu 16.04.3 - linux image 4.11.0-14-lowlatency. And also had the opportunity to test the behaviour in docker ubuntu:16.04. In both cases the behaviour were the same.

The code start processing great and after a few parallel executions (blocking or nonblocking), the engines stops to respond to the controller and I needed to interrupt the kernel to get it back.When I was executing heavy data on the engines my kernel just died.

As I mentioned earlier now everything is fine when I switched back to pyzmq==16.0.3
But I was using python 3.5.2 and as principal packages those was involved was :
jupyter-client==5.2.0
jupyter-core=4.4.0
ipython==6.2.1
ipyparallel==6.0.2
pyzmq==17.0.0b3
notebook==5.2.2

Even using a stupid code like this is reproducible behaviour if I switch back to pyzmq=17.0.0b3
<pre>
import ipyparallel as ipp
rc = ipp.Client()

dview = rc[:]
dview.block = False

ar = dview.apply(lambda : 42)
a = ar.get(-1)
print(a)

dview.block = True
b = dview.apply(lambda : 42)
print(b)
</pre>

**Comment by cyberwillis** [comment]
Just to mention I updated the previous post with a little more information about the entire packages I have in the machine test

**Comment by cyberwillis** [comment]
I got some time to redo this tests and I cold notice that:
 in pyzmq 16.0.4 (**no problems found**)
 in pyzmq 17.0.0b3 (**the problem still there**)
 in pyzmq 17.0.0b4 (**no problems found**)

**Comment by cyberwillis** [comment]
Now my system have:

**pip freeze**:
```
ipyparallel==6.2.4
pyzmq==18.1.0 
tornado==6.0.3
```

**python --version**
```
Python 3.6.9 :: Anaconda, Inc.
```

**Comment by minrk** [comment]
both ipyparallel and pyzmq have had significant updates, especially with regard to event loop integration, so I'm going to close this optimistically because I'm guessing it's fixed. But always feel free to reopen if you have problems with current versions.
