### ISSUE TITLE
`ZMQEventLoop` does not recognize EOF with subprocess pipes (atleast on some Linux) 

### ISSUE THREAD

**Issue by SillyFreak** [zeromq/pyzmq#1124]
Code to reproduce:

    import sys
    import asyncio
    import zmq.asyncio
    
    print("libzmq-%s" % zmq.zmq_version())
    print("pyzmq-%s" % zmq.pyzmq_version())
    print("Python-%s" % sys.version)
    
    
    async def subprocess():
        proc = await asyncio.create_subprocess_exec(
            "echo", "hello",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE)
    
        proc.stdin.close()
    
        print(await proc.stdout.readline())
        print(await proc.stdout.read())
        print(await proc.stderr.read())
        print(await proc.wait())
    
    
    asyncio.set_event_loop(zmq.asyncio.ZMQEventLoop())
    asyncio.get_event_loop().run_until_complete(subprocess())

Without the `set_event_loop` line,  I get the expected output:

    libzmq-4.1.6
    pyzmq-16.0.3
    Python-3.6.2 (default, Jul 20 2017, 03:52:27) 
    [GCC 7.1.1 20170630]
    b'hello\n'
    b''
    b''
    0

With it, I get the `b'hello\n'` line. but then nothing more and the CPU is at 100%. Inspecting this, at least on my flavor on Linux `zmq_poll` returns `POLLERR` events for the pipes (because they are closed/at EOF). However, the `ZMQSelector` ignores this event, see `_zmq2aio`.

For this particular issue, treating `POLLERR` like `POLLIN` fixes it, but that might of course have other consequences.

    $ uname -a
    Linux ******** 4.9.51-1-MANJARO #1 SMP PREEMPT Wed Sep 20 10:37:40 UTC 2017 x86_64 GNU/Linux

**Comment by SillyFreak** [comment]
(just checked the master branch and saw that this has been thoroughly restructured

**Comment by minrk** [comment]
@SillyFreak you can test out the latest beta, which should have these changes, with `python3 -m pip install --pre pyzmq`. Please report any further issues if you find any!

**Comment by SillyFreak** [comment]
I have, everything works fine there!
