### ISSUE TITLE
AttributeError: '_socketobject' object has no attribute 'send_json'

### ISSUE THREAD

**Issue by dplgehgb** [zeromq/pyzmq#1130]
as titled

**Comment by minrk** [comment]
Please provide more information. Can you include the output of `pip list`, what Python version you are using, and code to reproduce the issue? `_socketobject` does not occur in the pyzmq source, so it could be an issue with code in another project.

**Comment by kkotyk** [comment]
For anyone who stumbles upon this, this issue happens when you assign the .bind() or .connect() to a variable. ex
sock = ctx.socket(...)
x = sock.connect()
x.send_json(...)
