### ISSUE TITLE
PAIR works only with one client (the very first one)

### ISSUE THREAD

**Issue by dsuch** [zeromq/pyzmq#1131]
Hello,

the behaviour that I'm observing with pyzmq 15.3.0 and 17.0.0b3 is that there can be only one client PAIR socket connecting to a socket that binds in that PAIR until the binding socket is created.

This can be seen by copy-and-pasting usage examples here:

https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pair.html

Starting first the server part (.bind) and running the client next (.connect) works as expected initially but after the client is stopped and started again, it will not receive from nor send any messages to the server part until the server is also restarted.

I changed the protocol to IPC from TCP and it was the same situation.

I understand that with PAIR there can be only one pair at a time, this is clear, but is it expected that there can be only one .connecting socket for the lifetime of the socket that .binds?

Regards.

**Comment by minrk** [comment]
I'm not sure if PAIR can be reconnected with a new client. In general, PAIR tends to be used only in local inproc communication, not inter-process with reconnects. In general, I would recommend using DEALER-DEALER connections for this (or PUSH-PULL if flow is unidirectional).
