### ISSUE TITLE
Problem with socket.recv_pyobj()

### ISSUE THREAD

**Issue by Robinbux** [zeromq/pyzmq#1136]
Hey, I'm trying to build a chatbot as a practice, but can't get the publisher running.
This is my code:

    import time
    import zmq

    context = zmq.Context()
    socket = context.socket(zmq.PUB)
    socket.bind('tcp://127.0.0.1:5555')

    while True:
    
        message = socket.recv_pyobj()
        print("%s: %s" % (message.get(1)[0], message.get(1)[1]))
        time.sleep(1)
    
        socket.send_pyobj({1:[message.get(1)[0], message.get(1)[1]]})

When I try to run it, I get the following error message:

`  File "chatserver.py", line 10, in <module>
    message = socket.recv_pyobj()
...
...
zmq.error.ZMQError: Operation not supported`

Do I use recv_pyobj() somehow wrong?

**Comment by guidog** [comment]
See http://api.zeromq.org/4-2:zmq-socket  on PUB sockets.

**Comment by Robinbux** [comment]
Hi guidog, thanks for your help.
I took those commands from this example for Publish/ Subscribe: https://gist.github.com/ramn/7061042 
If send_pyobj() and recv_pyobj() is already outdated, how would you send/receive objects now?

**Comment by guidog** [comment]
Outdated? What you're talking about?
Just read the link I posted above.
Get yourself the basics of ZMQ sockets.

**Comment by Robinbux** [comment]
Ah ok, I was just irritated, because in the example I sent to you, the send and recv functions are still used, but I just mixed publisher and subscriber. 
Ok seems like there is no way for the client to send to the pub then.
Thanks for your help :)
