### ISSUE TITLE
zmq_version() reports incorrect version

### ISSUE THREAD

**Issue by deric** [zeromq/pyzmq#1150]
On Debian 9 when I run:
```
import zmq
print("Current libzmq version is %s" % zmq.zmq_version())
print("Current  pyzmq version is %s" % zmq.pyzmq_version())
````
I get:
```
Current libzmq version is 4.1.6
Current  pyzmq version is 16.0.4
```
However, when I run `apt install libzmq5` before installing `pyzmq`, the system `libzmq5.so` library is used. `pip install pyzmq==16.0.4` correctly detects the system library and doesn't fetch new library version. While Debian bundles `libzmq` in version `4.2.1`, but `pyzmq` report library version that would be bundled in case that no `libzmq*.so*` is found.

**Comment by minrk** [comment]
zmq.zmq_version is a function call in libzmq itself, so it's very unlikely that it is reporting the incorrect version. What is probably happening is that pyzmq is not loading the libzmq you expect it to. Can you include the output from installing pyzmq? Did it fetch the public wheel? If so, it will use a bundled libzmq, which is 4.1.6. If you want to force pyzmq to recompile against your system libzmq, use:

    pip install pyzmq --install-option=--zmq=/usr/lib

**Comment by deric** [comment]
@minrk Right, thanks!

`pyzmq >= 16.0.0` fetches the wheel, while the older versions doesn't. I was doing something like this and I was surprised that the system library is not used. 
```
FROM python:3.6-slim-stretch as builder
RUN apt-get update && apt-get install --no-install-recommends -y libzmq5-dev build-essential\
 && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install pyzmq==15.4.0

FROM python:3.6-slim-stretch
ENV LANG C.UTF-8

RUN apt-get update && apt-get install --no-install-recommends -y libzmq5\
 && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/lib/python3.6/site-packages/ /usr/local/lib/python3.6/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
RUN mkdir -p /app && chown -R www-data:www-data /app
ADD test.py /app
WORKDIR /app
ENTRYPOINT ["python3", "test.py"]
```
and after upgrading to `16.0.4` the behavior changed:
```
Current libzmq version is 4.2.1
Current pyzmq version is 15.4.0
```
