### ISSUE TITLE
gevent: AssertionError: Only one greenlet can be waiting on this event

### ISSUE THREAD

**Issue by liorchen** [zeromq/pyzmq#1154]
Hi

I'm using zmq for gevent,
when I try to send multipart messages on one socket instance from multiple greenlets I sometimes get the following error:
```
AssertionError: Only one greenlet can be waiting on this event
```

What am I doing wrong? my understanding is that zmq-gevent support cross greenlet sockets.

appreciate your reply 

Lior

**Comment by minrk** [comment]
Do you have a code sample that reproduces the issue? The error should mean that multiple greenlets are waiting on the same event (e.g. concurrent calls to socket.recv), which can't be expected to work.

**Comment by liorchen** [comment]
The only thing I don't understand is if multiple greenlets per sock isn't supported by design or not. because in the function ```send``` in  code itself I see the following comment:
```send, which will only block current greenlet```
this makes me understand that this method, and the entire socket can be shared accross multiple greenlets.
In order to solve my problem I used gevet's ```Semaphore``` and it work's fine.

As for an example: well let's say I have a simple wsgi gevent based http server that just forwards requests to zmq push socket:

```
from zmq import green as zmq
from zmq.utils.monitor import recv_monitor_message
from gevent.pywsgi import WSGIServer

class WSGIServerApplication(object):

    def __init__(self, addr, target_addr):
        ip, port = addr.replace('http://', '').split(':')
        self._addr = (ip, int(port))
        self._context = zmq.context()
        self._sock = self._context.socket(zmq.PUSH)
        self._sock.connect(target_addr)
        self._monitor_sock = self._sock.get_monitor_socket(zmq.EVENT_ALL)
     
     def start_monitoring(e):
         poller = zmq.Poller()
         poller.register(monitor, zmq.POLLIN)
         while not e.is_set():
              events = dict(poller.poll(1))
              if self._monitor_sock in events:
                  mon_msg = recv_monitor_message(self._monitor_sock)
                  # do something with msg

    def handle_req(self, environ, start_response):
        req_id = req_id_generator()
        try:
            sock.send_multipart([...., ..., ....])
            start_response('200 OK', [])
            return []
        except Exception:
            logger.exception("error handling request")
            start_response('500 Internal Server Error', [])
            return []
        finally:
            logger.debug("finished request, req-id %s", req_id)


    def serve(self, e):
        s = WSGIServer(self._addr, self.handle_req)
        s.start()
        try:
            e.wait()
        finally:
            s.close()
```
and the main process initializes this class using and uses gevent's ```Group``` instance to run the ```server``` and ```start_monitoring```` as greenlets

**Comment by minrk** [comment]
Waiting on events on a single zmq socket in multiple greenlets is not supported. If it were supported in terms of there not being an error, you would still have a race as to who gets to handle the events, and the first event listener could change the state so that other event listeners that wake on the same event would get no events to process. A semaphore works because as long as you don't have multiple greenlets *waiting on events* on the same socket at the same time, you are fine.

**Comment by liorchen** [comment]
thanks for the clarification!
