### ISSUE TITLE
ZMQError: Address already in use when using with Sanic multiworker configuration

### ISSUE THREAD

**Issue by bnopne** [zeromq/pyzmq#1155]
I'm building some sort of gateway app, which should accept incoming websocket connections from client and pass this traffic to microservices via `ZeroMQ`. I built simple `Sanic` application which will use `ZeroMQ` socket along with websockets, provided by `Sanic` itself, here is my code:

```
import zmq
from sanic import Sanic
from zmq.asyncio import Context


class ServiceApp(Sanic):
    zeromq_ctx = Context.instance()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_task(self.zeromq_listener())

    async def zeromq_listener(self):
        self.service_sock = self.zeromq_ctx.socket(zmq.REP)
        self.service_sock.bind('tcp://127.0.0.1:5555')

        while True:
            msg = await self.service_sock.recv_json()
            resp = await self.handle_zeromq_message(msg)
            await self.service_sock.send_json(resp)

    async def handle_zeromq_message(self, message):
        return message 
```

I can run this app and it seems to work
```
app = ServiceApp()
app.run(workers=1)
```

But if i set multiple workers (2, 3,...), i get an `zmq.error.ZMQError: Address already in use`
It seems that each worker process tries to bind to the socket, but only the first one succeeds, other workers will fail and not going to get any traffic. So, is there a way to handle situation like this?

**Comment by minrk** [comment]
You need to make sure that you don't have multiple listeners bound do the same port. You could use a proxy that binds to one port and each worker connects to it.

**Comment by bnopne** [comment]
Should i create single `ROUTER` socket bound to external address, single `DEALER` socket, `REP` socket in each worker and then use `zmq.proxy` to connect `ROUTER` and `DEALER`?

**Comment by minrk** [comment]
that would be reasonable (I'd always use ROUTER instead of REP, but it doesn't make much difference).
