### ISSUE TITLE
Failed to compile using Solaris Studio 12.6

### ISSUE THREAD

**Issue by jurajlutter** [zeromq/pyzmq#1157]
While trying to compile 4.2.3 using Oracle Developer Studio 12.6 I am getting:

"src/ctx.cpp", line 467: Error: Could not find a match for std::map<std::string,zmq::endpoint_t>::insert(std::pair<const char*, zmq::endpoint_t>) needed in zmq::ctx_t::register_endpoint(const char*, const zmq::endpoint_t&).

and a bunch of other Notes (notices.)

Please, any known workaround for this?

Thanks.

**Comment by jurajlutter** [comment]
- OS: Solaris 11.3
- Compiler: cc: Studio 12.6 Sun C 5.15 SunOS_i386 2017/05/30
- libc and libc++ are from Solaris 11.3

**Comment by bluca** [comment]
Closing here, tracking via https://github.com/zeromq/libzmq/issues/3090

**Comment by bluca** [comment]
@jurajlutter pull libzmq from the master branch, should be all good now
