### ISSUE TITLE
`REQ_CORRELATE` and `REQ_RELAXED` don't work

### ISSUE THREAD

**Issue by mo-han** [zeromq/pyzmq#1159]
I can set these two options without error, but they don't take effects. After that, I try to get these two options but encounter Invalid arguments error.

Do I miss something or is it designed so for pyzmq? 

---

Thanks to @zpincus it turns out to be a matter of [libzmq's version](https://pyzmq.readthedocs.io/en/v17.0.0/#supported-libzmq)

**Comment by zpincus** [comment]
Testing this with the latest 17.0 release as well as 16.0.3, I find:
 - setting `REQ_CORRELATE` and`REQ_RELAXED` works fine, and the settings appear to take effect properly (e.g. with `REQ_RELAXED` I can `send` multiple requests without interleaving `recv` calls.) This works either with `socket.setsockopt(zmq.REQ_CORRELATE, True)` or `socket.REQ_CORRELATE = True`.
 - however, getting these options (via `val = socket.getsockopt(zmq.REQ_CORRELATE)` or just `val = socket.REQ_CORRELATE` raises an error.

The error raised in the former case (using `getsockopt`) is:
```
In [33]: s.getsockopt(zmq.REQ_CORRELATE)
---------------------------------------------------------------------------
ZMQError                                  Traceback (most recent call last)
<ipython-input-33-c7406ed2575f> in <module>()
----> 1 s.getsockopt(zmq.REQ_CORRELATE)

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.get()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._getsockopt()

~/miniconda/lib/python3.6/site-packages/zmq/backend/cython/checkrc.pxd in zmq.backend.cython.checkrc._check_rc()

ZMQError: Invalid argument
```
The error in the latter case (using the socket attr) is similar.

I can't find an obvious source for the error. These constants are type `int` in the ZMQ documents, and the code path in `zmq/backend/cython/socket.pyx` seems to calling `zmq_getsockopt` assuming an `int` type. Does the underlying zmq library incorrectly set an error condition? Or is `zmq.backend.cython.checkrc._check_rc` incorrectly detecting an error that isn't there? Getting other int-type socket options such as RCVTIMEO works fine, so it's not a general problem.

**Comment by mo-han** [comment]
@zpincus 
Thank you for the infomation. The `getopt` bug can be put aside, as long as these two options can be set successfully. When I do the `getopt` I set them to `1` rather than `True`, turns out they didn't take effect. I'm not sure if it's the root of the problem, and will do some tests myself, but how do you think of it?

**Comment by mo-han** [comment]
I just did another test, revealing that these two options still not working for me. pyzmq version is 17.0.0. I simply make an REQ socket, setsockopt REQ_CORRELATE and REQ_RELAXED to True, and connect. I tried one send and one recv, it's working fine. Then I send twice without recv, it stuck.

@zpincus said these two options  do take effects, but it seems the luck is not with me.

**Comment by zpincus** [comment]
@mo-han, you need to show your test code if you want help debugging it. ([Here's](https://testlio.com/blog/the-ideal-bug-report/) a good guide to writing a clear bug report.)

Below is a simple test of `REQ_RELAXED`. In my hands, it works fine.

First, run a simple REP "echo server":
```python
import zmq
c = zmq.Context()
s = c.socket(zmq.REP)
s.bind('tcp://127.0.0.1:5555')
while True:
    s.send(s.recv())
```

Second, run this REQ client, which performs an out-of-order send:
```python
import zmq
c = zmq.Context()
s = c.socket(zmq.REQ)
s.REQ_RELAXED = True
s.REQ_CORRELATE = True
s.connect('tcp://127.0.0.1:5555')

s.send(b'test1')
print(s.recv())

s.send(b'test2')
# note: no recv after this send!

s.send(b'test3')
print(s.recv())
```

Using pyzmq version 17.0.0 and libzmq version 4.2.3 (i.e. `zmq.VERSION` is `40203`), the above works fine. However, if `REQ_RELAXED` is not set (i.e. comment out that line), then an error is raised. 

How does your test code differ? Does the above test work on your system? If not, what is the libzmq version?

**Comment by mo-han** [comment]
@zpincus Tried your test code, no good, same issue.

pyzmq version 17.0.0.
libzmq version 4.1.6 (zmq.VERSION is 40106)
OS is Windows 10 LTSB 64-bit

I could't help wondering the OS matters.

**Comment by zpincus** [comment]
What's the specific error you're getting? The one about "operation could not be completed in the current state"? A stack trace might be helpful here.

One thought is that it is the version of libzmq that matters. Can you try with a newer version of libzmq? (4.1.6 was released in November 2016.) Perhaps this is the result of a bug that has been subsequently fixed. I think the version of libzmq that's linked with the pyzmq which can be pip installed is 4.2.2 or something like that. Alternately, you could try installing a separate python environment with anaconda/miniconda to test this in. I think that also ships with libzmq 4.2.2...

**Comment by mo-han** [comment]
@zpincus 
I just made a fresh virtualenv and `pip insatll pyzmq` which installed pyzmq 17.0.0 with `zmq.VERSION=40106`. It refuses to give me the new `libzmq` :(
I'm using python 3.5, does that matter?

**Comment by zpincus** [comment]
So it seems, per [the docs](https://pyzmq.readthedocs.io/en/v17.0.0/), that pyzmq 17.0.0 from PyPI (and thus pip) ships with libzmq 4.1.6. Try using anaconda / miniconda, which ships with a later libzmq. Or you could build (or download a pre-build) libzmq and build pyzmq against that (following the directions in the pyzmq readme file).

**Comment by mo-han** [comment]
@zpincus
Thank you so much for that clue. wouldn't even think about such possibility by myself.
