### ISSUE TITLE
Alternative storage and verification scheme for client Public keys with CURVE authentication 

### ISSUE THREAD

**Issue by desmoteo** [zeromq/pyzmq#1164]
Hi

I am working on a project using CURVE authentication. Clients obtain the keys at startup via HTTPS API calls, so that they are not stored permanently on remote devices.  For these reasons client keys are stored in a db and are copied to files in a credentials folder accessible to the pyzmq Authenticator. 
Every time a key is added to/removed from the db we have to modify the content of the  credentials folder accordingly and call configure_curve to update the state of the Authenticator.  

I think it would be useful to provide an alternative scheme where during ZAP authentication, a callback is called to asses the client public key validity.

I will try to provide a pull request for this.

**Comment by minrk** [comment]
That makes sense to me.

**Comment by bluca** [comment]
Isn't this what the ZAP protocol is for?

**Comment by desmoteo** [comment]
As far as I understand, the Authenticator can be configured to lookup keys in the location folder when calling configure_curve(self, domain='*', location=''). I would like to lookup public keys in a db instead of a folder.

**Comment by bluca** [comment]
Sure, what I mean is that if you wish you can setup your own authenticator using the ZAP protocol: https://rfc.zeromq.org/spec:27/ZAP

**Comment by minrk** [comment]
@bluca isn't that what this is doing? It's using ZAP. ZAP doesn't define where/how curve certificates are stored, which is why there's more than one way to implement "get me the CURVE certificates I should accept". Providing a callable makes at least as much sense to me as specifying a directory layout, which is not part of the ZAP specification, as far as I understand.

**Comment by bluca** [comment]
Yeah that's a good point, fair enough
