### ISSUE TITLE
Compile From Source Failed

### ISSUE THREAD

**Issue by larrymeng** [zeromq/pyzmq#1168]
OS: CentOS 6.2
libzmq: 4.2.5
pyzmq: 17.0.0

$ python setup.py configure --zmq=/usr/local/libzmq
...
Configure: Autodetecting ZMQ settings...
    Custom ZMQ dir:       /usr/local/libzmq
build/temp.linux-x86_64-2.7/scratch/tmp/timer_createL6ua7m.o: In function `main':
timer_createL6ua7m.c:(.text+0x15): undefined reference to `timer_create'
...
undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info'
collect2: ld 返回 1

error: command 'gcc' failed with exit status 1

**Comment by minrk** [comment]
Can you show the full output of configure and install?
