### ISSUE TITLE
Cannot get socket options REQ_CORRELATE or REQ_RELAXED

### ISSUE THREAD

**Issue by zpincus** [zeromq/pyzmq#1176]
**Description**: Getting the socket options `REQ_CORRELATE` or `REQ_RELAXED` fails. Setting these options works fine. Getting other int-valued options works fine too.

**Configuration**: I verified the error with pyzmq 17.0.0 and 16.0.3, linked against either libzmq 4.2.3 or a build of the git master. This is on OS X 10.12.6.

**Test code**:
```python
import zmq
c = zmq.Context()
s = c.socket(zmq.REQ)

# both of the below error out.
# note: setting REQ_RELAXED first doesn't help
s.getsockopt(zmq.REQ_RELAXED)
s.REQ_RELAXED
```

**Expected result**: `False` should be returned for the REQ_RELAXED option.

**Actual result**: For`s.getsockopt(zmq.REQ_RELAXED)`, an exception is raised thus:
 ```python
>>> s.getsockopt(zmq.REQ_CORRELATE)
ZMQError                                  Traceback (most recent call last)
s.getsockopt(zmq.REQ_CORRELATE)
zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.get()
zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._getsockopt()
~/miniconda/lib/python3.6/site-packages/zmq/backend/cython/checkrc.pxd in zmq.backend.cython.checkrc._check_rc()
ZMQError: Invalid argument
```
The error produced by `s.REQ_RELAXED` is similar.

**Comment**: I can't find an obvious source for the error. These constants are type `int` in the ZMQ documents, and the code path in `zmq/backend/cython/socket.pyx` seems to calling `zmq_getsockopt` assuming an `int` type. Does the underlying libzmq incorrectly set an error condition? Or is `zmq.backend.cython.checkrc._check_rc` incorrectly detecting an error that isn't there? Getting other int-type socket options such as RCVTIMEO works fine, so it's not a general problem.

**Comment by minrk** [comment]
Cleaning out old issues, but REQ_RELAXED, etc. are set-only options (valid in setsockopt, but not in getsockopt), and cannot be retrieved. This can be brought up with libzmq if it should change.
