### ISSUE TITLE
SUB socket filter with reverse logic?

### ISSUE THREAD

**Issue by devxpy** [zeromq/pyzmq#1179]
I know we can filter out the messages containing a keyword at the start of message, using -

`zmq.setsocketopt(zmq.SUBSCRIBE,  <keyword>)`

But how do I use this in reverse logic i.e., how do I __exclude__ all messages containing that keyword?

**Comment by devxpy** [comment]
Multi-part messages, with the first part as a filter-able were the way to go for me:

```
identity, response = sock.recv_multipart()

if identity != self._identity:
   ...
```

**Comment by haverins** [comment]
According to the documentation ZMQ_INVERT_MATCHING option should do the trick: http://api.zeromq.org/4-2:zmq-setsockopt

**Comment by devxpy** [comment]
@haverins 
That seems to just block off all messages on `pyzmq 17.1.2`

**Comment by haverins** [comment]
It's working for me. Did you set invert matching for both sockets (PUB/SUB)?

**Comment by devxpy** [comment]
Thanks, that totally works now!

**Comment by devxpy** [comment]
@haverins Is there any way to ZMQ_INVERT_MATCHING for just one subscription?

Here is the message format -

`<Identitiy> <namepsace> <message>`

- identity is the identitiy of the sender.
- namespace is the namespace from which the socket wishes to receive messages inside. 
- message is the message data.

What I want -

The socket gets
- Only the messages from specified namespace.
- Except the messages with it's own identity (so that it doesn't recv it's own messages).

Earlier, I didn't have the namespace, so stuff was fine, but how do I achieve this?
