### ISSUE TITLE
Illegal monitor event

### ISSUE THREAD

**Issue by pvanderlinden** [zeromq/pyzmq#1180]
I sometimes get a monitor event of type 4096, which doesn't seem to exist at all (The constant doesn't exist)

**Comment by chrisjbillington** [comment]
This is EVENT_HANDSHAKE_SUCCEEDED, which was probably a draft API when you wrote this, but now in zmq 4.3 it's stable. But pyzmq doesn't include the constant yet.

**Comment by minrk** [comment]
Closing outdated issues, as this is libzmq behavior and constants are now fully up-to-date. Subscribing to e.g. `zmq.Event.ALL_V1` allows you to subscribe to all the events you know about without getting new libzmq events that have been added since then.
