### ISSUE TITLE
pycharm Cannot find reference 'SUB' in '__init__.py

### ISSUE THREAD

**Issue by Xiang929** [zeromq/pyzmq#1191]
Such as the title， All socket_types are not available, others are not automatically completed.
pycharm version: 2018.1.4
system: Window10
pyzmq version: 17.0

**Comment by Bobsans** [comment]
+

**Comment by Bobsans** [comment]
plus 1

**Comment by minrk** [comment]
This is a duplicate of #1018. Static analysis cannot find runtime-defined names.
