### ISSUE TITLE
Missing binary wheels for Python 3.7 on windows

### ISSUE THREAD

**Issue by nonZero** [zeromq/pyzmq#1195]
Hi!
Python 3.7 was released!

Please upload to pypi the new binary wheels for windows.

Thank you!

**Comment by nonZero** [comment]
This issue currently breaks the installation of jupyter /  ipython notebook under windows.

**Comment by minrk** [comment]
I had to wait for Appveyor to get 3.7 support, which just landed in #1185. As soon as I get a chance, I'll release 17.1 with wheels for 3.7, probably in the next day or two.

**Comment by minrk** [comment]
Release process has begun. Windows wheels take a while to build, but should be uploaded within an hour or two.

**Comment by minrk** [comment]
3.7 wheels are the first to finish, and are up now!
