### ISSUE TITLE
Testsuite hangs

### ISSUE THREAD

**Issue by jdemeyer** [zeromq/pyzmq#1198]
When running the `pyzmq` testsuite using `python setup.py test`, I get
```
running test
Testing pyzmq-17.1.0 with libzmq-4.2.5
========================================================================= test session starts ==========================================================================
platform linux2 -- Python 2.7.15, pytest-3.6.3, py-1.5.4, pluggy-0.6.0 -- /usr/local/src/sage-config/local/bin/python
cachedir: .pytest_cache
rootdir: /tmp/pyzmq, inifile:
collected 242 items                                                                                                                                                    

zmq/tests/test_auth.py::TestThreadAuthentication::test_blacklist
```
and then it just hangs forever. Even sending `SIGINT` to interrupt doesn't work. When running this under `strace`, I can see that it's calling `sleep(1)` forever without doing anything else.

I don't know what is causing this, it might very well be a problem with `pytest`.

**Comment by jdemeyer** [comment]
Never mind, the problem is in the zeromq library.

**Comment by mgorny** [comment]
Heh, that comment is not very helpful to us who keep hitting the same problem years later.
