### ISSUE TITLE
test_buffer_numpy sometimes hangs

### ISSUE THREAD

**Issue by jdemeyer** [zeromq/pyzmq#1202]
I don't have more information for now but I noticed that sometimes the following tests just hangs
```
zmq/tests/test_message.py::TestFrame::test_buffer_numpy
```
This happens say 1 in 20 times that I run the testsuite. By pressing CTRL-C, I found out that it seems stuck here:
```
                while numpy.isnan(A).any():
                    # don't let nan sneak in
                    A = numpy.ndarray(shape, dtype=dt)
```

**Comment by marbre** [comment]
I can confirm this for python 3.6, whereas the test passes for lower python versions. Found this in connection with https://github.com/gentoo/gentoo/pull/9284.

**Comment by mgorny** [comment]
With Python 3.6, it hangs for me every time.
