### ISSUE TITLE
CFFI and Cython

### ISSUE THREAD

**Issue by lazuka13** [zeromq/pyzmq#1204]
Am I right to think that CFFI and Cython in pyzmq are just two different implementations of connection to libzmq? And is it right that I can completely get rid of CFFI, if I want to, without losing any functionality?

**Comment by minrk** [comment]
Yes, the CFFI backend is generally unused when working with CPython and Cython is only used with CPython, so it depends on which Python implementation you are running with.

**Comment by lazuka13** [comment]
OK, thank you!
