### ISSUE TITLE
python stub annotations for typeshed 

### ISSUE THREAD

**Issue by mristin** [zeromq/pyzmq#1206]
Hi!

Have you considered to make python stub annotations (.pyi) for pyzmq? This would allow users of the library to apply statical type checks with mypy and spot many bugs before running the actual code.

I would like to provide a first version if you prefer. However, it makes only sense to introduce stub files if they are consistently updated.

Please let me know what you think. Thanks!

**Comment by minrk** [comment]
If you are happy to commit to keeping them up to date, I've no objection.

**Comment by mristin** [comment]
Hi @minrk,
Thanks for the fast response! 

The problem with the stubs is that they can not be generated automatically. Hence they need to be kept in sync with the implementation manually. I'd like to generate the first version of stubs, but it's impossible to maintain them if not all the contributors sign up to it. (For example, we would need to review at each pull request whether the stubs need to change.)

Please let me know if you think this matters for you. What about other contributors?

**Comment by minrk** [comment]
If you are willing to commit to reviewing pull requests to keep this up to date, then it would be fine. Personally, I do not have the bandwidth to do it, so I would be relying on you.

**Comment by minrk** [comment]
It's relatively rare. pyzmq and libzmq are fairly mature libraries that do not change too often these days, usually just adding a simple new API once in a while.

> On a side note, should I also add contracts

No, I think just the annotations for now.

**Comment by minrk** [comment]
sorry, wrong button.

**Comment by moreal** [comment]
Hello, is there any update?

**Comment by mristin** [comment]
Hi @moreal ,
The issue got burried in my backlog, thanks for raising it up again! I'll try to produce the annotation in the next few days. Would you be interested in reviewing it/beta testing?

**Comment by moreal** [comment]
Hi @mristin .
Yes, I do! I would like to help this issue 😀
