### ISSUE TITLE
Pickle ZMQ context

### ISSUE THREAD

**Issue by surfingkaka** [zeromq/pyzmq#1222]
Since this is not possible, how does one pass around a ZMQ context ? I am trying to use a library that pickles to pass stuff

**Comment by guidog** [comment]
A context is not meant to be passed around.
Find out what a context is for an explanation.
Can be closed.

**Comment by surfingkaka** [comment]
ok, why is this different ? http://zguide.zeromq.org/py:mtrelay

pls close this. thanks
