### ISSUE TITLE
Use ZMQ_SERVER and ZMQ_CLIENT

### ISSUE THREAD

**Issue by Kipsora** [zeromq/pyzmq#1234]
As `libzmq` has already provided `ZMQ_CLIENT` and `ZMQ_SERVER`, I am wondering how to use these two features on Python.

**Comment by Kipsora** [comment]
Solution is found [here](https://pyzmq.readthedocs.io/en/latest/draft.html). Issue closed.

**Comment by andre-merzky** [comment]
That page is invalid by now, and I have the same question.  Would it be possible to include the answer in this ticket?  Thank you!

**Comment by minrk** [comment]
A more stable link [here](https://pyzmq.readthedocs.io/en/v22.3.0/draft.html)
