### ISSUE TITLE
[Win] Building pyzmq with draft sockets

### ISSUE THREAD

**Issue by TheSaw** [zeromq/pyzmq#1235]
Trying to build pyzmq with draft sockets enabled, on win10 and win7, no success. I was following the docs, which worked for me on Unix, but don't on Windows. Steps I take:

Build libzmq x64 from git, with drafts enabled
- Tried versions 4.31, 4.2.5, 4.22
- Tried building with cmake+VS2013 and the build.bat

So far everything went ok, I have used the draft sockets, they work very well.

Now I'm trying to install pyzmq with draft sockets enabled on python 2.7 and 3.6

First, with bundled libzmq:
`- pip install -v --pre pyzmq --install-option=--enable-drafts --install-option="--zmq=bundled"`

Getting these unresolved externals:
```
    message.obj : error LNK2001: unresolved external symbol __imp_zmq_msg_set_group
    message.obj : error LNK2001: unresolved external symbol __imp_zmq_msg_group
    message.obj : error LNK2001: unresolved external symbol __imp_zmq_msg_set_routing_id
    message.obj : error LNK2001: unresolved external symbol __imp_zmq_msg_routing_id
```

Second, with specifying the location of libzmq. This fails, because it expects the root libzmq folder to have a lib directory, which it doesn't by default. I created the directory, copied the libzmq.lib there (tried both static and dynamic), and then it gets further I assume, but it halts with this linker error: 

`   vers.obj : error LNK2019: unresolved external symbol __imp_zmq_version referenced in function main`

Full output of this pasted here: [paste](https://gist.github.com/TheSaw/0914ecec9f0b13cd1b4c29a2d3288cb9)

This is the most I could achieve. Did anyone manage to build this? Any tips what else can I try?

**Comment by minrk** [comment]
This should work with pyzmq 26 (new build system using cmake):

```
ZMQ_DRAFT_API=1 
ZMQ_PREFIX=bundled
pip install -v --pre pyzmq
```
