### ISSUE TITLE
ZMQ stuck on exception, finally section is not executed

### ISSUE THREAD

**Issue by vsmelov** [zeromq/pyzmq#1237]
Hi! Thanks you for cool library :-)
I faced with problem on handling application exception.

If I init ZMQ Context and Socket and then my application failed due to some exception (or Ctrl+C doesn't matter), all python code stops, but process still run (see main1 in examples below).
Can you please explain such behavior?

This is very unuseful if you run program with docker-compose restart=always,
failed program will just run forever!

As far as I understand I have to destroy Context manually (but it is not clear why)
If I wrap execution in try/except (see main2), but on exception program does not go to finally section at all! (in normal execution it does, see main0).
Why finally section is not executed when I use zmq?

So the solution I use is atexit.register, then destroy-code is executed and program exit. But it's weird.

```python
import asyncio
import atexit

import zmq.asyncio


async def foo_print():
    while True:
        print('foo_print')
        await asyncio.sleep(1)


async def foo_zmq():
    context = zmq.asyncio.Context.instance()
    socket = context.socket(zmq.PUB)
    bind_to = 'tcp://*:20000'
    socket.bind(bind_to)
    while True:
        print('foo_zmq')
        await asyncio.sleep(1)


async def main0():
    """ Nothing: try-except (works as expected) """
    try:
        await foo_print()  # press Ctrl+C here
    except:
        pass
    finally:
        print('finally')  # this will be called


async def main1():
    """ ZMQ: just run (stuck on exception) """
    await foo_zmq()  # press Ctrl+C here


async def main2():
    """ ZMQ: try-except destroy (doesn't work) """
    try:
        await foo_zmq()  # press Ctrl+C here
    except:
        pass
    finally:
        print('finally')  # it will be never called!
        zmq.asyncio.Context.instance().destroy(linger=0)  # this is too
        # so program will stuck until you press Ctrl+C twice!


async def main3():
    """ ZMQ: atexit destroy (works) """
    def final():
        print('finally')  # it will be called!
        zmq.asyncio.Context.instance().destroy(linger=0)  # this is too
    atexit.register(final)
    await foo_zmq()  # press Ctrl+C here


if __name__ == '__main__':
    # asyncio.get_event_loop().run_until_complete(main0())  # check nothing (works as expected)
    asyncio.get_event_loop().run_until_complete(main1())  # ZMQ: just run (stuck on exception)
    # asyncio.get_event_loop().run_until_complete(main2())  # ZMQ: try-except destroy (doesn't work)
    # asyncio.get_event_loop().run_until_complete(main3())  # ZMQ: atexit destroy (works)

```

Environment:
```
(.venv) vsmelov@blocktech-008:~/PycharmProjects/base_price_publisher$ python -V
Python 3.6.6
(.venv) vsmelov@blocktech-008:~/PycharmProjects/base_price_publisher$ pip freeze | grep zmq
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pyzmq==17.0.0
(.venv) vsmelov@blocktech-008:~/PycharmProjects/base_price_publisher$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

>>> print("libzmq-%s" % zmq.zmq_version())
libzmq-4.1.6
>>> print("pyzmq-%s" % zmq.pyzmq_version())
pyzmq-17.0.0
>>> print("Python-%s" % sys.version)
Python-3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

```

**Comment by minrk** [comment]
This is an asyncio issue with KeyboardInterrupt, not a pyzmq issue. It can be reproduced with:

```python
import asyncio

async def main():
    try:
        print("interrupt me!")
        await asyncio.sleep(10) # Ctrl-C here
    finally:
        print("finally!") # will not occur on KeyboardInterrupt

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```


Sending SIGINT raises KeyboardInterrupt in *the eventloop*, not in the waiting coroutines. So the coroutine runner stops, not the apparently blocking functions. This is one of the weird things about async programming. While you are blocking, the `foo_zmq` function is *not* running, so signals received are not handled by the zmq functions (or any other async-blocking function). If you do want a try/finally on keyboardInterrupt, it needs to be around `run_until_complete`, not inside coroutines:

```python
try:
    asyncio.get_event_loop().run_until_complete(main())
finally:
    cleanup()
```

The finally block in your code *will* run if the zmq calls actually raises exceptions, such as timeouts, etc.

**Comment by vsmelov** [comment]
Thank you for response :-)

Actually, my problem was with stuck program on exiting.

When we faced with exception program did not exit. It just stops run any python code but did not actually exit. I tried to solve the problem with destroying zmq Context (then it exits).

But when I switched to the new version.

```
pyzmq==17.1.2
```

The problem was gone. I now do not need to call destroy explicitly.

**Comment by minrk** [comment]
good to know!
