### ISSUE TITLE
Assertion failed: Bad address [10014] (bundled\zeromq\src\tcp.cpp:270) on Windows

### ISSUE THREAD

**Issue by lunarplasma** [zeromq/pyzmq#1239]
This seems to be an issue which began in `pyzmq 17.1.0`, with the bundling of `libzmq 4.2.5`. It triggers occasionally on `socket.recv_xx`

This appears to not be a bug with pyzmq itself, but with the underlying libzmq library:
https://github.com/zeromq/libzmq/issues/3263#issuecomment-426305440

`libzmq` Merge request to fix this issue: https://github.com/zeromq/libzmq/pull/3297

Meanwhile, I have found that reverting to `pyzmq 16.0.4` helps in that my server isn't crashing every few seconds.

**Comment by minrk** [comment]
Thanks! We can look forward to bumping the bundled libzmq to 4.2.6 when it is released

**Comment by lgcanto** [comment]
Hi! Any updates on this? Still happens on 19.0.2

**Comment by Bosma** [comment]
Receiving "Bad address (src/tcp.cpp:256)" occasionally on 19.0.2, crashes programs.

**Comment by DillionApple** [comment]
Hi! Any updates? My zmq version is 23.2.0, still has this problem, and program crashes

**Comment by minrk** [comment]
should be fixed in the latest 4.3.5 builds of libzmq. Feel free to open new issues against libzmq if this continues to be a problem.
