### ISSUE TITLE
ZMQ_LINGER not honored, sockets end up in TIME_WAIT state

### ISSUE THREAD

**Issue by mx781** [zeromq/pyzmq#1249]
Hello pyzmq maintainers,

We seem to be running into an issue where the `linger=0` flag for `zmq_close` does not seem to be honored. Here is a minimal repro script:

**main.py**
```python
import zmq
import psutil
import time
import subprocess
import sys

def get_conns_for_port(port):
    return {conn.raddr: conn for conn in psutil.net_connections() if conn.laddr.port == port}

port = 7890
subprocess.Popen([sys.executable, 'server.py', str(port)])

ctx = zmq.Context()
sock = ctx.socket(zmq.REQ)
sock.connect('tcp://127.0.0.1:{}'.format(port))

time.sleep(1) # wait for connection to happen
print(get_conns_for_port(port))

sock.send(b'terminate')
sock.recv()
sock.close(linger=0)
ctx.term()

# time.sleep(15)
print(get_conns_for_port(port))
```

**server.py**
```python
import zmq
import sys

port = sys.argv[1]
ctx = zmq.Context()
socket = ctx.socket(zmq.REP)
socket.bind('tcp://127.0.0.1:{}'.format(port))
socket.setsockopt(zmq.RCVTIMEO, 2000)

msg = socket.recv()
assert msg == b'terminate'
socket.send(b'ok')
socket.close(linger=0)
ctx.term()

print("Server process complete")
```

The output looks like this:
```
$ python main.py 
{addr(ip='127.0.0.1', port=37364): sconn(fd=15, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=7890), raddr=addr(ip='127.0.0.1', port=37364), status='ESTABLISHED', pid=12170), (): sconn(fd=14, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=7890), raddr=(), status='LISTEN', pid=12170)}
Server process complete
{addr(ip='127.0.0.1', port=37364): sconn(fd=-1, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=7890), raddr=addr(ip='127.0.0.1', port=37364), status='TIME_WAIT', pid=None)}
```

The first print shows expected results: the REP socket is listening, and has 1 established connection (to the REP). However, after a single pair of send/recv and closing both with `linger=0` and terminating context, `psutil` shows that the pair that was `ESTABLISHED` is now in status `TIME_WAIT`. According to [man netstat](http://netstat.net/) (which uses /proc under the hood, just like psutil), 
> `TIME_WAIT` The socket is waiting after close to handle packets still in the network.

which sounds exactly what `linger=0` should be preventing. In fact, it seems the C# bindings for 0MQ have an option to do this exactly (as per [this issue](https://github.com/zeromq/netmq/issues/303) and related PRs). However in our case, it does not seem to be honored. 

If you uncomment the `time.sleep()`, the same occurs - the socket is in a `TIME_WAIT` state until the TCP timeout runs out (`net.ipv4.netfilter.ip_conntrack_tcp_timeout_time_wait` on UNIX if I understand correctly). 

In our real-world app, we make use of a lazy-pirate like pattern with pollers, etc; and we have also tried zmq_setsockopt on the sockets rather than passing it to close - neither aspect seems to change this behavior.

Could anyone shed some light on whether this is to be expected (and if so, can it be mitigated in any way), or point at what we're doing wrong? Many thanks. 

env:
```
$ pip freeze
psutil==5.4.8
pyzmq==17.1.2

$ uname -a
Linux server3 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by minrk** [comment]
If all messages are being delivered, setting LINGER should do nothing at all, which appears to be the case in your example. LINGER only affects how long `ctx.term()` should wait for undelivered messages before discarding them. Different values of LINGER should have no effect on the state after `ctx.term()` has returned, only when it should block and for how long.

I'm not sure about the underlying tcp states of the sockets. That's probably a question for libzmq. @bluca?

**Comment by bluca** [comment]
The listening socket will be reaped by the background thread asynchronously. What's the issue exactly?

**Comment by mx781** [comment]
It seems that is not taking place - in my example, the TCP socket is still open although the python processes (including the reaper thread, I would assume) have terminated. Is that expected behavior?

The root issue here is that we're trying to keep track of what ports are safe to bind to. We assumed that a process shutting down gracefully with `socket.close(linger=0)` and `ctx.term()` would be enough to ensure that - but the TIME_WAIT state means it is still unsafe. We can, of course, use that same psutil block in my example to check - but my impression was that ZMQ would free the TCP sockets up gracefully?

**Comment by bluca** [comment]
After the process exits it's the kernel that manages the socket. I assume it's doing whatever is best for safely terminating the connection. The important thing is that this is not an issue. The appropriate socket options are used so that when the program re-runs it will work.

**Comment by mx781** [comment]
Sorry, I'm not sure I fully follow - are you saying that if there is a TCP socket in a TIME_WAIT state on port 1234, then binding/connecting via ZMQ on that port is safe and should work?

**Comment by bluca** [comment]
If it's the kernel doing cleanups, then yes

**Comment by mx781** [comment]
After running some more tests, it does seem that ZMQ works with sockets that have a connection in a  state in netstat/psutil without any issues. Thanks for replying and the clarification! :+1:
