### ISSUE TITLE
Zmq Router does not reply  back from kubernetes pod to client

### ISSUE THREAD

**Issue by abhi1092** [zeromq/pyzmq#1250]
I have a client-server where server uses zmq router to accept message on port1, process it and reply back on port 2. The server is running inside a kubernetes pod and the pod has single docker container running in it. This docker container has the python server script running. The socket listens on tcp://*:port1. Below are the arrangements and how it works
1. When I have only one pod running the client sends a message, the server receives it, and replies back. Everything works as expected
2. When I have 2 or more pods running, the server receives message and replies back. But the client never receives the message. To investigate further:
    * I ran tcp track and as expected tcp connection is created on port1 and port2. But only port1 sees activity, port2 is always idle. 
    * I checked the ip-save table on worker node and everything looks intact
    * I created a very simple test server and client using zmq REP and REQ and ran it on multiple pod setting it also works flawlessly.
    * I stripped down the entire server code and just accepted the message using Router and reply the same thing back but it also did not work.
    * I tried testing the kubernetes network setting by running different debug service (https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/) and everything worked.
Based on this I feel the issue might be with the zmq router, but because I am very new to networking and kubernetes, I am not able to figure out what might be causing this issue.

**Comment by danielecr** [comment]
I did not understand why there is need to open a port2 in rep-req schema.
The req client open a connection to port1, via connect(), while the service bind a port to which to listen, by bind(). This is what is working, right? But there is no port2 in this case.
While. if I understood, you are using ROUTER-REQ?
or something like load balancing router http://zguide.zeromq.org/php:chapter3#A-Load-Balancing-Message-Broker ?

**Comment by minrk** [comment]
Closing stale, general libzmq questions, which don't belong on the pyzmq repo
