### ISSUE TITLE
[Question] Empty frame in dealer / router example

### ISSUE THREAD

**Issue by mondwan** [zeromq/pyzmq#1251]
Hello all, I am not sure whether this is a good place to ask question. Let me know if there is a better place to ask...

I am confused about the DEALER / ROUTER implementation here and example in ZMQ document. According to the ZMQ document, [Dealer and router example][1], there are 3 `frames` for a message envelop, which are ID, EMPTY FRAME, and DATA FRAME. [PYZMQ example][2], however, does not contains the empty frame concept.

[1]: http://zguide.zeromq.org/page:all#ROUTER-Broker-and-DEALER-Workers
[2]: https://github.com/zeromq/pyzmq/blob/master/examples/asyncio/helloworld_pubsub_dealerrouter.py#L162

As first, I guess the empty frame is embedded internally through the API. I try to pick a [C example from zguide][3] as a server, and a mimic a dummy DEALER example as below:

```python
import zmq
import sys

if len(sys.argv) != 4:
    print 'Usage: dumb_dealer_client IP PORT MSG'
    sys.exit(1)

ip = sys.argv[1]
port = sys.argv[2]
msg = sys.argv[3]

context = zmq.Context()
socket = context.socket(zmq.DEALER)
# socket.set(getattr(zmq, 'REQ_CORRELATE'), 0)
socket.identity = b'dumb_client'

endpoint = "tcp://%s:%s" % (ip, port)
socket.connect(endpoint)
print 'Go to %s' % endpoint

# This statement works with C example
# socket.send_multipart(['', msg])

# This statement does not work with C example
# socket.send(msg)
empty = socket.recv()
print 'Received empty from server: |%s|' % empty
reply = socket.recv()
print 'Received msg from server: |%s|' % reply
```

[3]: https://github.com/booksbyus/zguide/blob/master/examples/C/hwserver3.c

It turns out that I need to explicitly specify `socket.send_multipart(['', msg])` in order to create a 3 `frames` message.

Finally, my question is which implementation I should conform to? Do I miss anything? Thanks for your time.

**Comment by minrk** [comment]
The empty frame as delimiter is purely an application-level concept (i.e. zmq treats an empty message frame the same as any other, the handling of the frame is all in your code). It looks like the Python implementation in the guide doesn't choose to use the empty frame while the C example does. It's not important to use the empty frame or not, as long as your application is consistent. I'd say the main reason to use an empty frame is if the length of the routing prefix for your messages is variable (i.e. the same code could use multiple levels of ROUTERs or sometimes a ROUTER socket and sometimes a DEALER with no prefix, etc.)

**Comment by TMPxyz** [comment]
I'm new to ZeroMQ, so correct me if I mistake something here.

I've tried using REQ to connect ROUTER and there's an empty frame in between when call send(). 

So my question is: Is the _empty frame_ a fixed part of the protocol between the socket type _(eg: REQ to REP / REQ to ROUTER)_ ? If so, will this difference make pyzmq unable to communicate with other ports of ZeroMQ?

**Comment by mondwan** [comment]
As the answer from Min RK, such empty frame can be omitted as long as both
server and client know what to do. That's is as long as you are able to
control both endpoint, you own the protocol. Then, empty frame is an
optional decision from you although it is recommended from the ZMQ guide.

For your concerns on communications between different zmq language binding,
this is irrelevant to the empty frame design. Language binding does not
block the communication but the protocol does. You need to confirm that
both end points conform the same rule on communications (include empty
frame or not) instead of concerning their zmq language binding.

That's my understanding on ZMQ. Let me know if I am wrong. Thanks

在 2019年6月12日週三 17:27，TMPxyz <notifications@github.com> 寫道：
