### ISSUE TITLE
await sock.send_multipart() does not yield control to event loop

### ISSUE THREAD

**Issue by akking** [zeromq/pyzmq#1259]
For: https://github.com/zeromq/pyzmq/blob/bf5fbb8c515614f0abb4ee75b55ccbd0149eddb1/examples/asyncio/coroutines.py#L44

If you remove the `await sleep(1)`, the coroutine won't yield control back to the event loop. As a result, the receive won't get any change to receive the message. Is this the expected behavior?

Thanks

**Comment by haverins** [comment]
It's expected. Usually (but not always) send() resolves immediately. See this answer: https://github.com/zeromq/pyzmq/issues/1203#issuecomment-412073705
