### ISSUE TITLE
repeatedly construct and destroy context gives an error

### ISSUE THREAD

**Issue by junhyeokahn** [zeromq/pyzmq#1260]
Hello.
Under my project, I need to repeatedly construct and destroy context but it gives an error.
For example,
```
import zmq

for i in range(100):
    print(i)
    context = zmq.Context()
    data_socket = context.socket(zmq.SUB)
    data_socket.connect("tcp://127.0.0.1:5552")
    data_socket.setsockopt_string(zmq.SUBSCRIBE, "")
    context.destroy()
```

and it returns
```
0
1
2
3
4
5
6
7
8
9
10
11
12
13
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    data_socket.connect("tcp://127.0.0.1:5552")
  File "zmq/backend/cython/socket.pyx", line 580, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Socket operation on non-socket
```

**Comment by minrk** [comment]
Can you provide some more info?

- Python version (sys.version)
- pyzmq version (`zmq.__version__`)
- libzmq version (`zmq.zmq_version()`)
- os (sys.platform)

**Comment by minrk** [comment]
Does it work if you do explicit cleanup (use `socket.close()` and `context.term()` instead of `context.destroy()`?

**Comment by junhyeokahn** [comment]
Sorry for the weak information I provided, but I got this resolved in [here](https://stackoverflow.com/questions/54659190/repeatedly-construct-and-destroy-context-gives-an-error-1260/54665470#54665470).
The problem was that I tried to set option after connect.
