### ISSUE TITLE
Update link in the main website - Edit in GitHub

### ISSUE THREAD

**Issue by Houcine19** [zeromq/pyzmq#1262]
Hello,

Not related to the code itself. The link in the main website: https://pyzmq.readthedocs.io/en/latest/ that send us to GitHub (`Edit in GitHub`) is not working. Is possible update so that can go to the right repo.

It's giving back a 404 at the moment.

**Comment by minrk** [comment]
This seems to be a readthedocs bug. the pyzmq docs do not create this link, the readthedocs theme does it.

**Comment by kinow** [comment]
Just tried the link in the top right of that readthedocs page, and it appears to be working fine for me :+1:

**Comment by minrk** [comment]
Thanks for checking!
