### ISSUE TITLE
PyZMQ 18.0.0 wheels missing for Windows

### ISSUE THREAD

**Issue by vphilippon** [zeromq/pyzmq#1264]
Hello maintainer(s)!

Currently, the `win32` and `win_amd64` wheels for v18.0.0 are missing on PyPI.

Just making sure this doesn't fall into a crack :)

Cheers!

**Comment by minrk** [comment]
Yup, they take a while to build on appveyor. Should be up soon.

**Comment by minrk** [comment]
18.0 has all the Windows wheels now.

**Comment by vphilippon** [comment]
Thanks a lot!
