### ISSUE TITLE
Cython imports fail in latest version

### ISSUE THREAD

**Issue by tjgrilley** [zeromq/pyzmq#1266]
https://github.com/zeromq/pyzmq/blob/a047a08245af36fe35466951b118c23c9423b7ab/zmq/backend/cython/socket.pxd#L26

Could we replace
`from context import Context`
with
`from .context import Context`

This second version is less reliant on building from within the cython directory. It was not an issue on earlier versions of cython, but with the latest version this causes an error if you try to 
`from zmq.backend.cython.context cimport Socket`

There may be a way to use sym links to solve this if someone does want to use zmq from within cython so they don't need the gil to access a thread isolated socket, but i've tried several variations and none of them satisfy both the cython compilation and the actual running of the application.

Tried solutions:
Link at cython compile time with the -I directive, and append the zmq path to sys.path:
`cython your_module_name.pyx -I/usr/lib/python3/dist-packages/zmq/backend/cython/`
 
with header in your_module_name.pyx:
`import zmq.backend.cython
import sys
sys.path.append(zmq.backend.cython.__path__)
from zmq.backend.cython.socket cimport Socket
from zmq.backend.cython.context cimport Context`

Linking in os:
ln -s /usr/lib/python3/dist-packages/zmq/  /project/folder/zmq

**Comment by tjgrilley** [comment]
I mean `from zmq.backend.cython.socket cimport Socket`, sorry.

**Comment by minrk** [comment]
Yeah, a relative import is probably the right thing to do. Would you like to make a PR?

**Comment by tacaswell** [comment]
This is fixed by #1292 .
