### ISSUE TITLE
Why does PyZMQ open so many Unix socket files?

### ISSUE THREAD

**Issue by Peque** [zeromq/pyzmq#1279]
I tried to monitor the number of opened Unix socket files with `lsof -U | wc -l` while I executed this code:

```python
>>> import zmq
# xx75 Unix socket files
>>> c = zmq.Context()
# xx77 Unix socket files
>>> s = c.socket(zmq.PUSH)
# xx83 Unix socket files
>>> s.close()
# xx81 Unix socket files
>>> c.destroy()
# xx75 Unix socket files
```

As you can see, there are 2 Unix socket files opened after context creation and another 6 after socket creation. They are all of type "STREAM":

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/M2q15.png

Why is that? I would expect a TCP/IPC socket file being opened when connecting/binding the socket, but what about those files before even connecting/binding?

It seems this does not happen when executing a similar code written in C.

**Comment by minrk** [comment]
Can you show what C code you used to reproduce this? pyzmq doesn't allocate any FDs, so this should all be in libzmq itself.

**Comment by Peque** [comment]
@minrk Thanks for your quick response.

This is the simplest code:

```c
#include <stdio.h>

#include <zmq.h>

int main(void)
{
	void *context;
	void *socket;

	context = zmq_ctx_new();
	socket = zmq_socket(context, ZMQ_PUSH);
	getchar();
}
```

I open two terminals:

- `watch -n 1 "lsof -U | wc -l"`
- `gcc -lzmq foo.c && ./a.out`

The C executable waits for user input, but I cannot see the number output by `lsof -U | wc -l` increase. Whereas it increases if I execute the Python script instead.

**Comment by Peque** [comment]
@minrk Where you able to reproduce it?

**Comment by Peque** [comment]
@minrk Some useful information can be found in [this StackOverflow question](https://stackoverflow.com/questions/55513294/why-does-pyzeromq-open-so-many-unix-socket-files). Taken from there:

- It seems the issue can be reproduced if the package is installed with `pip`, but not with `conda` (?)
- A better script to reproduce the issue:

```python
import os
pid = os.getpid()
count=0

def lsof():
    global count
    count += 1
    print(count,':')
    os.system("lsof -p {0:d} 2>/dev/null | grep -E 'unix|IPv4|IPv6'".format(pid)) # -U doesn't work togeter with -p option
    # Alternatively, you can use "lsof -U 2>/dev/null | grep -E {0:d}"
    # but only unix socket file will be listed.

import zmq
c = zmq.Context();lsof()
tcp = c.socket(zmq.PUSH);lsof()
unix = c.socket(zmq.PUSH);lsof()

print('--- To bind  ---')
tcp.bind('tcp://127.0.0.1:19413');lsof()
unix.bind('ipc://filename');lsof()

print('--- To close ---')
tcp.close();lsof()
unix.close();lsof()
```

**Comment by minrk** [comment]
The code of pyzmq itself is not at all different when using pip or conda. What can be different, however, is the version of libzmq being used. Can you verify that you cannot reproduce the issue in C with the same libzmq version reported by `zmq.zmq_version()`? And can you perhaps reproduce the issue in C if you link the libzmq bundled with a pyzmq wheel (in zmq/libzmq*.so)?

**Comment by Peque** [comment]
@minrk I have not tried with a different ZMQ library in C, but does this help? (Note that `test_script.py` is [the script I provided in my comment just above](https://github.com/zeromq/pyzmq/issues/1279#issuecomment-483151262))

With `conda`:

```bash
conda create -n foo python=3.6
conda activate foo
conda install pyzmq
python -c "import zmq; print(zmq.zmq_version())"
# 4.3.1
python test_script.py
# A few Unix socket files shown, as expected
```

With `pip`:

```bash
python3.6 -m venv venv
source ./venv/bin/activate
pip install pyzmq
python -c "import zmq; print(zmq.zmq_version())"
# 4.3.1
python test_script.py
# Many Unix socket files shown, not expected
```

So they are both reporting the same `zmq.zmq_version()`, but yield different results. Can you reproduce it?

My system's ZMQ installation seems to be 4.1.6, so I am guessing it is not affecting the experiment as both environments report to be using 4.3.1.

**Comment by minrk** [comment]
interesting, might be something in the way that libzmq is built in the wheel. It's built via manylinux tools, I guess that might be relevant. I don't know what would cause that to be the case.

**Comment by Peque** [comment]
@minrk Do you know someone who could shed some light on this? Do you need me to share/try anything else?

**Comment by minrk** [comment]
Maybe @bluca has an idea? I'm guessing it has to do with how libzmq is built. Perhaps with/without drafts, or perhaps a least-common-denominator choice caused by building the wheels on CentOS 5 (to ensure it works everywhere, some optimized choices are excluded).

**Comment by bluca** [comment]
What's the OS?

**Comment by Peque** [comment]
@bluca Linux x86_64 (I use Fedora 29, but I can reproduce it with other Linux distributions like Debian 9).

**Comment by bluca** [comment]
What is the problem again? Running out of file descriptors?

**Comment by Peque** [comment]
@bluca Unexpected (too many) Unix socket files opened. You can reproduce the issue with [the script provided in this comment](https://github.com/zeromq/pyzmq/issues/1279#issuecomment-483151262).

Supposing that script is saved to a file `test_script.py`, I get different outputs depending on whether I install `pyzmq` with Conda or wheels. See [this comment to reproduce both cases](https://github.com/zeromq/pyzmq/issues/1279#issuecomment-483689801).

I would expect it to behave as it currently does when installed with Conda, but with wheels (pip), I do not understand why it opens so many Unix socket files.

**Comment by bluca** [comment]
What does too many mean? Is the system runnign out? You can increase the limit with ```ulimit -n```

**Comment by Peque** [comment]
@bluca Yeah, not an issue with the user/system's limit, although I have an application in which I end up having 4e6+ Unix socket files due to this. So it is more about understanding why it opens so many (and maybe how to prevent it). Hence this issue "Why does PyZMQ open so many Unix socket files?"

I do not understand why would `pyzmq` open 8 Unix socket files when binding a single IPC/TCP socket? Or why would it open any number at all when creating the ZMQ context.

I would not expect that behavior. And I cannot reproduce it if I use a C test program or if I use the Python test script but with a Conda-installed `pyzmq`.

**Comment by Peque** [comment]
@bluca Can you reproduce the issue on a Linux/Unix machine? Do you have any ideas on what could be going on?

**Comment by bluca** [comment]
I don't know the python details, but there is no expectation nor promise that 1 socket == 1 file descriptor

**Comment by minrk** [comment]
There's nothing Python-specific about it, it's libzmq's behavior in implementing internal FDs, sensitive to some build-time configuration. Sometimes libzmq's internal FDs are reported in lsof, sometimes they aren't. The conda vs pip is only linking two different builds of libzmq. I discovered the same can be found using `conda install -c conda-forge zeromq` which behaves like the pip build, vs `conda install -c defaults zeromq`. I'm guessing it's something in the configure during build that results in a different detail of internal FD implementation.

**Comment by bluca** [comment]
probably it differs on what polling method it picks, if you have the logs for both have a look for it in the configure output
