### ISSUE TITLE
Is there a way to know if the server has been established when the client connects?

### ISSUE THREAD

**Issue by fiecato** [zeromq/pyzmq#1293]
In my project, the server and client are in different projects, and I don't know who will start running first.

So once the server is not established and the client starts to connect to the server, the client connection will hang, which will affect my other tasks.

So, I want to know if there is any way to know if the server is not set up or the client has timed out to give up the connection.

I used the request and response, publish and sucscribe.

Thank you

**Comment by minrk** [comment]
You can use monitor events for this, though it's generally considered the case that you shouldn't be checking for whether peers are up with zmq. Rather, to avoid the hang that's the more direct concern, use POLLOUT on the socket you are sending to tell whether a send right now will block. You can use async/eventloops/polling to avoid blocking other actions while waiting for a socket to be ready to send.
