### ISSUE TITLE
parameter missing in documentation

### ISSUE THREAD

**Issue by chinmayprabhudesai** [zeromq/pyzmq#1298]
https://github.com/zeromq/pyzmq/blob/c189da9f9bf146790a1a765645282b04d8fce877/zmq/backend/cython/utils.pyx#L65

**Comment by minrk** [comment]
closing for duplicate in #1299

**Comment by chinmayprabhudesai** [comment]
@minrk , Thanks for that. I don't know what happened, I accidentally posted this partial issue, so I edited it to provide more information, but apparently it just created a new issue #1299
