### ISSUE TITLE
Getting Socket operation on non-socket when creating and destroying contexts

### ISSUE THREAD

**Issue by ddamiani** [zeromq/pyzmq#1309]
I'm encountering an issue when creating and destroying contexts multiple times. When using a context created after destroying another, sometimes all the sockets created from that context will immediately show as closed via `socket.closed` and throw a "Socket operation on non-socket" error if used (which makes sense if they are closed).

Here is a simple script that reliably causes the issue for me:

```python
import zmq

print("pyzmq: %s zmq: %s" %(zmq.__version__, zmq.zmq_version()))

for i in range(1000): 
    print("pass", i) 
    ctx = zmq.Context()
    print("ctx info", hex(id(ctx)), hex(id(ctx.underlying)))
    sock1 = ctx.socket(zmq.REQ) 
    sock2 = ctx.socket(zmq.REQ) 
    print("after create", sock1.closed, sock2.closed, ctx.closed)
    print("after create", sock1.fileno(), sock2.fileno()) 
    ctx.destroy() 
    print("after destroy", sock1.closed, sock2.closed, ctx.closed)
```

Example output of the error:
```
pyzmq: 18.0.2 zmq: 4.3.1
pass 0
ctx info 0x7fccb2ab50d0 0x7fccb66e4710
after create False False False
after create 15 17
after destroy True True True
pass 1
ctx info 0x7fccb2ab5150 0x7fccb600a1b0
after create True True False
Traceback (most recent call last):
  File "really_stupid_test.py", line 13, in <module>
    print("after create", sock1.fileno(), sock2.fileno()) 
  File "/u1/ddamiani/ami-venv/lib/python3.7/site-packages/zmq/sugar/socket.py", line 161, in fileno
    return self.FD
  File "/u1/ddamiani/ami-venv/lib/python3.7/site-packages/zmq/sugar/attrsettr.py", line 48, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "/u1/ddamiani/ami-venv/lib/python3.7/site-packages/zmq/sugar/attrsettr.py", line 52, in _get_attr_opt
    return self.get(opt)
  File "zmq/backend/cython/socket.pyx", line 477, in zmq.backend.cython.socket.Socket.get
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
```
The iteration of the loop the error happens on is not always the same. If I explicitly close all the sockets before destroying the context then everything is fine. Also if I force it to use the **cffi** backend instead of **cython** then there is no error. I get the same behavior on pyzmq 17 and later. Everything is fine on pyzmq 16.

**Comment by minrk** [comment]
I can reproduce this. After some debugging, I think it's a race condition between destroy and the garbage collector when memory addresses get re-used. Something like:

1. ctx.destroy closes handle S1 on sock1 gen 1
2. new context
3. new socket re-uses handle S1 for sock1 gen2
4. gc of sock1 gen1 checks closed on S1 which is not closed, but is also not the same socket! Closes it as part of cleanup.
5. sock1 gen2 is now closed

I'll look for a reason destroy is implemented in C without notifying Socket objects that they've been closed, which would be the source of this. Using weakrefs as is done in cffi should work more reliably.

**Comment by ddamiani** [comment]
I tried the branch in the pull request and it fixes the issue for me
