### ISSUE TITLE
build wheels on CI with delocate

### ISSUE THREAD

**Issue by minrk** [zeromq/pyzmq#1311]
Currently releases are made on my laptop by running:

```bash
invoke release --upload 18.0.3
```

This requires that I have framework Pythons for all supported mac Pythons (3.4, 3.5, 3.6, 3.7, soon 3.8), mac compilers and the 10.9 SDK, and docker for making the Linux builds. Windows wheels are automated on Appveyor (download & upload to PyPI is still manual), but we should probably be automating all wheel builds on CI to reduce the bus factor and improve testing. Additionally, we should be using delocate-wheel to build and bundle 'real' libzmq and libsodium on mac like we do on Linux. Currently, mac wheels bundle libzmq as an extension like Windows.

It would also probably be good to take this opportunity to adopt more CI services, since Travis is getting bogged down. Azure pipelines is the current cool kid on the block, since it seems to give the most resources for free.

**Comment by chrisjbillington** [comment]
Hi @minrk, I've been thinking about having a go at making a patch to change how building wheels is done here and am wondering what I am signing up for if I give it a shot.

My interest is in getting libsodium bundled on Windows wheels. And if I understand correctly, libsodium isn't used on mac either, right? I managed to get the extension compiling with libsodium so far, so I could contribute a patch that does just that, but I feel like it might be the case that I'd be patching something that is likely to be overhauled anyway.

So a few questions before I try out much else:

1. Is it just incidental/historical that libzmq is compiled as a Cython extension on Windows, or is there a good reason for this? If I can get it compiling as a regular dll and bundle it in similarly to on Linux, would that be preferable? With libsodium what I've got working so far requires me to just bundle the libsodium .dll, so it would be more consistent for both libzmq and libsodium to be bundled in the same way.

2. How do you feel about GitHub actions? I'm pretty familiar with using it for building wheels with compiled extensions on multiple platforms, so I could contribute GitHub Actions workflows to build wheels for all platforms.

**Comment by minrk** [comment]
>  I've been thinking about having a go at making a patch to change how building wheels is done here and am wondering what I am signing up for if I give it a shot.

Wonderful to hear! I'd love this. I'd say the main thing you are signing up for is some CI scripts to build the wheels. We know [from conda-forge](https://github.com/conda-forge/pyzmq-feedstock/tree/master/recipe) that pyzmq works against available libzmq and/or libsodium on all platforms, so it is mainly a matter of scripting the builds to bundle the dependencies properly. The infrastructure to do this has *greatly* improved in recent years. In particular, you shouldn't need to do any messing about with the elaborate, historical mess of edge cases that is our `setup.py`. It should mostly be a matter of:

1. building libsodium & zeromq
2. pointing pyzmq to them with e.g. `python setup.py bdist_wheel --zmq=/zmq/install/prefix`
3. making sure the dylibs are bundled in the wheel (this *may* require some help on Windows, but auditwheel/delocate handle this on linux and mac)
4. smoke-test the wheels by removing the original dylibs, installing the wheel, and running `python -c 'import zmq.backend.cython'`

The mac builds should look very much like the linux ones we have now, just using `delocate` instead of auditwheel. Windows is the one that's more of a mystery to me.

> Is it just incidental/historical that libzmq is compiled as a Cython extension on Windows, or is there a good reason for this? 

Not *quite*. Building libzmq as a C extension (not Cython) is there as a fallback when "properly" built libzmq cannot be found (i.e. most of the time when building from source, and almost always on Windows). So

1.  the setup.py code to build libzmq as an extension should not be removed, but
2. if official wheels can be built without it, they should be!

> If I can get it compiling as a regular dll and bundle it in similarly to on Linux, would that be preferable?

Yes, 100%

> How do you feel about GitHub actions?

Great! I have had wonderful experiences with it in recent months.

> I could contribute GitHub Actions workflows to build wheels for all platforms.

That sounds absolutely perfect.

**Comment by chrisjbillington** [comment]
Apologies for disappearing on this @minrk! Great to see it resolved.

I'm still interested in getting libsodium building on Windows, so will likely still look at that aspect of the wheel-building at some point in the future.
