### ISSUE TITLE
ZMQ with Python 3.7 on Raspberry Pi - Error: ...cython/error.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: zmq_strerror

### ISSUE THREAD

**Issue by HWiese1980** [zeromq/pyzmq#1323]
I'm trying to migrate a Python program on a Raspberry Pi from Python 2.7 to Python 3.7. It uses ZMQ for communication with a PC. Now, when running the program in Python 3.7 I'm getting the following error message:

```
    import zmq
  File "/usr/local/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/usr/local/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/local/lib/python3.7/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/local/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /usr/local/lib/python3.7/site-packages/zmq/backend/cython/error.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: zmq_strerror
```

Is there a way to fix this issue? 

Thank you!

**Comment by FishEatingCat** [comment]
Hello, have you solved this problem? I also encountered this problem.
```
pi@I3oT-pro:~ $ python3
Python 3.7.3 (default, Jun 13 2019, 13:28:28) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/pi/.local/lib/python3.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/pi/.local/lib/python3.7/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/pi/.local/lib/python3.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/pi/.local/lib/python3.7/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/pi/.local/lib/python3.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/pi/.local/lib/python3.7/site-packages/zmq/backend/cython/error.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: zmq_strerror

```

**Comment by HWiese1980** [comment]
Nope, not yet. I guess we need a developer to take a look

**Comment by jarednm** [comment]
Any update on this issue?

**Comment by minrk** [comment]
This sounds like it's an issue with the wheels on `piwheels.org`. I don't maintain those, so I'm not sure what's wrong with them. Try something like:

```bash
# install libzmq
apt-get install libzmq5-dev
# build pyzmq
pip install -vv --no-binary pyzmq pyzmq --install-option --zmq=/usr
```

**Comment by GABowers** [comment]
Having the same issue. Tried this--



> 
> 
> This sounds like it's an issue with the wheels on `piwheels.org`. I don't maintain those, so I'm not sure what's wrong with them. Try something like:
> 
> ```shell
> # install libzmq
> apt-get install libzmq5-dev
> # build pyzmq
> pip install -vv --no-binary pyzmq pyzmq --install-option --zmq=/usr
> ```

--but it still doesn't work. I'm actually having the issue for both 2.7.13 and 3.5.3.

**Comment by jarednm** [comment]
I eventually ditched ubuntu and installed the latest Raspbian.  No issues with pyzmq now.

**Comment by GABowers** [comment]
I've also got it working, after running multiple "apt-get update" and "apt-get upgrade cython" cycles.

**Comment by henrique67-web** [comment]
Good night.
I am just new on python, but I did the following and now it is working correctly:

C:\Users\hbl4731\AppData\Local\Programs\Python\Python37\Scripts>pip uninstall pyzmq
Uninstalling pyzmq-18.1.0:
  Would remove:
    c:\users\hbl4731\appdata\roaming\python\python37\site-packages\pyzmq-18.1.0.dist-info\*
    c:\users\hbl4731\appdata\roaming\python\python37\site-packages\zmq\*
  Would not remove (might be manually added):
    c:\users\hbl4731\appdata\roaming\python\python37\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c
Proceed (y/n)? y
  Successfully uninstalled pyzmq-18.1.0

C:\Users\hbl4731\AppData\Local\Programs\Python\Python37\Scripts>conda
'conda' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\hbl4731\AppData\Local\Programs\Python\Python37\Scripts>pip install --upgrade pyzmq
Collecting pyzmq
  Downloading https://files.pythonhosted.org/packages/e8/be/9cbcdf37890942a9f8f09102903dd69d275258752a530b87fe7273fa26ba/pyzmq-18.1.1-cp37-cp37m-win_amd64.whl (1.0MB)
     |████████████████████████████████| 1.1MB 1.6MB/s
Installing collected packages: pyzmq
Successfully installed pyzmq-18.1.1

**Comment by henrique67-web** [comment]
Basically upgraded pyzmq from 18.1.0 to 18.1.1

**Comment by lchlch** [comment]
Python 2.7.8(centos7 arrch64), Having the same issue. Tried upgraded pyzmq but not worked，any suggestions?

**Comment by doubleAbrew** [comment]
Having the issue here too. Running Python 3.7, and pyzmq 19.1. I double checked and tried the pip install --upgrade pyzmq, apt-get update, and the "fix environment" script and no luck either. Reference #471

**Comment by wxzzzz** [comment]
help

**Comment by minrk** [comment]
pyzmq 26 has a totally ifferent build system, so hopefully this either has been fixed, or will be fixed. Please feel free to reopen if anyone sees issues with pyzmq >=26 (needs `--pre` for now)
