### ISSUE TITLE
[Question] How to use zmq for this?

### ISSUE THREAD

**Issue by topic2k** [zeromq/pyzmq#1324]
I'm working on an app with multiple proccesses which need to transfer data between some of them and the main process needs to signal the worker processes to exit. Which solution would be the best using zmq?

I've read through the docs, but still not sure. For example the conection between _main_ and _worker_1_: do i need

- context in _main_ with one socket PUB and one socket SUB,
context in _worker_1_ with one socket SUB and one socket PUB or
- context in _main_ with PUB/SUB socket in _main_ and _worker_1_

Please, can someone give me advise how to accomplish the below:

![Workflow](https://user-images.githubusercontent.com/6463113/64003622-e5fb2b80-cb0c-11e9-8fd6-c5f384281bc8.png)

**Comment by joubs** [comment]
It is pretty complicated to advise something in particular without knowing your exact requirements, in other words there are plenty of manners to implement 'working solutions' according to what you mentionned above. 

I'd rather suggest to read specific parts of the documentation to be able to design it with accuracy.
You need to understand the differences between the different socket types (REQ/REP, DEALER/ROUTER, PUB/SUB, PUSH/PULL, PAIR) each one taking part in a specific messaging pattern and thus implementing specific behaviors. 

Examples of questions you could tackle from there would be "Do I need synchronous or asynchronous communication?", "If one of my processes has several listeners, should the messages it send be duplicated for each listener or only be pulled once by one of them" etc. 
This design step takes time, but from there the implementation should be straightforward. 

Finally, to answer your specific question about how to connect your main process with worker 1, you **could** go for:
  - one PUB socket in your main 
  - one SUB socket in your worker 

You have to create a context instance in each of your processes by the way. With this setup you would have a one way communication from main to worker, this is perhaps not the pattern you'd like to select if you need the worker to be able to reply. REQ/REP or DEALER/ROUTER are best suited for that. 

Cheers

**Comment by minrk** [comment]
I'm cleaning up a lot of issues. This isn't really a place to get design advice for zeromq applications, but rather specific pzymq bugs. Maybe asking in other channels about libzmq you will get more feedback.
