### ISSUE TITLE
socket.bind("tcp://*:5555") error

### ISSUE THREAD

**Issue by htrifol** [zeromq/pyzmq#1326]
Not accepting under MacOS Mojave 10.14.6 (18G95) the socket.bind("tcp://*:5555") it only takes a full address (127.0.0.1). 

zmq.__version__
'18.1.0'

Exception has occurred: ZMQError
Invalid argument
  File "/Users/me//Python/zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
  File "/Users/me/Python/Zmq_client.py", line 6, in <module>
    socket.connect("tcp://*:5555")

**Comment by sakurai-youhei** [comment]
Did you get the error when running NOT `socket.bind("tcp://*:5555")` BUT `socket.connect("tcp://*:5555")`? According to [documentation](http://api.zeromq.org/4-3:zmq-tcp), the wild-card `*`  can't be used when connecting a socket.
