### ISSUE TITLE
Support unix domain sockets under Win10

### ISSUE THREAD

**Issue by casabre** [zeromq/pyzmq#1327]
According to the following [blog article](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/), Win10 supports now AF_UNIX domain sockets. If I use `ipc://`, a not supported socket type will be reported. Thus, could please extend the compatible Win10 sockets to AF_UNIX as well. The support of the utilized Win10 version can be checked by `sc query afunix`

**Comment by minrk** [comment]
pyzmq doesn't limit libzmq's ipc support, it passes URLs directly to libzmq. so I think this is an issue for libzmq to deal with, unless it's pyzmq's bundled libzmq that's not setting necessary flags.

**Comment by casabre** [comment]
@minrk Thanks for the update. I will raise another issue at libzmq and link it.
