### ISSUE TITLE
zmq.PUSH can't push message to zmq.PULL

### ISSUE THREAD

**Issue by xiongma** [zeromq/pyzmq#1328]
1. my server structure is VENTILATOR-> PRE WORKER -> WORKER -> SINK，which was modified by standard zmq pipline, I added a PRE WORKER into it. all of WORKER sare python process
2. in VENTILATOR, I create several push sockets include VENTILATOR -> PRE WORKER push socket, PRE WORKER -> WORKER push socket, 
3. when the server initialize, I send the PUSH socket address to PRE WORKER which was created in VENTILATOR, and create new PUSH sockets and use new sockets to connect the sended address
4. but the problem was appeared, the VENTILATOR -> PRE WORKER sockets can send message normal, but sockets of PRE WORKER can't send message to WORKER

**Comment by policeme** [comment]
@minrk hope u can help me, I have been search many days, but I can't find a solution to solve it.
