### ISSUE TITLE
Fails to install with Python 3.8 (stable) 64 bit windows using pip

### ISSUE THREAD

**Issue by fzzylogic** [zeromq/pyzmq#1335]
Similar to #1315, Python 3.8.0 (stable) 64 bit (Windows 10) / pyzmq 18.1 installed via pip fails. Error:

ERROR: Command errored out with exit status 1:
   command: 'C:\Users\me\wenv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-kurpdktj\\pyzmq\\setup.py'"'"'; __file__='"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-kurpdktj\\pyzmq\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\me\AppData\Local\Temp\pip-wheel-7wo68hje' --python-tag cp38

**Comment by shivan** [comment]
same here, cannot install and did not find any whl-file yet.

But I've got visual studio 2019 installed with cmake and c++ core tools.

**Comment by minrk** [comment]
pyzmq often doesn't build on Windows from source (I'm still not sure exactly what's required on the host system, but distutils finding the compilers is an important part and often needs some help from environment variables).

Took me too long to get py38 wheels building on Windows, but 18.1.1 wheels are up for Python 3.8 now.
