### ISSUE TITLE
18.1.1 - 'zmq' has no attribute 'ZMQ_REQ_CORRELATE'

### ISSUE THREAD

**Issue by Meow-ops** [zeromq/pyzmq#1350]
Using pyzmq version 18.1.1, i got the following error:

```
    new_sock.setsockopt(zmq.ZMQ_REQ_CORRELATE, 1)
    AttributeError: module 'zmq' has no attribute 'ZMQ_REQ_CORRELATE'
```
The feature was introduced in 0MQ version 4.0.0 (RC1), released on 2013/09/20, is there any reason why this is not available on pyzmq?

**Comment by minrk** [comment]
What OS and how was pyzmq installed? Can you include the values for `zmq.__version__` and `zmq.zmq_version()`? As well as Python version, `pip list` (or `conda list`) etc.?

**Comment by Meow-ops** [comment]
It is running on archlinux, I installed pyzmq with yay :
```
% yay pyzmq
2 community/python2-pyzmq 18.1.1-1 (390.9 KiB 1.8 MiB) 
    Python2 bindings for zeromq, written in Cython
1 community/python-pyzmq 18.1.1-1 (417.6 KiB 1.8 MiB) (Installed)
    Python3 bindings for zeromq, written in Cython

```
Installed versions:
```
In [3]: zmq.__version__                                                                                                                                                                       
Out[3]: '18.1.1'

In [4]: zmq.zmq_version()                                                                                                                                                                     
Out[4]: '4.3.2'

python -V
Python 3.8.0

pip list|grep pyzmq
pyzmq                         18.1.1            

```

**Comment by minrk** [comment]
This would be the reason:

```
In [4]: zmq.zmq_version()                                                                                                                                                                     
Out[4]: '4.3.2'
```

you have pyzmq built against libzmq 4.3.2. Upgrade libzmq to 4.4 and rebuild pyzmq and you should have libzmq 4.4 features.

**Comment by Meow-ops** [comment]
According to this [post](http://wiki.zeromq.org/docs:changes-4-0-0) the feature should be included in libzmq 4.0 right?

**Comment by minrk** [comment]
ahh, my mistake, I read 4.0.0 as 4.4.0. This is a much simpler issue - `ZMQ_` constants are exposed by pyzmq without the (redundant in Python) `ZMQ_` namespacing prefix, so `ZMQ_REQ_CORRELATE` is `zmq.REQ_CORRELATE`, not `zmq.ZMQ_REQ_CORRELATE`, `zmq.PUB` not `zmq.ZMQ_PUB`, etc. In general, `s/ZMQ_/zmq./` for constant names.

**Comment by Meow-ops** [comment]
Thanks, it was such a simple thing.
