### ISSUE TITLE
No way for async <-> sync communication over inproc transport.

### ISSUE THREAD

**Issue by devxpy** [zeromq/pyzmq#1354]
Example:

```python
import zmq
import zmq.asyncio as azmq
from threading import Thread
import asyncio

addr = 'inproc://#1'

def sender():
    ctx = zmq.Context.instance()
    sock = ctx.socket(zmq.PAIR)
    sock.bind(addr)
    sock.send(b'hello')

async def receiver():
    ctx = azmq.Context.instance()
    sock = ctx.socket(zmq.PAIR)
    sock.connect(addr)
    print(await sock.recv())

Thread(target=sender).start()
asyncio.run(receiver())
```

Output:
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    asyncio.run(receiver())
  File "/Users/dev/.pyenv/versions/3.8.1/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Users/dev/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "test.py", line 18, in receiver
    print(await sock.recv())
TypeError: object bytes can't be used in 'await' expression
```

I think this is caused by https://github.com/zeromq/pyzmq/issues/1172. I could be wrong.

---

Using different `Context` objects results in an infinite block on `recv()` because `inproc` sockets need to be under the same `Context`.

---

Thanks for maintaining this great binding.

**Comment by minrk** [comment]
Agreed that this should be easier! It is technically possible, though, through the [shadow method](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Context.shadow) (on both contexts and [sockets](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Socket.shadow)). shadow wasn't created for this purpose (it was created for cross-compatibility with pyczmq or lower-level C/Cython code), but it does work.

Sockets and Contexts have an `.underlying` attribute that is the pointer to the actual underlying libzmq object. This can be used to cast any blocking or async Socket or Context to any other Socket or Context class. For instance, in your async code:

```python
    ctx = zmq.Context.instance()
    # create an asyncio handle on the same underlying zmq_ctx object
    actx = azmq.Context.shadow(ctx.underlying)
    asock = actx.socket(zmq.PAIR)
    # or shadow only the Socket instead of the Context
    sock = ctx.socket(zmq.PAIR)
    asock = azmq.Socket.shadow(sock)
```

At the very least, this should be documented better, but a more prominant/discoverable API for creating different socket classes from a context would be great.

**Comment by devxpy** [comment]
This is great, thanks!
