### ISSUE TITLE
Pre-built wheel for python 3.7 windows amd64 missing from pypi for version 19.0.0

### ISSUE THREAD

**Issue by simmdan** [zeromq/pyzmq#1366]
I just noticed that in the latest release (19.0.0) the pre-built wheel for python 3.7 windows amd64 seems to be missing.  The win32 version is present for python 3.7, and the both win32 and amd64 are present for other versions of python, but not python 3.7.

Is this an intentional omission or a bug?

Thanks for any help you can give.

**Comment by Suudy** [comment]
We are running into the same thing.  Our CI docker images are locked to Python 3.7.  We need the cp37m build.

**Comment by omry** [comment]
pip install pyzmq fails on Windows, breaking my CI as well.

```
    running configure
    {'libraries': ['libzmq'], 'include_dirs': [], 'library_dirs': [], 'runtime_library_dirs': [], 'extra_link_args': []}
    ************************************************
    Warning: Couldn't find an acceptable libzmq on the system.

    If you expected pyzmq to link against an installed libzmq, please check to make sure:

        * You have a C compiler installed
        * A development version of Python is installed (including headers)
        * A development version of ZMQ >= 3.2 is installed (including headers)
        * If ZMQ is not in a default location, supply the argument --zmq=<path>
        * If you did recently install ZMQ to a default location,
          try rebuilding the ld cache with `sudo ldconfig`
          or specify zmq's location with `--zmq=/usr/local`
```

**Comment by minrk** [comment]
Some of the Windows wheels stalled because the CI failed. Should all be up now.

**Comment by Suudy** [comment]
> Some of the Windows wheels were delayed because the CI hit an error. Should all be uploaded now.

Thank you!
