### ISSUE TITLE
Request to declare static entry for those runtime-declare global variable

### ISSUE THREAD

**Issue by stevenleeS0ht** [zeromq/pyzmq#1376]
For the global "variable" defined during runtime, like `zmq.REP` or `zmq.REQ`, or some functions.

It would be nice to define a static "placeholder" in static for example `zmq.REP = None`, or some other number. It would be very convenient for static checking and IDE auto-complete.

**Comment by kinow** [comment]
I never invested time into this, but I can confirm that in PyCharm, whenever I inspect my code it complains about `zmq.REQ` and `zmq.REP`. If a placeholder as suggested above fixes it, without causing any issue for pyzmq developers, I'm +1 for that.

Thanks

**Comment by sakurai-youhei** [comment]
Here are ways of suppression for 2 IDEs; These don't help auto-complication, though.

**For PyCharm**

```python
# noinspection PyUnresolvedReferences
from zmq import REP

# noinspection PyUnresolvedReferences
print(zmq.REP)
```

**For Eclipse+PyDev.**

```python
from zmq import REP  # @UnresolvedImport

print(zmq.REP)  # @UndefinedVariable
```

**Universal but dirty way**

```python
from zmq import REP  # noqa

print(zmq.REP)  # noqa
```

P.S. VSCode doesn't seem to claim anything and I don't use Visual Studio.
