### ISSUE TITLE
'AssertionError: yield from wasn't used with future' on recv_multipart()

### ISSUE THREAD

**Issue by sarthak-chakraborty** [zeromq/pyzmq#1379]
ERROR:root:Traceback (most recent call last):
  File ".\async_client.py", line 18, in <module>
    [topic, msg] = sockfd.recv_multipart()
AssertionError: yield from wasn't used with future

Received this error?
Can anyone tell how or when such an error arises?

Can anyone help with this issue?

**Comment by sarthak-chakraborty** [comment]
Fixed it. `recv_multipart()` is an asyncio coroutine and hence `await` keyword was necessary. However, my sender side did not have any `await` keyword but still it worked. Wondering why?

**Comment by minrk** [comment]
while send is technically async, it only waits if it has to, so almost always returns a completed Future in realistic scenarios.
