### ISSUE TITLE
Failing to connect to host on another network

### ISSUE THREAD

**Issue by jhalter2** [zeromq/pyzmq#1388]
I'm using the basic example host and client with the Req/Rep sockets and it works fine when executing both from two separate computers on the same local network. However, when trying to execute the example with machines on two different networks, the client never receives the message sent by the server. 

I've eliminated any firewall/router issues, so I think it may be an issue with how I'm doing the connect call on the client. 

My code for binding the server is `socket.bind("tcp://*:5555")`
and my code for connecting on the client is `socket.connect("tcp://public_ip:router_port;local_ip:local_port")`

where I'm filling in the ips and ports with the actual IP values.

**Comment by minrk** [comment]
I think you want just one url to connect: `socket.connect("tcp://public_ip:router_port")`

if that still doesn't work, you might try making sure you can create a tcp connection to that ip:port with stdlib [socket.create_connection](https://docs.python.org/3/library/socket.html#socket.create_connection) to eliminate zmq from the equation.

**Comment by jhalter2** [comment]
Was able to get it working. My port forwarding was setup incorrectly.
