### ISSUE TITLE
High throughput test on TCP & EPGM

### ISSUE THREAD

**Issue by dxb-super** [zeromq/pyzmq#1397]
Hi, everyone !
I want to use zeromq pub/sub to transport large size msgs (e.g. images data). 
I did the below test in python environment:
1. send different sizes of msg (from 2kB - 16MB) with random data
2. one publisher in one docker container, and one subscriber in one other seperate container
3. calculate the total data size and time, to estimate the throughput (total size / time) in MB/s

tcp have good performance, but epgm I only got 20MB/s throughput even after I set the socket.rate, hwm ... Just want to know the reason. I hope I can use epgm because it is multicast protocol which should have advantage than tcp in multi subscriber cases.. test result have been shown below and test code has been attached. 

![image](https://user-images.githubusercontent.com/53667804/85020741-5ca00d00-b1a3-11ea-8850-323555677a11.png)
![image](https://user-images.githubusercontent.com/53667804/85020758-63c71b00-b1a3-11ea-8bf7-5accef591ab2.png)

**The code I used as below:**
[zmq throupug test dockerized.zip](https://github.com/zeromq/pyzmq/files/4798560/zmq.throupug.test.dockerized.zip)

**Comment by minrk** [comment]
Probably better to ask on libzmq; more folks there with relevant experience and I wouldn't expect much that pyzmq does to be relevant to the difference between tcp and epgm. If you do the same benchmark in C and get significantly different results from pyzmq, that would definitely be relevant here.

**Comment by dxb-super** [comment]
move the issue to https://github.com/zeromq/libzmq/issues/3961, so I close this one
