### ISSUE TITLE
Python 3.10 support?

### ISSUE THREAD

**Issue by fperez** [zeromq/pyzmq#1400]
In [this PR about PEP-6222](https://github.com/gvanrossum/patma/pull/117) I created an experimental build of Python 3.10 that is available [at this binder link](https://mybinder.org/v2/gh/fperez/patma/master?urlpath=lab). However if I try to install using `py10 -m pip install pyzmq`, the build fails:

```
[ lots of elided early output]

    building 'zmq.backend.cython._device' extension
    creating build/temp.linux-x86_64-3.10/zmq
    creating build/temp.linux-x86_64-3.10/zmq/backend
    creating build/temp.linux-x86_64-3.10/zmq/backend/cython
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SYS_UN_H=1 -Ibundled/zeromq/include -Izmq/utils -I/home/jovyan/.local/include/python3.10 -c zmq/backend/cython/_device.c -o build/temp.linux-x86_64-3.10/zmq/backend/cython/_device.o
    gcc -pthread -shared build/temp.linux-x86_64-3.10/zmq/backend/cython/_device.o -o build/lib.linux-x86_64-3.10/zmq/backend/cython/_device.cpython-310-x86_64-linux-gnu.so
    building 'zmq.backend.cython._poll' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SYS_UN_H=1 -Ibundled/zeromq/include -Izmq/utils -I/home/jovyan/.local/include/python3.10 -c zmq/backend/cython/_poll.c -o build/temp.linux-x86_64-3.10/zmq/backend/cython/_poll.o
    zmq/backend/cython/_poll.c: In function ‘__Pyx_PyList_Append’:
    zmq/backend/cython/_poll.c:1252:23: error: lvalue required as left operand of assignment
             Py_SIZE(list) = len+1;
                           ^
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/jovyan/.local/bin/py10 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-up2ewe5s/pyzmq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-up2ewe5s/pyzmq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gjmp6rt5/install-record.txt --single-version-externally-managed --compile --install-headers /home/jovyan/.local/include/python3.10/pyzmq Check the logs for full command output.
```

This may or may not be an easy fix, not sure, but I figured I'd flag it in case it's doable. Having pyzmq support would help us to try to get a Jupyter kernel for python 3.10 so folks could more easily experiment with new language features via a pre-built binder that has all the right environment.

**Comment by Carreau** [comment]
I think that might be a cython issue, and you need a more recent Cython, I believe some Macro in Python are now const-fn so can't be use in LHS.

**Comment by Carreau** [comment]
Pretty sure it is; 

https://github.com/python/cpython/commit/fe2978b3b940fe2478335e3a2ca5ad22338cdf9c and https://bugs.python.org/issue39573
```
* Since :c:func:`Py_SIZE()` is changed to the inline static function,
  ``Py_SIZE(obj) = new_size`` must be replaced with ``Py_SET_SIZE(obj, new_size)``:
  see :c:func:`Py_SET_SIZE()` (available since Python 3.9).
  (Contributed by Victor Stinner in :issue:`39573`.)
```

**Comment by Carreau** [comment]
and that would be in `Cython/Utility/Optimize.c`

**Comment by Carreau** [comment]
Rebuilding PyZMQ master with latest Cython seem to work out of the box.

**Comment by kinow** [comment]
Just tested and successfully built PyZMQ master, Ubuntu LTS, Python 3.10 latest, cython 0.29.21, libzmq3-dev:amd64 4.2.5-1ubuntu0.2

**Comment by minrk** [comment]
Yeah, making a new sdist with regenerated Cython sources ought to make it work with 3.10. It would be nice if we could publish updated sdists for an existing release without also invalidating all bdists, but I don't think PyPI post-release fixes allow that. So I'll have to do a whole new release with all the wheels. I will try to get to that soon.
