### ISSUE TITLE
Wheel support for aarch64.

### ISSUE THREAD

**Issue by odidev** [zeromq/pyzmq#1401]
**Summary**
Installing pyzmq on aarch64 via pip using command "pip3 install pyzmq" tries to build wheel from source code

**Problem description**
pyzmq don't have wheel for aarch64 on PyPI repository. So, while installing pyzmq via pip on aarch64, pip builds wheel for same resulting in it takes more time to install pyzmq. Making wheel available for aarch64 will benefit aarch64 users by minimizing pyzmq installation time.

**Expected Output**
Pip should be able to download pyzmq wheel from PyPI repository rather than building it from source code.

@pyzmq-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make pyzmq wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by minrk** [comment]
That would be awesome! Lacking any aarch64 access myself, I think we need to finally set up build and deploy from CI in order to do this, so the tasks would be:

1. build aarch (and mac) in CI
2. set up deploy job for upload of wheels to PyPI on tags, to be run on mac, aarch64, x86-64

**Comment by odidev** [comment]
Thanks @minrk I will work on adding aarch64 builds in Travis-ci first and update you.

**Comment by odidev** [comment]
@minrk I have successfully added the jobs for arm64 in travis.yml and all tests are passing successfully, please have a look at the Travis build logs: https://travis-ci.com/github/odidev/pyzmq/builds/175891421

> 1. build aarch (and mac) in CI

I have added jobs for Python version 3.6, 3.7, and 3.8 only Travis.yml diff: https://github.com/odidev/pyzmq/commit/981a88de350f8f556b0bf6884adc1bb3c660f3fe, Please have a look and suggest if anything else needs to be done from my end, I have added jobs for building wheels for ``` env: ZMQ= BUILD_WHEEL=true ``` for x86 and arm64. Please suggest do I need to add jobs ( with wheel ) for any other env or not.

There are many jobs added with different env variables, please suggest if I should remove or add any. I will work on setting up deploy jobs for the upload of wheels to PyPI accordingly.

**Comment by minrk** [comment]
Awesome! Feel free to open a WIP PR, and we can discuss there.

**Comment by odidev** [comment]
@minrk I have raised the pull request, please have a look: https://github.com/zeromq/pyzmq/pull/1404.

**Comment by odidev** [comment]
@minrk I have been working on modifying the script as per your suggestion, added only 4 jobs for arm64 and used ```tools/tasks.py``` for wheel building( for python 3.7 amd64 currently ). 

**Travis.yml:** https://github.com/odidev/pyzmq/blob/Testing/.travis.yml
**tools/tasks.py**: https://github.com/odidev/pyzmq/blob/Testing/tools/tasks.py

I am facing the below issue, I modified the ```tools/task.py``` file and commented few lines of the code specific to OSX: 

```
ValueError: Need 3.8 at /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8
607
The command "cd tools && invoke release 14.3.1" exited with 1.
```

**Issue Description:** 

-> It looks like that the issue is comming from https://github.com/zeromq/pyzmq/blob/master/tools/tasks.py#L69.
-> The value for ```_framework_py``` is not able to set it is expecting a certain value and getting something else.
-> I tried running it for python v3.8 and v3.6 also but the issue remains the same.

Please have a look at the Travis-ci log: https://travis-ci.com/github/odidev/pyzmq/jobs/366712370 . Please share your thoughts on this.

**Comment by minrk** [comment]
Yeah, tools.py itself won't want to be ported, since that's for scripting building a release and several builds from one machine. With CI, the travis matrix will take care of it.

**Comment by odidev** [comment]
@minrk Explored already present wheels on pypi of different platforms and observed that in few wheels there is an additional pyzmq.libs folder present which contains .so files of libzmq and libsodium.

```
pyzmq-19.0.2-cp38-cp38-win_amd64.whl            No library folder      No .so files present
pyzmq-19.0.2-cp38-cp38-macosx_10_9_x86_64.whl   No library folder      libzmq.cpython-38-darwin.so
pyzmq-19.0.2-cp37-cp37m-manylinux1_x86_64.whl   pyzmq.libs             libsodium-bcf9f097.so.23.3.0 and libzmq-1358af2c.so.5.2.2
pyzmq-19.0.2-cp38-cp38-manylinux1_i686.whl      pyzmq.libs             libsodium-1bcd177c.so.23.3.0 and libzmq-265b44a9.so.5.2.2
```

The created(manually/using task.py) AArch64 wheels don't have such folder. Can you please let me know if it is expected or am I missing anything while creating wheel.

Run logs for task.py- https://travis-ci.com/github/odidev/pyzmq/jobs/384567748

**Comment by odidev** [comment]
@minrk could you please share your thoughts on this.

**Comment by minrk** [comment]
the pyzmq.libs dir is created by [auditwheel](https://github.com/pypa/auditwheel), which is only run on linux wheels. For mac, we should be using https://github.com/matthew-brett/delocate to do the same, but we are currently building libzmq as an extension on mac and windows.

**Comment by BlackDark** [comment]
@minrk is the latest wheel already released for aarch64?

**Comment by minrk** [comment]
I haven't yet published pyzmq 21, which will be the first release with these changes.

**Comment by skast96** [comment]
The website https://www.piwheels.org/project/pyzmq/ still says that there is no package for arm64 which takes a lot of time to build by myself in an emulator

**Comment by minrk** [comment]
piwheels is not related to this repo. I think you may mean to open an issue on their own resources. But it looks like there are wheels now, when I look. Presumably took a little bit to register the latest release.

**Comment by skast96** [comment]
@minrk you may be right. What I wanted to point out is that if you want to use pyzmq on an ARM 64-Bit based machine (RPI4) you have to build the package. You do not get precompiled packages from PyPi, piwheels, or whatever.

**Comment by minrk** [comment]
I don't know much about RPi, but there are aarch64 wheels [on PyPI](https://pypi.org/project/pyzmq/#files) for Python 3.6-3.10. What compatibility tags do you get for `pip debug -v`? Are you using pip 22.1?
