### ISSUE TITLE
ZMQStream: fd added twice

### ISSUE THREAD

**Issue by vvvverre** [zeromq/pyzmq#1405]
Hello,

I am trying to use ZMQStream and the tornado event loop. I have tried the following code based on the example in docs:

```python
from tornado import gen, ioloop
import zmq
import sys
from zmq.eventloop.future import Context
from zmq.eventloop.zmqstream import ZMQStream

print("libzmq-%s" % zmq.zmq_version())
print("pyzmq-%s" % zmq.pyzmq_version())
print("Python-%s" % sys.version)
print()

ctx = Context.instance()

s = ctx.socket(zmq.REP)
s.bind('tcp://127.0.0.1:12345')
stream = ZMQStream(s)
def echo(msg):
    stream.send_multipart(msg)
stream.on_recv(echo)
ioloop.IOLoop.instance().start()
```

I keep getting the following error about the fd being added twice:

```
libzmq-4.3.2
pyzmq-19.0.1
Python-3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]


Traceback (most recent call last):
  File "testzmqstream.py", line 16, in <module>
    stream = ZMQStream(s)
  File "C:\Users\Wouter\Envs\gpr\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "C:\Users\Wouter\Envs\gpr\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "C:\Users\Wouter\Envs\gpr\lib\site-packages\tornado\platform\asyncio.py", line 97, in add_handler
    raise ValueError("fd %s added twice" % fd)
ValueError: fd 572 added twice
```

This output is from Windows 7, but I get the same error on Linux. I installed pyzmq via pip in both cases.
Does anyone have any idea where this error may be coming from?

Many thanks in advance!

**Comment by minrk** [comment]
Thanks, might be something different about asyncio on Windows. What tornado version?

**Comment by Xirui** [comment]
Same issue for me:
`from tornado import gen, ioloop
import zmq
import sys
import tornado
from zmq.eventloop.future import Context
from zmq.eventloop.zmqstream import ZMQStream

print("libzmq-%s" % zmq.zmq_version())
print("pyzmq-%s" % zmq.pyzmq_version())
print("Python-%s" % sys.version)
print("tornado-{}".format(tornado.version))

ctx = Context.instance()

s = ctx.socket(zmq.REP)
s.bind('tcp://127.0.0.1:12345')
stream = ZMQStream(s)
def echo(msg):
    stream.send_multipart(msg)
stream.on_recv(echo)
ioloop.IOLoop.instance().start()`

Output:
`libzmq-4.3.2
pyzmq-19.0.2
Python-3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0]
tornado-6.0.4
Traceback (most recent call last):
  File "ttt1.py", line 17, in <module>
    stream = ZMQStream(s)
  File "/home/users/xgir/.local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "/home/users/xgir/.local/lib/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 552, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "/home/users/xgir/.local/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 97, in add_handler
    raise ValueError("fd %s added twice" % fd)
ValueError: fd 16 added twice`

Os: Ubuntu 18.04.5 LTS

Appreciate any help or hint :)

**Comment by minrk** [comment]
Oh, I finally see! Thank you for including the example and sorry for not seeing it sooner. The issue is this line:

```python
from zmq.eventloop.future import Context
```

ZMQStream must be used with base Sockets, not the `zmq.eventloop.future` API. Those sockets add themselves to the io_loop when they are created, hence the "added twice" error. They really are being added twice.

So the gist is: to use zmq Sockets with an event loop, *either* use `zmq.eventloop.future` (or `zmq.asyncio`) with coroutines *or* ZMQStream with regular blocking sockets, but not both.
