### ISSUE TITLE
why pyzmq(19.0.2) and c++ zeromq4.1.2 failed to communicate?

### ISSUE THREAD

**Issue by nickhuangxinyu** [zeromq/pyzmq#1408]
Hi,
i want to use pyzmq to transfer message between c++ and python.
when i use python2.7.15(pyzmq '17.1.2') and pyzmq and c++ zeromq 4.1.2, the msg will be ok to pass.

but when i use python3(pyzmq '19.0.2'). it failed.

so, what is the correct version in c++, so i can pass msg with python3? and is it compatiable with python2?

**Comment by minrk** [comment]
The version of pyzmq isn't generally relevant, but the version of libzmq may be. Check `zmq.zmq_version()` to see what version of libzmq pyzmq is running with. You can try building pyzmq from source with a shared libzmq if the version is far off, for example, to skip the prebuilt wheels:

    pip install --no-binary pyzmq pyzmq
