### ISSUE TITLE
asyncio without Futures

### ISSUE THREAD

**Issue by willstott101** [zeromq/pyzmq#1411]
We're trying to rebuild our existing pyzmq Poller based eventloop on top of asyncio. The change in performance due to all the Future book-keeping is unacceptable for us. We're integrating to get async/await, but also to interoperate with httpx and other async libraries. If we want to use Futures from pyzmq (which would be rare for us, as we're normally publishing / subscribing) we can easily wrap callback code.

Would it be possible to have a leaner asyncio integration which uses loop.add_reader but doesn't provide futures support? Futures as sugar over a call-back based implementation makes a lot more sense to me.

It looks like the best option currently is forking the _future module and simply ripping out the Future parts... or trying out aiozmq.

What would you recommend?

**Comment by minrk** [comment]
You can use zmq sockets with asyncio with `loop.add_reader(socket.fileno())` exactly as-is. If you don't want Futures, go ahead and do that. Lower-level integrations are fine, but I'm not sure what one could be that's generally useful to be included in pyzmq.

I would recommend using aiozmq, though it, too, uses Futures. It may perform better, though. `zmq.asyncio` is *absolutely not* meant to replace aiozmq, it's just a basic "the socket api, but awaitable," which necessarily means Futures. I'm not sure what code in pyzmq is useful or reusable if you want to avoid Futures. Benchmarking test cases and performance improvements are welcome, though—it's entirely possible the performance hits are not necessary.

Do you have a sample code that exhibits the performance issues you are seeing?

**Comment by nodakai** [comment]
Hijacking the thread... is it possible to support something like [`get_nowait()`](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue.get_nowait) and `poll_nowait()` which are not `async` functions?

Use case: we have one async `Poller` monitoring several async SUB `Socket`s, and we expect messages arrive in batches, so we want to have this kind of nested loops to process each "batch" efficiently without generating `Future`s:

```
while True:
    for sock, _ in await poller.poll():  # single await here
        while True:
            data = sock.recv_nowait()
            munch(data)
            if sock.poll_nowait() == 0:
                break
```

**Comment by minrk** [comment]
> is it possible to support something like [`get_nowait()`](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue.get_nowait) and `poll_nowait()` which are not `async` functions?

yes, absolutely! The edge-triggered FD issue means we need to be a little careful to schedule an async consumption of remaining tasks next tick (`self._schedule_remaining_events()`) at the end of any nowait calls (or make them explicitly unsafe), but this should be fine. 

You can do this today by creating a blocking socket to shadow the async socket:

```python
    ctx = zmq.asyncio.Context.instance()
    receiver = ctx.socket(zmq.PULL)
    receiver.connect(url)
    # create a blocking Socket object against the same underlying zmq_socket
    shadow = zmq.Socket.shadow(receiver.underlying)
    poller = zmq.asyncio.Poller()
    poller.register(receiver, zmq.POLLIN)
    while True:
        # use asyncio to wait for events
        events = await poller.poll()
        while events:
            # use blocking socket to consume events, without invoking a Future for each message
            try:
                msg = shadow.recv_multipart(zmq.DONTWAIT)
            except zmq.Again:
                # checking events on the asyncio socket ensures the edge-triggered FD will wake if needed
                events = receiver.events & zmq.POLLIN
            else:
                process(msg)
```

Note: in this as-fast-as-possible example with no awaits, it's possible for a fast sender to starve your eventloop so that you never wake to advance any other coroutines if the sender is producing messages as fast as the receiver can process them. Adding limits to the number of messages processed per blocking chunk before you defer to the loop or other starvation-avoiding strategies allows you to mitigate this, as with any blocking event consumption in a cooperatively async application.

A full example can be seen [here](https://gist.github.com/0068aac48e0ab64f1049647cb96d2f90), which processes at least ~250k msgs/sec on my laptop.

**Comment by willstott101** [comment]
Well, I managed to get something working. But for dealer sockets to work with our RPC mechanisms I had to watch for read & write readiness with `EPOLLET`, sub sockets worked fine with just `add_reader`. Thanks to https://stackoverflow.com/questions/46815141/use-python-asyncio-to-wait-for-gpio-interrupt I discovered you can use `add_reader` on an epoll fd so we're happily running on asyncio.

I don't really understand the need to wake on EPOLLOUT to get DEALER sockets to work and can't find any mention of it online

Essentially
```python
self._epoll = select.epoll()
# We can then watch the _epoll to get into asyncio, thanks to:
# https://stackoverflow.com/questions/46815141/use-python-asyncio-to-wait-for-gpio-interrupt
self.loop.add_reader(self._epoll.fileno(), self._epoll_read)
# But it does mean we need to keep our own callback sets
self._callback_info = {}

def add(self, socket_or_fd, callback, description, **callback_kwargs):
    callback = sanitize_callback(callback, description, callback_kwargs)

    if isinstance(socket_or_fd, _BaseSocket):
        fd = socket_or_fd.fileno()
        evts = select.EPOLLIN | select.EPOLLET
        if socket_or_fd.socket_type in (zmq.DEALER,):
           evts |= select.EPOLLOUT
       self._epoll.register(fd, evts)
        if fd in self._callback_info:
            raise KeyError(f"Already registered a callback for socket fileno: {fd}")
        self._callback_info[fd] = (socket_or_fd, callback, description)
    else:
        self.loop.add_reader(socket_or_fd, callback)

def _epoll_read(self):
    for fd, evt in self._epoll.poll(0):
        socket, callback, description = self._callback_info[fd]
        if socket.events & zmq.POLLIN:
            self._zmq_read_pollin(socket, callback, description)
def _zmq_read_pollin(self, socket, callback, description):
    # Loops forever until zmq.Again
    try:
        callback()
    except zmq.Again:
        # We've exhausted the messages :)
        return
    except Exception:
        log.exception("in callback: {0}".format(description), context="ioloop")
    # No Again error so we carry on!
    self.loop.call_soon(self._zmq_read_pollin, socket, callback, description)
```

**Comment by willstott101** [comment]
The key thing here is that we just want the `def add(self, socket_or_fd, callback ...` style for subscriptions. Some sockets might make sense with await, some won't. So we avoid futures altogether at the ioloop level.

**Comment by minrk** [comment]
Note that you will never want to use EPOLLOUT with zmq FDs. The [zmq FD](http://api.zeromq.org/4-3:zmq-getsockopt#toc11) is an edge-triggered, read-only FD. There will be a write event on any state change, whether that's the socket becoming readable *or* writable. That means waiting to write on a socket is *also* waiting for POLLIN on the FD.  There will *not* be a read event if you start waiting on the FD while there are already events pending. If you look for zeromq edge-triggered ZMQ_FD, you'll find some discussions of all the trouble, [like this one](https://funcptr.net/2012/09/10/zeromq---edge-triggered-notification/).

This edge-triggered behavior is the single most frustrating thing about libzmq, in my experience, and I've been trying to get it changed for several years, but lack the time and expertise to do it myself, so gave up hope a long time ago. If anything, the situation has only [gotten worse](https://github.com/zeromq/libzmq/issues/2941).
