### ISSUE TITLE
Asyncio error on Windows Python 3.8 due to proactor event loop

### ISSUE THREAD

**Issue by chriscline** [zeromq/pyzmq#1423]
Using `zmq.asyncio` on Windows with Python 3.8 fails, due to `asyncio` using the "proactor" event loop by default. See https://github.com/tornadoweb/tornado/issues/2608 for related discussion.

Specifying that `asyncio` should use the selector event loop (the previous default) allows `zmq.asyncio` to run successfully.

Can pyzmq be updated to support the proactor event loop, or do we need to manually change the event loop to selector for anything using `zmq.asyncio`?

Example: the code below generates an error unless the `asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())` line is uncommented.

```python
import asyncio
import zmq
import zmq.asyncio

port = 5556

#asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
ctx = zmq.asyncio.Context()


async def recv_and_process():
    sock = ctx.socket(zmq.REP)
    sock.connect('tcp://localhost:%d' % port)
    msg = await sock.recv_string() 
    await asyncio.sleep(1)
    await sock.send_string('ack')


async def send_and_wait():
    sock = ctx.socket(zmq.REQ)
    sock.bind('tcp://*:%d' % port)
    await sock.send_string('msg')
    reply = await sock.recv_string()


async def sendAndRecv():
    await asyncio.gather(
        send_and_wait(),
        recv_and_process()
    )


asyncio.run(sendAndRecv())
```

libzmq-4.3.2
pyzmq-19.0.2
Python-3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]

**Comment by minrk** [comment]
> Can pyzmq be updated to support the proactor event loop

I don't think there is any way to make this happen until/unless the proactor event loop implements the fundamental `add_reader` methods, but I'd love to be wrong. See [this discussion on Python](https://bugs.python.org/issue37373) for details. Essentially, there is no way for *libraries* to declare themselves incompatible with proactor, and apparently no way to use proactor with FD/socket-based APIs like libzmq without some shenanigans or new features implemented in the standard library.

If someone could write an example that works with zmq sockets (not the current asyncio wrappers) and proactor, that would be awesome. But as far as I can tell, especially with tornado in a similar boat, I think most Windows folks simply can't use the default event loop policy if they need to do anything with sockets/FDs. It's still technically a solvable problem, but Python 3.8 and 3.9 have chosen not to address it.

**Comment by willmendil** [comment]
fyi, python 3.10 shows the same issue. Does that mean zmq asyncio is broken for good ?

**Comment by minrk** [comment]
pyzmq will run on proactor if you have tornado 6.1, which provides the necessary compatibility layer to fill in the missing features.
