### ISSUE TITLE
Curve User-Id for Dealer/Router

### ISSUE THREAD

**Issue by oddjobz** [zeromq/pyzmq#1425]
Hi, I've just switched a REP/REQ pair for a ROUTER/DEALER pair only to find that I can no longer access the Curve User-Id for a connection. This is a bit of an issue for me with regards to security and making sure the connection I'm working with is still the one I think I'm working with .. apparently this is a known issue, documented here with a (C++?) fix;

https://github.com/zeromq/libzmq/issues/1537

Is there a similar work-around in Python?
(I'm suspecting the fix needs to be implemented in pyzmq??)

**Comment by minrk** [comment]
I haven't come up with a good API for accessing message properties with `copy=True` (ideas welcome!), but you can use attribute/item-access (which in turn call the `.get(property)` method on a [`zmq.Frame`](https://pyzmq.readthedocs.io/en/20.0.0/api/zmq.html#zmq.Frame.get), which you get from `recv[_multipart](copy=False)`:

```python
msg_frames = await socket.recv_multipart(copy=False)
user_id = msg_frames[0]["User-Id"]
bytes_list = [frame.bytes for frame in msg_frames]
```
