### ISSUE TITLE
CPython 3.9 wheels

### ISSUE THREAD

**Issue by frenzymadness** [zeromq/pyzmq#1429]
Hello. Could you please release CPython 3.9 manylinux wheels on PyPI?

Python 3.9.0 final was released this week: https://www.python.org/downloads/release/python-390/

Thank You.

**Comment by tycarac** [comment]
All Python 3.9 wheels please.  Personally I am looking for the Windows 64-bit (amd64) wheel.

pyzmq is a dependency for installing **JupyterLab** and **Jupyter**

**Comment by minrk** [comment]
pyzmq Windows wheels are built on appveyor, which is still [waiting for Python 3.9](https://github.com/appveyor/ci/issues/3541). I'll try to work around it if they don't ship promptly.

**Comment by minrk** [comment]
wheels for cp39 on linux and mac are uploaded, Windows will have to wait a bit

**Comment by tycarac** [comment]
@minrk  Thanks
Shame about the Windows builds.  Now that Python has major releases each year, this will be an annual event.  
I will be looking for tools to help me understand the Python package dependency tree and the current available package builds.

**Comment by minrk** [comment]
I'll try to have it by the end of the week, I'm just busy through Tuesday.

Switching all CI and wheel building to GitHub actions should make this easier to keep updated. Appveyor has proved unreliable at prompt Python support.

**Comment by minrk** [comment]
pyzmq-19.0.2 now has a cp39 wheel for Windows.

**Comment by mostealth** [comment]
Only the 64 bits Windows wheel has been uploaded to pypi, however for the other versions both 32 and 64 bits are available.
Any chance to upload the missing one?
