### ISSUE TITLE
Idea - Add "bound" and "connected" context managers to Socket

### ISSUE THREAD

**Issue by randallpittman** [zeromq/pyzmq#1436]
I find it important at times to connect/disconnect a socket to an subscriber endpoint in an ephemeral manner. I made a simple subclass of Socket to do this in a `with` block:  https://gitlab.com/osu-nrsg/zmq-quicklink/-/blob/master/zmq_quicklink/__init__.py

Happy to do a PR if folks think this would be worth including in pyzmq.

**Comment by minrk** [comment]
Yeah, makes sense! I think you can make these context managers returned from the existing `bind`/`connect` methods without a real downside, I think. If you can think of a clear downside, then new methods are okay, too.
