### ISSUE TITLE
What is a suitable forum for pyzmq for video and audio communication using pyzmq

### ISSUE THREAD

**Issue by AnthonyTheKoala** [zeromq/pyzmq#1438]
I have three questions please on the pyzmq package and am very interested in the applications of the pyzmq package.

(1) On a web search one can find lots of information on using pyzmq wth a camera. Where can I find information on using pyzmq with a microphone and synchronizing both sound and audio using pyzmq?

(2) Where can I find information on using pyzmq with not only TCP/IP, but other protocols such as RTP, RTSP, VOIP?

Most grateful for an answer.

Thank you,
Anthony of Sydney

Thank you,
Anthony of Sydney

**Comment by minrk** [comment]
pyzmq is a wrapper around libzmq, which is probably where you will find the most information about using zeromq in different domains. libzmq talks bytes, so it doesn't really matter what sort of device or application your bytes come from, zeromq is a mechanism for distributing those bytes across the network.

pyzmq cannot support protocols that libzmq does not support, which generally means: tcp, udp, epgm. If you want to use other protocols, you would need to write an application that adapts those protocols using an appropriate library (e.g. twisted or some such) and adapt messages to be sent out over zmq.

**Comment by AnthonyTheKoala** [comment]
Kjære Benjamin, takk for svaret ditt (using google translate).
From your answer, it appears that pyzmq is 'protocol' independent.
I had a look at code applying pyzmq to a camera. 
To illustrate there is a demonstration of code using a camera and the zmq socket using TCP at https://www.pythonforthelab.com/blog/using-pyzmq-for-inter-process-communication-part-2/ . 
I would like to know if there is anything faster that TCP for a video camera as in this small snippet.
<pre>
import zmq
 from time import sleep
def publisher(queue, event, port):
    port_pub = port
    context = zmq.Context()
    with context.socket(zmq.PUB) as socket:
        socket.bind("tcp://*:%s" % port_pub)
 </pre>
That is why I ask about other protocols.
Thank you, danke, merci, obrigado, Takk skal du ha
Anthony of Sydney

**Comment by minrk** [comment]
pyzmq isn't protocol independent, it relies on libzmq's supported transports. Specifically, those listed above. You can try other options than tcp and see what performance you might get. e.g. epgm, udp, ipc.
