### ISSUE TITLE
sockets are not threadsafe

### ISSUE THREAD

**Issue by Viissataa** [zeromq/pyzmq#1443]
As the title says:

If one has a socket (ROUTER socket in this case) on blocking receive, and this socket is closed from another thread, instead of raising a python exception, the whole interpreter crashes, bringing all threads with it. 

While it is certainly the case that low level libraries cannot reasonably be expected to be as un-crashable as vanilla python itself, I was a bit surprised by this. A socket.close() is about the most classic example of a cross-thread function call I could come up with, so I would have expected a cleaner exit. 

Running in PyCharm the error produced is this:

```
Assertion failed: Connection reset by peer [10054] (bundled\zeromq\src\signaler.cpp:368)

Process finished with exit code 1073741845
```

A reproducer that is not so minimal, but reasonably short:
(Conditioning the receive loop on external namespace variable is a shorthand on what I was doing when discovering this. Not necessary on reproducing the bug)

```
import zmq
import queue
import threading
import time
import types

def make_zmq_socket(port):
    cntxt = zmq.Context()
    s = cntxt.socket(zmq.ROUTER)
    s.bind("tcp://*:{}".format(port))
    return s

def zmq_server_rcv(que:queue.Queue, sock:zmq.sugar.context.Socket, parent):
    sock.RCVTIMEO = 3000
    while parent.on:
        try:
            r = sock.recv_multipart()
            que.put(r)
        except zmq.error.Again:
            pass
        except:
            parent.on = False
            break

def close_conn(NS,zsock:zmq.sugar.context.Socket):
    NS.on = False
    try:
        zsock.close()
    except:
        pass

NS = types.SimpleNamespace()
NS.on = True
in_que = queue.Queue(100)
zsock = make_zmq_socket(5555)
t_receiver = threading.Thread(target=zmq_server_rcv, args=(in_que, zsock, NS), daemon=True)
t_receiver.start()

print("ping 1. {} threads alive.".format(threading.active_count()))
time.sleep(0.5)
close_conn(NS,zsock)
time.sleep(0.5)
print("ping 2. {} threads alive.".format(threading.active_count()))
time.sleep(0.5)
print("ping 3. {} threads alive.".format(threading.active_count()))
```

**Comment by minrk** [comment]
libzmq sockets, around with pyzmq Sockets are a very thin wrapper, are not threadsafe, as [is documented](https://pyzmq.readthedocs.io/en/latest/morethanbindings.html#thread-safety). If you want threadsafe access to sockets, you must use locks in your application code. In order for pyzmq itself to always be threadsafe, it would need to acquire a lock in every method call, a performance cost that I don't think we should be paying *by default*.

We could offer a convenience method, e.g. 

```python
with socket.lock:
    socket.send()
```

but I think the locks are always going to be explicit.

**Comment by Viissataa** [comment]
Thank you for the answer.
This indeed is the case, and as I experimented further, a feature with rather big consequences in python (not in C/C++).

Long story short: If one wants to construct a server which is connected to several clients, and can talk to those clients so that both parties can initiate talking, constructing a sound design becomes cumbersome, and rather ugly.

In the above situation, one wants to both listen a ROUTER socket, and be capable of sending to it, if the server process wants to. If latency is an issue we are concerned with, (and we should) this means that without polling, one has to loop around waiting and checking for sendable packets at about 100Hz. This is too much, and would be visible in system CPU usage even when nothing is happening. Using two sockets does not remove the issue, since client identifier is acquired upon receive.

Why "without polling" is important is because in pyzmq, Poller().poll() is only able to poll for sockets. This then necessitates that the poll() listens to two sockets, one of which is an internal auxiliary socket created just to pass notification triggers to the poller. The polling process can then for example be hinted that there is stuff to be pulled from some "send_queue".

I then ask, would it be a reasonable feature suggestion to enable Poller() the ability to poll for example queue.Queues, and threading Events? Anologous stuff is possible in C/C++ through file descriptors, but in python that is either impossible, or possible through some ctypes -hack that would be rely on undocumented features, and not constitute sound design.

I may have misunderstood something and all of the above is actually bs, but I'm rather confident this is the case.
