### ISSUE TITLE
Throughput fluctuations

### ISSUE THREAD

**Issue by cheind** [zeromq/pyzmq#1461]
Hey,

I'm currently benchmarking ZMQ/pyzmq for an application scenario that demands high throughput. For this reason, I created a minimal working example that computes throughput metrics and that runs either on bare OS or virtualized in docker containers (supporting different backends on Windows).

Interestingly enough, with the recent version of pyzmq (20.0.0), libzmq 4.3.3, python 3.8, I find
_ZMQ virtualized using docker (WSL2) on Windows achieves higher throughput than running on bare Windows (2x) or virtualized using Windows containers (10x)._

In particular 
|Os|Container Backend|Transport|Bytes/Sec|
|--|--|--|--|
|Ubuntu 20.4|Linux|TCP/IP|1.4GiB/Sec|
|Ubuntu 20.4|Linux|IPC|1.6GiB/Sec|
|Windows 10.1904|WSL2|ICP|1.5GiB/Sec|
|Windows 10.1904|WSL2|TCP/IP|1.5GiB/Sec|
|Windows 10.1904|Windows Container|TCP/IP|154.4MiB/sec|
|Windows 10.1904|no-container|TCP/IP|604.2MiB/sec|

I'm unsure if the reason for this lies within pyzmq, but would be happy about any additional insights. The source code + details are available here

https://github.com/cheind/zmqdockertest

**Comment by minrk** [comment]
Sorry for never responding. Closing here as not really actionable on this repo, but I don't know how to diagnose performance issues in Windows networking or containers. It's almost certainly better directed to libzmq than pyzmq.
