### ISSUE TITLE
pyzmq-20.0.0-cp39-cp39-win_amd64.whl does not have libzmq?

### ISSUE THREAD

**Issue by kozo2** [zeromq/pyzmq#1467]
It seems that
pyzmq-20.0.0-cp39-cp39-win_amd64.whl in https://pypi.org/project/pyzmq/#files does not have libzmq inside it.

![image](https://user-images.githubusercontent.com/12192/103669832-2f3e7380-4fbc-11eb-892d-c449bcb2bd25.png)

I tested this on Windows Sandbox.
You can reproduce this error with

1. Run Windows Sandbox
2. Download python-3.9.1-amd64 from python.org (and install it).
3. run Command Prompt and cd to the folder of python.exe
4. run `python.exe -m pip install pyzmq` in Command Prompt (Actually, in the above image, I installed jupyterlab).
5. run `python.exe -c "import zmq"`

Please tell me if there is anything that I can help with.

**Comment by minrk** [comment]
Thanks! I'm not sure how that happened. I've totally updated the CI infrastructure for building wheels and the 3.9 wheel [uploaded here](https://github.com/zeromq/pyzmq/suites/1598318904/artifacts/29116086) should work. I'll try to get a release built from the new infrastructure soon.

**Comment by kozo2** [comment]
I tried this wheel

![image](https://user-images.githubusercontent.com/12192/104217086-44b11300-547e-11eb-9855-140f05a7bd00.png)

but it failed as before

![image](https://user-images.githubusercontent.com/12192/104217014-2cd98f00-547e-11eb-842b-ecbc6baf08be.png)

**Comment by minrk** [comment]
I've been looking into this and libzmq is present, but `msvcp` is not in the cp39 wheel, meaning that  you need to have the [vc redist installed](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) for it to load properly. The mechanism used to bundle this in 3.5-3.8 doesn't work anymore in 3.9, but I'll be working on a fix

**Comment by kozo2** [comment]
I'm sorry, I forgot to tell it.
That's right.
After installing `Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019`, `pyzmq-20.0.0-cp39-cp39-win_amd64.whl` works well.

**Comment by minrk** [comment]
Fixed in #1470, I'll try to push updated wheels in the next week.

**Comment by QuLogic** [comment]
Is that fix only for 3.9? It appears wheels are broken for other Pythons ([pyzmq 20.0.0](https://ci.appveyor.com/project/matplotlib/matplotlib/builds/37260469/job/ylbx89uyc9n0652b) vs [pyzmq 21.0.0](https://ci.appveyor.com/project/matplotlib/matplotlib/builds/37267040/job/3b4wcdxj30qhk8su) on Python 3.7)

**Comment by minrk** [comment]
@QuLogic there was a different but related issue in 21.0.0 (#1472 , the first release from a new CI build system) that should be fixed for all supported Windows versions in 21.0.1. Unsupported Windows (e.g. Windows 7, which is more than 12 months past Extended Support EOL) is still known to have issues, but I haven't figured out a fix yet.
