### ISSUE TITLE
Provide socket.bind_to_random_port() as a contextmanager

### ISSUE THREAD

**Issue by cmarqu** [zeromq/pyzmq#1468]
Since v20.0.0 (https://github.com/zeromq/pyzmq/commit/6d74c684d4cf9e7994afe480c760c6ac9bed1cff), `bind()` and `connect()` can be used as contextmanagers - it would be nice if also `bind_to_random_port()` would be supported.

**Comment by minrk** [comment]
Indeed it does. Would you like to try a PR?
