### ISSUE TITLE
pep561 compliance

### ISSUE THREAD

**Issue by arnimarj** [zeromq/pyzmq#1477]
Hi. Just noticed that the package has started shipping type stubs (`pyi` extension). When trying to test this with my current projects I was unable to make mypy find the stubs. It seems that `py.typed` is missing. Its existence is a signal that the package is partially stubbed:

https://www.python.org/dev/peps/pep-0561/#partial-stub-packages

See https://github.com/maxmind/GeoIP2-python/pull/93/files for a similar fix in `geoip2`

If/when the project ships inline annotations this becomes unnecessary, I think.

**Comment by minrk** [comment]
Makes sense, thanks! Want to make the appropriate PR?

How did you discover that it didn't work? It would be handy to have a test, but everything I tried worked fine.

**Comment by arnimarj** [comment]
> Makes sense, thanks! Want to make the appropriate PR?
> 
> How did you discover that it didn't work? It would be handy to have a test, but everything I tried worked fine.

Hi. We have been maintaining our own set of stubs to help with the development of some internal libraries, and the test was simply to remove those stubs. I'll try to steal some time for this in the next few days. Cheers.

**Comment by arnimarj** [comment]
> Makes sense, thanks! Want to make the appropriate PR?
> 
> How did you discover that it didn't work? It would be handy to have a test, but everything I tried worked fine.

Hi. I just opened a PR here: https://github.com/zeromq/pyzmq/pull/1483
