### ISSUE TITLE
Documentation incorrectly implies Context isn't thread safe

### ISSUE THREAD

**Issue by ajasmin** [zeromq/pyzmq#1499]
According to the [documentation for zmq.Context.instance()](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Context.instance):

> Most single-threaded applications have a single, global Context. Use this method instead of passing around Context instances throughout your code.

This seems to imply that multithreaded applications would use more than one Context which shouldn't be required.

Indeed, the code for zmq.Context.instance() ensures thread-safety and the "inproc://" socket type requires multiple threads to share sockets created from a single context.

**Comment by minrk** [comment]
Indeed, the mention of single-threaded applications is not intended to indicate a lack of threadsafety. We could change that text to "single process" and be just as accurate, if you'd like to submit a PR.
