### ISSUE TITLE
PUB/SUB Suddenly Stops Sending and Receiving Data at Various Times

### ISSUE THREAD

**Issue by bkeng44** [zeromq/pyzmq#1503]
Hello,

My System Info:

libzmq-4.1.4
pyzmq-22.0.2
Python-3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]
Ubuntu 18.04.5 LTS
aarch64

I am running into an issue where my pub/sub architecture suddenly stops sending/receiving data. Sometimes this happens 15 seconds after I kick off my run, sometimes it wont happen for 30 minutes.

I've seen similar issues posted here:
[https://github.com/zeromq/libzmq/issues/2763](https://github.com/zeromq/libzmq/issues/2763)
[https://stackoverflow.com/questions/26112992/zeromq-pub-sub-on-unreliable-connection](https://stackoverflow.com/questions/26112992/zeromq-pub-sub-on-unreliable-connection)
[https://github.com/zeromq/libzmq/issues/1199](https://github.com/zeromq/libzmq/issues/1199)

The solutions posed in these threads don't get to the core of the issue however. I've setup a heartbeat monitor as recommend that allows me to see when I am no longer receiving data when it's expected, and I can reinitialize the PUB/SUB and continue getting data. However, I am constructing a real-time pipeline and consistent reinitializations are too disruptive to be a permanent solution.

I've also looked into adjusting the TCP_KEEPALIVE parameters and these changes are visible when inspecting the sockets via: netstat -anpo. However, transmission signals are never sent on the failures leading me to believe the connection is not actually broken.

Has anyone seen this issue before and had any success with a permanent fix?

Thanks!

**Comment by minrk** [comment]
I think zeromq/libzmq is a better place to ask about libzmq behavior.
