### ISSUE TITLE
Using zmq.asyncio.Context.instance creates a new instance rather than yield the existing one. 

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1515]
Hello :) 

I've been working with asyncio and inproc transport. I was not getting any messages through though. I managed to get a minimal test case working with dealer sending a simple string to the router. Here's the code for that...

```python
import zmq.asyncio

z_ctx = zmq.asyncio.Context()
z_ctx2 = zmq.asyncio.Context.instance()

print("ASYNCIO TEST ID(z_ctx) :", id(z_ctx))
print("ASYNCIO TEST ID(z_ctx2) :", id(z_ctx2))

dealer = z_ctx.socket(zmq.DEALER)
router = z_ctx.socket(zmq.ROUTER)

router.bind("inproc://thingy")
dealer.connect("inproc://thingy")

def test():
    
    dealer.send_multipart([b"Hi"])
    result = router.recv_multipart()
    print(result)

test()

z_ctx.destroy(linger=0)
z_ctx2.destroy(linger=0)
```

Here's the output of this code

> ASYNCIO TEST ID(z_ctx) : 5114289808
> ASYNCIO TEST ID(z_ctx2) : 5359901392
> <Future finished result=[b'\x00\xa6\xc7~^', b'Hi']>

What is interesting is that the id of each of the two contexts is different, but in the above code, I only use one to create both sockets. Now here is the code with a slight modification that causes no message to be received, as you can probably guess, I use z_ctx for the dealer, and z_ctx2 for the router

```python
import zmq.asyncio

z_ctx = zmq.asyncio.Context()
z_ctx2 = zmq.asyncio.Context.instance()

print("ASYNCIO TEST ID(z_ctx) :", id(z_ctx))
print("ASYNCIO TEST ID(z_ctx2) :", id(z_ctx2))

dealer = z_ctx.socket(zmq.DEALER)
router = z_ctx2.socket(zmq.ROUTER)

router.bind("inproc://thingy")
dealer.connect("inproc://thingy")

def test():
    
    dealer.send_multipart([b"Hi"])
    result = router.recv_multipart()
    print(result)

test()

z_ctx.destroy(linger=0)
z_ctx2.destroy(linger=0)
```

Now the output is 

> ASYNCIO TEST ID(z_ctx) : 5359899760
>ASYNCIO TEST ID(z_ctx2) : 5359901392
><Future pending cb=[_AsyncSocket._add_recv_event.<locals>.<lambda>() at /Users/jamescrowther/Library/Application Support/Blender/2.92/scripts/addons/crowdrender/lib/Darwin/3_7/zmq/_future.py:351]>

As you can see the router socket has not received anything as the returned future is still in the pending state. If I run an event loop to wait for the future to complete, it never returns, hanging the interpreter/thread.

I even tried swapping the contexts used for each of the sockets so that the router had z_ctx and dealer z_ctx2, but this made no difference, the same result happened. 

I am fairly sure this is not intended. The  [docs for zmq.Context.instance](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Context.instance) basically tell us that its better to use the instance method than to 'pass around' copies of the original context created in that thread. But, for asyncio at least, I cannot do this and get inproc sockets to work, as its been stated in [another issue](https://github.com/zeromq/pyzmq/issues/940#issuecomment-584080377), one cannot use two different contexts if you wish to get inproc sockets to work. 

So, I feel we're in need of a fix for this, or a change to the docs to state that for inproc/asyncio, you cannot use zmq.asyncio.Context.instance() to get a ref to the current threads global zmq context.

If I have missed this fact in the docs somewhere, I apologise ;) please point me to the right place and feel free to close this issue.

Best wishes

J

**Comment by minrk** [comment]
I think I must be confused - the title mentions `Context.instance()`, but the code sample doesn't use `Context.instance()`. It definitely won't do anything if you don't use it...

Using the `Context()` constructor, as is done here, does always return a new context, like all Python object constructors.

If you change your script to use `Context.instance()`:

```python
z_ctx = zmq.asyncio.Context()
z_ctx2 = zmq.asyncio.Context()
```

then `z_ctx is z_ctx2` and inproc should work just fine, since it is only for communication within a single context. With that change, your script gives me:

```
ASYNCIO TEST ID(z_ctx) : 140528841725328
ASYNCIO TEST ID(z_ctx2) : 140528841725328
<Future finished result=[b'\x00\x80\x00A\xa7', b'Hi']>
```

**Comment by Jeducious** [comment]
Hi Min my mistake, I've edited the code to make the second context use the instance method. I've re-run this test and the same result happens

```
ASYNCIO TEST ID(z_ctx) : 5055822160
ASYNCIO TEST ID(z_ctx2) : 5055820528
^C
Sent an internal break event. Press ^C again to kill Blender

Sent an internal break event. Press ^C again to kill Blender
Traceback (most recent call last):
  File "/more_asyncio_tests.py", line 31, in <module>
  File "/Applications/Blender.app/Contents/Resources/2.92/python/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/Applications/Blender.app/Contents/Resources/2.92/python/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/Applications/Blender.app/Contents/Resources/2.92/python/lib/python3.7/asyncio/base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "/Applications/Blender.app/Contents/Resources/2.92/python/lib/python3.7/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
Error: Python script failed, check the message in the system console
```

**Comment by Jeducious** [comment]
If the router socket uses the second z_ctx2 object, then I get the output in my last comment, and I have to Ctrl - C to get the terminal to respond again, it hangs my interpreter. If I just use z_ctx for both, then it returns the following

```
ASYNCIO TEST ID(z_ctx) : 5055881872
ASYNCIO TEST ID(z_ctx2) : 5057017808
<Future finished result=[b'\x00%P\xe2a', b'Hi']>
```

**Comment by minrk** [comment]
Yeah, it makes sense that if the two contexts are different inproc wouldn't work. Both contexts must use the instance method. `zmq.Context()` does not register a context as the global instance, only `instance()` does that. Using `zmq.Context()` means you *don't* want to use the global instance.

**Comment by Jeducious** [comment]
Thanks Min, that makes sense, and this works too, can confirm in my example above that if I do

```Python
z_ctx = zmq.asyncio.Context.instance()
z_ctx2 = zmq.asyncio.Context.instance()
```
in my example above, then the output is 

> ASYNCIO TEST ID(z_ctx) : 5151133424
> ASYNCIO TEST ID(z_ctx2) : 5151133424
> <Future finished result=[b'\x00\x85\xaa+J', b'Hi']>

The docs show an example, but the example didn't really drive this home to me, this idea of an instance method was new, and I thought I'd try it out. But I had become used to always creating a context somewhere that simply used zmq.Context(). The docs didn't mention that if I used zmq.Context(), then this would **not** create a global instance and I'd get these strange results.  

They just show this example

```Python
class MyClass(object):
    def __init__(self, context=None):
        self.context = context or Context.instance()
```
It might be worth mentioning that this is an either/or situation where if you intend to use global contexts then stick to using the instance method, unless you want one that is not global. Don't know why anyone would want that though as I seem to recall somewhere that said you should stick to one context object per process?

**Comment by minrk** [comment]
There are various scoping/threading reasons to use different contexts in a process in some advanced use cases (ensure everything around a task is cleaned up when it's done, avoid GIL interactions from the IO thread in a background device function, etc.)

But in general, one context for an application usually does make sense.

I'm not sure how to improve the docs around the global instance and Context() always returning a new context like any other constructor, but suggestions are certainly welcome. I'm going to close this issue as resolved.

**Comment by Jeducious** [comment]
Hi @minrk Had a thought about this, a bit late since the issue is closed, but I think a slight tweak to the layout of text and examples on the page would actually do the trick here. 

> Most single-threaded applications have a single, global Context. Use this method instead of passing around Context instances throughout your code.

```Python
context = zmq.Context.instance()
```
**Using zmq.Context() will always create a separate context to one generated by zmq.Context.instance()**

> A common pattern for classes that depend on Contexts is to use a default argument to enable programs with multiple Contexts but not require the argument for simpler applications:

```Python
class MyClass(object):
    def __init__(self, context=None):
        self.context = context or Context.instance()
```
