### ISSUE TITLE
Z85 decoding seems not correct

### ISSUE THREAD

**Issue by everthu** [zeromq/pyzmq#1517]
Hello,
I like to use the ZMQ decode function to properly decode an ascii85 string.
Encoding looks fine, however decoding gives another string than expected. Probably I do something wrong.
See next snippet:

def decode()
    client_public = \
    b"\xBB\x88\x47\x1D\x65\xE2\x65\x9B" \
    b"\x30\xC5\x5A\x53\x21\xCE\xBB\x5A" \
    b"\xAB\x2B\x70\xA3\x98\x64\x5C\x26" \
    b"\xDC\xA2\xB2\xFC\xB4\x3F\xC5\x18"
    encoded = z85.encode(client_public)
    decoded = z85.decode(encoded)
    print(decoded)

The output of this print in the definition is:
 b'\xbb\x88G\x1de\xe2e\x9b0\xc5ZS!\xce\xbbZ\xab+p\xa3\x98d\\&\xdc\xa2\xb2\xfc\xb4?\xc5\x18'

I had expected the same string as the client_public definition, however it is not completely the same. However it looks somewere I am thinking wrong.

Can somebody help me?

Evert Huijben

**Comment by minrk** [comment]
You can check with:

```python
decoded == client_public
```

and see that they are the same. You might be being tripped up by the fact that `b'\x47' and `b'G'` are the same byte, because Python byte reprs use the ascii char when a given byte is in the ascii range.

For consistent hex representation of bytes even when they are in the ascii range, you can use `bytes.hex()`:

```python
In [10]: b'\xbb\x88G\x1de\xe2e\x9b0\xc5ZS!\xce\xbbZ\xab+p\xa3\x98d\&\xdc\xa2\xb2\xfc\xb4?\xc5\x18'.hex()
Out[10]: 'bb88471d65e2659b30c55a5321cebb5aab2b70a398645c26dca2b2fcb43fc518'
```

**Comment by everthu** [comment]
Hi, thank you for the response, 
you are right, this is the issue, now I have correctly im
Some other question:
I have to convert a ascii string which is not a multiple of 5, so the decode function does not accept this string.
However the https://cryptii.com/pipes/z85-encoder side does encode this string correctly. Also the Java alternative does correctly decode the string.

I thought just adding '0' at the end of the string would resolve this issue, however the last byte seems not decoded correctly anymore in all situations.
Does someone has a solution for this?

**Comment by minrk** [comment]
Do you mean encode? All valid z85 strings are multiples of 5 chars in length. If it's not a multiple of 5 chars, it's not z85.

From [the spec](https://rfc.zeromq.org/spec/32/): 

> The binary frame SHALL have a length that is divisible by 4 with no remainder. The string frame SHALL have a length that is divisible by 5 with no remainder.
