### ISSUE TITLE
PyZMQ PUB-SUB Pattern duplicate order issue

### ISSUE THREAD

**Issue by Udayaprasad** [zeromq/pyzmq#1518]
I am facing a duplicate order issue in my current multi-threaded pub-sub model (multiple pub-sub services).

 In my current design, from the Publisher side, each thread has one publisher (having its own Zmq Context(), TCP port, and topic name) sending multipart messages to the assigned Subscriber (having its own Zmq Context() and listening to the same TCP port configured for publisher running in a different thread).

What I observed is, initially ` socket.recv_multipart() ` started well, after some time, it is downloading duplicate information meaning, duplicate order.

Environment:-
```
pyzmq-22.0.3
Python-3.8.5 
```

Publisher code:-

```    
def publish_frames(
            record_data):
        try:
            print(record_data)
            video = cv2.VideoCapture(0)
            frame_count = 0
            # ZMQ connection
            url = "tcp://{}:{}".format("0.0.0.0", str(record_data["port"]))
            print("Going to connect to: {}".format(url))
            ctx = zmq.Context()
            socket = ctx.socket(zmq.PUB)
            socket.bind(url)  # publisher connects to subscriber
            time.sleep(1.0)
            print("Pub connected to: {}\nSending data...".format(url))

            while video.isOpened():
                ret, frame = video.read()
                if ret:
                    frame_count += 1
                    print("Producer-", frame_count)
                    form_topic = 'topic-' + str(record_data["camera"])
                    topic = form_topic.encode('utf-8')
                    _, img_buffer_arr = cv2.imencode(".png", frame)
                    img_bytes = img_buffer_arr.tobytes()
                    header_dict = {"frameCount": str(frame_count),
                                   "zoneName": "Break Room Zone",
                                   "cameraName": "Break Room Camera",
                                   "timestamp": str(round(time.time()))}
                    socket.send_multipart([topic, str(header_dict).encode('utf-8'), img_bytes])  # 'test'.format(i)
                    # time.sleep(.5)
        except (KeyboardInterrupt, SystemExit):
            video.release()
            cv2.destroyAllWindows()
            error_message = str(traceback.format_exc())
            print(error_message)
        except Exception:
            error_message = str(traceback.format_exc())
            print(error_message)
        finally:
            video.release()
            cv2.destroyAllWindows()
            sys.exit()

        return record_data
```

Consumer Code:-

```
    def consumer_poll(self, record_data):
        url = "tcp://{}:{}".format("0.0.0.0", str(record_data["port"]))
        print("Going to bind to: {}".format(url))
        ctx = zmq.Context()
        socket = ctx.socket(zmq.SUB)
        socket.connect(url)  # subscriber creates ZeroMQ socket
        topic_name = 'topic-'+str(record_data["camera"])
        socket.setsockopt(zmq.SUBSCRIBE, topic_name.encode('utf-8'))  # any topic
        time.sleep(1.0)
        print("Sub bound to: {}\nWaiting for data...".format(url))

        while True:
            # wait for publisher data
            output = socket.recv_multipart()
            topic, headers, image = output[0].decode("utf-8"), eval(output[1].decode("utf-8")), output[2]
            img = cv2.imdecode(np.frombuffer(image, np.uint8), cv2.IMREAD_COLOR)
            print("Topic {}, Frame Number: {}".format(topic, headers["frameCount"]))
```

My current problem with the code is duplicate orders. Can anyone suggest how to avoid these duplicate ordering messages? 
Is there any setting for message Idompentance?

In the below image, you can see that, there are two sequences, starts from **434 and 22167**

![image](https://user-images.githubusercontent.com/8266316/113326456-50063300-9337-11eb-880d-20457ee438ca.png)

**Comment by minrk** [comment]
I'm sorry, I don't really understand the question or situation. The log messages are not produced by the code snippets given here, which makes it hard to debug anything, as I don't think the relevant code is included. I don't really know what "duplicate ordering" means or what message idempotence would mean in this context - when you send a message, that message is delivered exactly, in order (for a given socket pair) to the recipient.

From the looks of it, you have two concurrent publisher/subscriber instances, both using the same logger. There's nothing fundamentally wrong with that without knowing more about your application. It sounds like maybe your application started a new publisher-subscriber pair that you didn't intend? It seems unlikely that pyzmq is related to what's going on here.
