### ISSUE TITLE
[Clarification Request] Large messages and zmq proxy

### ISSUE THREAD

**Issue by Padarn** [zeromq/pyzmq#1519]
Hi, sorry I have a bit of basic question:

I have a system in which I want to use a proxy to connect multiple clients with multiple servers. The proxy would be used to solve the discoverability problem (and perhaps in the future handle load balancing?).

However my messages are very large. Is there a simple pattern to use that would avoid the actual message content going through the proxy, but directly between the client and server that the proxy connects?

**Comment by minrk** [comment]
If you only want to handle discoverability, you can have a standalone registry service that returns a collection URLs, and then have your clients talk directly to them - then no 'work' messages go through the proxy

- workers register themselves with the registry when they start, plus some kind of keepalive / shutdown if workers go away
- clients query the registry periodically (or registry publishes updates to clients)
- clients connect directly to workers

If you want the proxy to do load-balancing, that's harder. You might use your registry to implement the load balancing and on *every request* ask "where should I send this?" That adds a whole request-reply roundtrip to each message, increasing latency.
