### ISSUE TITLE
Request for an "--enable-drafts" release

### ISSUE THREAD

**Issue by Bootstrap360** [zeromq/pyzmq#1523]
The project I am working on requires "--enable-drafts" and would like to be able to deploy it either to my private pipe repository or make changes to this project's deploy stages. 

I am unsure as to how to do this correctly. Below is the script that I am using to deploy locally.

```bash
cd ~/Downloads && \
export ZMQ_VERSION=4.3.4 && \
export PREFIX=/usr/local && \
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && \
wget https://github.com/zeromq/libzmq/releases/download/v${ZMQ_VERSION}/zeromq-${ZMQ_VERSION}.tar.gz \
    -O libzmq.tar.gz && \
tar -xzf libzmq.tar.gz && \
cd zeromq-${ZMQ_VERSION} && \
./configure --prefix=${PREFIX} --enable-drafts && \
make -j && \
sudo make install && \
ZMQ_DRAFT_API=1 pip install -v --pre pyzmq --install-option=--enable-drafts --install-option=--zmq=/usr/local
```

@minrk Guidance as to how to change the wheels.yml file below would be great. 

https://github.com/zeromq/pyzmq/blob/f1db8e5c495057173380cae9e00cc160cb3bac4a/.github/workflows/wheels.yml#L39

**Comment by minrk** [comment]
I don't think this repo should publish drafts builds (at least not to PyPI). But if you wanted to base something on the existing CI workflow for you own deployments, you can enable drafts in libzmq [here](https://github.com/zeromq/pyzmq/blob/f1db8e5c495057173380cae9e00cc160cb3bac4a/tools/install_libzmq.sh#L53) and in pzymq by adding ZMQ_DRAFT_API=1 to the env for the wheel build [here](https://github.com/zeromq/pyzmq/blob/f1db8e5c495057173380cae9e00cc160cb3bac4a/.github/workflows/wheels.yml#L65-L70)

**Comment by xbotuk** [comment]
@minrk is it possible to include windows 64 and 32 bit builds with enable drafts so that we can test the web sockets? Building locally isn't smooth as most of the dependencies are missing if we are to try building locally each time?

**Comment by minrk** [comment]
I don't think it can be on PyPI, since pip doesn't have a way to distinguish them. They would need to be built and hosted somewhere else so they can be opt-in. I can't currently justify building and maintaining 36 additional wheels, which would be required to be fully supported in the current release pipeline.

I'd recommend building the wheel once and hosting your own wheelhouse for your projects, so you don't need to build every time. Modifying the github actions here is one way to do it, as I described above, since it uploads wheels as local assets.

**Comment by Bootstrap360** [comment]
@minrk

1. I know how to download and build zeromq with --enable-trafts
2. I know how to use python -m build --wheel and tarn to generate a .whl

I do not understand how to merge these two stages and succesfuly attach the outputs of step 1 to the wheel file of step 2. I have looked through the source code of pyzqm and your comment [here](https://github.com/zeromq/pyzmq/issues/1523#issuecomment-831735377) but was not able to follow your steps.

I have attached a zip file with a docker_run.sh script which runs and tests in a series of docker containers.

Files:
docker_run.sh: Entry point
Dockerfile_build: Docker file that builds and installs zeromq, builds a wheel file and runs test_zmq_client_server.py
Dockerfile_test: Loads the wheel file built inside Dockerfile_build an then re-runs test_zmq_client_server.py

[pyzmq_build_with_client_server.zip](https://github.com/zeromq/pyzmq/files/11749047/pyzmq_build_with_client_server.zip)

**Comment by minrk** [comment]
Here's a Dockerfile that builds a portable wheel with drafts (on arm, but other arches would be the same with different base images):

```dockerfile
# pick the manylinux image which has all the tools we want
# I'm on an ARM machine, so I chose aarch64
FROM quay.io/pypa/manylinux_2_28_aarch64
ARG LIBSODIUM_VERSION=1.0.18 \
    LIBZMQ_VERSION=4.3.4 \
    PREFIX=/usr/local

# install libzmq with libsodium
RUN curl -L -O "https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VERSION}.tar.gz"
RUN tar -xzf libsodium-${LIBSODIUM_VERSION}.tar.gz \
 && cd libsodium-${LIBSODIUM_VERSION} \
 && ./configure --prefix="$PREFIX" \
 && make -j4 \
 && make install

RUN curl -L -O "https://github.com/zeromq/libzmq/releases/download/v${LIBZMQ_VERSION}/zeromq-${LIBZMQ_VERSION}.tar.gz"
RUN tar -xzf zeromq-${LIBZMQ_VERSION}.tar.gz \
 && cd zeromq-${LIBZMQ_VERSION} \
 && ./configure --prefix="$PREFIX" --with-libsodium --disable-Werror --enable-drafts \
 && make -j4 \
 && make install

RUN ldconfig
# build the wheel
ENV PYZMQ_DRAFT=1 \
    ZMQ_PREFIX=$PREFIX
ENV PATH=/opt/python/cp310-cp310/bin:$PATH
RUN python3 -m pip wheel --no-binary pyzmq pyzmq

# (optional) bundle libzmq, libsodium into the wheel for portability
RUN auditwheel repair -w /wheels/ *.whl

FROM python:3.10
COPY --from=0 /wheels/ /wheels/
RUN python3 -m pip install /wheels/*.whl
```

It really is:

1. install libzmq with `--enable-drafts`, and
2. compile pyzmq with `PYZMQ_DRAFT=1` env set

and then optionally run `auditwheel repair` to bundle libzmq and libsodium into the wheel so they don't need to be on the destination system already.
