### ISSUE TITLE
async RCVTIMEO timeouts not cancelled upon successful recv

### ISSUE THREAD

**Issue by p4l1ly** [zeromq/pyzmq#1526]
Currently, when using asyncio, the RCVTIMEO timeouts are handled in the following way. In addition to setting the RCVTIMEO option of the socket, a *timeout* asyncio future is created for each `recv` (or `recv_multipart`). The timeout future references the zmq `_Future` and cancels it after the timeout if the `_Future` is not `done()`. Now, imagine a client with a `REQ` socket that cyclically receives a big message from a `REP` socket and handles it shortly. The message cannot be garbage collected because it is still referenced by the timeout future until the specified RCVTIMEO timeout passes. If RCVTIMEO is big and the receivings are frequent, the dangling messages referenced by the dangling timeout futures may consume a lot of memory.

### Current Solution

https://github.com/zeromq/pyzmq/blob/145746d8e96c3c36882d5a5e85891de3b959a04f/zmq/_future.py#L292

### Evidence

```
# server.py
import asyncio
import zmq
import zmq.asyncio


async def srv():
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.REP)
    sock.bind("tcp://127.0.0.3:5952")
    i = 0
    while True:
        print(i, flush=True)
        await sock.recv_multipart()
        await sock.send_multipart([b"." * 50000000])
        i += 1

asyncio.run(srv())
```

```
# client.py
import asyncio
import zmq
import zmq.asyncio
import gc
import linecache
import tracemalloc
import uvloop

uvloop.install()

def display_top(snapshot, key_type="lineno", limit=10):
    "return memory consumption log"
    snapshot = snapshot.filter_traces(
        (
            tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
            tracemalloc.Filter(False, "<unknown>"),
        )
    )
    top_stats = snapshot.statistics(key_type)

    ret = []
    ret.append("Top %s lines" % limit)
    for index, stat in enumerate(top_stats[:limit], 1):
        for line in stat.traceback.format():
            ret.append("#%s: %s:" % (index, line))
        frame = stat.traceback[0]
        ret.append(" " * 110 + "%.1f KiB" % (stat.size / 1024))
        line = linecache.getline(frame.filename, frame.lineno).strip()
        if line:
            ret.append("    %s" % line)

    other = top_stats[limit:]
    if other:
        size = sum(stat.size for stat in other)
        ret.append("%s other: %.1f KiB" % (len(other), size / 1024))
    total = sum(stat.size for stat in top_stats)
    ret.append("Total allocated size: %.1f KiB" % (total / 1024))
    return "".join(line + "\n" for line in ret)


async def client():
    ctx = zmq.asyncio.Context()
    sock = ctx.socket(zmq.REQ)
    sock.setsockopt(zmq.RCVTIMEO, 1000)  # by increasing this timeout, more memory is consumed
    sock.setsockopt(zmq.REQ_RELAXED, 1)
    sock.setsockopt(zmq.REQ_CORRELATE, 1)
    sock.connect("tcp://127.0.0.3:5952")

    tracemalloc.start()
    for i in range(20):
        print(i, flush=True)
        await sock.send_multipart([b""])
        await sock.recv_multipart()

        gc.collect()
        snapshot = tracemalloc.take_snapshot()
        print(display_top(snapshot, key_type='lineno', limit=1))

    await asyncio.sleep(2)

    gc.collect()
    snapshot = tracemalloc.take_snapshot()
    print(display_top(snapshot, key_type='lineno', limit=1))

asyncio.run(client())
```

### Proposal

`_FutureEvent` should reference its timeout future and it should cancel it upon successful receiving.

**Comment by minrk** [comment]
Excellent diagnosis! Proposal sounds quite sensible. Would you like to take a stab at a PR?

**Comment by p4l1ly** [comment]
Actually, my experience with pyzmq internals are almost as narrow as this diagnosis, so I'd maybe need some guidelines. But this does not seem very complicated. I'm going to create the PR in few minutes. Anyway, are you sure there's no easy better solution? So that there wouldn't be two timers, one in C and one in Python.

**Comment by minrk** [comment]
> Anyway, are you sure there's no easy better solution? So that there wouldn't be two timers, one in C and one in Python.

The C timer ought to never be used in asyncio, only the Python one. Because we wait for POLLOUT on the asyncio loop and always send with DONTWAIT, libzmq should never start its timers. We use the same socket options to start *equivalent* timers in Python, since we cannot use the C timer, which only allows for blocking calls, which we cannot use in asyncio (since doing that would block the event loop while waiting, an asyncio no-no).
