### ISSUE TITLE
Cannot set _fd "FD attribute is write-only" on PyPy, windows?

### ISSUE THREAD

**Issue by mattip** [zeromq/pyzmq#1533]
Any thoughts on this [stack-overflow question](https://stackoverflow.com/questions/67274218/error-while-choosing-pypy-as-jupyter-notebook-kernel) about trying to use a PyPy jupyter kernel on windows? The last few lines in the exception are
```
> in init_sockets
>     self.init_iopub(context)   File "C:\Users\plop1\PyPy3\site-packages\ipykernel\kernelapp.py", line 300,
> in init_iopub
>     self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)   File "C:\Users\plop1\PyPy3\site-packages\ipykernel\iostream.py", line
> 66, in __init__
>     self._setup_pipe_in()   File "C:\Users\plop1\PyPy3\site-packages\ipykernel\iostream.py", line 139,
> in _setup_pipe_in
>     self._pipe_in = ZMQStream(pipe_in, self.io_loop)   File "C:\Users\plop1\PyPy3\site-packages\zmq\eventloop\zmqstream.py", line
> 103, in __init__
>     self._fd = self.socket.FD   File "C:\Users\plop1\PyPy3\site-packages\zmq\sugar\attrsettr.py", line 57,
> in __getattr__
>     raise AttributeError("{} attribute is write-only".format(key)) AttributeError: FD attribute is write-only
```

**Comment by mattip** [comment]
Maybe because they are using PyPy 7.3.4? PyPy released 7.3.5 a few days ago.

**Comment by mattip** [comment]
It seems to be a real failure. I tried to [add a windows pypy CI run](https://github.com/mattip/pyzmq/pull/1) on my fork and ran into [that error](https://github.com/mattip/pyzmq/pull/1/checks?check_run_id=2659800732)

**Comment by cgohlke** [comment]
The cffi backend uses C `int` for Windows `SOCKET`, which is 64 bit on win_amd64. The correct type is `zmq_fd_t`. For example (but not limited to):

https://github.com/zeromq/pyzmq/blob/b33873ca76a0d9d9ff9a959e78d26f1c25f9d29c/zmq/backend/cffi/_cdefs.h#L59-L65
I'll submit a PR.
