### ISSUE TITLE
Question - I think installed libs for aarch64 are too big?

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1541]
I recently installed the aarch64 version of pyzmq using pip. 

```Python
dependencies ={'pyzmq':{'platform':{'Darwin_x86_64':'macosx_10_9_x86_64', 
                                    'Darwin_arm64':'macosx_10_15_universal2',
                                    'Win64':'win_amd64',
                                    'Linux_x86_64':'manylinux2010_x86_64',
                                    'Linux_aarch64':'manylinux2014_aarch64'}
                                     },
                'distro':{'platform':{'any':'any'}}
                                     }

for dep_name, dep in dependencies.items():
        proc = subprocess.Popen(
                            [sys.executable, '-m',
                             'pip', 'install',
                             '--target', parent_dir,
                             '--platform', platform_tag, 
                             #replace underscores as pip uses "37" not "3_7" for 
                             # major and minor versions of python
                             '--python-version', py_version.replace("_","",-1),
                             #default upgrade strategy is 'only_if_needed'
                             # see https://pip.pypa.io/en/stable/reference/pip_install/#options
                             '--upgrade',
                             '--progress-bar', 'pretty',
                             '--ignore-installed',
                             '--no-deps',
                             '--no-cache-dir',
                             '--only-binary',
                             ':all:',
                             dep_name])
```

I was packing them for a new build of our software, when I noticed that the aarch64 versions of the zmq packages were about double the size:

<img width="689" alt="Screen Shot 2021-05-31 at 1 04 14 pm" src="https://user-images.githubusercontent.com/34228929/120134562-bad9ca80-c211-11eb-994a-31a57056724d.png">

Just wanted to ask if this is normal/expected?

Thanks!

**Comment by minrk** [comment]
The aarch64 wheels bundle zeromq from EPEL, which has more dependencies than the x64 builds because it's built with some more feature flags enabled, so it makes sense that they are bigger. Looks like ~twice as big, which is not unreasonable, I think. It's conceivable some of these aren't stripped, though that would be a bit weird. I tried stripping the dylibs in the wheel after the fact, and it changes nothing about pyzmq's own extensions, so those are stripped. It did reduce the bundled dylibs a tiny bit (about 10% of dylibs, 5% total) but not a significant amount.

**Comment by Jeducious** [comment]
Ok, closing this issue then :) I just thought I'd ask since the size difference wasn't expected, but if you're expecting it (or not finding it as unexpected, hopefully this makes sense eh?) then no issue really. 

Thanks for responding :)

James
