### ISSUE TITLE
This library desperately needs a "Getting Started" section in the docs

### ISSUE THREAD

**Issue by void4** [zeromq/pyzmq#1542]
Just a basic client-server example

I often come back to this project but never know how to start again

I just found this: https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pair.html which should probably linked to in the readthedocs

**Comment by minrk** [comment]
The place to learn about using zeromq (including with pyzmq) is the [zmq guide](https://zguide.zeromq.org/docs/chapter1/), which has 91 pyzmq examples. I'll add a link to the docs.
