### ISSUE TITLE
Issues with zmq

### ISSUE THREAD

**Issue by ChandArya** [zeromq/pyzmq#1545]
I am using PUSH/PULL for sending data to multiple terminals at different ports. Here are the sender and receiver codes:

When the number of pull receivers increase the sender codes crash with the following errors:

**SENDER SIDE:**

```python
def create_push_socket(self, ip, port):
  # print('PUB')
  context = zmq.Context()
  socket = context.socket(zmq.PUSH)
  socket.setsockopt(zmq.LINGER, 1000)
  socket.setsockopt(zmq.SNDTIMEO, 1000)
  socket.setsockopt(zmq.SNDHWM, 0)
  zmq_address = "tcp://{}:{}".format(ip, port)
  socket.connect(zmq_address)
  return socket
objectname=create_push_socket('127.0.0.1',7001)
objectname.send_json(str(data))
```

**RECEIVER SIDE**

```python
def __init__(self):
  contextx = zmq.Context()
  self.subsocket = contextx.socket(zmq.PULL)
  self.subsocket.setsockopt(zmq.LINGER, 1000)
  self.subsocket.setsockopt(zmq.RCVTIMEO, 1000)
  self.subsocket.setsockopt(zmq.RCVHWM, 1000)
  self.subsocket.bind("tcp://127.0.0.1:7001")
  pass

x= json.loads(self.subsocket.recv_json())
```

1. Segmentation fault, core dumped.
2.  Invalid Pointer
3. Resource Temporarily unavailable
4. Assertion failed
5. Exception in thread
6. double free or corruption out
7. Bad adress 
8. Aborted (core dumped)

version :-
python =3.8.0
zmq=22.0.3
ubantu= 20.04

I am using UBUNTU 20.04 OS and tried libtcmalloc and many other things but unable to solve the error. When number of pull receivers are low then the frequency of crash decreases.

**Comment by minrk** [comment]
Do you have a complete example? This isn't enough information to reproduce an error. How has pyzmq been installed? Are there any additional processes or threads being used?

**Comment by Avv22** [comment]
> I am using PUSH/PULL for sending data to multiple terminals at different ports. Here are the sender and receiver codes:
> 
> When the number of pull receivers increase the sender codes crash with the following errors:
> 
> **SENDER SIDE:**
> 
> ```python
> def create_push_socket(self, ip, port):
>   # print('PUB')
>   context = zmq.Context()
>   socket = context.socket(zmq.PUSH)
>   socket.setsockopt(zmq.LINGER, 1000)
>   socket.setsockopt(zmq.SNDTIMEO, 1000)
>   socket.setsockopt(zmq.SNDHWM, 0)
>   zmq_address = "tcp://{}:{}".format(ip, port)
>   socket.connect(zmq_address)
>   return socket
> objectname=create_push_socket('127.0.0.1',7001)
> objectname.send_json(str(data))
> ```
> 
> **RECEIVER SIDE**
> 
> ```python
> def __init__(self):
>   contextx = zmq.Context()
>   self.subsocket = contextx.socket(zmq.PULL)
>   self.subsocket.setsockopt(zmq.LINGER, 1000)
>   self.subsocket.setsockopt(zmq.RCVTIMEO, 1000)
>   self.subsocket.setsockopt(zmq.RCVHWM, 1000)
>   self.subsocket.bind("tcp://127.0.0.1:7001")
>   pass
> 
> x= json.loads(self.subsocket.recv_json())
> ```
> 
> 1. Segmentation fault, core dumped.
> 2. Invalid Pointer
> 3. Resource Temporarily unavailable
> 4. Assertion failed
> 5. Exception in thread
> 6. double free or corruption out
> 7. Bad adress
> 8. Aborted (core dumped)
> 
> version :- python =3.8.0 zmq=22.0.3 ubantu= 20.04
> 
> I am using UBUNTU 20.04 OS and tried libtcmalloc and many other things but unable to solve the error. When number of pull receivers are low then the frequency of crash decreases.

Hello, what are the meanings of the following please?

```
  socket.setsockopt(zmq.LINGER, 1000)
  socket.setsockopt(zmq.SNDTIMEO, 1000)
  socket.setsockopt(zmq.SNDHWM, 0)
```
