### ISSUE TITLE
aarch64 grpc Python package must be imported _before_ pyzmq

### ISSUE THREAD

**Issue by hanxiao** [zeromq/pyzmq#1546]
This is a mirror of https://github.com/grpc/grpc/issues/26457, the problem is more likely on the `grpc` side, but I post it here again for reference.

---

### What version of gRPC and what language are you using?

grpcio 1.38, 
Python 3.7,3.8,3.9

### What operating system (Linux, Windows,...) and version?

Armv8 Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.7,3.8,3.9

### What did you do?

Here is a Dockerfile you can reproduce the bug

```dockerfile
# 3.7, 3.8, 3.9, all the same
ARG PY_VERSION=3.7

FROM python:${PY_VERSION}-slim

RUN pip install pyzmq grpcio

# zmq first and grpc second wont work!
# low-level error throws from the grpc package
# #5 0.217 free(): invalid pointer
# #5 0.219 Aborted
RUN python -c "import zmq, grpc"

# changing the order will work!
RUN python -c "import grpc, zmq"

```

Run docker build
```bash
docker buildx build --platform linux/arm64 -f bug.Dockerfile -t jinaai/grpcarm64:latest .
```

Will throw
```
------
 > [3/4] RUN python -c "import zmq, grpc":
#7 0.256 free(): invalid pointer
#7 0.257 Aborted
------
```

Notice that (1) the above low-level error is thrown from `grpc` (2) changing the import order will work
```diff
- RUN python -c "import zmq, grpc"
+ RUN python -c "import grpc, zmq"
```

### What did you expect to see?

I expect import orders should be completely irrelevant.

### Anything else we should know about your project / environment?

I found this bug when developing [Jina](https://github.com/jina-ai/jina), where `grpc` and `zmq` are used jointly. Note that this bug does not appear for `amd64` package.

For reference, I will post a mirror issue in pyzmq project page. But this bug seems more like a `grpc` bug rather than a `zmq` bug, as the error throws from `grpc`.

**Comment by minrk** [comment]
My guess is this is due to an incompatible version of some common shared-library dependency that is bundled in one or both wheels. I don't know a way to avoid it in general, other than skip the wheels and build pyzmq from source (`pip install --no-binary pyzmq pyzmq`).

**Comment by hanxiao** [comment]
thanks for the update. 

the issue has been addressed in https://github.com/grpc/grpc/issues/26279 grpc side will release a fix. I'm closing this issue.
