### ISSUE TITLE
Ayncio Socket instantiation creates event loop

### ISSUE THREAD

**Issue by gramhagen** [zeromq/pyzmq#1547]
When creating a socket object using asyncio a new event loop is started. i'm not an async expert but this was a bit surprising and led to some difficulty trying to embed async functionality into a class that initializes the socket in it's own init function.

here's a simple example (intentionally leaving out cleanup / error handling)...
the client side:
```
import zmq

if __name__ == "__main__":
    ctx = zmq.Context.instance()

    client = ctx.socket(zmq.REQ)
    client.connect("tcp://127.0.0.1:5555")
    client.send(b"ping")
    print(client.recv())
```

the server side
```
import asyncio
import zmq.asyncio

class Player:
    def __init__(self):
        self.ctx = zmq.asyncio.Context.instance()
        # this doesn't work!
        self.server = self.ctx.socket(zmq.REP)

    async def bounce(self):
        self.server.bind("tcp://*:5555")
        msg = await self.server.recv()
        print(msg)
        await self.server.send(b"pong")

if __name__ == "__main__":
    asyncio.run(Player().bounce())
```
this hangs I believe because aysncio.run doesn't seem to create an event loop before Player is instantiated or the async socket can't properly retrieve it.

I can either switch the main to do this:
```
    loop = asyncio.get_event_loop()
    loop.run_until_complete(Player().bounce())
    loop.close()
```

or I can create a separate async function to initialize the socket
```
class Player:
    def __init__(self):
        self.ctx = zmq.asyncio.Context.instance()
        self.server = None

    async def connect(self):
        if self.server is None:
            self.server = self.ctx.socket(zmq.REP)

    async def bounce(self):
        await self.connect()
        self.server.bind("tcp://*:5555")
        msg = await self.server.recv()
        print(msg)
        await self.server.send(b"pong")
```

Both approaches are easy to do, but it seems unintuitive that creating a socket would lead to this behavior. As I said I'm new to async, so perhaps this is expected. If not I'm wondering whether there is a better way to delay how the event loop is pulled in when you create a async socket object or a more standard way to initialize these objects in an object oriented setting.

**Comment by gramhagen** [comment]
I see there are similar issues already: #1255 #1296, maybe that's a good indication that either a change can be made to make avoid this scenario or documentation can be added to make it clear that this setup isn't valid?

**Comment by minrk** [comment]
Yeah, I think attaching later is probably the right thing to do. Then the question becomes: do we attach to a specific loop as soon as we need to (e.g. first send/recv), or do we put a call to `asyncio.get_event_loop()` in every method that needs it. The former has the same issue we have now, but delayed one loop later (e.g. two consecutive calls to `asyncio.run(socket.send())` still won't work), while calling `get_event_loop()` all the time seems wasteful and has the opposite problem: hooking up one socket to multiple loops without warning could have its own set of issues. But at least using it with `asyncio.run` should *usually* work.

**Comment by gramhagen** [comment]
is calling asyncioio.run consecutively typical? 

also, wondering if it's possible to push the responsibility for creating the event loop outside of the socket and use get_running_loop() instead of get_event_loop().

**Comment by minrk** [comment]
> is calling asyncio.run consecutively typical?

No, I don't think so. But that doesn't mean it doesn't happen. When implementing a sync api on top of an async one, it can happen. It's exactly the kind of thing people are doing now that doesn't work (calling methods that invoke the current loop, then using `asyncio.run()` to create a new one, which I think people often don't expect it to do).

> also, wondering if it's possible to push the responsibility for creating the event loop outside of the socket and use get_running_loop() 

That's a good idea, although our methods are not actually coroutines, they are future-returning functions, so e.g. `asyncio.run(socket.send())` wouldn't work if socket.send relied on `get_running_event_loop`. I'll think about whether there's a way to safely rely on `get_running_loop()`, but I think perhaps the exact cases that aren't working now might not work if we did that. They have short-circuilts to fire immediately without waiting an eventloop tick, which is an important performance issue.

**Comment by minrk** [comment]
#1551 defers event loop retrieval to every method call, rather than init time. I tried `get_running_loop`, but since it means `asyncio.run(poller.poll())`  won't work, I don't think it's the right approach.

**Comment by gramhagen** [comment]
So are the options now just try to delay it to the first send/receive to cover a few more standard use-cases and/or add more documentation to identify what requirements are around setting up the event loop?

**Comment by minrk** [comment]
#1551 takes the approach to always retrieve the current loop, so it should work with consecutive `asyncio.run()` calls, etc. Anywhere you call an async method should work after that.

**Comment by gramhagen** [comment]
Oh, sorry I misunderstood that. Thanks, and let me know if I can do anything to test or document.

**Comment by minrk** [comment]
Awesome, thank you! If you want to take #1551 for a spin and make sure it works for you, I think I can land it and everything should work in a more expected manner now. If you find somewhere in the docs where you think caveats and explanations would help, that's always welcome.
