### ISSUE TITLE
Executables generated with pyinstaller do not import json correctly

### ISSUE THREAD

**Issue by dnltz** [zeromq/pyzmq#1548]
Hey,

I wrote a Qt5 application which uses pyzmq. If I start the app with the Python interpreter, everything works and I can use the package. I just tried to create an executable from the app and run into the following problem:
```
Traceback (most recent call last):
  File "src/controller/connections.py", line 42, in keyPressEvent
    self.openMainWindow()
  File "src/controller/connections.py", line 37, in openMainWindow
    self.main = MainController(self.model.getData())
  File "src/controller/main.py", line 59, in __init__
    success, result = server.isConfigured()
  File "src/server.py", line 30, in isConfigured
    return self._send_command('status')
  File "src/server.py", line 54, in _send_command
    self.socket.send_json(command)
  File "zmq/sugar/socket.py", line 758, in send_json
  File "zmq/utils/jsonapi.py", line 41, in dumps
AttributeError: 'NoneType' object has no attribute 'dumps'
Fatal Python error: Aborted

Current thread 0x00007f5d7df99b80 (most recent call first):
  File "athena.py", line 11 in main
  File "athena.py", line 17 in <module>
Aborted (core dumped)
```
Seems like the jsonapi module is unable to import one of these three packages. Even install simplejson does not fix the issue. Here is a complete list of the packages:
```
altgraph==0.17
appdirs==1.4.3
CacheControl==0.12.6
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.3
contextlib2==0.6.0
distlib==0.3.0
distro==1.4.0
html5lib==1.0.1
idna==2.8
importlib-metadata==4.5.0
ipaddr==2.2.0
lockfile==0.12.2
msgpack==0.6.2
packaging==20.3
pep517==0.8.2
progress==1.5
pyinstaller==4.3
pyinstaller-hooks-contrib==2021.1
pyparsing==2.4.6
PyQt5==5.14.2
PyQt5-sip==12.7.2
pytoml==0.1.21
PyYAML==5.3.1
pyzmq==22.1.0
requests==2.22.0
retrying==1.3.3
six==1.14.0
typing-extensions==3.10.0.0
urllib3==1.25.8
webencodings==0.5.1
zipp==3.4.1
```

BTW: The executable was generated in a virtual environment using py37 on an Ubuntu 20.04.

Does anyone have used pyzmq in combination of pyinstaller recently? I read py38 is not supported, so I downgraded to 3.7 and also upgraded to the latest zmq version without success.

**Comment by minrk** [comment]
This is not an issue with pyzmq. This eror means pyinstaller is stripping modules too aggressively, and failing to detect what's actually required. It should make sure to include json from the standard library.

**Comment by dnltz** [comment]
Ah, thanks! Adding json as hidden import to pyinstaller actually fixed this. Thanks for your help!
```
pyinstaller --onefile athena.py --hidden-import json
```
Should I document this somewhere?

**Comment by minrk** [comment]
Glad you found it!

**Comment by minrk** [comment]
> Should I document this somewhere?

It's a general pyinstaller issue that any optional imports are often not found and need to be added explicitly. I'm not sure pyinstaller-specific recommendations have a place in pyzmq docs. For instance, json is *not* required by pyzmq unless you are using the JSON methods. I've removed the optional import logic in #1549, which should avoid this particular case, at least.
