### ISSUE TITLE
22.1.0: pytest is failing (circular import in zmq code?)

### ISSUE THREAD

**Issue by kloczek** [zeromq/pyzmq#1550]
Just normal build, install and test cycle used on building package from non-root account:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to setearch and sitelib inside </install/prefix>
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-zmq-22.1.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-zmq-22.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ PYTHONDONTWRITEBYTECODE=1
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, cases-3.6.1, flaky-3.7.0, hypothesis-6.14.0, benchmark-3.4.1, xdist-2.3.0, Faker-8.8.1
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:783: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
zmq/__init__.py:103: in <module>
    from zmq import backend
zmq/backend/__init__.py:32: in <module>
    raise original_error from None
zmq/backend/__init__.py:27: in <module>
    _ns = select_backend(first)
zmq/backend/select.py:32: in select_backend
    mod = import_module(name)
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
zmq/backend/cython/__init__.py:6: in <module>
    from . import (
E   ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/zmq/backend/cython/__init__.py)
========================================================================= short test summary info ==========================================================================
ERROR  - ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/home/tkloczko/rpmbui...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.60s =============================================================================
```

**Comment by kloczek** [comment]
The same error shows setuptools `build_spjhinx` command (below is executed after `build`)
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/docs/source/conf.py", line 70, in <module>
    import zmq
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/zmq/backend/__init__.py", line 32, in <module>
    raise original_error from None
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/zmq/backend/select.py", line 32, in select_backend
    mod = import_module(name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/home/tkloczko/rpmbuild/BUILD/pyzmq-22.1.0/zmq/backend/cython/__init__.py)
```

**Comment by minrk** [comment]
This is frustrating, because there is definitely *not* a circular import, and Python is hiding the real error (almost certainly a failed dylib load) to give an inaccurate error message.

I f you have a dockerfile or something portable to reproduce the error, that would help me track it down. I haven't been able to reproduce this yet, personally.

Can you test with pyzmq==21.* and pyzmq==20.* to see if you get the same results and/or share full build output as well?

**Comment by kloczek** [comment]
I've been thinking that it could be issue with pytest.
Here is pyerst developer comment https://github.com/pytest-dev/pytest/issues/8731#issuecomment-863895943
(will try have look on that one more time tomorrow)

**Comment by minrk** [comment]
I don't think it's related to pytest. I have done some testing, and this is the error message that Python gives starting in 3.8 if *any* `from . import x` fails.

You can verify with:

```python
# testpkg/__init__.py
from . import nosuchfile
```

where `python -c import testpkg` gives the error

```
ImportError: cannot import name 'nosuchfile' from partially initialized module 'testpkg' (most likely due to a circular import) (/Users/minrk/dev/zmq/pyzmq/testpkg/__init__.py)
```

making a wild, *misleading* guess at what caused the error.


Where the older, more direct message in Python 3.7 would be:

```
ImportError: cannot import name 'nosuchfile' from 'testpkg' (/Users/minrk/dev/zmq/pyzmq/testpkg/__init__.py)
```

more directly indicating that there is no such module to import.

I *have* however found that it does not seem to occur when a DLL load fails. This tells me that you are probably running `python -m pytest` (which puts the current directory on sys.path, unlike a direct `py.test` invocation), but haven't done an `--inplace` build, which must be done if you want to test a development install.

If you are doing a regular install and want to run the tests, you must not have the repo dir on sys.path. The simplest version of this is to `cd` to a different directory before running the tests:

```bash
cd /tmp
py.test -v --pyargs pyzmq.tests
```

**Comment by kloczek** [comment]
FYI I found that issue because I've been working on my own rpm package.
Typical process preparation of the python module resources consist of:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

So this is why you see on top line with setting $PYTHONPATH 
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-zmq-22.1.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-zmq-22.1.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
```
And in my packages I'm trying to have always %check section which executes package test suite. That part is very important because with that condition in I was able to catch maaany bugs in packages and not always in packaged resources but sometimes in software already packaged and installed in build env.

Issue is that many modules looks like have been tested with assumption that would be at least used files from build/lib (prepared by "setyp.py build" but all files in source tree.

Nevertheless don't worry to much. I'm not expecting that it is any bug per se in your module. I'm almost sure that it is only issue with testing procedure. As I've just packaged your module it would be good to have working test suite to have kind of correctly working "base line" which will be important when whole distribution will be changing in future :)

> I have however found that it does not seem to occur when a DLL load fails. This tells me that you are probably running python -m pytest (which puts the current directory on sys.path, unlike a direct py.test invocation), but haven't done an --inplace build, which must be done if you want to test a development install.

No I'm not using `python -m pytest` because it adds upfront $PWD to python `sys.path`. Intention is not to test source tree but actual resources at least prepared in build/lib-<os>.<arch> it installed in --root </install/prefix>.
Using `--inplace` cannot help with that kind of methodology. That exactly methodology is recommended by pytest developers And I've learned about only that when I've opened https://github.com/pytest-dev/pytest/issues/8731. Up that moment I've been using always `python -m pytest` because I've been thinking that that could be independent from python binary, but I was wrong because I didn't know that running pytest script and `python -m pytest` caused that in booth cases pytest is behaving not the same way.

**Comment by kloczek** [comment]
> If you are doing a regular install and want to run the tests, you must not have the repo dir on sys.path

That exactly guarantees execution of the pytest script (usually /usr/bin/pytest)

**Comment by minrk** [comment]
Thanks for explaining. Okay to close? Doesn't sound like there's anything left to do here.

**Comment by kloczek** [comment]
So moment .. how to solve that circular dependency issue?

**Comment by kloczek** [comment]
https://www.overcoded.net/django-circular-imports-153910/

**Comment by minrk** [comment]
There is no circular dependency, that's a completely spurious error message from Python that happens when files are missing. The issue is that an incomplete zmq is being imported, e.g. by having the repo dir on sys.path. When this is failing, double check what `__file__` is, e.g. by launching the test in a debugger (`pytest --pdb --pyargs zmq.tests`)

**Comment by kloczek** [comment]
So where is the bug?

**Comment by minrk** [comment]
The bug is in how pyzmq is installed and/or how pytest is being invoked, because pyzmq is being imported from a location that doesn't actually have a complete installation of the package, most likely the repo itself. You can follow the steps I gave to try to figure this out (see `__file__` or launch pdb).

**Comment by kloczek** [comment]
Could you please open issue ticket for `pyzmq`?
I think that it would be easier explain nature of that issue to `pyzmq` maintainer :)

**Comment by minrk** [comment]
I don't know where you are asking for a ticket to be opened, since it's not a pyzmq issue.

The issue is that both the docs build and the pyzmq tests are being invoked in ways that put the current working directory on sys.path, while being run from a directory containing the source code which can't be imported without doing an in-place build.

1. for tests, make sure to run `pytest --pyargs zmq.tests`, and/or cd to a temp directory to be safe
2. for docs, make sure to `cd docs` before building

**Comment by iUnknwn** [comment]
This seems to affect the doc building procedure as well, and seems to occur from the docs directory. It can be reproduced by the following steps from a clean checkout (Ubuntu 20.04).

```
git clone https://github.com/zeromq/pyzmq/
cd pyzmq/docs
python3 -m venv ./venv
. ./venv/bin/activate
pip install -r requirements
make
```

This will generate the circular dependency error:
```
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v4.1.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/USERNAME/pyzmq/docs/venv/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
    exec(code, namespace)
  File "/home/USERNAME/pyzmq/docs/source/conf.py", line 71, in <module>
    import zmq
  File "/home/USERNAME/pyzmq/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/USERNAME/pyzmq/zmq/backend/__init__.py", line 32, in <module>
    raise original_error from None
  File "/home/USERNAME/pyzmq/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/USERNAME/pyzmq/zmq/backend/select.py", line 32, in select_backend
    mod = import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/USERNAME/pyzmq/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/home/USERNAME/pyzmq/zmq/backend/cython/__init__.py)

make: *** [Makefile:58: html] Error 2
```

Is there a more correct way to build the docs?

**Comment by minrk** [comment]
Building the docs assumes an inplace build (`pip install -e .`) has been run first. I've never seen `setup.py build_sphinx`, I guess that's provided by setuptools. I'd recommend following standard steps:

```
pip install -e .
cd docs
pip install -r requirements.txt
make html
```

**Comment by kloczek** [comment]
> Building the docs assumes an inplace build (`pip install -e .`) has been run first. I've never seen `setup.py build_sphinx`, I guess that's provided by setuptools. I'd recommend following standard steps:

```console
[tkloczko@ss-desktop docs]$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v4.3.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/pyzmq-22.3.0/docs/source/conf.py", line 18, in <module>
    from buildutils.bundle import bundled_version
ModuleNotFoundError: No module named 'buildutils'
```
So here is definitely one issue to solve.
`buildutils` is no longer maintained (last release was 15~ y ago) and it uses `distutils` which is already marked as deprecated.

**Comment by minrk** [comment]
is `conf.py` modified in any way? Or the repo contents? buildutils is a local package in the top-level of the pyzmq repo, added to sys.path [here](https://github.com/zeromq/pyzmq/blob/8318ab8982fe86fc1f9cc65df61e6e8f5fb5d6f8/docs/source/conf.py#L21). This import failure means that either the CWD is not what it should be, or the contents of he repo dir have been modified, or something else has resulted in non-standard Python import behavior.

For reference, here's a Dockerfile showing complete steps to build pyzmq and the docs. It really is the exact commands I gave above to build from a completely fresh environment:

```dockerfile
FROM ubuntu:20.04
RUN apt-get -y update && apt-get -y install python3-pip libzmq3-dev wget
ARG VERSION=22.3.0
RUN wget https://pypi.io/packages/source/p/pyzmq/pyzmq-${VERSION}.tar.gz \
 && tar -xzf pyzmq-${VERSION}.tar.gz
WORKDIR pyzmq-${VERSION}
RUN python3 -m pip install --upgrade pip
# install pyzmq
RUN python3 -m pip install -e .
# build docs
RUN cd docs \
 && pip install -r requirements.txt \
 && make html
```
