### ISSUE TITLE
FATAL ERROR: OUT OF MEMORY 

### ISSUE THREAD

**Issue by RichardLions** [zeromq/pyzmq#1555]
Hello

I am trying to debug a python load test package called Locust.

It creates a ROUTER and several DEALERs. The ROUTER often crashes due to this assert: warning : FATAL ERROR: OUT OF MEMORY (C:\projects\libzmq\src\decoder_allocators.cpp:85)

It is setup to use zmq.green.

This is running on a windows machine using localhost.

pyzmq version 22.1.0

I doubt this is something wrong with pyzmq. What sort of misuse could cause such an error to be thrown?

Thanks

**Comment by Matthew--Townsend** [comment]
I have the same issue with Locust and version 22.1.0 of pyzmq.  I am new to using it so I don't have any idea if other versions have worked.

python 3.9.5
locust 1.5.3
pyzmq 22.1.0

FATAL ERROR: OUT OF MEMORY (C:\projects\libzmq\src\decoder_allocators.cpp:85).

**Comment by minrk** [comment]
The call that's failing is [malloc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/malloc). I'm not an expert in Windows memory management. But possible causes include:

- allocating a very large message (larger than _HEAP_MAXREQ), which is ~ 4 GB when run under win32
- failure to deallocate messages (they could be queued in memory if they cannot be delivered, or they might not be freed properly)

Unfortunately, it's hard to say much without reproducible test cases.

**Comment by RichardLions** [comment]
Hello

I believe the issue is std::size_t shared_message_memory_allocator::_max_counters is being overridden by mistake from somewhere.

I wrote some debug to output the values of _max_counters when calls to shared_message_memory_allocator are made. The normal value should be 249 however it changes to large values such as 1947977969464. The value it changes to is never the same each test but is always very large. The assert does not trigger when _max_counters changes. The value can be in a malformed state for most of the applications lifetime. If an allocation is made it will use the large _max_counters which triggers the assert due to trying to allocate an incredibly large amount of memory.

Note: _max_counters can actually be made const. When doing so the value stops become malformed but I suspect this is the compiler hiding the memory override somehow.

I have attached a small folder for VSCode that will reproduce the issue. It is about 1/5 repro rate for the assert. However most runs will malform _max_counters.

[libzmq_repro.zip](https://github.com/zeromq/pyzmq/files/6771022/libzmq_repro.zip)

**Comment by minrk** [comment]
@bluca this sounds like a libzmq bug to me. Any idea what could be writing weird values to `_max_counters`?

**Comment by bluca** [comment]
check the usual suspects first - multithreading, etc

**Comment by RichardLions** [comment]
https://github.com/zeromq/pyzmq/pull/1560

I have added the above pull request to fix this issue.

**Comment by Matthew--Townsend** [comment]
I have implemented your change to core.py locally on my box in C:\Program Files\Python39\Lib\site-packages\zmq\green\core.py.  After doing so, the out of memory issues that I was getting with locust (uses pyzmq) are gone.  Thanks for finding and fixing (or at least working around)!
