### ISSUE TITLE
What is 'python bindings for ØMQ' means?

### ISSUE THREAD

**Issue by GuardianRain** [zeromq/pyzmq#1559]
Hello, I have some questions about 'python bindings for ØMQ' , may anybody help me with that? I am very grateful.
What is 'python bindings for ØMQ' means? 
Does it mean pyzmq is a python version to replace ØMQ？
Does pyzmq work correct without installing libzmq, when running neutron process?
I build pyzmq with libzmq installed, but running neutron without libzmq installed, and I havn't find any abnormal about neutron，does it mean pyzmq needn’t libzmq when running? Libzmq is needed just when build the pyzmq ?

Looking forward to your reply，thank you very much.

**Comment by minrk** [comment]
"bindings" means a wrapper around another  library, in this case libzmq. pyzmq doesn't replace libzmq, it wraps it in a Python API. pyzmq does need libzmq.

> Does pyzmq work correct without installing libzmq, when running neutron process?

I don't know about neutron, but if you install pyzmq from a wheel, it includes libzmq as well. pyzmq cannot work without libzmq, but installing pyzmq usually means installing libzmq as well, if it's not already present.

**Comment by GuardianRain** [comment]
> "bindings" means a wrapper around another library, in this case libzmq. pyzmq doesn't replace libzmq, it wraps it in a Python API. pyzmq does need libzmq.
> 
> > Does pyzmq work correct without installing libzmq, when running neutron process?
> 
> I don't know about neutron, but if you install pyzmq from a wheel, it includes libzmq as well. pyzmq cannot work without libzmq, but installing pyzmq usually means installing libzmq as well, if it's not already present.

Okey, I see. Thank you very much!
