### ISSUE TITLE
How to create a mutable numpy array from a non-copying recv?

### ISSUE THREAD

**Issue by ronawho** [zeromq/pyzmq#1566]
[serialsocket.py](https://github.com/zeromq/pyzmq/blob/c02e8a1094be8d817020af221a283176ff22eed5/examples/serialization/serialsocket.py) has an example of how to recv a numpy array, but this doesn't seem to work with the cffi backend. Running this example or [test_buffer_numpy](https://github.com/zeromq/pyzmq/blob/f0b60e2e9cfc0d51b4db0f24c7d795bd94d79c1f/zmq/tests/test_message.py#L306-L335) under PyPy I see errors like:

```python
Traceback (most recent call last):
  File "examples/serialization/serialsocket.py", line 78, in <module>
    main()
  File "examples/serialization/serialsocket.py", line 70, in main
    C = req.recv_array(copy=False)
  File "examples/serialization/serialsocket.py", line 47, in recv_array
    A = numpy.frombuffer(msg, dtype=md['dtype'])
TypeError: 'Frame' does not support the buffer interface
```

[serialization.rst](https://github.com/zeromq/pyzmq/blob/c02e8a1094be8d817020af221a283176ff22eed5/docs/source/serialization.rst) has a slightly different example that explicitly wraps the `Frame` with a `memoryview`, but that fails in a similar manner under PyPy. Wrapping with a `memoryview` also makes the numpy array readonly with the cython backend.

Using `Frame.buffer` seems to work for both backends, but it also seems to create a readonly array with the cython backend. e.g.:

```diff
diff --git a/examples/serialization/serialsocket.py b/examples/serialization/serialsocket.py
index 824f02b..5a5e766 100644
--- a/examples/serialization/serialsocket.py
+++ b/examples/serialization/serialsocket.py
@@ -43,7 +43,7 @@ class SerializingSocket(zmq.Socket):
     def recv_array(self, flags=0, copy=True, track=False):
         """recv a numpy array"""
         md = self.recv_json(flags=flags)
-        msg = self.recv(flags=flags, copy=copy, track=track)
+        msg = self.recv(flags=flags, copy=copy, track=track).buffer
         A = numpy.frombuffer(msg, dtype=md['dtype'])
         return A.reshape(md['shape'])

@@ -72,6 +72,7 @@ def main():
     print("Okay" if (A == B).all() else "Failed")
     print("Checking send_array...")
     print("Okay" if (C == B).all() else "Failed")
+    print("numpy readonly={}".format(memoryview(C).readonly))


 if __name__ == '__main__':
```

```
pyzmq (main) $ python3 examples/serialization/serialsocket.py
...
Checking send_array...
Okay
numpy readonly=True

pyzmq (main) $ pypy3.7 examples/serialization/serialsocket.py
...
Checking send_array...
Okay
numpy readonly=False
```

So I'm wondering how to create a mutable numpy array from a non-copying recv.

A simple fix might be to change https://github.com/zeromq/pyzmq/blob/c02e8a1094be8d817020af221a283176ff22eed5/zmq/backend/cython/message.pyx#L221 to be `buffer.readonly = 0` and use the above `.buffer` code in the examples/tests. Or maybe in addition fix the buffer interface support for `Frame` under the cffi backend? (I'm not sure what's involved with that)

I was also wondering if it's worth adding numpy to CI testing, but I wasn't sure if that would add too much time.

Here are my version details:

<details>

cpython/cython:

```
libzmq-4.3.4
pyzmq-22.2.0.dev
Python-3.8.6 (default, Nov 30 2020, 10:09:44)
[Clang 10.0.1 (clang-1001.0.46.4)]
```

pypy/cffi:
```
libzmq-4.3.4
pyzmq-22.2.0.dev
Python-3.7.10 (77787b8f4c49, May 19 2021, 05:28:43)
[PyPy 7.3.5 with GCC Apple LLVM 12.0.5 (clang-1205.0.22.9)]
```

</details>

**Comment by ronawho** [comment]
Fixing the buffer interface for `Frame` with the cffi backend ended up being pretty straightforward -- https://github.com/zeromq/pyzmq/pull/1567 should address that. Enabling numpy for CI testing adds 5-10 minutes, which seems like a lot given the current 10 minute timeout so I opted to add a standalone memoryview test in that PR instead.

I think my last remaining question is whether there's any reason for the cython backend to make the memoryview readonly.

**Comment by minrk** [comment]
> I think my last remaining question is whether there's any reason for the cython backend to make the memoryview readonly.

It was a choice made long ago because libzmq could still be using that memory and it may be unsafe to edit, e.g. sending the frame then modifying the memory could result in a corrupted message because send is actually async and the memory is shared.

However, I now think enforcing that in the flags was a mistake, especially since most of the time when you recv a message you aren't going to re-send it, so that issue doesn't apply to buffers created by pyzmq. So if you want to change the flag to read-write, that would be fine with me.

**Comment by ronawho** [comment]
Gotcha, thanks for the explanation. https://github.com/zeromq/pyzmq/pull/1569 makes this change.
