### ISSUE TITLE
Memory leak on subscriber with no copy after accessing buffer attribute of the received frame 

### ISSUE THREAD

**Issue by jmspereira** [zeromq/pyzmq#1582]
Hello everyone,

I use pyzmq in my application, and I started to notice an increase in the memory usage in the subscribers after running the application for a long time. After some digging, I reduced the leak to pyzmq and I can show a small contained example to reproduce the problem. This was only tested in Linux, with the latest 22.2.1 and 22.1.0 library versions in Python 3.8, and to see the leak you just need to open a system monitoring tool to see the subscriber memory increasing. Note that the problem does not exist if I set `copy=True` in the subscriber or even with `copy=False` but without accessing the buffer attribute. 

Publisher:
```
import time
import numpy as np
from zmq import Context, PUB, NOBLOCK, Socket

socket_handler: Socket = Context.instance().socket(PUB)
socket_handler.bind('tcp://127.0.0.1:5555')

msg = np.random.randint(0, 255, (1280, 720, 3), dtype=np.uint8).tobytes()

while True:
    socket_handler.send_multipart((b"abc", msg), NOBLOCK, copy=False)
    time.sleep(1)
```

Subscriber:
```
from zmq import Socket, Context, SUB, SUBSCRIBE

socket_handler: Socket = Context.instance().socket(SUB)
socket_handler.setsockopt(SUBSCRIBE, b"")
socket_handler.connect('tcp://127.0.0.1:5555')

while True:
    content = socket_handler.recv_multipart(copy=False)
    print(content[1].buffer)
```

**Comment by minrk** [comment]
What if you add `gc.collect()` to your while loop? When I do that, I get steady memory usage at 31MB for hundreds of iterations.

**Comment by jmspereira** [comment]
Calling the garbage collector appears to solve the problem. However, I would like to understand why that is needed (in my application the recv it's not called directly in an infinite loop), and if should not be the library responsible for freeing the memory of the received frame? 

Thank you for the answer!

**Comment by minrk** [comment]
It has to do with [garbage collection thresholds](https://devguide.python.org/garbage_collector/#collecting-the-oldest-generation).

My guess is that the cyclic reference of Frame -> Frame.buffer -> memoryview(Frame) prevents immediate garbage collection, and only a 'full' (generation 2) garbage collection will clean them up. These are run less frequently, but will  run *eventually*

**Comment by minrk** [comment]
#1590 switches `Frame.buffer` to use a weakref. This breaks the cycle and allows efficient garbage collection without any intervention.

BTW, in the meantime, if you do `buf = memoryview(content[1])` and avoid accessing the `.buffer` attribute, you will get the same result avoiding the cycle and memory will not grow.

**Comment by jmspereira** [comment]
Thank you again, using  `buf = memoryview(content[1])` solves my problem for now! I will use this solution until #1590 is in a future release.

**Comment by minrk** [comment]
I'd also argue that using `memoryview(content)` is also the right approach in general in 2021. The `Frame.buffer` API dates from a time when there were 3 different APIs (buffer and memoryview at the Python level, one more  at the C-API level) to access underlying memory, so it was convenient to expose a single API that worked on Python 2.5-3.2. Now that we are comfortably in the Python 3 world, the `.buffer` convenience property doesn't do anything beyond `memoryview(frame)` anymore.
