### ISSUE TITLE
Constants (options) in linked libzmq library are not present in pyzmq build QUESTION

### ISSUE THREAD

**Issue by cbowers1020** [zeromq/pyzmq#1588]
I modified my zmq source code with updated options specific to the NORM implementation present in zmq. They are present in my zmq.h file. After following the instructions [here](https://github.com/zeromq/pyzmq/wiki/Building-and-Installing-PyZMQ) for building pyzmq from git source:
`pip install -e .`
(which I am not sure is even necessary since pyzmq should look for the system libzmq when using "pip install --no-binary pyzmq pyzmq"). However, when I attempt to test the new options using (similar to zmq.constants.MULTICAST_HOPS):
```
import zmq
print(zmq.constants.NORM_OPTION)
```
the new constants are not in pyzmq. I could just be missing a step in how to generate the correct updated constants.

**Comment by minrk** [comment]
I updated the install steps, but you need to explicitly enable the draft API:

```bash
ZMQ_DRAFT_API=1 pip install --no-binary pyzmq pyzmq
```

**Comment by cbowers1020** [comment]
I have that enabled, which provides the RADIO-DISH functionality. Attached is my install script that I run to build my fork of libzmq and then install pyzmq with the necessary --no-binary options, etc. 

I am still unable to access my new libzmq options in pyzmq.
[install.txt](https://github.com/zeromq/pyzmq/files/6961905/install.txt)

**Comment by cbowers1020** [comment]
I have NORM working in pyzmq--I guess I just had the wrong thing in there to check it.

My issue is that I have added additional constants to the zmq.h file that act as new NORM options in libzmq. I now want to be able to access those via pyzmq, but installing pyzmq against my modified libzmq is not generating those constants in pyzmq.

**Comment by minrk** [comment]
pyzmq doesn't automatically export the contents of zmq.h, so adding things to zmq.h doesn't change anything in pyzmq. But they are just integers, so you can use your own constants, e.g. `OPTION = 25` or the literal `25` if the socket option is an integer. You'll have to add it to e.g. `zmq.constants.bytes_sockopts` if it should be bytes instead of a single integer, but if it's an integer like most socket options, pyzmq doesn't need to know about it at all.

**Comment by cbowers1020** [comment]
Ok--makes sense.

So to clarify, the options I added to zmq.h are:
`#ifdef ZMQ_HAVE_NORM
#define ZMQ_NORM_FIXED 115
#define ZMQ_NORM_CC 116
#define ZMQ_NORM_CCE 117
#define ZMQ_NORM_CCL 118
#define ZMQ_NORM_UNICAST_NACK 119
#endif`

So, I simply need to (after installing my modified libzmq and pyzmq with --no-binary) set the socket options as:
`socket.setsockopt(115, 50000)`
etc.

**Comment by minrk** [comment]
Exactly right. pyzmq only needs to know about socket options where the values are *not* integers.

**Comment by cbowers1020** [comment]
Great! Thank you!
