### ISSUE TITLE
ZMQ on Kubernetes

### ISSUE THREAD

**Issue by JoanFM** [zeromq/pyzmq#1589]
Hello,

I have a client server application. I would like to deploy the server on kubernetes to profit from their load balancing and scaling capabilities.

However, it seems that load balancing does not work with a single connection. 

Is there a way to achieve this?

**Comment by JoanFM** [comment]
Hello @minrk ,

Thank you for your reply. I have tried this approach, and I seem to have problems with a pattern that connects a `DEALER` socket with a bound ROUTER socket. 

Is this a combination of sockets where it may not be safe to keep closing and opening connections?

Thanks in advance

**Comment by minrk** [comment]
> Is this a combination of sockets where it may not be safe to keep closing and opening connections?


As long as you hold the connection until you receive a reply, that should be okay. But you cannot reconnect and expect to get a reply to a message sent from a previous connection unless you add extra logic.
