### ISSUE TITLE
Open files leak 

### ISSUE THREAD

**Issue by Blindfreddy** [zeromq/pyzmq#1591]
I am running a multi-process (and multi-threaded) python script on debian linux which uses zeromq with ipc. 

One of the processes repeatedly crashes after 4-5 days with following error message in syslog.  It is always the same, unique workload on the process that crashes. The underlying process simply disappears, no dump etc.  It also behaves completely normally and produces normal results, then suddenly stops. Seems the kernel simply kills the process.

syslog extract follows:  first row is the last entry made by the rogue process (just before it fails), the 2nd row is the one pointing to the underlying error: `too many open files`.

```
Aug 10 08:30:13 rpi6 python[16293]: 2021-08-10T08:30:13.045 WARNING w1m::pid 16325, tid 16415, taking reading from sensors  with map {'000005ccbe8a': ['t-top'], '000005cc8eba': ['t-mid'], '00000676e5c3': ['t
Aug 10 08:30:14 rpi6 python[16293]: Too many open files (bundled/zeromq/src/ipc_listener.cpp:327)
A
```

It's not obvious where / why files are opened and not closed.  How can I analyse further ?

**Comment by Blindfreddy** [comment]
Forgot to mention
"zmq_version": "4.3.4",
"pyzmq_version": "22.0.3",

**Comment by minrk** [comment]
This isn't enough information to identify the issue, but one zmq socket actually corresponds to more than one FD. So if you are leaking sockets, you can run out of FDs rapidly. You can see open zmq Sockets at the Python level with:

```python
import gc
open_sockets = [
        obj
        for obj in gc.get_referrers(zmq.Socket)
        if isinstance(obj, zmq.Socket) and not obj.closed
    ]
```

I can't say if your workload is failing to close sockets, or if it actually needs enough sockets to exceed the default limit (can be increased to e.g. 10,000 with `ulimit -n 10000`).

One bit of info you might need: calling `socket.close()` doesn't actually close the underlying socket until all pending messages have been disposed of. If you have permanently undeliverable messages, this prevents sockets from closing indefinitely by default. You may be interested in setting `LINGER` to a finite value (e.g. `socket.linger = 3000` for 3 seconds before discarding a message).

**Comment by Blindfreddy** [comment]
Thanks for the ideas.  My workload definitely doesn't require >1000 open socket - more like 10 or 20.  I am aware of the ```linger``` parameter and added it explicitly in a ```finally: ``` clause - previously I relied on the garbage collector to close the socket which caused this limit to be reached much faster. I do occassionally run into timeouts resulting ```zmq.AGAIN``` which I catch and then close the socket with ```linger=0```. Seems there is still a leak somewhere. I'll log the open sockets using above code to gain more insights in leakage, many thanks.  Once I have more insights I'll post an update.

**Comment by Blindfreddy** [comment]
Added above code and forced the suspect workload to a dedicated process - there are 19 open zmq sockets.  I'll keep an eye on it over the next few days and post update(s) here.

**Comment by Blindfreddy** [comment]
Quick update:  I made some changes to the code, open files (lsof) is stable at 243, gc open_sockets is stable at 23, and the process has now been running for ~10 days, which is twice as long as it did before, so that is very promising.  As such, I think we can close this issue. 

Separately, I will revert to an older commit which experienced the leak and try to pinpoint it (I think I know where it stems from). If my hunch turns out to be correct I'll raise a feature request around the gc behavior and the linger parameter.

**Comment by minrk** [comment]
Sounds good, thanks!
