### ISSUE TITLE
Doc Issue: Authenticator might need to be marked as a base class

### ISSUE THREAD

**Issue by iUnknwn** [zeromq/pyzmq#1593]
When attempting to use curve authentication, my first attempt was to use the `zmq.auth.Authenticator` class directly. However, this failed (and the debugging output didn't provide any information). 

Replacing the calls to `Authenticator` with `ThreadAuthenticator` solved the problem and the application worked without issue. I'm guessing this is a base class, and is not supposed to be used directly? 

If so, it would be great if this could be marked in the docs. 

More generally, it would be great if there was an example of curve encryption in the docs - there are quite a few samples online that appear out of date, and it's not clear from the docs if attributes like `curve_secretkey` should be set directly on the socket, or via `setsockopts`.

**Comment by minrk** [comment]
Definitely needs more docs! There are several [examples](https://github.com/zeromq/pyzmq/tree/v22.2.1/examples/security) though.

The base Authenticator is not an incomplete base class in that it is creates a fully configured socket and handlers, but it does not register with an event loop. So it can be used without a subclass if you handle receiving messages and calling `auth.handle_zap_message` somewhere in your application code, e.g.

```python

auth = zmq.Authenticator()
auth.allow("127.0.0.1")
auth.start()
while True:
    auth.handle_zap_msg(auth.zap_socket.recv_multipart()
```

or by registering `auth.zap_socket` with a Poller.

But usually you want ZAP to run in a way that doesn't block your main thread, i.e. in a thread / via asyncio, hence the subclasses provided.

**Comment by iUnknwn** [comment]
Hi @minrk - thank you for the explanation. 

Would it help if I updated the docs on the Authenticator class and filed a PR? I could include your explanation, and add a link to the examples as well.

**Comment by minrk** [comment]
That would be very welcome, yes!

**Comment by iUnknwn** [comment]
Will do - unfortunately I'm hitting #1550 when building the docs, which is causing issues (just left a comment over there), but once I figure out a work around I can try to tweak the class docs.

**Comment by minrk** [comment]
The docs require pyzmq itself to be installed. Run `pip install -e .` in the top-level dir before starting to build the docs.

**Comment by minrk** [comment]
Docs are also built on CI, so even if you can't get building locally for any reason, you can open a draft PR and check the readthedocs results from a link in the CI status.

**Comment by iUnknwn** [comment]
@minrk - Will do. Sorry for the delay - was on vacation the last two weeks. I'll try to have a PR for you later this week.

**Comment by iUnknwn** [comment]
And PR submitted - #1619
