### ISSUE TITLE
zmq.asyncio.Context appears to leak file descriptors when combined with unittest.IsolatedAsyncioTestCase

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1605]
# Problem 
On linux and macOS, when using the python [IsolatedAsyncioTestCase](https://docs.python.org/3/library/unittest.html#unittest.IsolatedAsyncioTestCase) I had been puzzled intensely by the tests failing every so often on linux/macos. 

Here's a quick and dirty example of the test fixture I am using. Note this version is the revised version with the fix I describe below. This hopefully gives you the feels for what I am doing though. These tests are for a python implementation of [the Majordomo Protocol](https://rfc.zeromq.org/spec/18/) which I am building.

```Python

class HelloWorldTest(IsolatedAsyncioTestCase):
    
    service_name = 'HELLO_WORLD'
    
    async def asyncSetUp(self):


        self.z_context = zmq.asyncio.Context.instance()

        #Start a broker process which will service this request.
        self.broker_proc = await asyncio.create_subprocess_exec(*[
            sys.executable,
            os.path.dirname(cress.__file__),
            '--context',
            'broker'
        ])
        
        self.worker_tasks =[]
        
        #Create a pool of workers to service the requests from the client.
        for i in range(0, 50):
            new_worker = self.HelloWorldWorker(z_context = self.z_context)
            self.worker_tasks.append(
                asyncio.create_task(
                    new_worker.start()
                )
            )
        
    async def test_client_request(self):
        """ round trip hello world request with live broker """

        #create a request
        await self.client_broker_context.send(
            b'',
            BrokerProtocolClient.REQUEST,
            bytes(self.service_name, 'utf-8')
        )
        
        while True:
            
            response = await self.client_broker_context.recv()

            if response.type == BrokerProtocolClient.FINAL:
        
                self.assertEqual(
                    response.body, 
                    bytes(self.service_name, 'utf-8'),
                    "".join([
                        "Failed to get 'Hello World' response. ",
                        "Got this instead... ",
                        response.body.decode('utf-8')
                    ])
                )
                
                print(f"CRESS:{__name__}:{__class__.__name__}: SUCCESS!")  
                break
        
    
    @classmethod
    async def handle_client_req(
        cls, 
        req, 
        rqst_handler_context
        ):

        try:
            
            worker_tasks = {}
            workers = {}
            #wait till we have at least 40 workers available
            while len(workers.get(req.service_name, [])) <= 40:
                workers = rqst_handler_context.get_active_nodes(
                    service_names = [req.service_name]
                )
                await asyncio.sleep(0)
            
            wrk_ids = workers.get(req.service_name,{})

            async def worker_task(worker):
                    
                rqst_handler_context.send_to_worker(
                    worker.worker_id,
                    BrokerProtocolWorker.REQUEST,
                    req.body,
                    req.client_address
                )
                
                worker_reply = await rqst_handler_context.recv_from_worker()
                
                return worker_reply
            
            for worker in wrk_ids:
                
                worker_tasks[tuple(worker.worker_id)] = asyncio.create_task(
                    worker_task(
                        worker
                        )
                )
        
            for task in asyncio.as_completed(
                worker_tasks.values(),
                timeout=10
            ):
                
                result = await task
                
                rqst_handler_context.send_to_client(
                    BrokerProtocolClient.PARTIAL,
                    result.body,
                    result.service_name
                )
                
            #FINISHED, tell client the request has been fulfilled
            rqst_handler_context.send_to_client(
                BrokerProtocolClient.FINAL,
                req.service_name,
                req.service_name
            )
        
        except asyncio.TimeoutError:
            
            rqst_handler_context.send_to_client(
                BrokerProtocolClient.ERROR,
                b'Timed out waiting for workers.',
                req.service_name
            )
            
            raise RuntimeError("HelloWorld task timedout waiting for workers")
    
    class HelloWorldWorker(Worker):

        service_name = "HELLO_WORLD"

        async def worker_run(wrkr_self):

            while True:
            
                req = await wrkr_self.ctx.recv()
                
                #respond
                
                if req.type == BrokerProtocolWorker.REQUEST:
                    
                    body = bytes(wrkr_self.service_name, 'utf-8')
                    #Simle reply to the request, just send back the service name
                    await wrkr_self.ctx.send(
                        BrokerProtocolWorker.FINAL,
                        body = req.service_name
                    )

    async def asyncTearDown(self):
       
        #make sure we clean up after ourselves.
        self.client_broker_context.close()
        for worker in self.worker_tasks:
            worker.cancel()
        await asyncio.gather(*self.worker_tasks, return_exceptions=True)
        self.broker_proc.terminate()
        await self.broker_proc.wait()
        

        self.z_context.destroy()

```

On further investigation the problem was logged as the process had run out of file descriptors. I checked and am to this day confident that I had closed all sockets created with both zmq.asyncio.Context, and the python socket class. I went over this several times.

# What fixed it
After a lot of testing and observation, I noticed that when run in isolation, in a single process, everything was fine. There were no file descriptors accumulating. It was **only** when the tests were run together, one after another, in a single process that the file descriptors leaked.

The only noteworthy commonality between the tests was that they shared a zmq.asyncio.context object. I decided to refactor the tests, and give each TestCase object I'd created its own zmq.asyncio.context which would be destroyed in the asyncTeadDown method of the test fixture. 

This worked, and both macOS and linux no longer have file descriptor leaks. 

# Hypothesis
The unittest.IsolatedAsyncioTestCase creates an event loop for each test case. This loop is shutdown and closed at the end of the test. I think this may be related to the issue. I think that the closure of the loop somehow prevents the cleanup of the open file descriptors that I believe are related to the zmq.asyncio.Context. 

# Impact on devs using pyzmq
Speaking for myself, the impact of whatever this issue turns out to be, was a lot of time spent doing exhaustive testing. I wanted to write automated tests that would hopefully simulate zmq getting pushed to its limits. I expected to find bugs and edge cases in my production code, but actually ended up spending most of my time debugging the tests! I am now able to get back to writing more tests to continue to batter my work with more torture tests. I feel I lost about maybe 3-4 days total (on and off) time trying to track this bug down. 

# Desired outcome
Please investigate! I got this to work, but am still not 100% sure if my hypothesis is correct. And as a result, I may only have the illusion of having fixing this. 

The tests I run are not an exact facsimile of production, so I am curious to know if, during prod when there is just one event loop running for all time (process time, until the process exists) if file descriptors from closed sockets will actually be cleaned up properly. The seem to be, if the tests are run in isolation, which is what I would estimate is close to what I consider prod conditions.

**Comment by minrk** [comment]
First, I do think it's a good idea to cleanup contexts

> I checked and am to this day confident that I had closed all sockets created with both zmq.asyncio.Context, and the python socket class. I went over this several times.

One quick way to confirm this is to use `context.term` instead of `context.destroy`. If there are open sockets, term will hang, which shows you right away that something isn't closed. Destroy prevents the hang, but it also hides possible leaks.

As you are debugging, you can also count FDs at various points in the process. One quick, cross-platform way is with psutil:

```python
import psutil
num_fds = psutil.Process().num_fds()
```

If you print this at a point in the tests, e.g. at the end of setup, it should report the same number for every test if you truly are cleaning things up.

Usually, when running tests leaks FDs, e.g. by failure to close sockets, it will crash pretty reliably at the same point on the same system, because the FD limit is fixed, and the number of open FDs throughout the test process is deterministic. If it's *not* so reliable, then my suspicion is it's related to something async under the hood, e.g. LINGER.

See for example this script:

```python
import time

import psutil
import zmq

url = "tcp://127.0.0.1:5555"


def main():
    fds = psutil.Process().num_fds
    print(f"before context,   fds={fds()}")
    ctx = zmq.Context()
    print(f"after context,    fds={fds()}")
    a = ctx.socket(zmq.PUSH)
    a.linger = 100  # discard unsent messages after 100ms

    a.connect(url)
    print(f"socket connected, fds={fds()}")
    a.send(b"message")
    print(f"socket sent,      fds={fds()}")
    a.close()
    print(f"socket closed,    fds={fds()}")
    time.sleep(1)
    print(f"linger expired,   fds={fds()}")
    ctx.term()
    print(f"after term,       fds={fds()}")


if __name__ == "__main__":
    main()
```

which prints

```
before context,   fds=8
after context,    fds=11
socket connected, fds=19
socket sent,      fds=20
socket closed,    fds=20
linger expired,   fds=17
after term,       fds=8
```

Note that the fd count does not drop immediately after `Socket.close()`! It only drops after the linger is expired, which lets the context clean up its pipes.

If you are confident that all sockets have been closed, then my next hunch is LINGER and undelivered messages holding those FDs open as long as the context is alive (or up to some timeout). `ctx.term()` always blocks until all sockets are closed and all LINGERs expired. (destroy adds calls to close for any still-open sockets, but is otherwise the same) That's the only call in libzmq that has guarantees about cleaning up FDs when it returns.

**Comment by Jeducious** [comment]
Thanks @minrk 

right now I am calling destroy at the end of each test and its cleaning up all the fd's. I've used a slightly different method to count the fd's

```Python
def get_num_fds():

    if platform.system() =="Linux":
        res = len(set(os.listdir(f"/proc/{os.getpid()}/fd")))
    elif platform.system() =="Darwin":
        res = len(set(os.listdir(f"/dev/fd")))

    else: res = -1 #default for non-supported OS types

    return res
```

The results show that if I don't close the context, and create a new one, then the fd's increase with each consecutive test fixture run. 

Incidentally you can see from this excerpt how I am closing the sockets

```Python

    async def disconnect(self):
        
        #stop listening for beacons
        self.beacon_listening_sckt.close()

        msg = BrkrProtoWorker.pack_msg( 
            type = BrkrProtoWorker.DISCONNECT
        )
        await self.zmq_socket.send_multipart(msg)

    async def close(self):

        await self.disconnect()
        self.zmq_socket.disable_monitor()
        self.mon_sock.close(linger=0)
        self.zmq_socket.close(linger=0)

```

This accounts for all the sockets used for the worker, for the client... well, its pretty much the same

```Python

    def close(self):

        self.zmq_socket.disable_monitor()
        self.mon_sock.close(linger=0)
        self.zmq_socket.close(linger=0)

```

These are the only sockets the TestCase creates. They are all closed using linger=0. 

As for deterministic, well, to be honest, with enough runs, there are variations to whether it will crash or not. Sometimes it would pass. Though it usually crashed in more or less the same spot, the times it passed were rare.


I can definitely try replacing the calls to destroy with term and see what difference this makes. I'll do that and report back.

**Comment by Jeducious** [comment]
hmmmm, ok, using context.term hangs, so according to what you wrote above, this means something isn't closed. Not sure what though. I'll dig a bit more.

**Comment by Jeducious** [comment]
Hi @minrk  :) good news, for pyzmq anyway, as you rightly pointed out there were some sockets I had indeed forgotten to close, so thanks for the very helpful advice above of using context.term() to find them. 

After applying context.term instead of destroy, I found some tests did in fact close properly, but others hung. After seeing this it didn't take long to spot that there was a socket in those now hanging tests that I hadn't called close on. 

So I dare say, if you agree, we can close this issue now since according to what you've said above, pyzmq is working correctly?

**Comment by minrk** [comment]
Glad you tracked it down!

**Comment by Jeducious** [comment]
I am hopefully improving 🙄.... hopefully.

One last thing though, from memory, the docs for zmq gave me the impression that you should have one context per process. Does zmq.asyncio have a different requirement? You have confirmed for me that I should have one context for each test case. 

Each IsolatedAsyncioTestCase object will create a new event loop and then destroy it. Does the creation of a new event loop mean that any zmq context used inside, should 'belong' to that loop only, and be cleaned up when the loop ends?

If so, I was wondering if this case I came across (and fell flat on my face over) would be a handy example for pyzmq's docs? It certainly wasn't obvious to me that the problem was the need for a separate context per test. And, since what I believe to be the actual defining thing causing the trouble in each test case was the new event loop created by IsolatedAsyncioTestCase, then there may be other edge cases out there like it. 

Keen to know your thoughts :) 

Oh and thanks again for the help!

**Comment by minrk** [comment]
> One last thing though, from memory, the docs for zmq gave me the impression that you should have one context per process. Does zmq.asyncio have a different requirement? You have confirmed for me that I should have one context for each test case.

No, one context per process is still often a good idea. It doesn't matter a whole lot, maybe tying the context lifetime to your objects, maybe to the process. But in test design, you usually want to cleanup as much as possible from one test to the next to avoid state leaking through. For instance, you had this FD exhaustion issue because there were sockets that weren't being closed in *some* tests. Failing to cleanup the test context between tests meant that leaking sockets in some tests caused failures in another test an arbitrary later point. That's hard to debug! If you clean up everything between tests, it's easier to find what's wrong because it should be somewhere in the test that failed, not any test that came before.
