### ISSUE TITLE
Can't get option ROUTER_HANDOVER from ROUTER socket

### ISSUE THREAD

**Issue by highviolet** [zeromq/pyzmq#1608]
Hi!

I'm trying to retrieve a socket option from a ROUTER socket, but I get "Exception has occurred: ZMQError".

Minimal example:
```python
import zmq

context = zmq.Context()
socket = context.socket(zmq.ROUTER)
socket.bind("ipc://dev.ipc")
socket.getsockopt(zmq.ROUTER_HANDOVER)
```
Any ideas?

**Comment by minrk** [comment]
It looks like ROUTER_HANDOVER is a write-only attribute. It's in [setsockopt][], but not [getsockopt][].

[getsockopt]: http://api.zeromq.org/4-3:zmq-getsockopt
[setsockopt]: http://api.zeromq.org/4-3:zmq-setsockopt

You can submit a feature request to libzmq to expose it to getsockopt.
