### ISSUE TITLE
[Question] License of PyZMQ

### ISSUE THREAD

**Issue by soimkim** [zeromq/pyzmq#1610]
COPYING.LESSER of PyZMQ is written as **LGPL-3.0 w/Static Linking Exception**, but License in the source code(ex- https://github.com/zeromq/pyzmq/blob/main/zmq/backend/cython/constants.pyx) is written as **LGPL-3.0**.

Is PyZMQ **LGPL-3.0** AND **BSD-3-Clause**? 
Or is it **LGPL-3.0 w/Static Linking Exception** AND **BSD-3-Clause**?

**Comment by minrk** [comment]
It is LGPL-3.0 w/Static Linking Exception for the core of the Cython backend, BSD-3-Clause for the rest.

**Comment by soimkim** [comment]
@minrk , Thanks for the quick reply.
