### ISSUE TITLE
zmq.auth.asyncio not documented, though it looks like it should be

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1612]
# Problem
This [part of the pyzmq docs](https://minrk-pyzmq.readthedocs.io/en/latest/api/zmq.auth.html) tells me:

> For integration with the asyncio event loop, see zmq.auth.asyncio.

However there is no link to this page, and, despite trying to substitute 'asyncio' into https://minrk-pyzmq.readthedocs.io/en/latest/api/zmq.auth.thread.html

I had no luck, but hey, can't blame a guy for trying :)

**Comment by minrk** [comment]
Oops! Fixed in #1611 . You can see the updated docs [here](https://pyzmq--1611.org.readthedocs.build/en/1611/api/zmq.auth.asyncio.html).

**Comment by Jeducious** [comment]
Hey hey :)

Nice, thanks! After reading the code for the auth module, I managed to get it to not error (still working on making it work), but this is awesome! Looking forward to using it in anger on production systems :)

Just out of curiosity, when does this change get pushed to the main docs?
