### ISSUE TITLE
Feasibility to implement P2P package distribution with pyzmq in justuse?

### ISSUE THREAD

**Issue by amogorkon** [zeromq/pyzmq#1625]
I'm considering different approaches to realizing P2P package distribution in https://github.com/amogorkon/justuse in order to unburden PyPI. I've stumbled across technologies like https://ipfs.io/ or cockroachDB, but those solutions don't really fit my case.. Have there been any attempts at using pyzmq in P2P networks? What are the benefits or drawbacks?

**Comment by minrk** [comment]
justuse looks cool!

zmq is really nothing like ipfs or cockroach. It's a much smaller, lower-level tool. If you used pyzmq, you'd need to do all the p2p parts yourself. zmq is really a socket library that enables certain messaging patterns (publish-subscribe, request-reply, etc.). It would be up to you to design and build a p2p system out of those message patterns, including resiliency, fault tolerance, security, etc.

I think you could build something like this *within a trusted LAN* for an on-premises kind of thing, but I think it would not be an appropriate tool over actual public Internet connections.

The [guide][] has some examples for doing local network P2P with zmq, to give you some idea.

[guide]: https://zguide.zeromq.org/docs/chapter8/
