### ISSUE TITLE
Mypy thinks Context.socket is an untyped function

### ISSUE THREAD

**Issue by bbatliner** [zeromq/pyzmq#1627]
Consider this minimal example:

```python
import zmq

ctx = zmq.Context.instance()
socket = ctx.socket(zmq.PULL)
```
When running mypy with the  `disallow_untyped_calls` option, an error surfaces about this function being untyped:

```
$ mypy --disallow-untyped-calls example.py 
example.py:4: error: Call to untyped function "socket" in typed context  [no-untyped-call]
```

My workaround is to annotate directly and ignore the error:

```
from zmq.sugar.socket import Socket
socket: Socket = ctx.socket(zmq.PULL)  # type: ignore
```

I've looked at https://github.com/zeromq/pyzmq/issues/1206 and it doesn't seem like [`context.py`](https://github.com/zeromq/pyzmq/blob/main/zmq/sugar/context.py) has either inline annotations or an associated `.pyi` file. Should this work out of the box?

**Comment by minrk** [comment]
I don't use mypy much. pyzmq definitely isn't *fully* covered by types (and I doubt it ever will be), but this much should definitely work!

#1631 fixes this example
