### ISSUE TITLE
error: command '/usr/bin/gcc' failed with exit code 1 

### ISSUE THREAD

**Issue by redsox10** [zeromq/pyzmq#1635]
Hi, I get this error when I try to install pyzmq 17.1.2 (I need this specific version) 

...
/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9/pyport.h:508:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
12 warnings and 1 error generated.
error: command '/usr/bin/gcc' failed with exit code 1

My system: 
macos Catalina 10.15.7
python 3.9.7 in newly created virtualenv
pip 21.3.1
zeromq 4.3.4 installed with brew

when I do pip install pyzmq==17.1.2 in virtualenv, it fails. Any suggestions please?

**Comment by minrk** [comment]
From [the changelog](https://pyzmq.readthedocs.io/en/v22.3.0/changelog.html#id13), compatibility with Python 3.9 was added in 19.0.2. So the only officially supported options are to upgrade pyzmq or downgrade Python to mutually compatible versions.

You can try checking out the source for 17.1.2 and regenerating the Cython sources with more recent Cython (`python setup.py cython && pip install -vv .`), but I'm not sure if that will be enough.

Can I ask why you are required to pin-down pyzmq to a version from 2018, but also need to use a version of Python itself from 2020, which can't reasonably be supported by extension packages from before it came out? Partially pinned environments are a recipe for incompatibility.
