### ISSUE TITLE
ipc support on windows in msys2 / mingw-w64-i686

### ISSUE THREAD

**Issue by grindhold** [zeromq/pyzmq#1636]
i tried building pyzmq 22.3.0 under windows 10 in a mingw-w64-i686 environment in order to obtain the possibility to create and use ipc://-sockets on windows.
i have tried using the mingw-based c++ compiler as well as the compiler by the greedy company that runs this site.
in any case, upon executing the following code, i receive `zmq.error.ZMQError: Protocol not supported`

```
import zmq
c = zmq.Context()
s = c.socket(zmq.PULL)
s.bind("ipc:///tmp/stream")
```

when i try the same thing based on the pure libzmq (version 4.3.4) in C it works without erroring.
Is there anything missing upstream in order for this to work? Am I missing anything?

**Comment by minrk** [comment]
I don't know enough about mingw or libzmq's IPC support on Windows to tell what's missing. It's possible there is some configuration or flag missing from the build.

Can you build pyzmq linking an already-built libzmq instead of trying to build libzmq as an Extension?

**Comment by minrk** [comment]
I believe this is fixed with pyzmq 26, which run libzmq's own CMake build system for the bundled libzmq. If that finds what it needs for IPC, it should be enabled.
