### ISSUE TITLE
non blocking rest api with n workers and zmq

### ISSUE THREAD

**Issue by mattou78400** [zeromq/pyzmq#1638]
Hello,

I'm trying to set up a rest API which I can call N times at once, and it'd queue those calls and distribute the work to M workers

Here's what I have:

rest API forwarding data to the zmq workers:

```
import json

import time
import zmq
import asyncio

url_client = "tcp://localhost:5559"
context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect(url_client)

from aiohttp import web
import json

async def process_orders(req):
    response_obj = { 'status' : 'success' }
    print('processing')
    body = await req.json()

    socket.send(str(body).encode())
    response = socket.recv()
    
    return web.Response(text=json.dumps(response.decode()))

app = web.Application()
app.router.add_post('/process_orders', process_orders)

web.run_app(app, port=6666)
```
workers:

```

from __future__ import print_function
import threading
import time
import zmq
import json

from order_manager import parseResponse
import time
import threading
import zmq

context = zmq.Context()

def worker():
    socket = context.socket(zmq.REP)
    socket.connect('inproc://workers')
    while True:
        msg = socket.recv_string()
        parsed_request = json.loads(msg.replace("'", '"'))
        res = parseResponse(parsed_request) # working part, takes time
        print('Received request:')
        # time.sleep(1)
        socket.send_string(str({"status":'ok'}))

url_client = 'tcp://*:5559'
clients = context.socket(zmq.ROUTER)
clients.bind(url_client)
workers = context.socket(zmq.DEALER)
workers.bind('inproc://workers')

for _ in range(4): # 4 workers
    thread = threading.Thread(target=worker)
    thread.start()

zmq.device(zmq.QUEUE, clients, workers)
```
When I send 10 requests at once, it will make 10 calls to the aiohttp route, but then only dispatch the work sequentially. Submit #1, wait until over, sumbit #2... instead I'm looking to submit #1 & #2 & ... & #M (number of workers) and managing the outputs as they come, while resubmiting work to idle workers

How could I do that? I guess there's something wrong with my ZMQ interface, but I can't figure it out...
Thanks a lot!

**Comment by minrk** [comment]
REQ/REP only allows one outstanding request at a time. You might also want to use `zmq.asyncio` instead of the blocking zmq interface, to avoid blocking the asyncio event loop while waiting for a reply.

You can deal with this by having either one client socket per request (e.g. via a socket pool) or use ROUTER/DEALER instead. ROUTER-DEALER would require a bit of additional logic to route a given reply to the right request handler, since they can arrive out of order.

**Comment by mattou78400** [comment]
Could you point me toward a python example of a ROUTER/DEALER set up?

That sounds good as the request order doesn't matter

**Comment by minrk** [comment]
[The guide] has several examples.

[the guide]: https://zguide.zeromq.org/docs/chapter3
