### ISSUE TITLE
Router gets stuck and uses 100% CPU

### ISSUE THREAD

**Issue by jrueb** [zeromq/pyzmq#1642]
I have the issue that if too many Dealers have a connection to one Router simultaneously, the Router stops doing anything and the process goes to 100% CPU usage. To reproduce, here are two Python files

router.py:
```python
import zmq

context = zmq.Context()
server = context.socket(zmq.ROUTER)
server.bind("tcp://*:54234")

poll = zmq.Poller()
poll.register(server, zmq.POLLIN)
i = 0
while True:
    print("polling")
    sockets = dict(poll.poll(1000))
    if sockets:
        server.recv_multipart()
        i += 1
        print(f"Got {i} connections")
```

dealer.py:
```python
import zmq
import time

connections = []
for i in range(80):
    context = zmq.Context()
    con = context.socket(zmq.DEALER)
    con.setsockopt(zmq.LINGER, 0)
    con.connect("tcp://127.0.0.1:54234")
    con.send(b"Hello")
    connections.append((context, con))
time.sleep(3600)
```

I start router.py and then run dealer.py 13 times in parallel. The messages from the Router go up to `Got 1009 connections` and stop there, while the CPU usage goes to 100%.

I assume the underlying reason for this is the maximum of open file descriptors, which on my system is 1024. I would expect that ideally ZMQ gives me an exception once this limit is hit, which is not the case. Also I don't think the CPU usage should go up.

Versions:
libzmq-4.3.4
pyzmq-22.3.0
Python-3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]

**Comment by minrk** [comment]
There might be an error internal to libzmq that is failing to propagate to something you can catch (since it would be async in the background). I don't think there's anything for pyzmq to do about it.

**Comment by jasmineforever** [comment]
Thanks, I found a same problem whit the process limit open files, you tips is useful for me.

**Comment by Vishnu070803** [comment]
@jrueb So zeromq doesn't add the cpu usage overhead?
