### ISSUE TITLE
Should I use asyncIO for subscriber socket or run subscriber socket in a different thread

### ISSUE THREAD

**Issue by yichong96** [zeromq/pyzmq#1645]
I am thinking of using zeroMQ sub socket to receive notifications from another service. The sub socket should not be blocking as the program has main code to run. 

Should I run the socket in a while loop in a different thread ? or should I use async IO sockets.

**Comment by minrk** [comment]
I can't really answer that. Both approaches work, and it will depend on the rest of your application which fits better. It's up to you to choose the concurrency model that suits your application best.

**Comment by frobnitzem** [comment]
I have created a new library, https://pypi.org/project/aiowire/ - specifically for creating servers based on zmq.asyncio.Poller.

Would it be good for me to put in a PR for an example in the dir -- https://github.com/zeromq/pyzmq/tree/main/examples/asyncio
