### ISSUE TITLE
Not detecting non-Proactor loop correctly

### ISSUE THREAD

**Issue by pthomas** [zeromq/pyzmq#1654]
The detection of a Proactor event loop doesn't seem to be working:

If I add these print lines:
```
    print(asyncio.get_event_loop_policy())
    print(hasattr(asyncio, "ProactorEventLoop"))
    print(isinstance(asyncio_loop, asyncio.ProactorEventLoop))
```

To line zmq/asyncio.py line 44
https://github.com/zeromq/pyzmq/blob/8d406b6e164b47655b2ddcd8dcca95cd8d4a2294/zmq/asyncio.py#L44

Then the result is this:
<asyncio.windows_events.WindowsSelectorEventLoopPolicy object at 0x000001AB18DE08E0>
True
True

Because asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy()) is already called the first line makes sense. However it looks like this is being used as the detection for Proactor loop, and the code is expecting either hasattr(asyncio, "ProactorEventLoop") or isinstance(asyncio_loop, asyncio.ProactorEventLoop) to be false, but neither are false.

Python version 3.10.0 pyzmq version 22.3.0

**Comment by pthomas** [comment]
If I bypass this I end up hitting:
https://github.com/python/cpython/blob/bde3765a3fd21e2ecf595a57998b285e3045f744/Lib/asyncio/events.py#L518

I guess I will use tornado for now.

**Comment by pthomas** [comment]
I'm so confused. I set the event loop policy to `WindowsSelectorEventLoopPolicy` just as the warning says to do, and then just before the if statement it reports this correctly with the first added print
`<asyncio.windows_events.WindowsSelectorEventLoopPolicy object at 0x000001AB18DE08E0>`

However the second two statements  are still true ('hasattr(asyncio, "ProactorEventLoop")' and 
    'isinstance(asyncio_loop, asyncio.ProactorEventLoop)' ), and I still get the warning. Have things changed and WindowsSelectorEventLoopPolicy is really a proactor loop? Can you no longer use:
    'asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())' as the warning says?

Can I do anything else besides installing tornado to get a proper event loop on Windows?

**Comment by minrk** [comment]
> Have things changed and WindowsSelectorEventLoopPolicy is really a proactor loop?

[No](https://github.com/python/cpython/blob/8b8673fe940c4ebc4512bff5af180b66def3d1ae/Lib/asyncio/windows_events.py#L305), but you can confirm with `asyncio_loop.__class__.mro()` which shows the class inheritance. If you believe you are using a SelectorEventLoop, the first thing I'd debug is what is the class of the actual loop instance here.

>  Can you no longer use: 'asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())' as the warning says?

You can, as long as you make sure to set the policy before instantiating the loop. Or you can instantiate and run the loop class of your choosing directly, without setting any policies.

> Can I do anything else besides installing tornado to get a proper event loop on Windows?

Tornado's the only current way to make pyzmq compatible with proactor, so it's that or use a SelectorEventLoop.

---

The event loop policy doesn't specify what the actual event loop is, it governs what is returned by `asyncio.new/get_event_loop()`. So it's always possible to have an asyncio loop that doesn't match the policy. One way to get into this situation is to set the policy _after_ something has already instantiated a loop with an earlier policy (or ignoring policy altogether, which is less common). That's my first guess based on your last comment, but I can't do more than guess without an example.

I suspect something like this has happened:

```python
loop = asyncio.get_event_loop() # more likely buried in some object's instantiation
# changing the policy now has no effect, because I've already got the loop I'm going to use
asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())
```

or it could be that some other code made a second set_policy call.

It's very hard to understand what is happening in your specific case without an example. If you provide an example that shows what you are experiencing, we can figure out what to do.
