### ISSUE TITLE
get_event_loop is deprecated in Python 3.10+

### ISSUE THREAD

**Issue by blink1073** [zeromq/pyzmq#1669]
cf https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_event_loop.

I believe [this](https://github.com/zeromq/pyzmq/blob/29aded1bf017385866dcbf7b92a954f272360060/zmq/asyncio.py#L103) needs to be changed to:

```python
def _default_loop(self):
    try:
		return asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.new_event_loop()
```

**Comment by minrk** [comment]
Must be something in the air: #1668

**Comment by minrk** [comment]
closed by #1668

**Comment by minrk** [comment]
btw, 23.0.0b1 is publishing right now if you want to do some testing. The new enums _shouldn't_ break anything, but it would be good to give folks testing with `pip install --pre` before making the final release.

**Comment by blink1073** [comment]
Cool, passing now with no warnings from zmq.

**Comment by blink1073** [comment]
I spoke too soon, we're still seeing `DeprecationWarning: There is no current event loop`, but it comes from creating a `Future` outside of a running event loop, which is now a general problem.
