### ISSUE TITLE
context options

### ISSUE THREAD

**Issue by yasseridris** [zeromq/pyzmq#1675]
I want to set ZMQ_THREAD_AFFINITY_CPU_ADD but it looks like it, and other context options are not exposed in the python api.. 

`zmq_context = SerializingContext()
  zmq_context.set(zmq.THREAD_AFFINITY_CPU_ADD, 3) # constant not defined.
  zmq_socket = zmq_context.socket(socketType)`

When I tried to directly use the value of the enum (7), and I got an exception that this option is not supported.. Am I missing something ?

**Comment by minrk** [comment]
what version of libzmq and pyzmq do you have (`zmq.zmq_version(), zmq.__version__`)? And how did you install them? This option was promoted to stable in libzmq 4.3.0, I think.

**Comment by yasseridris** [comment]
I just have zmq and pyzmq installed:

`pyzmq==22.3.0
 zmq==0.0.0`

**Comment by yasseridris** [comment]
(zmq.zmq_version(), zmq.__version__) return ('4.1.4', '22.3.0') .. I just used pip to install pyzmq

**Comment by minrk** [comment]
That's it, then. You need libzmq >= 4.3.0 for that feature.

**Comment by yasseridris** [comment]
oh, btw, I'm on a rasperypi 4 device, Ubuntu 64 bit installed.

**Comment by minrk** [comment]
You can install zeromq from source to get a version more recent than you have in apt, which follows the standard pattern for C projects:

```
./configure
make
make install
```

Or if you install pyzmq 22.3.0 from a wheel (I'm not 100% sure pyzmq's wheels will install on rPi), it will have libzmq 4.3.4.

To install pyzmq from source, ignoring libzmq you may have installed (after uninstalling pyzmq):

```
ZMQ_PREFIX=bundled pip install -vv pyzmq
```
