### ISSUE TITLE
GLIBC_2.28 not found when using Python after "pip install zmq" on Raspberry Pi 3b 

### ISSUE THREAD

**Issue by dangu** [zeromq/pyzmq#1678]
# Issue description
Error when trying to use the python version of zmq on a Raspberry Pi with Raspbian OS.
The error is "version `GLIBC_2.28' not found"

# Environment
* Raspberry Pi 3b
* libzmq version (commit hash if unreleased): Using pip install, this is what I get: "Collecting zmq
  Downloading https://www.piwheels.org/simple/zmq/zmq-0.0.0-py3-none-any.whl (2.0 kB)
Collecting pyzmq
  Downloading https://www.piwheels.org/simple/pyzmq/pyzmq-22.3.0-cp39-cp39-linux_armv7l.whl (6.8 MB)"

* OS: Raspbian GNU/Linux 9 (stretch)
* Using Python 3.9.10 (I installed it with pyenv)

# Minimal test code / Steps to reproduce the issue

1. mkdir zmq_test && cd zmq_test
2. pip install zmq
3. python
4. Inside the python interpreter:
5. import zmq

# What's the actual result? (include assertion message & call stack if applicable)
    pi@raspberrypi:~/zmq_test $ python
    Python 3.9.10 (main, Jan 26 2022, 13:24:57) 
    [GCC 6.3.0 20170516] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import zmq
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'zmq'
    >>> 
    pi@raspberrypi:~/zmq_test $ pip install zmq
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Collecting zmq
      Downloading https://www.piwheels.org/simple/zmq/zmq-0.0.0-py3-none-any.whl (2.0 kB)
    Collecting pyzmq
      Downloading https://www.piwheels.org/simple/pyzmq/pyzmq-22.3.0-cp39-cp39-linux_armv7l.whl (6.8 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 3.4 MB/s eta 0:00:00
    Installing collected packages: pyzmq, zmq
    Successfully installed pyzmq-22.3.0 zmq-0.0.0
    pi@raspberrypi:~/zmq_test $ python
    Python 3.9.10 (main, Jan 26 2022, 13:24:57) 
    [GCC 6.3.0 20170516] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import zmq
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/pi/.pyenv/versions/3.9.10/lib/python3.9/site-packages/zmq/__init__.py", line 61, in <module>
        _load_libzmq()
      File "/home/pi/.pyenv/versions/3.9.10/lib/python3.9/site-packages/zmq/__init__.py", line 36, in _load_libzmq
        from . import libzmq
    ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/.pyenv/versions/3.9.10/lib/python3.9/site-packages/zmq/libzmq.cpython-39-arm-linux-gnueabihf.so)
    >>> 

# What's the expected result?
The "import zmq" statement should succeed without errors

**Comment by dangu** [comment]
Next test: Using python 3.9.10

The above steps seem to work with 3.9.10. Now trying to do the same but without installing libzmq3-dev.

1. pyenv local 3.9.10

       (Python switched to 3.9.10)
3. sudo apt remove libzmq3-dev

       (success)
4.  pip install --no-binary pyzmq pyzmq

       (takes a loooooong time. Feels like longer than when libzmq3-dev was installed)

5. python

       Python 3.9.10 (main, Jan 26 2022, 13:24:57) 
6. import zmq

       >>>

Yay!

Conclusion: Installing with "pip install --no-binary" works with python 3.9.10 too, even without libzmq3-dev. Takes a loooong time to compile though.

**Comment by minrk** [comment]
I think this is a question for the [piwheels service](https://github.com/piwheels/packages/issues), since those are unofficial wheels. The error means that the wheel was built targeting a newer glibc than you have. You can ask there about what the right course of action is. Judging from [this PR](https://github.com/piwheels/packages/issues/210), I suspect they only build wheels targeting the system Python version for each supported Debian version, so you have a Python 3.9 wheel which targets Bullseye (Debian 11), but you are trying to run it on a too-old Debian 9.

FWIW, pyzmq's [official wheels](https://pypi.org/project/pyzmq/#files) now include aarch64 (not armv7l), so if you can run aarch64 you might be able to use the default wheels, which have correct `manylinux` tags to only install wheels if the host has supported glibc version.
