### ISSUE TITLE
Having multiple sockets for same context and same port in ZMQ

### ISSUE THREAD

**Issue by istabraqruhaili** [zeromq/pyzmq#1689]
My current system takes input stream from cameras, each camera in a separate instance, and apply Computer Vision models on each camera (Object Detection, Object Tracking and Personnel Recognition), and then pass the results to a sink/master process that performs the rest of functionality over those results and I'm using `ZMQ` as an inter-process communication.

What I implemented now is that each worker connects to a different port, and then the sink subscribes to these ports independently, but this solution is not scalable, as we might have 3 or 4 cameras/worker, and I felt that it won't be efficient to keep opening ports like that.

[Multiple Ports Implementation][1]

That's when I tried to implement `Multi-Pub/Single-Sub` module, where all workers will connect to one port and the sink will subscribe to that port only.

[Single Port Implementation][2]

The problem I faced is that I no longer can distinguish between different cameras since I'm receiving different footages in the same port which causes a problem in streaming them later, that's why I'm thinking about the possibility of having multiple sockets for each context, while each socket subscribes to a different IP, is that possible?

  [1]: https://i.stack.imgur.com/BOjfY.png
  [2]: https://i.stack.imgur.com/NFEyk.png
  [3]: https://stackoverflow.com/questions/32280271/zeromq-same-context-for-multiple-sockets

**Comment by minrk** [comment]
I think there are two primary ways to do this:

1. use a ROUTER socket on the sink side, which prefixes each message with a ROUTING_ID, identifying the peer. This is typically used for routing replies, but can be used to identify the sender for any other purposes, or
2. put the sender id in the message itself, so it isn't sensitive to underlying network implementations.

I generally prefer the latter, and usually implement my zmq messaging with something like:

```python
def send_message(socket, msg):
    header = build_header(msg)
    msg_buf = serialize(msg)
    return socket.send_multipart([header, msg_buf])
```

where `msg` is often a Python dict, and the header contains any metadata I'm interested in adding to the message (sender id, timestamps, etc.)

**Comment by istabraqruhaili** [comment]
I'm already doing that, I put the IP of the camera along with its frame in a package and publish it. The thing is that I could not figure out how to receive them concurrently. Because the current behavior is that either receive from camera one, or camera two, and that produces a problem in the live streaming.

**Comment by minrk** [comment]
> The thing is that I could not figure out how to receive them concurrently.

This should work fine with any socket combination other than REQ/REP (DEALER/ROUTER, PUB/SUB both work fine for concurrent clients). Can you describe what problem you are having with concurrency?

> As for the ROUTER option, I believe it is for the REQ/REP pattern while I want to use the PUB/SUB, am I right?

I'm actually not sure. It depends on your needs. The main reason to use PUB/SUB is if you want to drop messages when you can't keep up or if there are interruptions. If you actually want to deliver ~all of the messages you send, then PUSH/PULL is the socket pair to use (or DEALER/ROUTER if routing_id is still helpful) is probably better.

So the question you want to ask is: what should happen if the sink isn't running or available when a worker sends a message?

- PUB/SUB: drop the message and move on
- PUSH/PULL or DEALER/ROUTER: queue the message until the sink is ready:

**Comment by istabraqruhaili** [comment]
Thank you @minrk  for this explanation! I think that PUB/SUB is the suitable pattern for my use case because out of 30 frames/per second it is okay for me to drop some frames to avoid any latency in the live stream that might occur using other patterns.

> Can you describe what problem you are having with concurrency?

Let's say we have 2 cameras with the following IPs: `12.12.1.1` and '12.12.1.2`, the current behavior with the single port is as the following:
`Second x` : Packet from `12.12.1.1` is received
`Second x+0.01` : Packet from `12.12.1.2` is received

That causes a problem because I need to process them both at the same time,  so that the streams aren't depending on each other no matter how workers/cameras are connected. That's why I though of having multiple sockets but that didn't work when I tested it. I hope the question is clear now!

**Comment by minrk** [comment]
Certainly, having only one socket will serialize _receiving_ messages, but that doesn't mean _processing_ must also be serialized. You can spawn processing asynchronously, e.g. via Executors (threads or processes) or even your own workers.

Something like:

```python
while True:
    msg = await recv_msg(socket)
    process_task = executor.submit(process(msg))
```
