### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by blink1073** [zeromq/pyzmq#1697]
I tried to enable Python 3.11 beta for `jupyter_server`, but got this error when building [`pyzmq`](https://github.com/jupyter-server/jupyter_server/runs/6350119667?check_suite_focus=true):

```
             gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SYS_UN_H=1 -Ibundled/zeromq/include -Izmq/utils -I/opt/hostedtoolcache/Python/3.11.0-beta.1/x64/include/python3.11 -c zmq/backend/cython/_device.c -o build/temp.linux-x86_64-cpython-311/zmq/backend/cython/_device.o
            zmq/backend/cython/_device.c:217:12: fatal error: longintrepr.h: No such file or directory
              217 |   #include "longintrepr.h"
                  |            ^~~~~~~~~~~~~~~
            compilation terminated.
            error: command '/usr/bin/gcc' failed with exit code 1
            [end of output]
```

FWIW it looks like that file still [exists](https://github.com/python/cpython/blob/main/Include/cpython/longintrepr.h)

**Comment by minrk** [comment]
I've been waiting for Cython 0.29.29 to fix the 3.11 builds, but I'm going to make a prerelease with #1696 since that's been taking a while

**Comment by blink1073** [comment]
Ah, thanks!  Yeah it makes sense for us to target Python 3.11 only in our prerelease job.

**Comment by blink1073** [comment]
In [progress](https://github.com/jupyter-server/jupyter_server/runs/6352001282?check_suite_focus=true)

**Comment by blink1073** [comment]
Great!

**Comment by minrk** [comment]
23.0 is up
