### ISSUE TITLE
Socket.recv_multipart is missing from typestubs

### ISSUE THREAD

**Issue by zwn** [zeromq/pyzmq#1699]
`Socket.recv_multipart` is missing from typestubs. I believe it should go to to [zmq/backend/\_\_init\_\_.pyi](../blob/main/zmq/backend/__init__.pyi).

**Comment by minrk** [comment]
`recv_multipart` is defined in `zmq/sugar/socket.py` (the low-level `backend` does not have multipart), and imported in `zmq/sugar/__init__.pyi`. Where do you see it being missing? All my tests show type checks working with recv_multipart, but I don't know how everybody works with types.

You might check with 23.0.0b2, which has some fixes for typing.

**Comment by zwn** [comment]
Hmm, I see. PyCharm tells me it is unresolved. Maybe it got confused since both classes are called `Socket` and the one from `backend` is renamed on import to `SocketBase`. Now going through the code more carefully I also think is should work. However, I do not have much experience with typing.

So it might be something to report against PyCharm?

**Comment by minrk** [comment]
I do see `Any` for 22.3, but I get fully typed info for 23b2. With this script:

```python
import zmq

ctx = zmq.Context()
s = ctx.socket(zmq.PULL)
reveal_type(ctx.socket)
reveal_type(s.recv_multipart)
msg = s.recv_multipart()
reveal_type(msg)
```

mypy 0.942 gives the correct type of `msg` to be `list[bytes]`. So maybe it's a PyCharm issue? Or maybe you could give a script example where it gets confused? I'm pretty new to types (I don't use them much myself) and the generator/inheritance stuff in pyzmq is unkind to the strictness typing tools expect.

**Comment by zwn** [comment]
> So maybe it's a PyCharm issue?

That seems to be the case. It must be using some kind of lazy indexing system that got confused - it noticed the constants being available right after installing 23b2 but it didn't correctly decipher the return type of `ctx.socket`. After some time and/or PyCharm restart, now it does not complain anymore. So for me it :+1: for types in 23b2 and sorry for bothering you guys - I just thought I'll try to make pyzmq better and didn't know the context well enough.

**Comment by zwn** [comment]
For posterity - the PyCharm snap on ubuntu updated itself between the first and second test so it might have been fixed on the PyCharm side (the current version being `2022.1.1 (Community Edition)`).
