### ISSUE TITLE
Some constants not available under previous names

### ISSUE THREAD

**Issue by chrisjbillington** [zeromq/pyzmq#1710]
I have code getting an `AttributeError` in pyzmq 23.0 accessing the constant `zmq.EVENT_HANDSHAKE_SUCCEEDED`, which with the latest changes to provide enums as well as top-level constants, is now available as `zmq.HANDSHAKE_SUCCEEDED`.

Any chance of providing this (and other event-related constants, which are presumably affected too) under their old names, at least for a time, for backwards-compatibility? I can change my code easily enough, but bumping the required version of pyzmq for my project will prevent new releases being installable in environments where the latest pyzmq is not yet available (e.g. Anaconda), and replacing accesses with `getattr(zmq, 'HANDSHAKE_SUCCEEDED', getattr(zmq, 'EVENT_HANDSHAKE_SUCCEEDED'))` does not spark joy.

**Comment by chrisjbillington** [comment]
Thank you for the rapid fix and release! Much appreciated.

**Comment by minrk** [comment]
Thanks for reporting! 23.1 should propagate across various release channels shortly.
