### ISSUE TITLE
CURVE authentication - keys from env? (files are unsafe)

### ISSUE THREAD

**Issue by GeneralErrorOK** [zeromq/pyzmq#1713]
I have built a small server application that needs to work over the (corporate) network. The clients are cloud applications that are ran from a CI/CD pipeline. I don't like the fact that I need to include the keys as a file in my repo and then need to push these files to the cloud. I would much rather include them as environment variables. The documentation seems to suggest it's files only. But is it?

I have built the applications (both server and client side) using the Ironhouse example in which the server needs its own private and public keys but the client needs client private key, client public key but also server public key. So I'd think that just using zmq.curve_keypair() to generate the keys on the fly at the client side will not work?

**Comment by minrk** [comment]
Yup, you can do `socket.curve_secretkey = os.getenv("CURVE_SECRETKEY").encode("ascii")` and such, it should work fine.
