### ISSUE TITLE
Failed to start the Kernel. AttributeError: module 're' has no attribute 'Pattern'. View Jupyter log for further details.

### ISSUE THREAD

**Issue by MrYZhou** [zeromq/pyzmq#1722]
problem:Failed to start the Kernel. 
AttributeError: module 're' has no attribute 'Pattern'. 
View Jupyter [log](command:jupyter.viewOutput) for further details.

vscode:  version1.68.0
jupyternotebook:    use jupyter plugin v2022.5.1001601848
python: 3.10.5 -64bit

**Comment by minrk** [comment]
I think this might be opened in the wrong place? `re` does have a Pattern class:

```python
from re import Pattern
```

Is there a chance you have a `re` folder or `re.py` file somewhere?
