### ISSUE TITLE
zmq.auth - question on how curve authentication can be effectively tested

### ISSUE THREAD

**Issue by Jeducious** [zeromq/pyzmq#1723]
# Whats up?
I am creating a new system using pyzmq and intend to authenticate peers that wish to make a connection to another peer. 
I plan to use a credentials provider class to configure the curve server, this will decide whether to allow a connection or not. 
I also plan to use a monitor socket to be able to know when a socket is connected so I can start using the connection to send/recv messages without losing messagse.

I am designing tests to ensure the authentication system is working as intended. I have hit a problem though.

# How to tell if a peer is authenticated?
Of course I could just trust that pyzmq is doing its job and not allowing a bad peer to make a connection if it cannot be authenticated :) However, I decided to use the monitor socket to see the events being generated by the server socket that is playing the role of the auth server.

What I saw puzzled me because;
1. I never saw any events related to the ZMPT security mechanism, so things like EVENT_HANDSHAKE_FAILED_AUTH or EVENT_HANDSHAKE_SUCCEEDED for example. 
2. I created a test where the credentials provider will always refuse the connection, but, the connection, according to the events coming from the server socket's monitor sock, showed that the bad peer had been able to successfully connect. You can see this below.

```
CRESS:reverse proxy sub socket:EVENT: CONNECT_DELAYED:112:tcp://127.0.0.1:65488
CRESS:reverse proxy sub socket:EVENT: CONNECTED:1792:tcp://127.0.0.1:65488
CRESS:reverse proxy sub socket: Connected to 127.0.0.1:65488
``` 

# How pyzmq actually tests this
I took a look at [the tests here in the pyzmq repo](https://github.com/zeromq/pyzmq/blob/546b258f4b65939953eec57cafa2cd809debb93f/zmq/tests/test_auth.py#L100) and noticed that whether a client (sorry for my odd interchangeable use of client/peer/server) can connect to a server or not is decided by the success or failure of sending and the other socket then receiving a message, not whether the sockets are in a connected state. 

# So I guess my real question is...
A couple of questions actually now I come to think of it. 
1. When a client attempts to connect to a server using curve, is the connection actually successful regardless of whether the credentials provider accepts it?
2. How come there are no events related to authentication in the monitor socket for the client? Maybe the client isn't allowed to know what state the server has assigned to the client's connection attempt? So should I actually monitor the server socket instead if I want to see these messages?
3. What is the best way to test that our credentials provider; a accepts connections that are validated by the credentials provider, and b; does the opposite with connections that aren't.

Thanks!

**Comment by minrk** [comment]
I think this is mostly a question for libzmq, not pyzmq. I'm not qualified to give advice on how best to implement detection of failed auth.

> When a client attempts to connect to a server using curve, is the connection actually successful regardless of whether the credentials provider accepts it?

Depends on what you mean by 'accepts'. A tcp socket connection is accepted, but at the zmq level, it's as if the peer never showed up, so you can't send or receive messages. I don't know when/how the tcp connection is dropped.

> How come there are no events related to authentication in the monitor socket for the client?

I do see events for the client, but not the server when I add monitoring to e.g. `zmq/examples/security/ironhouse.py`


> What is the best way to test that our credentials provider; a accepts connections that are validated by the credentials provider, and b; does the opposite with connections that aren't.

I'd say:

1. run tests with credentials to make sure everything works, and
2. attempt to connect without credentials or with wrong credentials, and verify that no messages are received (or can be sent)

I wouldn't get monitor events into this anywhere except as a source of debug logs.

**Comment by Jeducious** [comment]
> run tests with credentials to make sure everything works,
Would the test examples from pyzmq be a good guide here? They don't use events as you recommend. They attempt to send a message, upon which the result of the test is judged rather than using events. I somewhat naively thought that I could use the events related to auth as a way to test things :)

**Comment by Jeducious** [comment]
@minrk you're correct on seeing events, turns out I was breaking on the CONNECTED event, all the auth stuff comes after that as shown below

```
CRESS:reverse proxy sub socket:EVENT: CONNECT_DELAYED:112:tcp://127.0.0.1:63416
CRESS:reverse proxy sub socket:EVENT: CONNECTED:1704:tcp://127.0.0.1:63416
CRESS:reverse proxy sub socket: Connected to 127.0.0.1:63416
CRESS:reverse proxy sub socket:EVENT: HANDSHAKE FAILED AUTH:400:tcp://127.0.0.1:63416
CRESS:reverse proxy sub socket:EVENT: DISCONNECTED:1704:tcp://127.0.0.1:63416
```
So in fact, the events do show that the connection was unsuccessful, but I think I will test for sure using the method in [the pyzmq tests](https://github.com/zeromq/pyzmq/blob/546b258f4b65939953eec57cafa2cd809debb93f/zmq/tests/test_auth.py#L100)

Thanks for the help :)
