### ISSUE TITLE
zmq.proxy missing capture in type hint

### ISSUE THREAD

**Issue by TedJH1** [zeromq/pyzmq#1728]
zmq.proxy(frontent, backend, capture) results in an unexpected argument error due to an incorrect function definition. 
The docs say this is a valid definition but pyzmq only has a definition for zmq.proxy(frontent, backend)
ZMQ Version: 23.2.0
libzmq3-dev Version: 4.3.4

**Comment by minrk** [comment]
`zmq.proxy` does indeed accept an optional `capture` argument, but the type annotation is missing it. Are you seeing actual errors, or warnings from a type-checker like mypy?

**Comment by TedJH1** [comment]
No actual errors, just a warning in PyCharm like so
![image](https://user-images.githubusercontent.com/48918709/175567778-c73e3431-984e-48e5-b786-91e6d3767732.png)
The PR should fix it so I will mark tht thread as closed. Thanks
