### ISSUE TITLE
Containerizing pyzmq

### ISSUE THREAD

**Issue by WaelKarkoub** [zeromq/pyzmq#1736]
Hello, I'm not really sure if this is the right place to discuss this but I would appreciate any insight. I'm trying to containerize an application that has pyzmq as a dependency (I'm using Bazel to build and push the containers) and i'm getting this error when I run the containers:

```
ImportError: cannot import name '_device' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import)
```

Does the environment at which I build the system affect how pyzmq is installed?
I'm not doing anything special, just listing pyzmq as a pip dependency.

**Comment by minrk** [comment]
> Does the environment at which I build the system affect how pyzmq is installed?

Yes, absolutely. Like any compiled Python Extension, it must be compiled for the target environment. I know cross compilation for Python extensions is possible, but I don't know much about it.

The 'circular import' error is just a completely wrong message that recent versions of Python show for ~any compiled extension that can't be loaded.

**Comment by wael-built** [comment]
Aahhh that makes a lot more sense, thanks for the help!
