### ISSUE TITLE
ZMQError: operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by thatrandomperson5** [zeromq/pyzmq#1741]
What does this even mean?

**Comment by minrk** [comment]
This is libzmq's EFSM, meaning the send/recv cycle on a REQ or REP socket was violated. It is not a pyzmq error. [this doc](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/client_server.html) has some explanation and an example.
