### ISSUE TITLE
missing docstring in zmq.utils.win32

### ISSUE THREAD

**Issue by willmendil** [zeromq/pyzmq#1749]
I was using pyzmq a few years back and I remember reading quite complete documentation, but now there's not much in it. 
And indeed, looking at the two links:
https://pyzmq.readthedocs.io/en/v23.2.1/api/zmq.utils.win32.html
https://pyzmq.readthedocs.io/en/v20.0.0/api/zmq.utils.win32.html
The latter has much more information?
What has happened after v20? Are there any plans in updating the old but very useful documentation?

**Comment by minrk** [comment]
That's definitely a mistake. The docstring's still there, I'm not sure why it isn't picked up by sphinx.

**Comment by minrk** [comment]
#1750 fixes this
