### ISSUE TITLE
zmq.Context as a context manager hangs if sockets are left open

### ISSUE THREAD

**Issue by bdube-jpl** [zeromq/pyzmq#1757]
A MWE:
```python
import zmq

with zmq.Context() as ctx:
    # deadlocks
    raise ValueError

# vs ...
ctx = zmq.Context()
# works normally / as expected
raise ValueError
```

python 3.10.5
OS: darwin/arm64 (M1)
pyzmq 23.2.0

**Comment by minrk** [comment]
I see an immediate and clean exit when I run that example (same Python, OS/platform and pyzmq). How did you install pyzmq (wheel, source, or conda)?

Did you perhaps remove the creation of some sockets from the MWE?

**Comment by bdube-jpl** [comment]
Ah, my apologies; I did indeed prune too much.  Here's a revision:

```python
# no_sock.py
import zmq

with zmq.Context() as ctx:
    # deadlock
    raise ValueError
```
```sh
$ python no_sock.py
Traceback (most recent call last):
  File "/Users/bdube/proj/cpm/isaac/cmd/lvmock/no_sock.py", line 5, in <module>
    raise ValueError
ValueError
```

```python
# sock_no_with.py
import zmq

with zmq.Context() as ctx:
    s = ctx.socket(zmq.REQ)
    raise ValueError
```
```sh
$ python sock_no_with.py
...waited several seconds ^CTraceback (most recent call last):
  File "/Users/bdube/proj/cpm/isaac/cmd/lvmock/sock_no_with.py", line 5, in <module>
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bdube/proj/cpm/isaac/cmd/lvmock/sock_no_with.py", line 3, in <module>
    with zmq.Context() as ctx:
  File "/Users/bdube/miniconda3/envs/isaac/lib/python3.10/site-packages/zmq/sugar/context.py", line 96, in __exit__
    self.term()
  File "/Users/bdube/miniconda3/envs/isaac/lib/python3.10/site-packages/zmq/sugar/context.py", line 192, in term
    super().term()
  File "zmq/backend/cython/context.pyx", line 83, in zmq.backend.cython.context.Context.term
  File "zmq/backend/cython/checkrc.pxd", line 13, in zmq.backend.cython.checkrc._check_rc
KeyboardInterrupt
```
And a third version:
```python
# sock_with.py
import zmq

with zmq.Context() as ctx:
    with ctx.socket(zmq.REQ) as s:
        raise ValueError
```
```sh
$ python sock_with.py
Traceback (most recent call last):
  File "/Users/bdube/proj/cpm/isaac/cmd/lvmock/sock_with.py", line 5, in <module>
    raise ValueError
ValueError
```

> How did you install pyzmq (wheel, source, or conda)?

Via conda, subject to `CONDA_SUBDIR=osx-arm64`
```sh
$ conda list pyzmq
# packages in environment at /Users/bdube/miniconda3/envs/isaac:
#
# Name                    Version                   Build  Channel
pyzmq                     23.2.0          py310hc377ac9_0  
```

**Comment by minrk** [comment]
Right - exit calls `term` which blocks until sockets are closed. This is _technically_ safest, in that it avoids crashes for valid use cases where sockets are run in other threads and must be cleaned up there.

But since it makes very little sense to me to use `with Context()` to launch sockets in other threads, plus hangs are really a lot more likely (and frankly more confusing and disruptive) than threadsafety crashes, calling `destroy()` in `__exit__` seems like the right behavior (with warning because it's always a user bug if there are any open sockets at time of `__exit__`).

**Comment by bdube-jpl** [comment]
Thanks -- this bit me fiddling with some code in a prompt, where N REQ sockets are spawned to by pass function calls through a ZMQ-based server, and in the wire protocol there is a means to return errors/exceptions.  Upon the first exception, everything just stopped since those sockets aren't (can't be) inside a `with ... as` block
