### ISSUE TITLE
BUG: Wheels not installing properly on CIs

### ISSUE THREAD

**Issue by larsoner** [zeromq/pyzmq#1763]
Over in MNE-Python our automated Linux Python 3.10 build is failing when trying to build ZMQ, which it shouldn't need to do since there should be wheels for it:

https://app.circleci.com/pipelines/github/mne-tools/mne-python/16391/workflows/984fab74-f98c-40f1-ad6a-1a77c6821448/jobs/49166

<details>

```
Building wheel for pyzmq (pyproject.toml) ... - error
  error: subprocess-exited-with-error
  
  × Building wheel for pyzmq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [183 lines of output]
  ...
      already have platform.hpp
      checking for timer_create
      ************************************************
      ************************************************
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/circleci/python_env/include -I/usr/include/python3.10 -c /tmp/timer_create5sbrpe06.c -o tmp/timer_create5sbrpe06.o
      /tmp/timer_create5sbrpe06.c: In function ‘main’:
      /tmp/timer_create5sbrpe06.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
          2 |     timer_create();
            |     ^~~~~~~~~~~~
      x86_64-linux-gnu-gcc tmp/timer_create5sbrpe06.o -L/usr/lib/x86_64-linux-gnu -o a.out
      ok
      ************************************************
      building 'zmq.libzmq' extension
      creating build/temp.linux-x86_64-cpython-310/buildutils
      creating build/temp.linux-x86_64-cpython-310/bundled
      creating build/temp.linux-x86_64-cpython-310/bundled/zeromq
      creating build/temp.linux-x86_64-cpython-310/bundled/zeromq/src
      x86_64-linux-gnu-g++ -std=c++11 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -DZMQ_IOTHREADS_USE_EPOLL=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/home/circleci/python_env/include -I/usr/include/python3.10 -c buildutils/initlibzmq.cpp -o build/temp.linux-x86_64-cpython-310/buildutils/initlibzmq.o
      buildutils/initlibzmq.cpp:10:10: fatal error: Python.h: No such file or directory
         10 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
Successfully built numpydoc pydata-sphinx-theme sphinx-gallery sphinxcontrib-bibtex sphinx_design mne-bids mne-connectivity
Failed to build pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
```

</details>

So I suspect there is some problem with your Linux wheels at least for the 24.0 release.

**Comment by larsoner** [comment]
... and adding to our `requirements_doc.txt` a `pyzmq!=24.0.0` we get a correct wheel detection:
```
Collecting pyzmq!=24.0.0
  Using cached pyzmq-23.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
```

**Comment by rb-determined-ai** [comment]
This is affecting us as well.  It looks like the 24.0.0 manylinux x86_64 wheels are just not there.  Maybe also manylinux aarch64.

**Comment by shughes-uk** [comment]
Looks like the github action that builds the manylinux wheel blew up to a random tcp error

https://github.com/zeromq/pyzmq/actions/runs/3061316889/jobs/4940934548

**Comment by joekohlsdorf** [comment]
@minrk Can you rerun the job which builds and publishes the x86_64 wheels?

**Comment by brando90** [comment]
this creates an issue for the arm wheels as well. I can confirm that before thi released it worked in my docker container on my m1 mac and docker container.

**Comment by brando90** [comment]
these are likely the same bug: https://github.com/zeromq/pyzmq/issues/1764

**Comment by brando90** [comment]
work around, install prev version:
```
pip install pyzmq==23.2.1
```

**Comment by minrk** [comment]
Several wheel upload steps failed on CI, sorry everyone! Arm linux wheels are uploaded, linux-x86_64 and mac-pypy should be up shortly.

**Comment by minrk** [comment]
Thanks for the reports, everyone! All the wheels are up now.

Note for anyone installing in environments without compilers, pip's `--only-binary` flag may be useful. It ignores versions and packages that don't have wheels. You can pass this for one or more packages, or for `:all:` to only consider wheels at all.

**Comment by HongW2019** [comment]
Yeah, now it works with the new uploaded wheel.

**Comment by joekohlsdorf** [comment]
> I'll have to investigate why this caused failures. I wouldn't expect missing wheels to cause ~any failures, only delays as pyzmq is built from source. Unless jobs are being run without any compilers available, which would be unusual for CI.

Building from source can only succeed if your machine has a compiler installed.
You can reproduce this by trying to install without a wheel in a slim variant of the Python Docker images.

Ideally the release shouldn't be published until all expected release artifacts built successfully.

**Comment by minrk** [comment]
> Ideally the release shouldn't be published until all expected release artifacts built successfully.

That sounds great! But can PyPI even do that? Once one file is uploaded, the release is published. I don't know that there's a mechanism for unpublished releases on PyPI.
