### ISSUE TITLE
aarch64 publish failed for 24.0.1

### ISSUE THREAD

**Issue by ddelange** [zeromq/pyzmq#1776]
Hi @minrk 👋 

I spotted this error (our CI pipeline broke on aarch64):

https://app.circleci.com/pipelines/github/zeromq/pyzmq/106/workflows/4cea02b2-7484-4640-91d1-67cc3322564d/jobs/191

Could you try re-running?

**Comment by minrk** [comment]
Yup, doing the manual upload now.

**Comment by minrk** [comment]
They should all be up now.
