### ISSUE TITLE
Documentation libzmq version typo

### ISSUE THREAD

**Issue by bmcdonald3** [zeromq/pyzmq#1778]
Looking at the documentation, I am seeing that libzmq versions `(≥ 3.2.2, ≥ 4.0.1 )` are supported (https://pyzmq.readthedocs.io/en/latest/#supported-libzmq), but am seeing `zmq.error.ZMQVersionError: zmq.has requires libzmq >= 4.1, have 4.0.4` on my machine. This is confusing to me, since this fits the constraints of the docs, but is being displayed as an error.

Is this a typo with the documentation or a mischecking by the error? (possibly `4.1.0` was meant, instead of `4.0.1` in the docs?)

Edit:
This is pyzmq version 24.0.1 (did not see this error on 24.0.0)

**Comment by minrk** [comment]
This is not a typo. zmq.has is a binding for libzmq's zmq_has, which was introduced in libzmq 4.1. PyZMQ builds against lots of different libzmq versions, but the features available depend on the underlying libzmq.

**Comment by minrk** [comment]
What's zmq.zmq_version() in your 24.0.0 and 24.0.1 installs? 4.0 is 8 years out of date, so it's a bit surprising to see it in 2022.
