### ISSUE TITLE
DRAFT Build overloads R.Pi / Ubuntu 22

### ISSUE THREAD

**Issue by breaker-of-stone** [zeromq/pyzmq#1792]
Followed the procedure(s) for building PyZMQ with DRAFT features:

https://github.com/zeromq/pyzmq/blob/main/examples/draft/install.sh
https://pyzmq.readthedocs.io/en/latest/howto/draft.html

Previously a DRAFT-mode v4.3.4 build worked fine under Ubuntu 20 on the Raspberry Pi 4B 4Meg with Python 3.9.6.

Upgraded in-place to Ubuntu 22.04 recently, and it installed Python 3.10.6 removing most installed modules.
Re-installed everything else, then re-ran the procedures documented above.

The Make step generates a stupid number of concurrent GCC (cc1plus) processes - 600-700 of them, pushing the load average past 90 until the system just froze.  Modified Make through progressively lower job limits until Make -j 8 succeeded in compiling libzmq.

You did know that the recommended command encourages Make to generate jobs without limit?

make -j && make install      # --- Did someone accidentally leave out the numeric value for the -j arg?

**Comment by minrk** [comment]
Yup, `make -j` should indeed get a number (no number will work on most systems except those extremely resource limited like an rPi, but always good). It would be nice if there were a reliable, portable way to count cpus, but python's `os.cpu_count()` is probably the best.
