### ISSUE TITLE
BUG: setuptools deprecating test

### ISSUE THREAD

**Issue by grawlinson** [zeromq/pyzmq#1806]
### What pyzmq version?

any

### What libzmq version?

any

### Python version (and how it was installed)

3.10

### OS

Arch Linux

### What happened?

No bug *yet*, but `setuptools` will be deprecating `python setup.py test` shortly. And from what I remember, pytest-runner isn't a viable replacement due to it using `python setup.py test` under the hood.

References:

* https://github.com/pypa/setuptools/issues/1684
* https://github.com/pypa/setuptools/issues/931

**Comment by minrk** [comment]
We don't seem to use anything from setuptools test for `setup.py test`. We have our own `TestCommand` which inherits from the base Command, and is a simple wrapper to shell out to `python -m pytest`.

I'm not sure why we have that! But it doesn't seem to touch anything that's deprecated. We don't have a tests_require.
