### ISSUE TITLE
pyzmq swallows error when attempting connection to blocked port (firewall)

### ISSUE THREAD

**Issue by ghpqans** [zeromq/pyzmq#1808]
**Actual:**

The following code swallows a connection error, if the firewall on the server-side blocks the port the client connects to.
```
import zmq

endpoint = "tcp://{IP}:{PORT}"   # < -- The PORT is blocked by a firewall

zmq_ctx = zmq.Context()
sock = zmq_ctx.socket(zmq.PAIR)
sock.connect(endpoint)  # <--- I would expect an exception thrown here, however this is not the case

sock.disconnect(endpoint)
sock.close()
zmq_ctx.term()  # <--- This blocks infinetely
```
Instead of throwing an exception the code runs into the `zmq_ctx.term()` and blocks infinitely, then.

**Expected:**

Having a possibility to catch such a connection error during initialization phase not during shutdown phase.
 
**Workaround:**
Attempt telnet connection before attempting zmq connection on the same endpoint.

**Comment by minrk** [comment]
Questions about libzmq behavior should generally be directed to the libzmq repo. pyzmq doesn't govern this behavior. libzmq's async connection behavior means that connection events happen in the background, and don't block, which often means errors can't be raised in connect (e.g. you can connect to a peer before it's there, and libzmq will retry until it succeeds).

It does seem like a libzmq bug that disconnect followed by close & term would hang, which is generally reserved for outstanding messages (governed by socket.linger).
