### ISSUE TITLE
BUG: error importing zmq

### ISSUE THREAD

**Issue by pnael** [zeromq/pyzmq#1814]
### What pyzmq version?

24.0.1

### What libzmq version?

libzmq3-3.2.5_1

### Python version (and how it was installed)

python 3.9

### OS

Freebsd 13.1-RELEASE-p5

### What happened?

I can't import zmq. I am getting this error:
Python 3.9.15 (main, Oct 22 2022, 01:13:09) 
[Clang 13.0.0 (git@github.com:llvm/llvm-project.git llvmorg-13.0.0-0-gd7b669b3a on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/philippe/.local/lib/python3.9/site-packages/zmq/__init__.py", line 61, in <module>
    _load_libzmq()
  File "/home/philippe/.local/lib/python3.9/site-packages/zmq/__init__.py", line 36, in _load_libzmq
    from . import libzmq
ImportError: /home/philippe/.local/lib/python3.9/site-packages/zmq/libzmq.cpython-39.so: Undefined symbol "unw_getcontext"

**Comment by minrk** [comment]
Please include the full command used to build and install pyzmq, and the pyzmq build output, e.g.

```
pip install -vv --no-binary pyzmq pyzmq
```

I'd also recommend using `libzmq4` instead of `libzmq3`, which is ~10 years outdated at this point, I think.

**Comment by pnael** [comment]
I hope I got your questions : 
[philippe@jupiter ~]$ pip install -vv --no-binary pyzmq pyzmq
Using pip 22.2.2 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-5k9t347i
Created temporary directory: /tmp/pip-build-tracker-lekfc55u
Initialized build tracking at /tmp/pip-build-tracker-lekfc55u
Created build tracker: /tmp/pip-build-tracker-lekfc55u
Entered build tracker: /tmp/pip-build-tracker-lekfc55u
Created temporary directory: /tmp/pip-install-hhaiadja
Requirement already satisfied: pyzmq in ./.local/lib/python3.9/site-packages (24.0.1)
Created temporary directory: /tmp/pip-unpack-js6lqfoj
Remote version of pip: 22.3.1
Local version of pip:  22.2.2
Was pip installed by pip? False
Removed build tracker: '/tmp/pip-build-tracker-lekfc55u'

**Comment by pnael** [comment]
I will wee if I can try libzmq4

**Comment by minrk** [comment]
Make sure to include the output of the build itself. What you've given only shows the output when pyzmq is already installed.

Try making a virtualenv and installing with `pip install -v --no-cache pyzmq` to avid re-using a past build.
