### ISSUE TITLE
BUG: pyzmq release depends on deprecated py package, which does not seem to be used

### ISSUE THREAD

**Issue by bneijt** [zeromq/pyzmq#1820]
### What pyzmq version?

24.0.1

### What libzmq version?

4.3.4

### Python version (and how it was installed)

3.10.8

### OS

Archlinux

### What happened?

Due to a [security advisory against the `py` package](https://osv.dev/vulnerability/GHSA-w596-4wvx-j9j6), the pytest team decided to drop py from [their code dependencies in their latest release](https://github.com/pytest-dev/pytest/releases/tag/7.2.0) to mitigate this issue.

I do not expect the pytest team to maintain/change the py package or release a new version. This means that if you run osv scanner against anything using libzmq you get an error stating you are including `py` which has the above mentioned issue.

Looking at the code of libzmq, I don't really see any import of the py library, so maybe this is even a dependency that is nolonger used? It is mentioned in the METADATA for the 24.0.1 release of pyzmq as `Requires-Dist: py ; implementation_name == "pypy"
`

### Code to reproduce bug

```python
Run osv-scanner on an environment where libzmq is installed.
```

### More info

I have no idea where the dependency gets injected, it might just be an artifact of automatically generating dependencies in the `setup.py` code??

**Comment by minrk** [comment]
Sounds like a bug in osv-scanner, if you aren't using pypy.

But this dependency has been removed in #1816

**Comment by bneijt** [comment]
The story is a bit more complicated indeed, but great to see the dependency is removed when it's not being used.

Thank you and looking forward to the upcoming release.
