### ISSUE TITLE
BUG: has_function in setup.py does not work

### ISSUE THREAD

**Issue by fweimer-rh** [zeromq/pyzmq#1825]
### What pyzmq version?

24.0.0

### What libzmq version?

24.0.0 (I believe)

### Python version (and how it was installed)

3.11, Fedora rawhide

### OS

Fedora rawhide

### What happened?

In `setup.py`, `has_function` is called for `timer_create`, to detect whether linking with `-lrt` is needed. This check does not work because `has_function` is fundamentally broken, see pypa/setuptools#3648. In this case, failure just leads to overlinking with `-lrt`, which has no effect on glibc 2.34+ anyway, but it still makes sense to migrate off this broken and unsupported `has_function` interface.

**Comment by minrk** [comment]
setuptools is no longer used
