### ISSUE TITLE
zmq.HWM socket failing with Invalid argument error

### ISSUE THREAD

**Issue by Zlopez** [zeromq/pyzmq#1831]
### What pyzmq version?

Python 3.11.1

### What libzmq version?

4.3.4

### Python version (and how it was installed)

Python 3.11.1 as Fedora package

### OS

Fedora Silverblue 37

### What happened?

When trying to setup `zmq.PUB` socket with `zmq.HWM` it fails with `zmq.error.ZMQError: Invalid argument`.

### Code to reproduce bug

```python
import zmq 

context = zmq.Context(1)

gateway_socket = context.socket(zmq.PUB)

hwm = 160000

gateway_socket.setsockopt(zmq.HWM, hwm)
```

### Traceback, if applicable

```shell
Traceback (most recent call last):
  File "/var/home/zlopez/work/fedmsg-gateway/zmq_reproducer.py", line 12, in <module>
    gateway_socket.setsockopt(zmq.HWM, hwm)
  File "zmq/backend/cython/socket.pyx", line 449, in zmq.backend.cython.socket.Socket.set
  File "zmq/backend/cython/socket.pyx", line 285, in zmq.backend.cython.socket._setsockopt
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
```

### More info

I tried different values for `hwm` variable, if you provide anything else than `int` it will complain when trying number, it will throw the error above.

**Comment by minrk** [comment]
There is no `zmq.HWM` in libzmq >= 3, I believe. send and receive hwm are separate: [zmq.SNDHWM](http://api.zeromq.org/4-3:zmq-setsockopt#toc52) and [zmq.RCVHWM](http://api.zeromq.org/4-3:zmq-setsockopt#toc40).

**Comment by Zlopez** [comment]
Thanks, I can now see where is the issue in original code that started failing.

It seems that `hasattr(zmq, "HWM")` still returns true, even in libzmq >= 3 and it falls back to libzmq 2 initialization. I will just check the version instead.
