### ISSUE TITLE
SUB socket declines all messages by default

### ISSUE THREAD

**Issue by KVasya** [zeromq/pyzmq#1846]
### What pyzmq version?

22.3.0

### What libzmq version?

4.3.4

### Python version (and how it was installed)

python 3.10 installed along with Ubuntu installation

### OS

Ubuntu 22.04 LTS

### What happened?

It's not a bug that I'm trying to report here, but rather a hint how to make the product better (as I think).   

Currently SUB socket declines all messages if not configured by socket.setsockopt().
To make SUB socket receive all messages,  one must set the option zmq.SUBSCRIBE to b'' by socket_SUB.setsockopt(zmq.SUBSCRIBE, b''). I spent a long time to reveal that such a default filtering  
exists, testing many hypotheses why SUB socket receives nothing.

I believe SUB socket must receive all messages by default. 
Filtering should be  introduced as an option.

**Comment by minrk** [comment]
Thanks for the suggestion! pyzmq doesn't modify libzmq behavior, so this would be a suggestion for upstream.

If you're making lots of sockets, you can make this a tiny bit more convenient in pyzmq by setting socket options on the _context_ (which is only a shortcut for calling setsockopt after socket creation):

```ptyhon
import zmq

ctx = zmq.Context()
ctx.setsockopt(zmq.SUBSCRIBE, b'')
s = ctx.socket(zmq.SUB) # already subscribed!
``
