### ISSUE TITLE
BUG: sdist is missing some test related files

### ISSUE THREAD

**Issue by mtelka** [zeromq/pyzmq#1857]
### What pyzmq version?

25.0.2

### What libzmq version?

NA

### Python version (and how it was installed)

NA

### OS

NA

### What happened?

The sdist package at PyPI is missing few files related to testing.  So far I identified these:
- the `mypy_tests` directory and all files in it
- `pytest.ini`
- `mypy.ini`

Please add missing files to sdist to make downstream testing easier.

Thank you.

**Comment by minrk** [comment]
Thanks for reporting! Fixed by #1860
