### ISSUE TITLE
[lint] abstract class instantiated

### ISSUE THREAD

**Issue by mrx23dot** [zeromq/pyzmq#1895]
### What pyzmq version?

25.0.0

### What libzmq version?

?

### Python version (and how it was installed)

3.8

### OS

win10

### What happened?

Pylint gives error for 

`zRepCtx = zmq.Context()`
Abstract class 'Context' with abstract methods instantiated

Not getting this for other libs, so I guess this is something not nice.
Still works, only a lint issue.

**Comment by minrk** [comment]
@mrx23dot can you check with pyzmq 25.1.1? I think this is fixed.
