### ISSUE TITLE
RFE: is it possible to restart making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [zeromq/pyzmq#1906]
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by minrk** [comment]
If I did this, I'd go with the empty version, because I don't want to duplicate release notes or assets already elsewhere, which is all already automated to the right places. Everything about the github release would be redundant other than the email notification, I guess. It wouldn't include assets or release notes, but might have a link to PyPI for assets and actual release notes.

**Comment by kloczek** [comment]
> If I did this, I'd go with the empty version

Most of the github projects does the same and it is 100% enough to send notification about new version 😋

**Comment by kloczek** [comment]
Thank you very much 👍 😄

**Comment by minrk** [comment]
didn't quite work, but I'm pretty sure it will next time.

**Comment by minrk** [comment]
[this one](https://github.com/zeromq/pyzmq/releases/tag/v26.0.0a4) was created by CI, so seems to work fine.

**Comment by kloczek** [comment]
yep .. just received notification 👍
