### ISSUE TITLE
pip install pyzmq doesn't include libzmq

### ISSUE THREAD

**Issue by zacwitte** [zeromq/pyzmq#193]
The readme incorrectly says

> We have binary installers for various Pythons on OSX and Windows, so you should be able to just easy_install pyzmq in many situations. These eggs include matching libzmq, so they should be the only thing you need to start using pyzmq

But when I try to install with pip it can't find zmq.h and fails to build.

```
$ sudo pip install pyzmq
Downloading/unpacking pyzmq
  Downloading pyzmq-2.1.11.tar.gz (611Kb): 611Kb downloaded
  Running setup.py egg_info for package pyzmq

Installing collected packages: pyzmq
  Running setup.py install for pyzmq
    ******************************************
    Configure: Autodetecting ZMQ settings...
        Custom ZMQ dir:       None
    llvm-gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/opt/local/include -Izmq/utils -Izmq/core -Izmq/devices -c detect/vers.c -o detect/vers.o
    detect/vers.c:3:17: error: zmq.h: No such file or directory
    detect/vers.c: In function ‘main’:
    detect/vers.c:7: warning: implicit declaration of function ‘zmq_version’
    detect/vers.c:3:17: error: zmq.h: No such file or directory
    detect/vers.c: In function ‘main’:
    detect/vers.c:7: warning: implicit declaration of function ‘zmq_version’
    lipo: can't open input file: /var/tmp//ccVFccmt.out (No such file or directory)
    Fatal:
        Failed to compile ZMQ test program.  Please check to make sure:

        * You have a C compiler installed
        * A development version of Python is installed (including header files)
        * A development version of ZMQ >= 2.1.4 is installed (including header files)
        * If ZMQ is not in a default location, supply the argument --zmq=<path>
        * If you did recently install ZMQ to a default location,
          try rebuilding the ld cache with `sudo ldconfig`
          or specify zmq's location with `--zmq=/usr/local`
```

After installing zeromq with homebrew it works. This is all fine, but the readme is wrong or I interpret it wrongly.

**Comment by stayhigh** [comment]
if you meet error on mac osX
build/temp.macosx-10.9-intel-2.7/scratch/vers.c:4:10: fatal error: 'zmq.h' file not found
    #include "zmq.h"
             ^
    1 error generated.

    error: command ‘cc’ failed with exit status 1

    Warning: Failed to build or run libzmq detection test.

It could be fixed by the following command if you have 'brew' .
brew install zerozmq 

After this command, if you still got message to ask you to install jijna2 tornado, just install them you fixed the problem.

**Comment by pokjnb** [comment]
what if installing libzmq in windows?
"easy_install" seems not worked ( I type them in CMD)

**Comment by minrk** [comment]
easy_install has been deprecated for many years. `pip install pyzmq` should get bundled libzmq on Windows.
