### ISSUE TITLE
BUG: IPC Support on Windows broken in 25.1.2

### ISSUE THREAD

**Issue by MrMoose** [zeromq/pyzmq#1959]
### This is a pyzmq bug

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

25.1.2

### What libzmq version?

libzmq-v141-mt-4_3_4-0a6f51ca.dll

### Python version (and how it was installed)

Python 3.10

### OS

Windows (10 and 11)

### What happened?

Opening an IPC socket on Windows will yield: ZMQError Protocol not supported.
This used to work with 23.0.0

### Code to reproduce bug

```python
#!/usr/bin/env python3

import zmq

if __name__ == "__main__":
    ctx = zmq.Context.instance()
    socket = ctx.socket(zmq.PAIR)
    socket.linger = 0
    socket.connect("ipc://ecm_data_sm.ipc")
```

### Traceback, if applicable

```shell
n/a
```

### More info

According to my guesswork this is because apparently the libzmq DLL used in the wheel got downgraded in the used ABI version. In 23.x there was: libzmq-v142-mt-4_3_4-4e355e3e.dll. Now in 25.x the used DLL is: libzmq-v141-mt-4_3_4-0a6f51ca.dll.
My guess is that the ABI 141 does not support IPC as mentioned in this (closed) bug report: https://github.com/zeromq/pyzmq/issues/1462#issuecomment-831884567

So this would be a bit of a regression and should perhaps be unit tested.

**Comment by MrMoose** [comment]
Ah, okay. I did not realize this was a deliberate change. That explains it.
I just tested the reproducer with the prerelease and it works. However, I will have to test the whole application with it, so this will take a while longer. I will comment here if it works.

Since I won't be able to use a prerelease in production, do you have some timeframe on when this is going to be the official release?

**Comment by minrk** [comment]
Not concrete, but hopefully soon. I'm trying to track down some cross-compilation issues, but the more 'works for me' reports I get from Windows folks, the better I'll feel.

**Comment by MrMoose** [comment]
I'm closing this as it will already be fixed with the 26.x release once it is out.
Thanks for your responses!
