### ISSUE TITLE
BUG: ZMQ.HELLO_MSG

### ISSUE THREAD

**Issue by adhish9899** [zeromq/pyzmq#1973]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
I am getting `ZMQError: Invalid argument` when I am trying to use zmq.HELLO_MSG

# Environment
ubuntu: 22.04
pyzmq.__version__ = '25.1.2'

* libzmq version (commit hash if unreleased): 
* OS: ubuntu 22.04

# Minimal test code / Steps to reproduce the issue

```
import zmq
context = zmq.Context()
router = context.socket(zmq.ROUTER)

hello_msg = b"Hello, World!"
router.setsockopt(zmq.HELLO_MSG, hello_msg)
```

# What's the actual result? (include assertion message & call stack if applicable)
ZMQError: Invalid argument

# What's the expected result?

**Comment by somdoron** [comment]
Hello message is for client / dealer / peer. When used, they will automatically send the hello message when connected or reconnected to the peer socket.

**Comment by adhish9899** [comment]
Still getting the same error for dealer. 

```
import zmq
context = zmq.Context()
dealer = context.socket(zmq.DEALER)

hello_msg = b"Hello, World!"
dealer.setsockopt(zmq.HELLO_MSG, hello_msg)
```

## ERROR MESSAGE
```
      3 dealer = context.socket(zmq.DEALER)
      5 hello_msg = b"Hello, World!"
----> 6 dealer.setsockopt(zmq.HELLO_MSG, hello_msg)

File _zmq.py:765, in zmq.backend.cython._zmq.Socket.set()

File _zmq.py:1367, in zmq.backend.cython._zmq._setsockopt()

File _zmq.py:164, in zmq.backend.cython._zmq._check_rc()

ZMQError: Invalid argument
```

**Comment by minrk** [comment]
`zmq.HELLO_MSG` is a draft socket feature, and only available if you have built libzmq with drafts enabled. pyzmq wheels do not have libzmq with unstable optional features enabled.

If you want to use draft features, you must install pyzmq from source after compiling libzmq with drafts enabled (`pip install pyzmq --no-binary pyzmq`, and make sure that `zmq.has("draft")` returns True.

**Comment by adhish9899** [comment]
Thank you @minrk for your help.
