### ISSUE TITLE
BUG: pyzmq 26.0.1 failed to install

### ISSUE THREAD

**Issue by crazygao** [zeromq/pyzmq#1978]
### This is a pyzmq bug

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

26.0.1

### What libzmq version?

Nan

### Python version (and how it was installed)

every version

### OS

Every system

### What happened?

![image](https://github.com/zeromq/pyzmq/assets/2208599/07acd84b-6a14-4840-b7fe-861ebfc02cdf)

**Comment by jorenham** [comment]
I'm facing the same issue with python-poetry:

```
❯ poetry update
Updating dependencies
Resolving dependencies... (5.0s)

Package operations: 0 installs, 2 updates, 0 removals

  - Updating pyzmq (26.0.0 -> 26.0.1): Failed

  RuntimeError

  Unable to find installation candidates for pyzmq (26.0.1)

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install pyzmq.
```

**Comment by L1Aigner** [comment]
Facing the same problem with my Poetry setup. Unfortunately, before this error, I didn't even know I use this package somewhere. 😄 
Tbh I don't want to restrict the version now explicitly within my `pyproject.toml` but it is also braking my GitHub actions. I'm looking forward to a hotfix somewhere 😄

**Comment by Matesanz** [comment]
## How to reproduce:

:point_right:  **Command:**

```bash
pip install pyzmq==26.0.1
```

:x:  **Error**

```
ERROR: Could not find a version that satisfies the requirement pyzmq==26.0.1 (from versions: 2.0.7, 2.0.8, 2.0.10, 2.0.10.1, 2.1.1, 2.1.4, 2.1.7, 2.1.9, 2.1.10, 2.1.11, 2.2.0, 2.2.0.1, 13.0.0, 13.0.1, 13.0.2, 13.1.0, 14.0.0, 14.0.1, 14.1.0, 14.1.1, 14.2.0, 14.3.0, 14.3.1, 14.4.0, 14.4.1, 14.5.0, 14.6.0, 14.7.0, 15.0.0, 15.1.0, 15.2.0, 15.3.0, 15.4.0, 16.0.0, 16.0.1, 16.0.2, 16.0.3, 16.0.4, 17.0.0b1, 17.0.0b2, 17.0.0b3, 17.0.0b4, 17.0.0, 17.1.0, 17.1.1, 17.1.2, 17.1.3, 18.0.0, 18.0.1, 18.0.2, 18.1.0, 18.1.1, 19.0.0, 19.0.1, 19.0.2, 20.0.0, 21.0.0, 21.0.1, 21.0.2, 22.0.0, 22.0.1, 22.0.2, 22.0.3, 22.1.0, 22.2.0, 22.2.1, 22.3.0, 23.0.0b1, 23.0.0b2, 23.0.0, 23.1.0, 23.2.0, 23.2.1, 24.0.0, 24.0.1, 25.0.0b1, 25.0.0, 25.0.1, 25.0.2, 25.1.0, 25.1.1b1, 25.1.1b2, 25.1.1, 25.1.2, 26.0.0a1, 26.0.0a2, 26.0.0a3, 26.0.0a4, 26.0.0a5, 26.0.0a6, 26.0.0b1, 26.0.0b2, 26.0.0)
ERROR: No matching distribution found for pyzmq==26.0.1
```

![image](https://github.com/zeromq/pyzmq/assets/44867923/04ff54ca-34df-44ac-999b-213498e8c035)

**Comment by maxrostron** [comment]
Same issue here. Using poetry, and broke our CI just over an hour ago when 26.0.1 was pushed. CI was working beforehand.

**Comment by mrdantutunaru** [comment]
+1...same issue here with Poetry

**Comment by markclare1992** [comment]
win_amd64 failed too https://github.com/zeromq/pyzmq/actions/runs/8751239804

**Comment by alexrs** [comment]
For the people that ended up here looking for a workaround, you can specify `pyzmq` as a dependency in your `pyproject.yml` enforcing a version < 26.0.0:

```
pyzmq = "<26.0.0"
```

**Comment by jorenham** [comment]
@alexrs `26.0.0` works fine, so `<26.0.1` is sufficient

**Comment by minrk** [comment]
26.0.1 is published now

**Comment by LucasSchelkes-BA** [comment]
Still encountering same problem with 26.0.1. in poetry
