### ISSUE TITLE
Bad file descriptor (C:\Users\runneradmin\AppData\Local\Temp\tmpw8fxpxar\build\_deps\bundled_libzmq-src\src\epoll.cpp:73

### ISSUE THREAD

**Issue by gary-harp** [zeromq/pyzmq#1999]
### This is a pyzmq bug

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

26.0.3

### What libzmq version?

Not sure

### Python version (and how it was installed)

3.11 via Windows 

### OS

Windows 11

### What happened?

I believe this is bundled with Jupyter. Spinning up the Jupyter server fails with the error above when first notebook is opened. Downgrading to 25.1.2 solved the issue.

**Comment by minrk** [comment]
Did you install Python via the Windows Store? If so, this is #1981 . In either case, can you test with the appropriate wheel for you from the latest build [here](https://github.com/zeromq/pyzmq/actions/workflows/wheels.yml?query=event%3Apull_request+branch%3Awindows-static-msvcp) and let me know if it fixes things for you?

**Comment by gary-harp** [comment]
Thanks I'm not sure what [this](https://github.com/zeromq/pyzmq/actions/workflows/wheels.yml?query=event%3Apull_request+branch%3Awindows-static-msvcp) means. I can try to increment to 26.2 and check if it resolved if you want.
python was installed from windows store. This is a work machine and the mandatory security software that it runs will not allow to install other python distros. I imagine that this is the same for many machines. Microsoft has made some changes to the python distro that can cause issues. Recommend to that windows store python distros to your testing procedures.

**Comment by minrk** [comment]
Unfortunately, Microsoft Store installations are not available in any testing environments to my knowledge, so that is not feasible. But I have managed to reproduce this issue and confirm it was fixed by #2024, so if you can confirm it does so for you, that would be great! Or if it does not, that would be super helpful as well.

**Comment by gary-harp** [comment]
It should be feasible but you will need to spin up windows VM and use some [Powershell](https://serverfault.com/questions/1018220/how-do-i-install-an-app-from-windows-store-using-powershell). I tried 26.0.3 and 26.2.0 just now and wasn't able to reproduce. Sorry. Anyway thanks for working it.

**Comment by minrk** [comment]
Thanks so much for testing!

I wish it was that easy to set up a vm, but it took me months to find one that actually reproduced the bug, and only in incredibly slow x86 emulation on arm. I don't know why the Store usually isn't available and no cloud provider I have access to supports VMs with the store available. And even the store alone is not sufficient to reproduce the bug, it needed a username with non-ascii characters as well.

**Comment by minrk** [comment]
If you happen to have a chance and can test an install install from one of [these wheels](https://github.com/zeromq/pyzmq/actions/runs/10559364231/artifacts/1854343269) (download and unzip, then `pip install --force-reinstall path/to/pyzmq-...whl`), I _think_ I have fixed the underlying libzmq problem in https://github.com/zeromq/libzmq/pull/4734.
