### ISSUE TITLE
BUG: Type errors instantiating zmq.asyncio.Context

### ISSUE THREAD

**Issue by obeattie** [zeromq/pyzmq#2028]
### This is a pyzmq bug

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

26.2.0

### What libzmq version?

4.3.5

### Python version (and how it was installed)

Python 3.12.5

### OS

macOS 14.5 (23F79)

### What happened?

When instantiating an `zmq.asyncio.Context` exactly [as described in the docs](https://pyzmq.readthedocs.io/en/latest/api/zmq.asyncio.html#module-zmq.asyncio), I get a type error:

<img width="937" alt="Screenshot 2024-08-31 at 8 14 43 AM" src="https://github.com/user-attachments/assets/a01f195d-74c2-495a-9ab3-327f7f10bf27">

Everything is _functionally_ fine if I add a `# type: ignore` to ignore the type error, but of course not ideal to have to do that!

### Code to reproduce bug

```python
import zmq.asyncio

zmq_context = zmq.asyncio.Context()
```

**Comment by minrk** [comment]
Can you share more of how you are doing the type checking? Because all the type checking tests pass, so it might be a problem in the env or checker.

**Comment by minrk** [comment]
Looks like pyright doesn't understand the use of generics the same way mypy does. Fixed by #2032.

**Comment by obeattie** [comment]
Sorry I didn’t see the earlier reply. And thanks for fixing it! ❤️

**Comment by achimnol** [comment]
This could be better fixed by replacing `SyncSocket` type used in the `__init__()` overload method signatures of `zmq.sugar.context.Context` with `typing.Self`.
For Python versions earlier than 3.11, we could use `typing_extensions` to use `Self`, which satisfies both mypy and pyright.
