### ISSUE TITLE
BUG: Delay required after PUB bind before sending

### ISSUE THREAD

**Issue by JC3** [zeromq/pyzmq#2036]
### This is a pyzmq bug? Maybe?

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

26.2.0

### What libzmq version?

4.3.5

### Python version (and how it was installed)

3.10

### OS

macOS 13.6.6, Ubuntu 22.04

### What happened?

It appears that a delay is needed after creating and binding a `PUB` socket before the first message can be successfully published. In testing, a 200ms delay seems to be the minimum required delay. There seems to be no difference between various protocols (tried TCP and IPC). The following graph shows the `send_multipart` success rate vs. the delay time after `bind` for various delays (30 trials each).

<img width="608" alt="Screenshot 2024-09-30 at 11 15 32 AM" src="https://github.com/user-attachments/assets/eaf9a9ef-9d84-4723-9b33-09c7a63fdbc2">

### Code to reproduce bug

```python
import zmq
import time
import multiprocessing as mp
import struct

TEST_DELAYS = range(0,251,10)
TEST_TRIALS = 30
ADDRESS = "ipc:///tmp/delay_test.ipc" # "tcp://127.0.0.1:43212"


def _sub_main (keep_running):

    ctx = zmq.Context()
    
    sub = ctx.socket(zmq.SUB)
    sub.connect(ADDRESS)
    sub.setsockopt(zmq.SUBSCRIBE, b"")
    sub.setsockopt(zmq.RCVTIMEO, 500)

    results = {}
    
    while keep_running.value:
        try:
            (delay,) = struct.unpack("<i", sub.recv_multipart()[0])
        except zmq.Again:
            continue
        results[delay] = results.get(delay, 0) + 1
        print((delay, results[delay]))

    sub.close()
    ctx.destroy()

    print("---------")
    for delay_ms, success_rate in results.items():
        print(f"{delay_ms},{success_rate/TEST_TRIALS:.3f}")


def run_test (delay):

    ctx = zmq.Context()
    pub = ctx.socket(zmq.PUB)
    pub.bind(ADDRESS)
    if delay > 0:
        time.sleep(delay/1000.0)
    pub.send_multipart([struct.pack("<i", delay)])
    pub.close()
    ctx.destroy()        

def main ():

    keep_running = mp.Value('i', 1)
    receiver = mp.Process(target=_sub_main, args=(keep_running,))
    receiver.start()

    for delay in TEST_DELAYS:
        for k in range(TEST_TRIALS):
            run_test(delay)

    keep_running.value = 0
    receiver.join()

    
if __name__ == "__main__":
    main()
```

### More info

Is there a more deterministic way to check if the `PUB` socket is ready to send rather than adding arbitrary delays?

Is this a ZMQ issue or a PyZMQ issue?

**Comment by minrk** [comment]
Yes, this is a general libzmq issue, not related to pyzmq. Subscriptions take a finite time to propagate and PUB sockets discard messages if there are no suscribers. You can either switch to XPUB, which receives notifications of subscriptions, or implement robust publishing/resubscription assuming messages may drop. Much of this is discussed in [the guide](https://zguide.zeromq.org/docs/chapter5/).

Closing here since it's not related to pyzmq.
