### ISSUE TITLE
BUG: A file is licensed Apache-2.0, but the license text is not distributed

### ISSUE THREAD

**Issue by musicinmybrain** [zeromq/pyzmq#2048]
### This is a pyzmq bug

- [X] This is a pyzmq-specific bug, not an issue of zmq socket behavior. Don't worry if you're not sure! We'll figure it out together.

### What pyzmq version?

26.2.0

### What libzmq version?

N/A

### Python version (and how it was installed)

N/A

### OS

N/A

### What happened?

The file `zmq/eventloop/zmqstream.py` is licensed [`Apache-2.0`](https://spdx.org/licenses/Apache-2.0.html),

https://github.com/zeromq/pyzmq/blob/01ed5532a7710653a9925ec25d11cfe37185f672/zmq/eventloop/zmqstream.py#L2-L14

so a copy of the Apache license text [should be included in source distributions](https://www.apache.org/licenses/LICENSE-2.0#apply), but no such license text file is present.

### Code to reproduce bug

```python
Reproduce by inspecting the source tree.
```

### Traceback, if applicable

```shell
N/A
```

### More info

This can be resolved by adding the contents of https://www.apache.org/licenses/LICENSE-2.0.txt to a file at the top level of the source tree and verifying that it appears in the sdist.

**Comment by musicinmybrain** [comment]
Similarly, `zmq/ssh/forward.py` is [`LGPL-2.1-or-later`](https://spdx.org/licenses/LGPL-2.1-or-later.html),

https://github.com/zeromq/pyzmq/blob/01ed5532a7710653a9925ec25d11cfe37185f672/zmq/ssh/forward.py#L2-L18

but it is my understanding that (unlike `Apache-2.0`) the GPL-family licenses do not require the license text to be distributed.

**Comment by minrk** [comment]
Thanks! Updated to add the Apache text to the licenses directory for the derivative work.

**Comment by musicinmybrain** [comment]
Thanks! Looks good to me.
