### ISSUE TITLE
a second bind() does not raise an error

### ISSUE THREAD

**Issue by tarekziade** [zeromq/pyzmq#209]
Hey

I am trying to solve an issue I have with a broker that opens a zmq 
router socket and just relay calls to workers via a socket dealer.

The problem is that I don't know how to prevent a second broker to bind 
itself to the same ipc.

Consider the following scripts where I isolate the issue:

The server: http://tarek.pastebin.mozilla.org/1649175
The client: http://tarek.pastebin.mozilla.org/1649176

If I run them they happily interact. Now I can run a second server. It 
will bind the socket but won't do anything or even error out.

Isn't that supposed to error out ?

**Comment by devxpy** [comment]
@tarekziade Did you find a solution? This is quite annoying.
