### ISSUE TITLE
Can't include interface for epgm

### ISSUE THREAD

**Issue by h3adache** [zeromq/pyzmq#378]
When I try specifying the interface as in: http://api.zeromq.org/3-2:zmq-epgm
ex. epgm://eth0;239.255.0.1:10001
I get zmq.error.ZMQError: Invalid argument

Leaving eth0 off works fine.

**Comment by pengfengyong** [comment]
Do you know why libzmq not support interface? I meet the seem problem.When i use c++ zmqlib to bind “ epgm://eth0;239.255.0.1:10001”，it doesn't work.When i ignore interface it works.
