### ISSUE TITLE
easy_install fails to build libzmq

### ISSUE THREAD

**Issue by ncarenton** [zeromq/pyzmq#391]
Hi there,

I could not manage to build libzmq on my CentOS 5.9 

```
python --version
Python 2.7.4
cat /etc/redhat-release 
CentOS release 5.9 (Final)
which python
/usr/local/uvcdat/1.3.3/bin/python




pip install pyzmq
Downloading/unpacking pyzmq
Running setup.py egg_info for package pyzmq

no previously-included directories found matching 'docs/build'
no previously-included directories found matching 'docs/gh-pages'
warning: no directories found matching 'bundled/uuid'
warning: no previously-included files found matching 'bundled/uuid/Makefile*'
warning: no previously-included files found matching 'bundled/zeromq/src/Makefile*'
warning: no previously-included files found matching 'setup.cfg'
warning: no previously-included files found matching 'zmq/libzmq*'
warning: no previously-included files matching '__pycache__/*' found anywhere in distribution
warning: no previously-included files matching '.deps/*' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '.mailmap' found anywhere in distribution
Installing collected packages: pyzmq
Running setup.py install for pyzmq
already have bundled/zeromq
already have platform.hpp
************************************************
Using bundled libzmq
cc -c /tmp/timer_createRiC0i7.c -o tmp/timer_createRiC0i7.o
cc tmp/timer_createRiC0i7.o -o a.out
tmp/timer_createRiC0i7.o: In function `main':
timer_createRiC0i7.c:(.text+0x15): undefined reference to `timer_create'
collect2: ld returned 1 exit status
************************************************
building 'zmq.libzmq' extension
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c buildutils/initlibzmq.c -o build/temp.linux-x86_64-2.7/buildutils/initlibzmq.o
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/object.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/object.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/ipc_address.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/ipc_address.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/io_object.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/io_object.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/dist.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/dist.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/router.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/router.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/push.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/push.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/signaler.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/signaler.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++
bundled/zeromq/src/signaler.cpp:68:25: error: sys/eventfd.h: No such file or directory
bundled/zeromq/src/signaler.cpp: In static member function ‘static int zmq::signaler_t::make_fdpair(zmq::fd_t*, zmq::fd_t*)’:
bundled/zeromq/src/signaler.cpp:229: error: ‘eventfd’ was not declared in this scope
error: command 'gcc' failed with exit status 1
Complete output from command /usr/local/uvcdat/1.3.3/bin/python -c "import setuptools;__file__='/tmp/pip-build-root/pyzmq/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-9FT_V2-record/install-record.txt --single-version-externally-managed:
running install
```

running build

running build_py

running build_ext

running configure

already have bundled/zeromq

already have platform.hpp

---

Using bundled libzmq

cc -c /tmp/timer_createRiC0i7.c -o tmp/timer_createRiC0i7.o

cc tmp/timer_createRiC0i7.o -o a.out

tmp/timer_createRiC0i7.o: In function `main':

timer_createRiC0i7.c:(.text+0x15): undefined reference to `timer_create'

collect2: ld returned 1 exit status

---

building 'zmq.libzmq' extension

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c buildutils/initlibzmq.c -o build/temp.linux-x86_64-2.7/buildutils/initlibzmq.o

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/object.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/object.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/ipc_address.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/ipc_address.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/io_object.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/io_object.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/dist.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/dist.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/router.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/router.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/push.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/push.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

gcc -pthread -fno-strict-aliasing -I/usr/local/uvcdat/1.3.3/Externals/include -L/usr/local/uvcdat/1.3.3/Externals/lib -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ibundled/zeromq/include -Ibundled -I/usr/local/uvcdat/1.3.3/include/python2.7 -c bundled/zeromq/src/signaler.cpp -o build/temp.linux-x86_64-2.7/bundled/zeromq/src/signaler.o

cc1plus: warning: command line option "-Wstrict-prototypes" is valid for Ada/C/ObjC but not for C++

bundled/zeromq/src/signaler.cpp:68:25: error: sys/eventfd.h: No such file or directory

bundled/zeromq/src/signaler.cpp: In static member function ‘static int zmq::signaler_t::make_fdpair(zmq::fd_t_, zmq::fd_t_)’:

bundled/zeromq/src/signaler.cpp:229: error: ‘eventfd’ was not declared in this scope

error: command 'gcc' failed with exit status 1

---

Command /usr/local/uvcdat/1.3.3/bin/python -c "import setuptools;**file**='/tmp/pip-build-root/pyzmq/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-9FT_V2-record/install-record.txt --single-version-externally-managed failed with error code 1 in /tmp/pip-build-root/pyzmq
Storing complete log in /root/.pip/pip.log

Thanks for your help

**Comment by shymonk** [comment]
```
yum install zeromq-devel
pip install pyzmq --install-option="--zmq=/usr/lib"
```
Works for me, thanks.

**Comment by betterenvi** [comment]
@shymonk 
I did as you wrote, and it worked! Thanks!

**Comment by yhf597869822** [comment]
yum install zeromq-devel 
pip install pyzmq --install-option="--zmq=/usr/lib"
also works for me ,thanks
