### ISSUE TITLE
cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'

### ISSUE THREAD

**Issue by coded-zz** [zeromq/pyzmq#49]
vs 2008 sp1 + atl update, zeromq/pyzqm 2.0.10. looks like a simple fix, in setup.py ignore_common_warnings is set to True in both cases.

**Comment by Apoorvachavan** [comment]
Can you please tell me where is this setup.py file located?

**Comment by Apoorvachavan** [comment]
Can you just tell me where is this setup.py file located?
