### ISSUE TITLE
Handling server deaths in simple XREQ-XREP scenario. 

### ISSUE THREAD

**Issue by tonimichel** [zeromq/pyzmq#51]
I have a client (XREQ) and a server (XREP). I want to do error handling at the client, which means that the client should notice when a server is gone.

=> I cant use socket.recv() at client, as otherwise the client will block for ever when sending a msg to a death server
=> I make use of zmq.NOBLOCK

My Testcase consists of two little scripts, a server and a client: https://gist.github.com/734639

Start the client: python client.py tcp://127.0.0.1:8000 tcp://127.0.0.1:8001
Now, only start one server: python server.py tcp://127.0.0.1:8000

The XREQ socket itself does not notice that the one server is not available. As this socket is loadbalancing, every second message is send to the non-existing server. My client handles this, by resending in case it encountered a certain timout while waiting for a reply. 

=> I spoke with some people at the zmq-irc and they were all like "ZMQ should notice the serverdeath and handle it for you"
=> obviously, it is not, as the client sends to server A gets a response, sends to server B (death), runs in timeout, resends the message to server A, sends the next message to server B again, gets timeout and so on.

So the question is, how to handle this properly? As far as I know, there is no way of disconnecting from one particular address manually.

Please correct me if I misunderstood something.

Thanks,
- Toni

**Comment by Manimozhis95** [comment]
Hi,I need to use message queue in publisher/subscriber patter .Can any know whether i can use DEALER and ROUTER as intermediate.or any solution
