### ISSUE TITLE
Blocking on recv when using ioloop

### ISSUE THREAD

**Issue by bbirand** [zeromq/pyzmq#580]
I have a simple ZMQ socket that for doing a simple REQ-REP, and now I'd like to change it so that it runs on top of the ioloop. But I can't seem to find the right approach for using the callbacks with the ioloop.

I used to have this function:

    def ping(): 
        context = zmq.Context().instance()
        socket = context.socket(zmq.REQ)
        socket.connect("tcp://localhost:%s" % port)
        socket.send(amsg)
        result = socket.recv()
        socket.close()
        return result

Now I'm trying to write this using `ZMQStream` and the ioloop, but I'm not sure how to return the argument to `_recv` from `ping2()`:

    def ping2(): 
        context = zmq.Context().instance()
        socket = context.socket(zmq.REQ):
        socket.connect("tcp://localhost:%s" % port)
        stream = ZMQStream(socket)

        stream.send(amsg)
        def _recv(amsg):
           # Must return amsg from ping2?!
        result = stream.on_recv(_recv)
        stream.close()
        return result

Tornado has support for the `yield` syntax for giving control back to the ioloop, and then continuing from there (http://tornado.readthedocs.org/en/latest/gen.html):

        ...
        response = yield http_client.fetch("http://example.com")
        ...

Being able to write something like this would be neat:

        result = yield stream.recv()

Are there any other ways of writing `ping2()` that I am missing?

**Comment by minrk** [comment]
I've added sockets that return Futures for both tornado and asyncio. Will release as pyzmq-15 shortly.
