### ISSUE TITLE
zmq.error.ZMQError: Address already in use (even after killing the PID involved)

### ISSUE THREAD

**Issue by marcoippolito** [zeromq/pyzmq#623]
Hi all,

I'm new to pyzmq, so please forgive me if I ask you something simple.

In order to understand how pyzmq works, I'm trying to do the following
example: http://learning-0mq-with-pyzmq.readthedocs.org/en/latest/pyzmq/patterns/client_server.html

But when running the file it says:
python reqrep_server.py 5546
14.0.1
Traceback (most recent call last):
  File "reqrep_server.py", line 43, in <module>
    socket.bind("tcp://*:%s" % port)
  File "socket.pyx", line 434, in
zmq.backend.cython.socket.Socket.bind
(zmq/backend/cython/socket.c:3928)
  File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc
(zmq/backend/cython/socket.c:6058)
zmq.error.ZMQError: Address already in use

I'm using Ubuntu 14.04 (Server edition) and pyzmq installed version is : 14.0.1 with python 2.76

sudo netstat -ltnp
Connessioni Internet attive (solo server)
Connessioni Internet attive (solo server)
Proto CodaRic CodaInv Indirizzo locale        Indirizzo remoto
Stato       PID/Program name
tcp        0              0 0.0.0.0:4664                    0.0.0.0:*
               LISTEN             1157/sshd
tcp6       0                0 :::4664
:::\*                    LISTEN             1157/sshd

So I kill the PID involved
sudo kill -9 1157
but the problem is still there:
python reqrep_server.py 5546
14.0.1
Traceback (most recent call last):
  File "reqrep_server.py", line 43, in <module>
    socket.bind("tcp://*:%s" % port)
  File "socket.pyx", line 434, in
zmq.backend.cython.socket.Socket.bind
(zmq/backend/cython/socket.c:3928)
  File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc
(zmq/backend/cython/socket.c:6058)
zmq.error.ZMQError: Address already in use

After rebooting, and even after uninstall and then re-install via pip pyzmq, I got the same error message:
zmq.error.ZMQError: Address already in use

netstat

Socket in dominio UNIX attivi (senza server)
Proto RefCnt Flags       Type       State         I-Node   Percorso
unix  2      [ ]         DGRAM                    8961     /var/run/wpa_supplica                                                                                                                                                             nt/wlan0
unix  9      [ ]         DGRAM                    7746     /dev/log
unix  3      [ ]         DGRAM                    1640
unix  3      [ ]         STREAM     CONNESSO      11248
unix  2      [ ]         DGRAM                    11247
unix  3      [ ]         STREAM     CONNESSO      11627
unix  3      [ ]         STREAM     CONNESSO      9491
unix  2      [ ]         DGRAM                    9196
unix  2      [ ]         DGRAM                    9105
unix  3      [ ]         STREAM     CONNESSO      7749
unix  3      [ ]         STREAM     CONNESSO      8877
unix  3      [ ]         STREAM     CONNESSO      11629
unix  3      [ ]         STREAM     CONNESSO      9494     @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNESSO      7946     /var/run/dbus/system_                                                                                                                                                             bus_socket
unix  3      [ ]         STREAM     CONNESSO      7935
unix  2      [ ]         DGRAM                    9053
unix  3      [ ]         STREAM     CONNESSO      11249
unix  2      [ ]         DGRAM                    12479
unix  3      [ ]         DGRAM                    1639
unix  2      [ ]         DGRAM                    7761
unix  3      [ ]         STREAM     CONNESSO      11250    /var/run/dbus/system_                                                                                                                                                             bus_socket
unix  3      [ ]         STREAM     CONNESSO      9751
unix  3      [ ]         STREAM     CONNESSO      9014     @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNESSO      7573     @/com/ubuntu/upstart
unix  3      [ ]         STREAM     CONNESSO      7756     /var/run/dbus/system_                                                                                                                                                             bus_socket
unix  3      [ ]         STREAM     CONNESSO      9072
unix  3      [ ]         STREAM     CONNESSO      11626
unix  3      [ ]         STREAM     CONNESSO      11554    /var/run/dbus/system_                                                                                                                                                             bus_socket
unix  2      [ ]         DGRAM                    11570
unix  3      [ ]         STREAM     CONNESSO      7938
unix  3      [ ]         STREAM     CONNESSO      7936

but in reqrep_server.py I put: port = "5556".....))))
What do I have to do to make pyzmq working?

Looking forward to your kind help.
Kind regards.
Marco

**Comment by kiloki-official** [comment]
Did you find a solution? Thanks
