### ISSUE TITLE
Who defines the `backend` global?

### ISSUE THREAD

**Issue by Kentzo** [zeromq/pyzmq#634]
I cannot figure out where the backend global is defined: https://github.com/zeromq/pyzmq/blob/master/zmq/__init__.py#L62

It appears to work in non-frozen version, but when it's frozen if leads to NameError (inside invocation of the _check_rc function).

**Comment by Kentzo** [comment]
This is probably related to #630.

**Comment by minrk** [comment]
@can you check #635, and see if it fixes the issue?

**Comment by Kentzo** [comment]
It does.

**Comment by minrk** [comment]
Perfect, thanks!

**Comment by Kentzo** [comment]
@minrk This issue is mission critical to us… May I expect 14.4.2 anytime soon?

**Comment by minrk** [comment]
I can try to cut a release by the end of the week.

**Comment by Kentzo** [comment]
Please do and also upload it to pypi. This issue is critical because it does not always reproduce, but crashes suddenly with a mysterious message.

**Comment by minrk** [comment]
All releases are uploaded to PyPI

**Comment by Kentzo** [comment]
@minrk Any chance to see it today?

**Comment by minrk** [comment]
Sorry, I've been sick the last few days. Maybe Monday.

**Comment by minrk** [comment]
@Kentzo pyzmq-14.5.0 [is up](https://pypi.python.org/pypi/pyzmq)
