### ISSUE TITLE
ZMQ_STREAM Bad Address

### ISSUE THREAD

**Issue by sabzo** [zeromq/pyzmq#638]
Using pip installed pyzmq==14.4.1
Libzmq Stable Release 4.0.5

The issue normally rises when creating a HTTP server and it was resolved for the deprecated ZMQ_ROUTER + RAW combination (https://github.com/zeromq/pyzmq/issues/435). However the issue of Bad Address still exists when using ZMQ_STREAM in the following combination:

1. Send an Identity Frame
2. Send an empty (0 length) frame to signal the end of the HTTP response back to the client. 

Like the issue referenced in the above link ZMQ the client "seems" to work, a response is returned however the server still raises an exception of "Bad Address".  Some examples are provided below:

1) Deprecated ROUTER + RAW combination which doesn't raise an exception (https://gist.github.com/ef5292c99f817ebe12dd)
2) New ZMQ_STREAM using multi_park which does raise a Bad Address exception (https://gist.github.com/b85a558c570d897a03d1)
3) New ZMQ_STREAM using regular "send" but still raises a Bad Address section (https://gist.github.com/41dd1017d27fd7b79faa)

**Comment by minrk** [comment]
Just like #435, this is not a pyzmq issue, but a libzmq one. I ran your scripts with libzmq-4.0.5 and I do see the problem, but I do not with 4.1.0, so this appears to be a fixed bug, but not yet in a stable release. I did modify your script, to address a few issues:

- you can still set zmq.SNDMORE on send_multipart, and STREAM sockets appear to want SNDMORE on every message.
- don't use zmq.error.ZMQError, use zmq.ZMQError
- poll to handle multi-segment requests
- various Python 3 things that don't really matter

My modified script is [here](https://gist.github.com/minrk/39a64deed5bee9de33e0).
