### ISSUE TITLE
Python runtime cannot be interrupted with Ctrl-C

### ISSUE THREAD

**Issue by amacleod** [zeromq/pyzmq#64]
When running a simple zmq REQ/REP server, the script does not stop immediately when I hit ^C.  Instead, it sits there (blocking in recv() I think) until something else happens, like data coming in from a client.

Test case code: https://gist.github.com/778171

This is probably very similar to the Ruby issue with Ctrl-C: https://github.com/zeromq/zeromq2/issues/#issue/127

**Comment by kevinlinxc** [comment]
I'm facing this issue on the latest pyzmq version:
![image](https://github.com/zeromq/pyzmq/assets/44324811/cbcab976-7371-4a7a-a744-547906f16574)

My code blocks on a subscriber.recv_json() call, and CTRL + C does not kill the script. This must be a later version than 2.1, so why do I still see this issue?
