### ISSUE TITLE
Invalid argument (bundled/zeromq/src/stream_engine.cpp:831)

### ISSUE THREAD

**Issue by nickponline** [zeromq/pyzmq#641]
I'm running `pyzmq==14.3.1` and after trying to connect a dealer socket

```python
self.socket = self.context.socket(zmq.DEALER)
self.socket.setsockopt(zmq.IDENTITY, self.API_KEY)
self.socket.connect(self.conduit_url)
```

Is seems to hang for about 16 minutes and then shows:
```
Invalid argument (bundled/zeromq/src/stream_engine.cpp:831)
```
It looks like the device running this code did not have internet connectivity, if that is relevant?

**Comment by minrk** [comment]
If there's a bug, it seems like it would have to be in libzmq. pyzmq doesn't reach into that C++.

**Comment by nickponline** [comment]
Ok, I'll move it to https://github.com/zeromq/libzmq/issues/1329 and see if that helps.

**Comment by minrk** [comment]
Thanks.
