### ISSUE TITLE
send_pyobj() fails for unpicklable objects with misleading error

### ISSUE THREAD

**Issue by meawoppl** [zeromq/pyzmq#642]
So we do some basic setup:
```python
In [11]: import zmq
In [12]: ctx = zmq.context()
In [17]: s = ctx.socket(zmq.PUB)
```
Then send a pretty big object, which works fine.
```
In [18]: s.send_pyobj([1]*(2**29))
```
Next we send a slightly bigger object (past the max size that pickle will deal with), we get an error that appears as a zmq EAGAIN type error as opposed to the pickle error that is expected.   
```
In [19]: s.send_pyobj([1]*(2**30))
---------------------------------------------------------------------------
Again                                     Traceback (most recent call last)
<ipython-input-19-9693fcc93b5f> in <module>()
----> 1 s.send_pyobj([1]*(2**30))

C:\Users\dev-pc\Anaconda3\lib\site-packages\zmq\sugar\socket.py in send_pyobj(self, obj, flags, protocol)
    362         """
    363         msg = pickle.dumps(obj, protocol)
--> 364         return self.send(msg, flags)
    365
    366     def recv_pyobj(self, flags=0):

C:\Users\dev-pc\Anaconda3\lib\site-packages\zmq\backend\cython\socket.pyd in zmq.backend.cython.socket.Socket.send (zmq\
backend\cython\socket.c:5437)()

C:\Users\dev-pc\Anaconda3\lib\site-packages\zmq\backend\cython\socket.pyd in zmq.backend.cython.socket.Socket.send (zmq\
backend\cython\socket.c:5199)()

C:\Users\dev-pc\Anaconda3\lib\site-packages\zmq\backend\cython\socket.pyd in zmq.backend.cython.socket._send_copy (zmq\b
ackend\cython\socket.c:2038)()

C:\Users\dev-pc\Anaconda3\lib\site-packages\zmq\backend\cython\socket.pyd in zmq.backend.cython.checkrc._check_rc (zmq\b
ackend\cython\socket.c:6115)()

Again: Resource temporarily unavailable
```
Python 3.4 linux64/win64 using current APD pyzmq version (14.5.0)

**Comment by minrk** [comment]
Can you demonstrate that making the same `pickle.dumps` call is what's failing? This example works fine here (also Python 3.4, linux64, OS X).

Maybe provide a complete example that fails, and show that when you unpack send_pyobj as two calls to pickle.dumps and socket.send, it's actually the pickle.dumps call that's failing?

**Comment by meawoppl** [comment]
I no longer believe that pickle is the cluprit in this.  

On the desktop I reported the error from, pickle began failing at the same power of two, so I had assumed this was correlated.  We ( myself and @belisarius222 ) discovered this with a PUSH-PULL configuration on the same computer, and it resulted in a crash of both the pushing and pulling processes.  I switched the demonstration to a PUB socket as without any subscribers as is should never exhibit this error state in my assessment.

I am now beginning to think that this is a memory issue of some variety.  Does there need to be some checks applied to [asbuffer_r here](https://github.com/zeromq/pyzmq/blob/master/zmq/backend/cython/socket.pyx#L168), to ensure that the call completed correctly?  The logic of that call is a bit complicated, but in my assesment, it seems that ```PyObject_GetBuffer()``` needs to be return-code checked in [this function](https://github.com/zeromq/pyzmq/blob/b7126b545753e2fd58d1c489309dcde1c0e2ceb2/zmq/utils/buffers.pxd#L159), or there might be some null-pointers floating about.   

This feels to me like something unexpected is getting passed into the ZMQ cAPI.

I got it again on my laptop (linux64 py3.4) which can sucessfully pickle the objects sent independent of the sending action.  
```python
In [1]: import zmq

In [3]: ctx = zmq.Context()

In [4]: s = ctx.socket(zmq.PUB)

In [5]: d = pickle.dumps([1]*(2**30))

In [6]: s.send(d)
---------------------------------------------------------------------------
Again                                     Traceback (most recent call last)
<ipython-input-6-9693fcc93b5f> in <module>()
----> 1 s.send_pyobj([1]*(2**30))

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/sugar/socket.py in send_pyobj(self, obj, flags, protocol)
    366         """
    367         msg = pickle.dumps(obj, protocol)
--> 368         return self.send(msg, flags)
    369 
    370     def recv_pyobj(self, flags=0):

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)()

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5196)()

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2035)()

/home/meawoppl/anaconda3/envs/py3k/lib/python3.4/site-packages/zmq/backend/cython/socket.cpython-34m.so in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6112)()

Again: Resource temporarily unavailable
```

Also, I noticed a weird capitalization on this line:
https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py#L364

**Comment by minrk** [comment]
So if pickle is unrelated, this should be reproducible with just a `bytes` object.

**Comment by minrk** [comment]
I just reproduced this behavior in C, so there doesn't appear to be any misbehavior in Python or pyzmq here. The buffer is properly allocated, but sending a message that large with no peers results in "Resource temporarily unavailable" in libzmq. I haven't checked if the lack of peers is relevant.

[c test](https://gist.github.com/cd70dce79cf0d8e50fb7). The error starts appearing around a message size of 2GB.

**Comment by minrk** [comment]
It would be appropriate to bring this up with libzmq, to see if the behavior is intended or not.

**Comment by meawoppl** [comment]
As mentioned before, I have gotten this error with PUSH-PULL configurations as well. I will ping their list and see if this is a know behavior.
