### ISSUE TITLE
bind_to_random_port seemingly does not try a new port when its first try is already bound

### ISSUE THREAD

**Issue by Sushisource** [zeromq/pyzmq#650]
bind_to_random seems to fail with errno 13 (Permission denied) on Windows (specifically this is windows 7 enterprise SP1, using python 3.4 with pyzmq 14.4.1) when seemingly the real problem was that the port was already occupied, and it should've tried a new one. As far as I can tell, this could be because the ZMQ library itself is returning the wrong error code, but my repro code (see below) has, on occasion, printed out a port that seemed not to be occupied at time-of-failure. I had also added a print statement into zmq/sugar/socket.py which would print if it ever retired to bind a new port, and I never saw that print happen.

My apologies if this bug really belongs over in the main libzmq project - but I figured might as well start here. Additionally, I would suggest it makes sense to add a "bind_to_available_port" function which simply binds to port 0, has the OS give it an available port, and then returns that to the user. I am doing that now, to overcome my problems with this intermittent bug.

```python
import time
import zmq

while True:
    print(loopnum)
    ctx = zmq.Context()
    sock = ctx.socket(zmq.SUB)
    port = sock.bind_to_random_port("tcp://127.0.0.1")
    print(port)
    sock.close()
    time.sleep(0.1)
    loopnum += 1
```

Thanks!

**Comment by minrk** [comment]
bind_to_random_port is a pyzmq feature, not libzmq, so this is definitely the right place. I don't know why failure to bind to an in-use port would raise EACCES instead of EADDRINUSE, but we can catch it anyway.

> I would suggest it makes sense to add a "bind_to_available_port" function which simply binds to port 0

That makes sense. The ability to retrieve the last endpoint bound by libzmq wasn't around when I wrote bind_to_random_port, and it's not available on all supported libzmq versions (< 3.0). But we can do it when it's available.

**Comment by minrk** [comment]
#651 should handle both issues of the wrong errno and using `:0` when available.

**Comment by Sushisource** [comment]
Great! Thanks much for fixing this so fast.
