### ISSUE TITLE
zmq.green import error with py3

### ISSUE THREAD

**Issue by AxelVoitier** [zeromq/pyzmq#666]
Hello,

With python3.4, gevent installed (1.0.1 and unofficially released [1.0.2](https://github.com/gevent/gevent/archive/1.0.2.zip)), I get the following error:
```
>>> import zmq.green as zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/zmq/green/__init__.py", line 33, in <module>
    from zmq.green.core import _Context, _Socket
  File "/usr/local/lib/python3.4/site-packages/zmq/green/core.py", line 24, in <module>
    from .poll import _Poller
  File "/usr/local/lib/python3.4/site-packages/zmq/green/poll.py", line 2, in <module>
    import gevent
  File "/usr/local/lib/python3.4/site-packages/gevent/__init__.py", line 36, in <module>
    from gevent.hub import get_hub, iwait, wait
  File "/usr/local/lib/python3.4/site-packages/gevent/hub.py", line 282
    except Exception, ex:
                    ^
SyntaxError: invalid syntax
```

Simply, gevent does not support py3 at the moment (see gevent/gevent#38, despite the many years effort it is still not here).
Incidentally, pyzmq can't unfortunately claim python 3 support when using greenlets :(. Could you add the exception to the readme?

(btw, why not using eventlet instead of gevent? One can do 'from eventlet.green import zmq', but it is a bit of a shame to have to use a zmq greenlet implementation from another package when pyzmq is already supposed to provide one).

**Comment by minrk** [comment]
That's right, gevent doesn't support Python 3. When gevent catches up, zmq.green will be ready for it.

> why not using eventlet instead of gevent?

No real reason. This code began as a separate package (gevent_zeromq) and was merged into zmq as zmq.green as it became popular, but lacked features and would be easier to maintain in zmq. This is the first I've heard of eventlet.green.zmq, but I think eventlet shipping its own compatibility is perfectly fine.
