### ISSUE TITLE
It is not possible to use two authenticated sockets in the same process

### ISSUE THREAD

**Issue by Crapworks** [zeromq/pyzmq#671]
Hi!

I'm currently working on a program which starts multiple ioloops in different threads. I also want to authenticate all of them, which is not working because of this lines:

```python
        self.zap_socket = self.context.socket(zmq.REP)
        self.zap_socket.linger = 1
        self.zap_socket.bind("inproc://zeromq.zap.01")
```

in ```zmq/auth/base.py```

Using that two times in the same process throws an 'Address already in use error' since the name of the socket is hardcoded.

Any ideas on how to make this work?

**Comment by minrk** [comment]
There can only be one authentication socket per Context. Do you want auth to be different for each of these sockets? If so, you will need to create separate Contexts for each authentication context. Otherwise, you should create a single authenticator and use it for all your sockets in the process.

**Comment by Crapworks** [comment]
I am creating several contexts. It is not working because the authenticator of both contexts want to create ```inproc://zeromq.zap.01```, which is obviously not possible.

**Comment by minrk** [comment]
inproc URLs can only be used once in a given context, but there can be many in a process, as long as each one is on a different context. Do you want the authentication to behave differently for every context? If not, creating a new auth socket for each is probably not the right thing to do.

An example creating two sockets bound to the same inproc endpoint:

```python
import zmq
s1 = zmq.Context().socket(zmq.PUB)
s1.bind('inproc://a')
s2 = zmq.Context().socket(zmq.PUB)
s2.bind('inproc://a')
```
