### ISSUE TITLE
Retry system calls automatically

### ISSUE THREAD

**Issue by flub** [zeromq/pyzmq#679]
Now that Python finally retries system calls automatically (https://www.python.org/dev/peps/pep-0475/) it would be great if the zmq API would behave in the same way and sensibly re-tries interrupted system calls.

**Comment by minrk** [comment]
Makes sense. Just need to make sure that I can distinguish between EINTR and a real interrupt, which shouldn't be retried.

**Comment by minrk** [comment]
@flub I've started implementing this in #692. I'm not sufficiently familiar to identify all the calls that might be retried, but I've done the obvious ones. If you have any pointers, that would be helpful.
