### ISSUE TITLE
zmq.tests.test_socket.TestSocket.test_tracker() hangs

### ISSUE THREAD

**Issue by Arfrever** [zeromq/pyzmq#682]
`zmq.tests.test_socket.TestSocket.test_tracker()` almost always hangs with all versions of Python (at least CPython 2.6, 2.7, 3.2, 3.3, 3.4) in both PyZMQ 14.6.0 and git trunk.
I use ZeroMQ 4.1.1.

Result of test suite of PyZMQ git trunk with CPython 2.7:
```
$ PYTHONPATH="build/lib.linux-x86_64-2.7" nosetests-2.7 -s -v -w build/lib.linux-x86_64-2.7/zmq/tests
...
test sending unicode objects ... ok
test_shadow (zmq.tests.test_socket.TestSocket) ... ok
test_shadow_pyczmq (zmq.tests.test_socket.TestSocket) ... SKIP: Requires pyczmq
test set/getsockopt roundtrip. ... ok
subclasses can assign attributes ... ok
test the MessageTracker object for tracking when zmq is done with a buffer ...
```

**Comment by minrk** [comment]
I believe this is a change in libzmq-4.1.1, which is not yet supported. I'll try to find some time to figure out the various things libzmq 4.1 has broken. Thanks for testing.

**Comment by minrk** [comment]
Are you using zmq-4.1.1 and not libzmq master? There is a bug in libzmq master that causes these tests to fail, but this test definitely passes with 4.1 and all those CPythons on travis and my machines. In those cases, the tests is behaving correctly, and it is libzmq where the behavior is incorrect.

**Comment by minrk** [comment]
This was a bug in libzmq, and is fixed.
