### ISSUE TITLE
pkg-config used to get prefix for libzmq, but should be used to get full paths

### ISSUE THREAD

**Issue by fwph** [zeromq/pyzmq#700]
pkg-config is currently used in setup.py like:

    pkg-config --variable=prefix --print-errors libzmq

But pkg-config can be used to get all the information needed to build against libzmq, rather than building the cflags/ldflags from the prefix. Attempting to construct it by doing

    pjoin(prefix, 'lib')

Can just lead to sadness when building in an environment with non-standard library dirs (as I've been doing, on a system that places 64-bit libraries into $PREFIX/lib64). It would be better to just use *all* the information pkg-config can provide in this case. (I may be able to provide a patch, but I need to check on some employer policies first; it's also a fairly simple exercise to get it basically working)

**Comment by minrk** [comment]
Makes sense. I've never encountered a case where this is needed, so it will probably be a low priority, as I will have no way to test if I've done it correctly.

**Comment by fwph** [comment]
I got approval, so I'll provide a patch shortly.

**Comment by minrk** [comment]
closed by #701
