### ISSUE TITLE
RPM build with bdist_rpm failed on RHEL/CentOS-6

### ISSUE THREAD

**Issue by dvusboy** [zeromq/pyzmq#704]
On a CentOS-6 host, with these installed (from CentOS or EPEL-6)

```
python-2.6.6-52.el6.x86_64
python-devel-2.6.6-52.el6.x86_64
python-setuptools-0.6.10-3.el6.noarch
zeromq3-3.2.5-1.el6.x86_64
zeromq3-devel-3.2.5-1.el6.x86_64
```

I try to build ```pyzmq``` RPM, which ended in error:

```bash
$ cd pyzmq-14.7.0
$ python ./setup.py bdist_rpm
running bdist_rpm
running egg_info
creating pyzmq.egg-info
...
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.66FWkg
+ umask 022
+ cd /home/kcwong/build/pyzmq-14.7.0/build/bdist.linux-x86_64/rpm/BUILD
+ cd pyzmq-14.7.0
+ python setup.py install --single-version-externally-managed -O1 --root=/home/kcwong/build/pyzmq-14.7.0/build/bdist.linux-x86_64/rpm/BUILDROOT/pyzmq-14.7.0-1.x86_64 --record=INSTALLED_FILES
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --single-version-externally-managed not recognized
error: Bad exit status from /var/tmp/rpm-tmp.66FWkg (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.66FWkg (%install)
error: command 'rpmbuild' failed with exit status 1
```

I think the fix is to change [setup.py](https://github.com/zeromq/pyzmq/blob/master/setup.py#L29) and unconditionally import ```setuptools```. The reason being the ```bdist_rpm``` command from ```setuptools``` will generate an RPM spec file that calls ```install``` out of ```distutils``` but with that additional option ```--single-version-externally-managed``` that is not understood by ```distutils```. I have tested this fix, and it worked, but I did not do enough regression to verify other setup commands.

**Comment by minrk** [comment]
> unconditionally import setuptools

That's definitely not going to happen. Running basic `setup.py install` with setuptools imported does *horrible* things, and shouldn't ever be done by anyone under any circumstances.

If you want to use `--single-version-externally-managed` like pip does, it should do its own exec of setup.py with setuptools, also like pip does.

**Comment by dvusboy** [comment]
Well, it isn't because I want to use ```--single-version-externally-managed```, but the RPM spec file generated by ```setuptools``` do this:

```
%install
python setup.py install --single-version-externally-managed -O1 --root=.../pyzmq-14.7.0/build/bdist.linux-x86_64/rpm/BUILDROOT/pyzmq-14.7.0-1.x86_64 --record=INSTALLED_FILES
```
(note: "..." means where the exploded tarball reside)

And that option is something that ```distutils``` does not understand. The bottomline is very simple, I cannot use ```bdist_rpm``` to build an RPM for ```pyzmq```.

**Comment by minrk** [comment]
Looks like this is actually a bug in setuptools, in that it should follow pip's suit of running setup.py with setuptools when/where appropriate, since setup.py should *never* import setuptools unconditionally. But there is a bug in pyzmq, in that we *do* import setuptools when `bdist_rpm` is attempted, and we actually shouldn't. Regular distutils provides bdist_rpm, and setuptools patches bdist_rpm run with setuptools to actually behave more like the distutils original. This should be fixed by #705. Can you verify that?

**Comment by dvusboy** [comment]
Yes, that fixed it. There is one issue that came up. I'm building on a RHEL6 host, and the Cython version from EPEL-6 is too old (0.14.1). I found a 0.17.2 RPM out there, so I installed that RPM, but ended up with a compile error:

```
Error compiling Cython file:
------------------------------------------------------------
...
        if not isinstance(option, bytes):
            raise TypeError("expected str, got: %r" % option)

        property_c = option

        cdef const char *result = <char *>zmq_msg_gets(&self.zmq_msg, property_c)
                       ^
------------------------------------------------------------

zmq/backend/cython/message.pyx:373:24: Syntax error in C variable declaration
```

Then I uninstalled the Cython RPM and did ```easy_install cython``` which install Cython 0.22.1. The compile error went away and I got my RPMs with:

```
$ python ./setup.py bdist_rpm --zmq=bundled
```

ending in

```
+ exit 0
moving build/bdist.linux-x86_64/rpm/SRPMS/pyzmq-14.7.0-1.src.rpm -> dist
moving build/bdist.linux-x86_64/rpm/RPMS/x86_64/pyzmq-14.7.0-1.x86_64.rpm -> dist
```

Thank you for your help.

**Comment by minrk** [comment]
Thanks, I'm not sure what version of Cython pyzmq requires at this point, but I'm guessing it's 0.19 or 0.20.
