### ISSUE TITLE
update zmq.Poller.poll docs

### ISSUE THREAD

**Issue by rakslice** [zeromq/pyzmq#706]
"The underlying zmq_poll uses microseconds and we convert to that in this function." That was true at the time that was written (https://github.com/zeromq/pyzmq/commit/18f5d061558a176f5496aa8e049182c1a7da64f6) but it isn't anymore.  Might save someone a wild goose chase.

**Comment by minrk** [comment]
woo, now that's a long time for a docstring to be out of date. Fixed by #707
