### ISSUE TITLE
pip install leaves /tmp/timer_create*.c

### ISSUE THREAD

**Issue by brian-cole-bluenewt** [zeromq/pyzmq#708]
Running `pip install pyzmq` leaves files in /tmp with names like  /tmp/timer_createGIXAk9.c and these files never get deleted.

On CentOS 7 with pip 7.1.0, it appears that this only happens when runing `sudo pip install` on a system-wide basis; a running in a virtualenv doesn't create them (?)
```
libzmq-3.2.5
pyzmq-14.3.1
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```
On CentOS 6 with pip 7.1.0, however, I am getting these files even when installing to a venv. So that's odd.
```
libzmq-4.0.4
pyzmq-14.1.1
Python-2.7.3 (default, Mar 11 2013, 22:38:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
```
(This one is showing 14.1.1 because it only creates the files when rebuilding, so in order to avoid the cache I just built on older version in that venv)

**Comment by minrk** [comment]
pyzmq uses distutils' `ccompiler.has_function` to check for `timer_create`. distutils, in turn, uses the stdlib tempfile module to create a temporary c file to compile and perform the check. Distutils doesn't clean up its tempfiles, but it probably should. I've [submitted a patch](http://bugs.python.org/issue25544) to Python to fix the issue in distutils.
