### ISSUE TITLE
Have you run this on Windows?

### ISSUE THREAD

**Issue by drozzy** [zeromq/pyzmq#714]
Has anyone actually successfully ran zeromq on windows from python?
I am getting really weird behavior, like CTRL+C not being detected, ports not being freed up (when I create a server socket), sockets not connecting to each other if I start them up from two separate command windows...

Just wandering if it's just me...

**Comment by minrk** [comment]
Yup, it's used quite frequently. The ^C not caught is a known issue that I still don't know how to address. It seems to be a C-level Python signal handling thing. I've not encountered the unfreed ports or failed connections across processes. That typically works well enough for me.

**Comment by drozzy** [comment]
Hm.. this is really weird. If I just split this example up into two files, "client.py" and `server.py`, and run each in separate minigw32 (git-bash) windows, they don't see each other:
http://learning-0mq-with-pyzmq.readthedocs.org/en/latest/pyzmq/multiprocess/multiprocess.html

`server.py`:
```
import zmq
import time
import sys

def server(port="5556"):
    context = zmq.Context()
    socket = context.socket(zmq.REP)
    socket.bind("tcp://*:%s" % port)
    print "Running server on port: ", port
    # serves only 5 request and dies
    for reqnum in range(5):
        # Wait for next request from client
        message = socket.recv()
        print "Received request #%s: %s" % (reqnum, message)
        socket.send("World from %s" % port)

if __name__ == "__main__":
    port='5520'
    server(port)

```

`client.py`:
```
import zmq
import time
import sys

def client(ports=["5556"]):

    context = zmq.Context()
    print "Connecting to server with ports %s" % ports
    socket = context.socket(zmq.REQ)
    for port in ports:
        socket.connect ("tcp://localhost:%s" % port)
    for request in range (20):
        print "Sending request ", request,"..."
        socket.send ("Hello")
        message = socket.recv()
        print "Received reply ", request, "[", message, "]"
        time.sleep (1)


if __name__ == "__main__":
    port='5520'
    client(port)
```

Here is the screenshot (you see it just hangs on first request there):
![no-comm](https://cloud.githubusercontent.com/assets/140710/9098557/a056a800-3b98-11e5-9da3-6daa00c399a6.jpg)

**Comment by minrk** [comment]
Does it work if you connect to 127.0.0.1 instead of localhost?

**Comment by drozzy** [comment]
No. But see, that's the thing, it works if I just run the original code as one thing:

```
import zmq
import time
import sys
from  multiprocessing import Process

def server(port="5556"):
    context = zmq.Context()
    socket = context.socket(zmq.REP)
    socket.bind("tcp://*:%s" % port)
    print "Running server on port: ", port
    # serves only 5 request and dies
    for reqnum in range(5):
        # Wait for next request from client
        message = socket.recv()
        print "Received request #%s: %s" % (reqnum, message)
        socket.send("World from %s" % port)
         
def client(ports=["5556"]):

    context = zmq.Context()
    print "Connecting to server with ports %s" % ports
    socket = context.socket(zmq.REQ)
    for port in ports:
        socket.connect ("tcp://localhost:%s" % port)
    for request in range (20):
        print "Sending request ", request,"..."
        socket.send ("Hello")
        message = socket.recv()
        print "Received reply ", request, "[", message, "]"
        time.sleep (1) 


if __name__ == "__main__":
    # Now we can run a few servers 
    server_ports = range(5550,5558,2)
    for server_port in server_ports:
        Process(target=server, args=(server_port,)).start()
        
    # Now we can connect a client to all these servers
    Process(target=client, args=(server_ports,)).start()
```

**Comment by minrk** [comment]
Oh, that's super weird, especially since in your example it's one script but still separate processes. Perhaps it's a progress group permissions thing? Do you have a firewall of some sort running?

**Comment by drozzy** [comment]
I think yes on Win 7 machine, but that's work setup.
At home on Win 8, I think there is one built in?

But still, why would it work when launching them as multiple processes from the same script, and not the other way? Is it doing something else if it runs within the same python instance?

**Comment by jizhilong** [comment]
Hi, drozzy, there is a bug in `client.py`: the function 'client' accepts list of ports, instead of a single port name.

**Comment by drozzy** [comment]
@jizhilong Haha, thanks. Dynamic types eh :-)
