### ISSUE TITLE
Assertion failed: mailbox.cpp

### ISSUE THREAD

**Issue by ceremcem** [zeromq/pyzmq#715]
Hi, 

I'm using pyzmq 14.6.0 and libzmq 4.0.5 on Raspbian. Here is what I got recently: 

> Assertion failed: ok (bundled/zeromq/src/mailbox.cpp:82)

Then the running program closed even without calling my cleanup function that is registered via 

```
atexit.register(self.cleanup)
```

**Comment by minrk** [comment]
Can you try upgrading pyzmq to 14.7? I think that's a bug in the libzmq version that's bundled with 14.6

**Comment by ceremcem** [comment]
OK, but I don't know how to reproduce this error. We can't know if this issue should be closed or not.

**Comment by minrk** [comment]
@ceremcem Thanks. I'll close here as a duplicate of zeromq/libzmq#1108. There's nothing pyzmq can do about asserts in libzmq.

**Comment by ceremcem** [comment]
OK then.
