### ISSUE TITLE
Windows ssh tunnel processes do not exit on connection close / crash

### ISSUE THREAD

**Issue by frmdstryr** [zeromq/pyzmq#717]
The timeout parameter is never used when using paramiko in:
https://github.com/zeromq/pyzmq/blob/master/zmq/ssh/tunnel.py#L275 

This causes the processes to never die if the parent crashes or is killed by another application (in which it cannot call the atexit handler).

Why not just use a daemon process?

**Comment by minrk** [comment]
Indeed they should be daemons. I'm not sure what I was thinking all those years ago. #720
