### ISSUE TITLE
Empty Poller's poll method does not make use of timeout

### ISSUE THREAD

**Issue by will133** [zeromq/pyzmq#718]
If there's no socket registered to the poller the zmq.Poller.poll() method would get into a busy loop.  It seems like instead of waiting for the specified time to return, the poll() call would just return immediately.   For example you can do something like:

```python
import zmq
import time

context = zmq.Context()
poller = zmq.Poller()
for i in xrange(3):
    t = time.time()
    poller.poll(1000)
    print('%.8f' % (time.time() - t))
```

 and you will get:

```
0.00001693
0.00000215
0.00000119
```

If you register a socket with the poller it would timed out correctly, but it should not get into such unexpected looping behavior in my opinion. 

I'm using conda build of python 2.7.10 with:

```
In [2]: zmq.zmq_version()
'4.0.5'

In [3]: zmq.__version__
'14.7.0'
```

**Comment by minrk** [comment]
Since both the underlying `zmq_poll` and Python siblings such as `select.poll` behave this way, I think it's important that zmq.Poller remain consistent with all the other pollers. A poll with no events registered is equivalent to `time.sleep`.
