### ISSUE TITLE
ImportError: cannot import name constants

### ISSUE THREAD

**Issue by arun6174** [zeromq/pyzmq#722]
I'm trying to run a simple piece of code using pyzmq. I am using Python 2.7 and pyzmq 14.5

```
$ python --version
Python 2.7.6
$ sudo find /usr -name "*pyzmq*"
/usr/local/lib/python2.7/dist-packages/pyzmq-14.5.0.egg-info
/usr/lib/python2.7/dist-packages/pyzmq-14.0.1.egg-info
```

Following is the code i'm trying to run:

```
import zhelpers

context = zmq.Context.instance()
server = context.socket(zmq.ROUTER)
server.bind("tcp://*:5678")

while (1):
	address, empty, data = server.recv_multipart()

	print("address = %s, data = %d" % (address, int(data)))

	data_i = int(data) + 10
	server.send_multipart([
        address,
        b'',
        str(data_i),
    ])
```

But, I'm getting following error and got no clue how to fix this:
```
Traceback (most recent call last):
  File "reqrep_server.py", line 8, in <module>
    import zhelpers
  File "/home/arun/pyzmq_server/zhelpers.py", line 11, in <module>
    import zmq
  File "/home/arun/pyzmq_server/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/home/arun/pyzmq_server/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/home/arun/pyzmq_server/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/home/arun/pyzmq_server/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/arun/pyzmq_server/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context, socket, utils, _poll, _version, _device)
ImportError: cannot import name constants
```
I've copied the whole **zmq** folder and placed it in the level as my .py file. 

Please help!

**EDIT:**

I have removed multiple versions of pyzmq (14.5 and 14.0.1) and installed 14.7 afresh. Still I'm getting the same error. What the heck I'm doing wrong?!

**Comment by minrk** [comment]
>What the heck I'm doing wrong?!

Copying the source directory is not installing pyzmq. pyzmq, like other Python packages, should be installed via the standard Python tool `pip`, e.g.:

    pip install pyzmq

Putting the `zmq` source directory in the working directory will only prevent zmq from ever working.

**Comment by aazim-lakhani** [comment]
I encountered a similar problem. `pip install --upgrade pyzmq` did the trick for me.
