### ISSUE TITLE
HWM problem

### ISSUE THREAD

**Issue by gabre** [zeromq/pyzmq#727]
I have two applications:
- a simple sender application which just sends messages (long strings) in a loop
- a simple receiver which has a loop where it sleeps and then receives a message
I use PULL-PUSH and set the HWM to 1000.
In this case the memory of the sender application is constantly growing.

I use PyZMQ 14.7.0 and ZeroMQ 4.1.2. With PyZMQ 14.6.0, the error is not present.

**Comment by minrk** [comment]
Can you provide actual code? And more information about the test environment (Python version, OS, etc.)? What are `zmq.__version__` and `zmq.zmq_version()` in both cases?

**Comment by gabre** [comment]
Sorry for not responding, I will provide more details soon.
