### ISSUE TITLE
socket not lingering even with explicit call to term

### ISSUE THREAD

**Issue by orodbhen** [zeromq/pyzmq#728]
I read #149, but it's overly specific in this case. I'm not using a ProcessDevice. I'm sending a multipart message via a PUB socket, just before exiting a process. However, the message is never received by the SUB socket, unless I use a sleep statement after calling send. 

#149 seems to explains why this happens. However, calling term() explicitly should block until all messages have been sent, per the ZMQ documentation. But this doesn't happen. This is a small message, so I'm surprised that ZMQ fails to send it fast enough.

Is there a way to ensure that everything has been sent before exiting? I really dislike using sleep statements, as it just feels like a dirty hack.

**Comment by minrk** [comment]
Can you provide code that exhibits a problem? It's easy to end up losing PUB messages if they are being sent before subscribers have finished subscribing. In this sort of case, linger isn't relevant.
