### ISSUE TITLE
question: optimize send_pyobj/recv_pyobj

### ISSUE THREAD

**Issue by finjulhich** [zeromq/pyzmq#733]
Hello,
This is a question rather than a issue per se. Are questions to be directed elsewhere?

I have 2 inproc PAIR sockets and i send python objects between them.
As the communication is purely inside python process, it seems a bit of waste to pickle/unpickle the python object. Is there an alternative to avoid the pickling/unpickling?

**Comment by minrk** [comment]
Yeah, you can definitely do this. What I would do is make a dictionary and pass objects around by id, like so:

```python
from itertools import count
import struct
import zmq

_msgs = {}
_msg_counter = count()

def send_obj_inproc(socket, obj):
    """'Send' an object by reference.
    
    Doesn't actually serialize anything,
    just pass a reference to the _msgs dict.
    Only for use with inproc sockets.
    """
    msg_id = next(_msg_counter)
    _msgs[msg_id] = obj
    socket.send(struct.pack('L', msg_id))

def recv_obj_inproc(socket):
    """'Receive' an object by reference.
    
    Message only contains a key into msgs dict,
    which contains the actual message contents.
    Only for use with inproc sockets.
    """
    buf = socket.recv()
    msg_id = struct.unpack('L', buf)[0]
    return _msgs.pop(msg_id)
```

[full example](https://gist.github.com/4db8b2ae749588a7884f)
