### ISSUE TITLE
Could the static linking exception in the libzmq licence be included in pyzmq?

### ISSUE THREAD

**Issue by johnsocp** [zeromq/pyzmq#754]
Could the special exception found in the libzmq license be included in the pyzmq license? Based on the documentation is sounds like that's within the spirit of the project but it would be nice to have it included in the license file. 
<pre>
--------------------------------------------------------------------------------

           SPECIAL EXCEPTION GRANTED BY COPYRIGHT HOLDERS

As a special exception, copyright holders give you permission to link this
library with independent modules to produce an executable, regardless of
the license terms of these independent modules, and to copy and distribute
the resulting executable under terms of your choice, provided that you also
meet, for each linked independent module, the terms and conditions of
the license of that module. An independent module is a module which is not
derived from or based on this library. If you modify this library, you must
extend this exception to your version of the library.

Note: this exception relieves you of any obligations under sections 4 and 5
of this license, and section 6 of the GNU General Public License.</pre>

**Comment by minrk** [comment]
Done. I just wish I had gotten to the project early enough to make the whole thing BSD.
