### ISSUE TITLE
Second socket.get_monitor_socket() hangs

### ISSUE THREAD

**Issue by sublee** [zeromq/pyzmq#756]
Second `socket.get_monitor_socket()` call without specific address hangs forever.  I think that it should raises `ZMQError: Address already in use`.

When my process receives a signal like `SIGPROF`, ZeroMQ socket calls raise `EINTR` error.  To continue the logic, I just retry the failed call.  That's because I called `socket.get_monitor_socket()` twice.

**Comment by minrk** [comment]
Should be fixed by #797

**Comment by sublee** [comment]
@minrk Thank you!
