### ISSUE TITLE
SSH connection error in Python3

### ISSUE THREAD

**Issue by nikitakit** [zeromq/pyzmq#759]
I had problems connecting to a remote ipython cluster, where both endpoints were running Python3. `pyzmq` is used for the connection.

I'm reporting this here, though I'm not sure where the actual bug is.

Traceback: https://gist.github.com/nikitakit/23e92cd94ccde6dfa8e1

My fix is to make `_password_pat` a byte regex instead of a string regex.
```python
import re, zmq
zmq.ssh.tunnel._password_pat = re.compile(b'pass(word|phrase):', re.IGNORECASE)
```

After running this code, the connection is successfully created and appears to function normally.

**Comment by minrk** [comment]
What's your pexpect version?

**Comment by nikitakit** [comment]
pexpect version is 3.3

**Comment by minrk** [comment]
Should be fixed by #763

**Comment by joystein** [comment]
Will there be a bugfix release with this included soon?

**Comment by minrk** [comment]
Yes, I'm planning to put out 15.2 tomorrow.

**Comment by joystein** [comment]
Great. Thanks!
