### ISSUE TITLE
pyzmq make the logging.handler.WatchedFileHandler write log to stdout

### ISSUE THREAD

**Issue by sh19871122** [zeromq/pyzmq#760]
pyzmq version >= 13.1.0

write log to WatchedFileHandler syslog, while send to stdout 

    formater = logging.Formatter("%(message)s")
    handler = WatchedFileHandler('msg_dir')
    handler.setFormatter(formater)
    logger = logging.getLogger('msg-%s' % log_type)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)

    when use pyzmq >= 13.01 
    logger.info("hello")
    
    while print to stdout hello

**Comment by minrk** [comment]
I'm sorry, I don't understand the question, or even if there is one. What happens now and what do you want to happen that's different?

**Comment by sh19871122** [comment]
import os
import sys
import zmq
import json
import time
import Queue
import logging
import traceback


from cStringIO import StringIO
from zmq.eventloop.ioloop import IOLoop, PeriodicCallback
from zmq.eventloop.zmqstream import ZMQStream
from logging.handlers import WatchedFileHandler, SysLogHandler

formater = logging.Formatter('%(asctime)-15s xxxxx[%(process)d:%(thread)d]:
%(message)s')
syslog = SysLogHandler(address='/dev/log',
facility=SysLogHandler.LOG_LOCAL3)
syslog.setFormatter(formater)
console = logging.StreamHandler(sys.stdout)
console.setFormatter(formater)
log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)
log.addHandler(syslog)
log.addHandler(console)


data_queue = Queue.Queue(1000)

LOG_DIR = 'test_a'
POST_DIR = 'test_p'
LOG_TYPE_PUB_PATH = 'xxxxx'
LOG_TYPES_PERSISTENT = ['A', 'B', 'C']
ZMQ_RCV_HWM_SIZE = 500

def get_logger(log_dir, log_type='access'):
    prefix = os.path.join(log_dir, log_type)
    formater = logging.Formatter("%(message)s")
    handler = WatchedFileHandler(prefix)
    handler.setFormatter(formater)
    logger = logging.getLogger('varnishlog-%s' % log_type)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)
    return logger


LOG_PERSISTENT_STATUS = {
    "recv_blocks": 0,
    "recv_bytes": 0,
    }

post_key = 'C'
loggers = {key: get_logger(LOG_DIR, log_type=key) for key in
LOG_TYPES_PERSISTENT if key != post_key}
if post_key in LOG_TYPES_PERSISTENT:
    loggers[post_key] = get_logger(POST_DIR, log_type=post_key)

io_bufs = {key: StringIO() for key in LOG_TYPES_PERSISTENT}
io_bufs_time = {key: time.time() for key in LOG_TYPES_PERSISTENT}


def recv_msg(msg):
    try:
        try:
            LOG_PERSISTENT_STATUS['recv_blocks'] += 1
        except:
            LOG_PERSISTENT_STATUS['recv_blocks'] = 1

        try:
            LOG_PERSISTENT_STATUS['recv_bytes'] += len(msg[1])
        except:
            LOG_PERSISTENT_STATUS['recv_bytes'] = len(msg[1])

        try:
            LOG_PERSISTENT_STATUS[msg[0]] += len(msg[1])
        except:
            LOG_PERSISTENT_STATUS[msg[0]] = len(msg[1])

        loggers[msg[0]].info(msg[1])
    except:
        log.error("%s" %
''.join(traceback.format_exception(*sys.exc_info())))


if __name__ == '__main__':
    loop_instance = IOLoop.instance()
    ctx = zmq.Context.instance()
    sock = ctx.socket(zmq.SUB)
    sock.set_hwm(ZMQ_RCV_HWM_SIZE)
    sock.connect(LOG_TYPE_PUB_PATH)
    for key in LOG_TYPES_PERSISTENT:
        if isinstance(key, str):
            sock.setsockopt(zmq.SUBSCRIBE, key)
        elif isinstance(key, unicode):
            sock.setsockopt_string(zmq.SUBSCRIBE, key)
        else:
            log.warn("... to set subscribe error:%s" % key)
    sock = ZMQStream(sock, loop_instance)
    sock.on_recv(recv_msg)
    loop_instance.start()



when execute it, pyzmq >= 13.1.0 while print to stdout

2015-11-26 17:36 GMT+08:00 Min RK <notifications@github.com>:

> I'm sorry, I don't understand the question, or even if there is one. What
> happens now and what do you want to happen that's different?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeromq/pyzmq/issues/760#issuecomment-159858538>.
>



-- 





石涵

**Comment by minrk** [comment]
When I run your code (after disabling the syslog bits, which don't work) and send messages on a PUB socket, I get the following logged to stdout:

    INFO:varnishlog-A:hi
    INFO:varnishlog-B:hello again

I'm afraid I still do not know what you are asking for.

**Comment by sh19871122** [comment]
It is this phenomenon

Under the right circumstances should write directly to the file, rather
than a re-export to stdout

2015-11-26 18:40 GMT+08:00 Min RK <notifications@github.com>:

> When I run your code (after disabling the syslog bits, which don't work)
> and send messages on a PUB socket, I get the following logged to stdout:
>
> INFO:varnishlog-A:hi
> INFO:varnishlog-B:hello again
>
> I'm afraid I still do not know what you are asking for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeromq/pyzmq/issues/760#issuecomment-159874160>.
>



-- 





石涵

**Comment by minrk** [comment]
I think I understand now. Python uses log propagation, so the root logger is alsohandling messages from your logger. Tornado (the IOLoop) initializes the root logger if it hasn't been done already with `logging.basicConfig()`. You can either disable the root logger explicitly:

```python
logging.getLogger().addHandler(logging.NullHandler())
```

or disable propagation from your loggers:

```python
logger.propagate = False
```
