### ISSUE TITLE
IDE auto complete friendly documentation of classes and methods

### ISSUE THREAD

**Issue by boerngen-schmidt** [zeromq/pyzmq#761]
Hello,

I noticed when using pyzmq, that the library does not seem to be very friendly towards the auto completition feature of my IDE, which is pycharm. 
It seems that the comments are written in restructured text and sphinx is used to generate the docs. To make the comments IDE friendly http://sphinx-doc.org/domains.html#info-field-lists could be used.
An example what does not work for me is 
```
s = context.socket(zmq.SUB)
s.bind('fooar')  # bind is not available via auto complete, but bind_to_random_port
```
Also not all constants seem to be available via auto complete. For example zmq.SUB for the subscriber socket. I tried to understand why these are not shown and my guess is, that it has something to do with them being implemented in cython. http://stackoverflow.com/questions/31766219/export-constants-from-header-with-cython seems to have a solution to the problem.

**Comment by minrk** [comment]
I'm not sure how PyCharm populates its completion. Does it use static code analysis, or does it actually import things?

pyzmq embeds signatures in numpydoc/napoleon format, which I think is a better compromise for humans vs machines than the linked info-fields, which make for much less pleasant docstrings to my eye.

As for the Cython-defined constants, I don't think that SO question addresses the issue of whatever PyCharm's inspection is failing to do, since it seems to be about constants not being available at all to Python, which is not the case in pyzmq. If pycharm imports the library, it will find these values in `dir(zmq)`.

**Comment by minrk** [comment]
Should be fixed in 15.2

**Comment by dvj** [comment]
I'm using 15.2.0, and this doesn't seem to be changed.

You can see a screenshot of what PyCharm is autocompleting here: http://cl.ly/3O323a2r3S2B

doing a `dir(zmq)` doesn't show things like `zmq.SUB` or `zmq.SUBSCRIBE`, and these show as unknown references in the IDE.

**Comment by minrk** [comment]
If `dir(zmq)` isn't showing those, then it seems like you don't have a working pyzmq. How did you install it? Does anything run? Completion works in IPython, and `SUB` certainly should be in `dir(zmq)`:

```python
In [1]: 'SUB' in dir(zmq)
Out[1]: True

In [2]: zmq.S<TAB>
zmq.SHARED        zmq.SNDHWM        zmq.SNDTIMEO      zmq.SOCKS_PROXY   zmq.STREAM        zmq.SUB           zmq.Socket
zmq.SNDBUF        zmq.SNDMORE       zmq.SOCKET_LIMIT  zmq.SRCFD         zmq.STREAMER      zmq.SUBSCRIBE     zmq.Stopwatch

In [2]: zmq.__version__
Out[2]: '15.2.0'
```

**Comment by bheklilr** [comment]
I'll chime in to say that I'm experiencing the same issue on PyCharm 5.0.4 under Python 3.4.4 64bit installed using conda.  My pymq version is 15.2.0.  If I load it into IPython the autocompletion works just fine and `"DEALER" in dir(zmq)` returns `True` in IPython and the default python REPL.  The constants are certainly in `__all__` for `zmq`, `zmq.sugar`, and ultimately `zmq.backend.cython.constants`.  I'll say that `zmq.constants.<TAB>` does not show the constants but instead just the values like `base_names`, `int_sockopt_names`, etc.  

PyCharm gives the following warning when it can't find a name, such as `zmq.DEALER`:

> This inspection detects names that should resolve but don't. Due to dynamic dispatch and duck typing, this is possible in a limited but useful number of cases. Top-level and class-level items are supported better than instance items.

So I think what is happening is that PyCharm is not actually importing `zmq` to provide completions but instead relying on static analysis which is failing in this particular case.  To get it to play well with PyCharm you would probably have to list each export individually.

Hope is not lost, Python has a trick up it's sleeve.  I noticed while poking around in the pyzmq code that you've used the style

```python
from module import submodule1
from module.submodule1 import *
from module import submodule2
from module.submodule2 import *

__all__ = submodule1.__all__ + submodule2.__all__
```
But Python has a better way through `from __future__ import absolute_import`
```python
from __future__ import absolute_import

from module.submodule1 import *
from module.submodule2 import *

__all__ = submodule1.__all__ + submodule2.__all__
```

So if you have them listed out explicitly in `__all__` in some lower level module you can use this style all the way up in a less dynamic manner.  This also works in Python 2, I think as early as 2.5 with the `__future__` import.  I don't know how well it plays with Cython imports, though.

**Comment by dvj** [comment]
Apologies, the entries do show up in `dir(zmq)`, but @bheklilr is right that PyCharm does static analysis, so these references aren't found.

The solution I came up with is to make a skeleton for zmq as seen at https://www.jetbrains.com/pycharm/help/using-python-skeletons.html

For the purposes of zmq, something like the output of:
```python
import zmq
for a in dir(zmq):
    if isinstance(getattr(zmq, a), int):
        print "{} = {}".format(a, getattr(zmq, a))
```
when placed in zmq.py in the appropriate config-directory will do. This isn't perfect, but does address the problem of the constants not being recognized in PyCharm

**Comment by kiminuo** [comment]
Adding type annotations for zmq package to https://github.com/python/typeshed would help a lot of people I guess.
