### ISSUE TITLE
Running performance test on 2 machines

### ISSUE THREAD

**Issue by sivabudh** [zeromq/pyzmq#768]
Hello,

I was going through the throughput performance test from perf.py source code here:

https://github.com/zeromq/pyzmq/blob/master/perf/perf.py

And my understanding is that the code structures the code such that both `def pusher` and `def throughput` always run on the same machine. This is quite a contrast when comparing to the original ZeroMQ's performance test as seen here:

http://zeromq.org/results:perf-howto

Is my understanding correct? If so, would the community be open to me submitting a pull request for a test case where `def pusher` and `def throughput` can be configured to run on 2 separate machines?

**Comment by sivabudh** [comment]
Hello,

I'm thinking perhaps the perf.py can be refactored into something along this line:

https://github.com/cloud-hm/pyzmq-perf

(comments welcomed)

**Comment by minrk** [comment]
If you want to add a version of the scripts, that would be fine. Or you can just add a reference to your existing pyzmq-perf repo. I don't think it's important to have these things in the pyzmq repo itself.
