### ISSUE TITLE
Polling on REP socket takes significant CPU

### ISSUE THREAD

**Issue by asmodehn** [zeromq/pyzmq#770]
I am currently running 14.0.1. on Ubuntu Trusty.

It seems that when I do : 
```python
        self._svc_address = 'ipc://' + self.tmpdir + '/services.pipe'
        zcontext = zmq.Context()
        zcontext.setsockopt(socket.SO_REUSEADDR, 1)
        svc_socket = zcontext.socket(zmq.REP)
        svc_socket.bind(self._svc_address,)

        poller = zmq.Poller()
        poller.register(svc_socket, zmq.POLLIN)

        # loop listening to connection
        while not self.exit.is_set():
            socks = dict(poller.poll(timeout=100))
```
my CPU load is quite high : 
- 5% < CPU load < 10% on a `product: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz`
- 20% < CPU load < 30% on a `product: Intel(R) Core(TM) i3-4130T CPU @ 2.90GHz`

From what I could gather, it seems the process in is "sleeping" state, but yet the CPU load comes from user space... `iotop` also doesn't seem to show anything big ( so probably not coming from the fact that I am using file/IPC ? )
I verified it was the polling by commenting that line, then CPU usage drops under 1%.

Could someone confirm this issue ? 
From what I understand, polling should not take any CPU, correct ?

Would I be able to workaround it if I refactor that code to have an event loop instead ?

**Comment by minrk** [comment]
Do you mean to be exiting and resuming poll every 100ms? Perhaps that's the cause. On my systems (Python 3.5, OS X 10.11, 4 GHz Intel Core i7), this code uses 0.1% CPU. Do you have other threads running?

Also, SO_REUSEADD isn't meaningful for zmq sockets. SO_REUSEADD is 4, which is actually being interpreted as zmq.AFFINITY, setting the IO thread affinity of the socket (having no effect, really).

**Comment by jizhilong** [comment]
Here is my hypoerthesis, not sure if I am correct or not:
  1. poller is level-triggered.
  2. your application code can't consume the sockets as soon as enough.
  3. so a piece of incoming message may keep triggering the poller for several times before it is consumed.

**Comment by asmodehn** [comment]
Thanks for the hints.

@minrk Yes I mean to poll every 100ms, since I might want to do something else ( like exist the loop or so on some event (not from the socket).

I actually have a lot of other threads and processes running, so I ll work to isolate the problem, double check how messages are sent, and maybe profile some function calls in details...

**Comment by asmodehn** [comment]
I tried to reproduce the issue on a simple project without anything other than zmq, but failed so far.
I think the reason for my problem is coming from another part of the code ( that still spins at a rate that depends on the timeout I pass in the poll() ) while not being the poll itself...
I ll investigate more and close this issue when I can confirm the CPU load doesnt come from zmq.

**Comment by minrk** [comment]
You can avoid dropping out of the poller to check other things by sending a signal that will wake the poller, instead of via another channel. But since the issue seems to be coming from somewhere else, I'll close here. If you can reproduce this as a zmq issue, feel free to open again.
