### ISSUE TITLE
Compilation on Android

### ISSUE THREAD

**Issue by hastebrot** [zeromq/pyzmq#778]
I compiled pyzmq on Android using Termux. Since Android is missing ˋlibrt.soˋ I removed the line that adds the dependency (ˋld -lrtˋ) to it in ˋsetup.pyˋ. It compiles fine, but when I run ˋjupyter notebookˋ (which uses pyzmq) it outputs:

```
OSError: dlopen failed: cannot locate symbol "_ZSt20__throw_length_errorPKc" referenced by "libzmq.cpython-35m-arm-linux-gnueabi.so"...
```

Do I need cross-compile the libary on Linux to statically link to ˋlibrt.soˋ or is there a way to compile this library on Android?

**Comment by minrk** [comment]
Good question. I have no idea how to compile pyzmq or anything else on Android. Perhaps @cyrilh has some ideas, since they contributed the existing Android build patches.

**Comment by cyrilh** [comment]
Hi,

 

I’m not sure, but it was a well documented toolchain for Android, it’s long ago and I didn’t do software in the last 3 years and not on that PC either!

I probably worked from Linux and used Eclipse and the toolchain was pretty well integrated to that.

If I had to tweak something I probably made my changes public … that would be:

-        GNU something ?

-        Github somewhere?

 

Sorry but I will not be able to support you more. I am no expert in cross compilation, that was my first Android job, and I probably spent a couple of weeks on getting this and a few other tools compiled and run including recompiling my android kernel.

 

Cyril
