### ISSUE TITLE
yield from syntax error in _test_asyncio.py for 15.1.0

### ISSUE THREAD

**Issue by timmooney** [zeromq/pyzmq#780]
Hi!

I've downloaded the pyzmq-15.1.0.tar.gz source code and am building an RPM package for RHEL 7.x x86_64.  RHEL 7 ships with /usr/bin/python as python 2.7.5 (plus "vendor sauce" patches and backports).  The organization I work for is a strong proponent of OS packages for all add-on modules for scripting languages like Python, Perl, and Ruby, so we don't use tools like pip, cpan, or rubygem to directly install add-on modules.

The standard RPM machinery on RHEL has a process that runs to re-compile the python byte code automatically just before the binary RPM package is generated.  This script is called

```
    /usr/lib/rpm/brp-python-bytecompile
```

When that process runs over all the files in the build-root (a temporary location created as a staging area to collect all the files that should be part of the package) for pyzmq, it errors out with the following:

```
Bytecompiling .py files below /var/tmp/python-pyzmq-15.1.0-1.packager/usr/lib64/python2.7 using /usr/bin/python2.7
Compiling /var/tmp/python-pyzmq-15.1.0-1.packager/usr/lib64/python2.7/site-packages/zmq/tests/_test_asyncio.py ...
  File "/usr/lib64/python2.7/site-packages/zmq/tests/_test_asyncio.py", line 37
    yield from a.send(b'hi')
             ^
SyntaxError: invalid syntax
```

I'm not an expert Pythoneer, but based on my understanding, it appears that "yield from" was formalized as part of PEP-0380 and is essentially new syntax for Python 3.3 and later.  Am I correct in thinking that's why the python 2.7.5 from RHEL 7 is failing to (re)byte-compile that file?

Since this is in the tests subdirectory, I'm planning on working around the issue by removing that directory before issuing the

```
  python setup.py install --root=/var/tmp/python-pyzmq-15.1.0-1.packager
```

directive in the RPM spec file. See any problem with that approach?

**Comment by minrk** [comment]
You are correct that the file isn't valid on old, legacy versions of Python. That shouldn't be a problem, because it's perfectly sensible for a package to contain some sources that are only valid on certain versions of Python. The bytecompiling tool should either ignore (and warn about) these failures like Python's own bytecompiling tools do, or allow passing a blacklist of files to skip compiling that you know ahead of time shouldn't be compiled. If it doesn't, you will have to monkeypatch the package to remove the files and replace them with placeholders prior to running the tool.

**Comment by timmooney** [comment]
Thanks Min!

You can feel free to close this (WONTFIX if that's a valid option).  I reported it as much to get it out there for others to find in case they run into the same issue as for any other reason.  I've gone the route of removing the entire "tests" directory so it's not included in the package, and that seems to be a reasonable workaround.

**Comment by majek** [comment]
I have some old python 2.7 and it doesn't support "yield from" keyword. In the docs you say python 2.6+ is supported https://pyzmq.readthedocs.io/en/latest/

The effect  is that calling "pip install pzmq" fails with:

```
        yield from a.send(b'hi')
                 ^
    SyntaxError: invalid syntax

```

**Comment by minrk** [comment]
Yes, this is not an issue. Asyncio support uses Python 3 syntax because asyncio itself requires Python 3.

Pip install does not generally fail due to syntax errors in unused files. Can you show the actual output of a failed installation? If it failed, the cause is likely something else.

**Comment by dgentry** [comment]
It's an issue for some of us.  When trying to package up a python 2.7-based app (using kivy, but this probably applies to any of the app bundling methods), the syntax error causes the compile step to fail. As someone who is just trying to use the software (zmq and kivy) to produce our own software, I'll need to go modify one or the other.

**Comment by minrk** [comment]
@dgentry current pyzmq (15.4, 16.0) doesn't ship the asyncio sources on Python 2, so that might help you.

**Comment by dgentry** [comment]
Ooh, thanks!  I'll update.
