### ISSUE TITLE
How to handle ZMQError raised from cython?

### ISSUE THREAD

**Issue by Kentzo** [zeromq/pyzmq#783]
I have the following block:

```
try:
    sock.send_multipart([identifier, b'', payload], zmq.DONTWAIT)
except zmq.ZMQError as e:
    LOG.warning("...")
```

However, when the following exception happened, it was not handled by the except statement:

```
  File "zmq/sugar/socket.py", line 329, in send_multipart
  File "zmq/backend/cython/socket.pyx", line 619, in zmq.backend.cython.socket.Socket.send (zmq\backend\cython\socket.c:6169)
  File "zmq/backend/cython/socket.pyx", line 666, in zmq.backend.cython.socket.Socket.send (zmq\backend\cython\socket.c:5931)
  File "zmq/backend/cython/socket.pyx", line 201, in zmq.backend.cython.socket._send_copy (zmq\backend\cython\socket.c:2400)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq\backend\cython\socket.c:7055)
zmq.backend.cython.zmq.error.ZMQError: Unknown error
```

**Comment by minrk** [comment]
Can you provide more detail, and perhaps a complete test case that reproduces the error? What OS? What Python, pyzmq, libzmq versions? Normally, ZMQErrors are raised and catchable just fine, which is done all over the test suite.

**Comment by Kentzo** [comment]
I don't know how to reproduce, error is "unknown". I only have crashlog.

I would have more details if my except would be executed. Instead this exception is propagated to a higher except that catches everything.

Could it be that class is duplicated for cython and therefore unrecognized by my except?

Windows 8, Python 3.5, pyzmq 14.7.0, libzmq 4.1.4


Best Regards
Ilya Kulakov

**Comment by minrk** [comment]
Is your code Cython as well? Can you provide the rest of the traceback?

The suspicious piece for me is the string `zmq.backend.cython.zmq.error.ZMQError`. There is no module `zmq.backend.cython.zmq.error`, so I'm guessing Cython is doing something a bit wrong.

**Comment by Kentzo** [comment]
Our code is Python. It is packaged with pyqtdeploy (frozen and put into binary). However it's not supposed to anyhow affect names.

If you have in mind a test case that would make _checkrc to fail with an Unknown error, I'm happy to reproduce it under debugger.

**Comment by minrk** [comment]
I don't have any such test cases because that, too, shouldn't happen.

**Comment by Kentzo** [comment]
At least could you somehow ensure that raised exception is of right type?

Best Regards
Ilya Kulakov

**Comment by minrk** [comment]
I believe I already do, which is why I'm confused. The error message you show indicates that an Exception class that does not exist is being raised. I cannot produce a test case because I do not understand how to cause the behavior you are seeing.

**Comment by Kentzo** [comment]
I did not encounter this error ever again.

**Comment by Peque** [comment]
@Kentzo Did you stop encountering this error after an OS upgrade? (Windows 8 to Windows 10) or after a PyZMQ upgrade?

**Comment by Kentzo** [comment]
@Peque PyZMQ upgrade.
