### ISSUE TITLE
pyzmq - undefined symbol: zmq_msg_gets

### ISSUE THREAD

**Issue by green96** [zeromq/pyzmq#791]
Hi, 
I have problem with zeromq, I get this error: 

    Traceback (most recent call last):   File "BasicPub.py", line 1, in <module>
        import zmq   File "/home/przemek/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/zmq/__init__.py", line 66, in <module>
        from zmq import backend   File "/home/przemek/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
        reraise(*exc_info)   File "/home/przemek/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
        _ns = select_backend(first)   File "/home/przemek/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
        mod = __import__(name, fromlist=public_api)   File "/home/przemek/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
        from . import (constants, error, message, context, ImportError: /home/przemek/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/zmq/backend/cython/message.so: undefined symbol: zmq_msg_gets

I installed it this way:
tar xzvf zeromq-4.1.4.tar.gz 
./configure
./configure --without-libsodium
make
sudo make install
pip install pyzmq

I use python2.7 and Ubuntu 14.04
Could you help me?

**Comment by minrk** [comment]
Is there a libzmq in `/home/przemek/Enthought/Canopy_32bit/User/lib`?

**Comment by green96** [comment]
przemek lib $ locate libzmq
/home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib/libzmq.a
/home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib/libzmq.la
/home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib/libzmq.so
/home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib/libzmq.so.4
/home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib/libzmq.so.4.0.0
/home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib/pkgconfig/libzmq.pc
/home/przemek/Enthought/Canopy_32bit/User/lib/python2.7/site-packages/zmq/backend/cython/libzmq.pxd
/usr/local/lib/libzmq.a
/usr/local/lib/libzmq.la
/usr/local/lib/libzmq.so
/usr/local/lib/libzmq.so.5
/usr/local/lib/libzmq.so.5.0.0
/usr/local/lib/pkgconfig/libzmq.pc

so there is something under this path:
/home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib/pkgconfig/libzmq.pc

**Comment by minrk** [comment]
My guess is something's getting confused so that Canopy is forcing it to load the bundled libzmq rather than the one in /usr/local/lib, which it compiled against. I'm not sure if there's a fix for pyzmq to make to force the right library to load or not.

**Comment by green96** [comment]
I notice that there is difference when I install 'sudo pip pyzmq' and 'pip pyzmq'. 
When I type 'pip list', I don't see  pyzmq when I type 'sudo pip list' pyzmq is on the list. 

I manually rm duplicated libzmq from /home/przemek/Canopy/appdata/canopy-1.5.4.3105.rh5-x86/lib

now when I try to run script I get:
python basicPub.py -> ImportError: No module named zmq
sudo python basicPub.py -> WORKS! 

I find this part in my .bashrc : 
# Added by Canopy installer on 2015-06-30
# VIRTUAL_ENV_DISABLE_PROMPT can be set to '' to make bashprompt show that Canopy is active, otherwise 1
VIRTUAL_ENV_DISABLE_PROMPT=1 source '/home/przemek/Enthought/Canopy_32bit/User/bin/activate'

could you tell me what should I do to run it in normal proper way without sudo?

**Comment by minrk** [comment]
`sudo python` and `python` are likely starting different Python installations due to differences in PATH. You can see the difference by running `python -c 'import sys; print(sys.executable)'` in both cases.

You can see which zmq is imported in each case (if there is one) with:

    python -c 'import zmq; print(zmq)'

If `sudo python` works and canopy doesn't, then it would seem that you have installed pyzmq with the system Python, but not with Canopy Python.

To make sure you install pyzmq with the right Python, do:

    /explicit/path/to/python -m pip install pyzmq

**Comment by green96** [comment]
przemek mateusz $ python -c 'import zmq; print(zmq)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named zmq
przemek mateusz $ sudo python -c 'import zmq; print(zmq)'
<module 'zmq' from '/usr/local/lib/python2.7/dist-packages/zmq/__init__.pyc'>

so  /explicit/path/to/python is /usr/local/lib/python2.7/?

**Comment by minrk** [comment]
No, it would be what you get from `which python`. The path to the `python` executable. What do you get from `which pip`?

**Comment by green96** [comment]
/home/przemek/Enthought/Canopy_32bit/User/bin/pip

**Comment by minrk** [comment]
That looks like libzmq has been upgraded out from under pyzmq. If you recompile pyzmq, it should link against the libzmq you have.
