### ISSUE TITLE
memory leak in failed send/recv

### ISSUE THREAD

**Issue by yshysh** [zeromq/pyzmq#793]
![image](https://cloud.githubusercontent.com/assets/6756230/12438022/10250a34-bf5e-11e5-8cd3-a1761ef502e0.png)
when we try to use Socket.send method, we found that if the flags is NOBLOCK, memory leak happens. After reading the socket.pyx, we found the reason of memory leak as shown in the picture. when the function "zmq_msg_send(&data, handle, flags)" failed, the memory alloc by "zmq_msg_init_size" is not freed.

**Comment by minrk** [comment]
How are you checking this leak? `zmq_msg_send` hands off the data to a background IO thread to send and free at a later point. The memory is not and should not be freed by the main thread.

**Comment by yshysh** [comment]
We found this leak in our project. Here is the API description of zmq_msg_close and zmq_msg_init_size(http://api.zeromq.org/2-1:zmq-msg-close  ,  http://api.zeromq.org/2-1:zmq-msg-init-size).
![image](https://cloud.githubusercontent.com/assets/6756230/12469685/e5e81ed4-c028-11e5-94ab-2bc98f5a2628.png)
 From the description, we know that when we do not need to use msg, we should use zmq_msg_close at once. In the picture we posted last time, while the rc less than 0 , the msg doesn't free.
Here is the deamon we test:
![image](https://cloud.githubusercontent.com/assets/6756230/12469698/f7870812-c028-11e5-9204-a73582a31d66.png)
If the code changes like this
![image](https://cloud.githubusercontent.com/assets/6756230/12469736/523019de-c029-11e5-8bb4-ef55e9b92357.png)
 , the problem will be solved.

**Comment by minrk** [comment]
Gotcha, thanks. I see that there can be a leak when send fails. That fix isn't quite right, but I know how to fix it now. Thanks!
