### ISSUE TITLE
pip install upgrade to 15.2.0 fails on windows

### ISSUE THREAD

**Issue by MrYsLab** [zeromq/pyzmq#795]
I have been using 15.1.0 without issue and tried to upgrade with pip install pyzmq --upgrade.

If I remove pyzmq and try pip install pyzmq==15.1.0, there are no issues.

Here is the output from the upgrade attempt:

[upgradeError.txt.zip](https://github.com/zeromq/pyzmq/files/100109/upgradeError.txt.zip)

**Comment by minrk** [comment]
The windows bdist upload failed, and I hadn't noticed. It should be fine, now.

**Comment by MrYsLab** [comment]
Thanks for the quick fix!!!!
