### ISSUE TITLE
32 bit test error

### ISSUE THREAD

**Issue by keenerd** [zeromq/pyzmq#799]
This pops up when running py3/py2 tests on a 32 bit platform.  The test (`test_large_send`) is already disabled on Travis, presumably for similar reasons.  Consider expanding the `@skip_if` ? 

    test_large_send (zmq.tests.test_socket.TestSocket) ... ERROR
    ======================================================================
    ERROR: test_large_send (zmq.tests.test_socket.TestSocket)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/build/python-pyzmq/src/pyzmq-15.2.0/zmq/tests/test_socket.py", line 443, in test_large_send
        buf = os.urandom(1) * (2**31 + 1)
    OverflowError: cannot fit 'int' into an index-sized integer
    ----------------------------------------------------------------------

**Comment by minrk** [comment]
Sorry, I forgot 32b systems existed :) Should be fixed by #800.
