### ISSUE TITLE
ImportError: cannot import name initthreads

### ISSUE THREAD

**Issue by baloan** [zeromq/pyzmq#80]
After installation python import zmq results in a traceback:

<pre>
Python 2.7.1 (r271:86832, Nov 27 2010, 18:30:46) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import zmq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "zmq\__init__.py", line 26, in <module>
    from zmq.utils import initthreads # initialize threads
ImportError: cannot import name initthreads
</pre>

I am using:
    \* zeromq-2.1.1
    \* pymzq-2.1.1
    \* Visual Studio 2008
    \* Windows XP SP3
Compilation was successful. Then I did the usual

<pre>
setup.py build
setup.py install
</pre>

**Comment by waschbaer00** [comment]
But this does not solve the problem, you want to always switch to that path then import? Something is wrong.
