### ISSUE TITLE
ZMQStream for asyncio

### ISSUE THREAD

**Issue by markbarks** [zeromq/pyzmq#802]
It would seem to be really useful if there was a port of the ZMQStream class for use with the asyncio eventloop. Is it something that has been considered and just not done yet, or am I missing another way of doing things with asyncio? Thanks, Mark

**Comment by minrk** [comment]
I wasn't planning on it. I figured with asyncio, one would want to use the more modern coroutine-style with Futures, rather than the old callback-style ZMQStream, since the two are really equivalent. Is there a reason you don't want to write with coroutines/Futures?

**Comment by markbarks** [comment]
None at all - only that I'm still pretty green with both ZeroMQ and asyncio and I was trying to reimplement your clonesrv5 example from the guide, which uses this pattern. Just knowing that this is _not_ the way to be thinking is already useful.
If you ever got a chance to put some more fully featured asyncio examples then that would be great too ;)
Thanks
