### ISSUE TITLE
zmq.auth.Authenticator should set public key so that it is gettable as frame property

### ISSUE THREAD

**Issue by JonasT** [zeromq/pyzmq#804]
zmq.auth.Authenticator should set public key used by a specific client (or as the very minimum, the fingerprint of the public key) so that it is obtainable via zmq.Frame's get() function as a property for each message to identify the respective client. Since configure_curve() just takes an entire folder with potentially a lot of keys to allow different clients/accounts, this is required to be able to identify _which_ client specifically has been allowed to connect and is currently speaking.

If such functionality is already available, please add a mention of the property's name in the documentation: http://pyzmq.readthedocs.org/en/latest/api/zmq.auth.html

**Comment by JonasT** [comment]
Since it is somewhat hard to make a non-trivial system where users have access rights without this feature, it would be really great if this could be eventually added! I assumed others might see the need as well, which is why I brought it up here on the bugtracker.

I was suggested on the ZMQ mailing list to implement this myself, however right now I have absolutely no idea of the ZMQ internals, much less the PyZMQ wrapper code on top.

It would be nice to know if you consider this feature doable at all, and/or whether there is any chance you might consider implementing it some time.

**Comment by minrk** [comment]
It should be doable. I don't have time to add it at the moment.

**Comment by JonasT** [comment]
Any chance this might be added some time in the future? I'm really not zmq-savvy enough to easily do this myself, but we're still hoping to be able to use this in our software.

We would love to make heavy use of the new curve encryption of ZeroMQ both for authentication and authorization, but not being able to identify the particular user is the only major roadblock that makes any sort of authorization use impossible right now. So seeing this added would really be a game changer for us

**Comment by JonasT** [comment]
Wow thanks :smile: what a new year's treat :heart:
