### ISSUE TITLE
How to make the Tornado IO loop use epoll?

### ISSUE THREAD

**Issue by Tinche** [zeromq/pyzmq#805]
We've been having a hard time making ZMQIOLoop use epoll - strace keeps showing poll calls. Is it even possible? Is there something we're missing?

Ubuntu Trusty base Docker image, CPython 2.7. We've tried using the bundled ZMQ, installing the system ZMQ (libzmq3{,-dev}), and rebuilding the system libzmq3 with --poller=epoll, but no dice.

Right now we're driving the ZMQ stuff in a separate thread so we can use the default Tornado event loop, which uses epoll - so we know epoll can work in this environment. Our cpu usage is roughly more than halved by using epoll, so it doesn't appear to be a trivial matter :)

**Comment by minrk** [comment]
ZMQPoller always uses `zmq_poll` (this is its whole point). `zmq_poll`, I believe, ought to use epoll when available. What versions of everything (Python, libzmq, pyzmq, pip, etc.) are you using?

**Comment by Tinche** [comment]
Let's see,

Docker base image: ubuntu:trusty
Python: CPython 2.7.6
ZMQ: libzmq3 4.0.4+dfsg-2 (system package, through apt-get)
pyzmq: 15.2.0
pip: 8.0.2
Tornado: 4.3

**Comment by Tinche** [comment]
For what it's worth, I'm able to reproduce this easily on my Ubuntu 15.10 desktop, using both the bundled ZMQ and system ZMQ, no Docker shenanigans needed.

**Comment by mulog1990** [comment]
We are experiencing this too. From this issue in libzmq https://github.com/zeromq/libzmq/issues/1667 and reading some of the code, it seems to me that libzmq uses epoll internally for polling the underlying system sockets, but not for `zmq_poll`.  

I believe you can reproduce this by running /examples/eventloop/web.py and run `strace` on all the threads.  The main thread(on which `zmq_poll` is called, i believe) always uses `poll`. There are two child threads created by libzmq to poll underlying system sockets, and they use `epoll`. Here are the output of the strace results:

main thread:
```
poll([{fd=10, events=POLLIN}, {fd=8, events=POLLIN}, {fd=9, events=POLLIN}, {fd=12, events=POLLIN}], 4, 0) = 1 ([{fd=9, revents=POLLIN}])
poll([{fd=8, events=POLLIN}], 1, 0)     = 0 (Timeout)
accept(9, {sa_family=AF_INET, sin_port=htons(40144), sin_addr=inet_addr("127.0.0.1")}, [16]) = 13
fcntl(13, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(13, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
recvfrom(13, "GET / HTTP/1.0\r\nHost: 127.0.0.1:"..., 65536, 0, NULL, NULL) = 83
write(1, "sending hello\n", 14)         = 14
sendto(13, "HTTP/1.1 200 OK\r\nDate: Tue, 21 J"..., 197, 0, NULL, 0) = 197
setsockopt(13, SOL_TCP, TCP_NODELAY, [1], 4) = 0
close(13)
.......
```

child thread 1:
```
poll_wait(7, {}, 256, 42)              = 0                   socket(PF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 13   fcntl(13, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(13, F_SETFL, O_RDWR|O_NONBLOCK)   = 0                   connect(13, {sa_family=AF_INET, sin_port=htons(15555), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(7, EPOLL_CTL_ADD, 13, {0, {u32=402656592, u64=139724278730064}}) = 0
epoll_ctl(7, EPOLL_CTL_MOD, 13, {EPOLLOUT, {u32=402656592, u64=139724278730064}}) = 0
epoll_wait(7, {{EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=402656592, u64=139724278730064}}}, 256, -1) = 1
epoll_ctl(7, EPOLL_CTL_DEL, 13, {EPOLLOUT, {u32=402656592, u64=139724278730064}}) = 0
getsockopt(13, SOL_SOCKET, SO_ERROR, [111], [4]) = 0          close(13)
......
```

child thread 2:
```
epoll_wait(5,  <unfinished ...>
+++ exited with 1 +++
```

**Comment by minrk** [comment]
ZMQIOLoop has been deprecated for a while, so whatever tornado is configured to use will be used
