### ISSUE TITLE
In function `main':  timer_createk9VCxz.c:(.text+0x15): undefined reference to `timer_create'  collect2: ld returned 1 exit status

### ISSUE THREAD

**Issue by jlec** [zeromq/pyzmq#808]
I see build problems, which are present also in [your travis runs.](https://travis-ci.org/zeromq/pyzmq/jobs/108012271#L555)

``` bash
Configure: Autodetecting ZMQ settings...

    Custom ZMQ dir:       

creating build/temp.linux-x86_64-2.7/scratch/tmp
cc -c /tmp/timer_createk9VCxz.c -o build/temp.linux-x86_64-2.7/scratch/tmp/timer_createk9VCxz.o
cc build/temp.linux-x86_64-2.7/scratch/tmp/timer_createk9VCxz.o -o build/temp.linux-x86_64-2.7/scratch/a.out
build/temp.linux-x86_64-2.7/scratch/tmp/timer_createk9VCxz.o: In function `main':
timer_createk9VCxz.c:(.text+0x15): undefined reference to `timer_create'
collect2: ld returned 1 exit status
```

**Comment by minrk** [comment]
Why do you say this is a problem? Does the build fail?

What you have pasted is part of the build detection for determining what libraries to link.

**Comment by jlec** [comment]
mmh, I am trying to figure out what the problem is in this https://bugs.gentoo.org/show_bug.cgi?id=572126 bug report.

**Comment by minrk** [comment]
I'm guessing it's this:

```
failed to import Cython: dynamic module does not define init function (PyInit_Scanning)
error: Cython does not appear to be installed
```

If it's building from a git tag, Cython is required for compilation.

**Comment by jlec** [comment]
That is build from the version 15.2.0 tarball from pypi. And on my system it builds fine without cython. Any reason why it would be needed for that user?

**Comment by minrk** [comment]
From the error, it looks like Cython is present, but broken. Maybe making sure it either is installed and works or isn't installed is the way to go.
