### ISSUE TITLE
zmq.green.Context.destroy freezes all greenthreads

### ISSUE THREAD

**Issue by stefanmh** [zeromq/pyzmq#809]
Reproduce with:

``` python
import gevent
import zmq.green as zmq

def heartbeat():
    while True:
        print 'alive'
        gevent.sleep(.1)

def zmq_stuff():
    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    print 'connecting'
    socket.connect('tcp://127.0.0.1:1234')
    print 'sending json'
    socket.send_json({}, zmq.NOBLOCK)
    gevent.sleep(1)
    print 'closing socket'
    socket.close()
    print 'destroying context'
    context.destroy()
    print 'destroyed context'

gevent.spawn(zmq_stuff)
gevent.spawn(heartbeat).get()
```

Output:

```
connecting
sending json
alive
...
alive
closing socket
destroying context
```

The main issue is not that `context.destroy` blocks the `zmq_stuff` greenthread (though such a block is debatable as well), but that it does not return to the hub, so `heartbeat` blocks as well.

**Comment by tkrajca** [comment]
Hi All, I am seeing the same issue as @stefanmh with gevent==1.2.1 or gevent==1.0.1 and pyzmq==14.4.2 or pyzmq==16.0.2. Have you found any workaround yet?

**Comment by tkrajca** [comment]
Hmm, looks like if I give it linger=0, then it works normally:

```python
socket.close(linger=0)
context.destroy(linger=0)
```

**Comment by minrk** [comment]
If linger fixes it, that means there are undelivered messages and context.term is hanging until the message is dealt with, per [its specification](http://api.zeromq.org/4-3:zmq-ctx-term) in libzmq.
