### ISSUE TITLE
error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by Sunacni** [zeromq/pyzmq#817]
![image](https://cloud.githubusercontent.com/assets/10613761/13529577/4d887c6c-e21d-11e5-9be3-2b86b665f431.png)

when trying to run the <a href="http://zeromq.org/bindings:python">PyZMQ Test Suit</a> the error above occurs. Using Windows10 machine.

**Comment by minrk** [comment]
What version(s) of Visual Studio and/or Windows SDK are you using?

**Comment by frmdstryr** [comment]
Try installing [Microsoft Visual C++ Compiler for Python](https://www.microsoft.com/en-us/download/details.aspx?id=44266) if you haven't already.
