### ISSUE TITLE
getting assertions from the zeromq lib

### ISSUE THREAD

**Issue by aaronavi** [zeromq/pyzmq#822]
Hi
I am getting the following assertion
Assertion failed: nbytes == sizeof (dummy) (bundled\zermq\src\signaler.cpp:303)

i understand it comes from the zeromq library, but i can't understand how is it possible to get assertions on a release version, as i know assert command only works on debug compiled library

i wish to handle this assertions:
1. Are you using debug complied library
2. is there anyway to handle those assertions so they won't crush my process?

thanks

**Comment by minrk** [comment]
If you've linked pyzmq against a debug build of libzmq, it will be a debug build. If pyzmq is bundling libzmq, as your path suggests, it uses Python's own compilation configuration to decide. You can tell Python to do a debug build with:

    python setup.py build -g

The releases of pyzmq are release builds, not debug builds.

C asserts cannot be handled by Python (or C) code. They unconditionally kill the process, and there is nothing that we can do about it. Any assert raised by zeromq is considered a bug in zeromq itself.

**Comment by aaronavi** [comment]
Hi Minrk
Thank you for your response, 
Regarding the C assert, from my experience the assert command only works on debug build, when assert is called from release build its being ignored.

I am using the latest release of pyzmq 15.2.0, and it seems the assertion calls are not being ignored, so that is why i am asking if by any chance the zeromq lib used is a debug build and not a release build?

thanks

**Comment by minrk** [comment]
> Regarding the C assert, from my experience the assert command only works on debug build, when assert is called from release build its being ignored.

libzmq isn't using the assert macro, it's using it's own checks and explicit `abort` calls on failure to kill the process.

**Comment by aaronavi** [comment]
I understand
Thank you for your assistance.
