### ISSUE TITLE
Compiling pyzmq v15.2.0 fails with python 2.7.11

### ISSUE THREAD

**Issue by thogra00** [zeromq/pyzmq#823]
I am using python 2.7.11 to compile pyzmq. It still works with v15.1.0 but not with version >= v15.2.0. 

The problem is that there has been some code introduced, which is using a new feature from python 3.3 (yield from self)
zmq/auth/asyncio.py:28:            events = yield from self.__poller.poll()
zmq/auth/asyncio.py:30:                msg = yield from self.zap_socket.recv_multipart()

I have seen this feature has already been used in v15.1.0 but only in docs, test and example code.

**Comment by minrk** [comment]
Yes, the asyncio bits only run on Python 3. That doesn't affect the ability to build or install pyzmq on Python 2. Those files should simply be ignored. How are you encountering these errors?

**Comment by thogra00** [comment]
I encountered the error message in three steps: 
  setup.py bdist
  setup.py install
  setup.py -m compileall

But as we are not using asyncio I just ignore the errors.
thanks for the quick reply.
