### ISSUE TITLE
Update docstrings about `context.term()` and `socket.close()` with regards to garbage collection

### ISSUE THREAD

**Issue by vlcinsky** [zeromq/pyzmq#831]
[Change log for 14.3.0](http://pyzmq.readthedocs.org/en/latest/changelog.html#id10) states.

> PyZMQ no longer calls `Socket.close(`) or `Context.term()` during process cleanup. Changes to garbage collection in Python 3.4 make this impossible to do sensibly.

[Docstring for `Context.term()`](http://pyzmq.readthedocs.org/en/latest/api/zmq.html#zmq.Context.term) states:

> This can be called to close the context by hand. If this is not called, the context will automatically be closed when it is garbage collected.

[Docstring for `Socket.close()`](http://pyzmq.readthedocs.org/en/latest/api/zmq.html#zmq.Socket.close) states:

> This can be called to close the socket by hand. If this is not called, the socket will automatically be closed when it is garbage collected.

**Docstrings seems to be obsolete** in regards to what change log states and shall be updated.

According to "Zen of Python" rule `There should be one-- and preferably only one --obvious way to do it.`, it would be great to devote short chapter to this topic in main documentation and update in main documentation all examples to be consistent with it.

**Comment by minrk** [comment]
These docstrings are still accurate. The changes in 14.3 describe *process cleanup* which is distinct from garbage collection. Python 3.4 changes how garbage collection resolves during process cleanup, but not in general. Sockets and Contexts that are garbage collected *under normal circumstances* will be closed/terminated, as described.

I'm not sure what the relevance of invoking Zen of Python is here.

**Comment by RojavaCrypto** [comment]
This is not true. I have an application I just spent the last 3 days trying to debug and finding this bug report helped me fix the problem. I am using ZMQ asyncio and when shutting down my application, I explicitly need to call ```socket.close()``` and ```context.term()``` otherwise it will hang indefinitely until I press CTRL-C.

**Comment by jeremyherbert** [comment]
FWIW I have the same problem, also with asyncio. I have a coroutine which creates a new socket each iteration of a loop (the socket from the previous iteration is not kept). If I don't explicitly `.close()` the socket, I shortly end up with ```zmq.error.ZMQError: Too many open files```

Using 17.0.0b3 with python 3.5.2 on ubuntu 16.04.

**Comment by minrk** [comment]
Asyncio behavior is different because the eventloop holds a reference to the socket, which prevents garbage collection, so when using asyncio an explicit close is required. This could probably be avoided with a careful use of weakref.
