### ISSUE TITLE
Broken Compatability with Python 2.7?

### ISSUE THREAD

**Issue by amznmatt** [zeromq/pyzmq#834]
I noticed some recent commits that seem to break compatibility with Python 2.7. For example line 28 in `zmq/auth/asyncio.py`:

`events = yield from self.__poller.poll()`

It looks like "yield from" was only introduced in Python 3.3 as per https://docs.python.org/3/whatsnew/3.3.html .  One of the stated goals of PyZMQ is:

> PyZMQ should work with any Python ≥ 2.6 (including Python 3), as well as PyPy.

So I figured I'd let you know about these seemingly breaking changes.

**Comment by minrk** [comment]
This isn't a breaking change. Only the asyncio submodule requires Python 3, which asyncio itself also requires. PyZMQ works fine on Python ≥ 2.6 as long as you don't try to use asyncio, which you already can't do on Python 2.
