### ISSUE TITLE
manylinux1 wheels for pyzmq?

### ISSUE THREAD

**Issue by ogrisel** [zeromq/pyzmq#835]
It would be great if pyzmq could ship binary wheels for linux as well.

@matthew-brett made some with this build script:

https://github.com/matthew-brett/manylinux-builds/blob/master/build_pyzmqs.sh

The result has been uploaded to a [rackspace container](http://ccdd0ebb5a931e58c7c5-aae005c4999d7244ac63632f8b80e089.r77.cf2.rackcdn.com) and can be installed with pip 8.1:

```
pip install \
    --trusted-host=ccdd0ebb5a931e58c7c5-aae005c4999d7244ac63632f8b80e089.r77.cf2.rackcdn.com \
    --find-links=http://ccdd0ebb5a931e58c7c5-aae005c4999d7244ac63632f8b80e089.r77.cf2.rackcdn.com \
    pyzmq
```

If you think those wheels are correct, it would be great to upload them to PyPI (for instance with twine).

**Comment by ogrisel** [comment]
Actually no, I was wrong, they have not been uploaded to the rackspace container for some reason (maybe there is a specific build problem?). I was mislead by the local pip wheel cache when I made some tests.

**Comment by matthew-brett** [comment]
No - no problem - I was just building them locally.  What can I do to help deloy these?

**Comment by ogrisel** [comment]
Weird I get an SSL handshake failure:

```
$ docker run --rm -e PYZMQ_VERSIONS=15.2.0 -e PYTHON_VERSIONS=3.5 -v $PWD:/io quay.io/pypa/manylinux1_x86_64 /io/build_pyzmqs.sh

curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

Do you get it too? Are we missing certificates in the docker image?

**Comment by minrk** [comment]
Great! I'll trust you guys to have figured out the relocatable linux stuff. I'll upload the 15.2 wheels, and look into adding this to my release process.

**Comment by minrk** [comment]
I also get the SSL errors when trying to run those images.

**Comment by ogrisel** [comment]
@njsmith is working on a fix: pypa/manylinux#54.

**Comment by ogrisel** [comment]
Actually I am not 100% sure this stems from the same cause but it's likely.

**Comment by njsmith** [comment]
I doubt it -- the curl on the manylinux image is from centos5, and is linked against the system openssl which knows how to find the system CA certs. The problem in pypa/manylinux#53 is with our hand-built openssl, which is only by our hand built pythons.

**Comment by njsmith** [comment]
Only *used

**Comment by ogrisel** [comment]
Won't the definition of the `SSL_CERT_FILE` environment variable impact subsequent calls to curl?

**Comment by njsmith** [comment]
Yes, it should switch us to using the new CA cert bundle in general IIUC. But that code is still in a PR, so the only way it could be related AFAICT is if this handshake failed thing is somehow caused by having an old cacert bundle. And I don't really have any reason to think that the centos5 bundle is even broken... Does anyone know what command is actually triggering this error message?

**Comment by minrk** [comment]
I believe it was the:

    curl -LO https://download.libsodium.org/libsodium/releases/libsodium-1.0.4.tar.gz

triggered by 

    build_archive libsodium...

**Comment by minrk** [comment]
I'm looking into this one again, and the issue persists with the current version of the manylinux-build images.

**Comment by matthew-brett** [comment]
I think the problem is that curl's version of OpenSSL is too old.

No fix from recompiling curl with `openssl-devel` installed.

Works when building latest curl against latest openssl.

Works with openssl in Python:

```
#!/opt/python/cp35-cp35m/bin/python
import sys
from os.path import basename
import urllib.request

def main():
    url = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else basename(url)
    urllib.request.urlretrieve(url, out_path)


if __name__ == '__main__':
    main()
```

**Comment by minrk** [comment]
Thanks, @matthew-brett!

**Comment by matthew-brett** [comment]
I hope this is fixed with https://github.com/pypa/manylinux/pull/68

**Comment by njsmith** [comment]
@matthew-brett's fix is merged now, so the manylinux docker image should start working in ~1 hour (once the build completes)

**Comment by njsmith** [comment]
Manylinux image should have a working curl now

**Comment by matthew-brett** [comment]
Download of libsodium and build_pyzmqs.sh script now working for me on the new image:

```
docker run --rm -e PYZMQ_VERSIONS=15.2.0 -e PYTHON_VERSIONS=2.7 -v $PWD:/io quay.io/pypa/manylinux1_x86_64 /io/build_pyzmqs.sh
```

**Comment by ogrisel** [comment]
I get the following error at the line where it tries to build the zeromq archive:

```
$ build_archive zeromq-${ZMQ_VERSION} http://download.zeromq.org
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error exit delayed from previous errors
bash: cd: zeromq-4.1.4: No such file or directory
```

I think it tries to find the tarball at:

http://download.zeromq.org/zeromq-4.1.4.tar.gz

while according to the website it should be at:

https://github.com/zeromq/zeromq4-1/releases/download/v4.1.4/zeromq-4.1.4.tar.gz

The `build_archive` function cannot be used directly because the URL root has version dependents bits in it.

**Comment by minrk** [comment]
Arg, zeromq took down `download.zeromq.org` just now. Releases are posting to GitHub now.

**Comment by minrk** [comment]
Cool, with https://github.com/matthew-brett/manylinux-builds/pull/8 I was able to build the wheels.

I've put x64 wheels on PyPI for 27, 34, 35. When I try to upload i686 wheels, I get

> HTTPError: 400 Client Error: Binary wheel for an unsupported platform for url: https://pypi.python.org/pypi

The 686 wheels look like:

    pyzmq-15.2.0-cp35-cp35m-linux_x86_64.manylinux1_i686.whl

I admit, I'm not really sure what they are for, and I see that numpy doesn't have them, so I'm assuming it's okay.

**Comment by njsmith** [comment]
That's a bug in auditwheel - you can work around it by renaming the wheel file to remove the substring `linux_x86_64.`

**Comment by matthew-brett** [comment]
Min - did you run the 32-bit builds prepending the docker command with `linux32`?   As in:

```
docker run --rm -e PYZMQ_VERSIONS=15.2.0 -e PYTHON_VERSIONS=2.7 -v $PWD:/io quay.io/pypa/manylinux1_i686 linux32 /io/build_pyzmqs.
```

The `linux32` is necessary to set the output of `uname` so that pip will detect its platform correctly.

**Comment by minrk** [comment]
I did not, thanks!

**Comment by ogrisel** [comment]
> That's a bug in auditwheel - you can work around it by renaming the wheel file to remove the substring linux_x86_64.

I think we already fixed that one. Indeed it's a matter of running with the `linux32` command prefix.

**Comment by ogrisel** [comment]
I just did:

```bash
$ pip install pyzmq
Collecting pyzmq
  Downloading pyzmq-15.2.0-cp35-cp35m-manylinux1_x86_64.whl (3.4MB)
    100% |████████████████████████████████| 3.4MB 316kB/s 
Installing collected packages: pyzmq
Successfully installed pyzmq-15.2.0
```

so I assume @minrk did the upload :) Closing.
