### ISSUE TITLE
auth tests deadlocking on non-x86 and zmq > 4.0.5

### ISSUE THREAD

**Issue by juliantaylor** [zeromq/pyzmq#838]
recently libzmq in debian got updated to 4.1.4 and the pyzmq started deadlocking on several architectures, see here for the logs:
https://buildd.debian.org/status/package.php?p=pyzmq&suite=unstable

it is also reproducable with git head pyzmq and git head zeromq-4.1
the tests that usually lock up are in zmq.tests.test_auth, test_plain_unconfigured_server and test_plain_bogus_credentials

Apparently the commit in zeromq which triggers the problem is 

https://github.com/zeromq/libzmq/commit/9a53f334d25c27416b84d94a2d40e74656135b50
Don't reconnect on protocol errors

reverting only it in the stable branches it fixes pyzmq testsuite.

Do you maybe have some advice if the issue is really in that commit or pyzmq itself?

**Comment by juliantaylor** [comment]
libzmq 4.0.5 works fine, the first version with the bad commit is 4.1.0 which fails

**Comment by minrk** [comment]
Thanks for tracking that down! There is likely a workaround that can be added to the pyzmq tests, now that the cause is known. Seeing that error, I'm almost certain there are unhandled race conditions in the auth tests that I should fix.

I'm not sure that zeromq/libzmq#1043 was the right thing to do, or what problem it solves.

**Comment by minrk** [comment]
I think I know a fix or two, but I'm having a hard time reproducing the failure, so I can't be sure. I've run the tests close to a hundred times now with zeromq-4.1.4 and pyzmq-master on half a dozen VMs, buildbots, and a couple of OSes, without a single hang. What are you running on when you can reproduce this?

**Comment by juliantaylor** [comment]
I cannot reproduce it on a x86 machine it only happens on arm, mips or powerpc which is strange, it occurs probably around 25% of times on powerpc. It once also failed on a i386 build machine but I haven't been able to reproduce that myself.
If you have a patch I can test it on one of the affected machines.

**Comment by minrk** [comment]
I opened #839 with a few fixes.
