### ISSUE TITLE
the length limit of the buf that pyzmq send or recv

### ISSUE THREAD

**Issue by xvsfekcn** [zeromq/pyzmq#842]
i have acount a problem..
use the PUSH/PULL model
when i send a buf that it's about 19 Bytes large to the server ,it will be success
but intthe same environment and code i send a 7000000-Bytes buf .It can't be sucess and both the hwm was set to 0.
so it make me very confused ,maybe i can get some help from here

**Comment by minrk** [comment]
Do you have a test case? It is unlikely for this to be a pyzmq issue, but a test case should help us narrow it down. 7MB isn't very big, and it is quite common to send messages of that size.
