### ISSUE TITLE
`Assertion failed: written` on address reuse

### ISSUE THREAD

**Issue by Wild-M** [zeromq/pyzmq#846]
To put it simply:

```
> import zmq
zmq.__version__
'15.2.0'
zmq.zmq_version()
'4.1.4'
context = zmq.Context.instance()
sock1 = context.socket(zmq.REP)
sock1.connect("inproc://mtest")
sock1.disconnect("inproc://mtest")
sock1.close()
sock2 = context.socket(zmq.REP)
sock2.bind("inproc://mtest")
Assertion failed: written (src/ctx.cpp:559)
Aborted (core dumped)
```

Since this issue doesn't happen if sock1 is never opened/closed, it seems that the inproc system does not correctly tear down the initial socket.

**Comment by minrk** [comment]
This is likely a libzmq issue, and not something pyzmq can do anything about. Perhaps it is best brought up at zeromq/libzmq.

**Comment by Wild-M** [comment]
Understood. I suspected possible misuse of the underlying C library, but I'll close and follow up with them once I learn to build equivalent code in C. Thanks!
