### ISSUE TITLE
Import failure on Windows 7 with 32 bit python

### ISSUE THREAD

**Issue by kmonson** [zeromq/pyzmq#858]
I'm running the 32 bit version of python on Windows 7 64-bit Enterprise. 
When trying to import I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Users\Yaoj993\AppData\Local\Programs\Python\Python35-32\lib\site-pack
ages\zmq\__init__.py", line 37, in <module>
    _libzmq = ctypes.cdll.LoadLibrary(bundled[0])
  File "c:\Users\Yaoj993\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__
init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "c:\Users\Yaoj993\AppData\Local\Programs\Python\Python35-32\lib\ctypes\__
init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

15.2.0 works without issue.

**Comment by minrk** [comment]
15.2.0 works, but 15.3.0 doesn't?

**Comment by kmonson** [comment]
Yes

**Comment by minrk** [comment]
15.3 makes two changes to how the underlying libzmq is built:

1. build libzmq 4.1.5 with tweetnacl instead of 4.1.2 with libsodium
2. wheels are built on appveyor instead of manually on a VM

so it's likely one or the other of these is the culprit. I will try to investigate when I get the chance.

**Comment by cgohlke** [comment]
Install the [Microsoft Visual C++ 2015 Redistributable x86](https://www.visualstudio.com/downloads/download-visual-studio-vs#d-visual-c).

**Comment by minrk** [comment]
Thanks, @cgohlke! That wasn't necessary when I was building my own wheels, so there's something different with my new appveyor builds that I wasn't expecting. I'll see if there's something to fix.

**Comment by nonZero** [comment]
Since wheel is the default installation method these days, this means that currently pyzmq is broken on windows (I believe also on 64 bit).
This highly affects novice/new developers trying to get into python, installing ipython/junyper notebook on their windows machines, and immediately hitting a dead end, with a cryptic error message.

@cgohlke: Is there a way to compile pyzmq that would not require the MSVC++ redistributable?  If not: what would be the best way to provide a better error message to the user? (And thank you very much for all the great work!!)

**Comment by cgohlke** [comment]
The "official" solution is to distribute the required runtime DLLs (`MSVCP140.DLL` and `CONCRT140.DLL`  in this case) next to the extensions depending on it (`libzmq` in this case). That's what matplotlib does. 
IMO it is better for the users to install the Microsoft Visual C++ Redistributable. It is then available to all software depending on it, it includes other common runtime DLLs (e.g. OpenMP), and it is kept up to date by Windows Update.
It is possible to statically link the C/C++ runtime using the `/MT` compile flag, which is [not really a good idea](http://stevedower.id.au/blog/building-for-python-3-5-part-two/).
Another possibility is to change the code such that it does not depend on the C++ runtime, but that does not make sense to me.

**Comment by nonZero** [comment]
> The "official" solution is to distribute the required runtime DLLs (MSVCP140.DLL and CONCRT140.DLL in this case) next to the extensions depending on it (libzmq in this case). That's what matplotlib does. 

+1 for that - for the sake of novice users and Python newbies.

**Comment by minrk** [comment]
I built the 15.3 wheels on AppVeyor, which apparently doesn't do the same thing as my VM scripts that I used for 15.2 and earlier, which don't need this. For now, I'll pull the current 15.3 wheels and push new ones built the old way, which should solve the issue for now.

I'll see if I can fix the AppVeyor builds to use the correct MSVC like my manual scripts do.

**Comment by minrk** [comment]
I've pushed new 15.3 wheels for Windows, which should hopefully fix this while I figure out why the AppVeyor builds are using the wrong CRT before I make the next release.

**Comment by cgohlke** [comment]
`MSVCP140.DLL` and `VCRUNTIME140.DLL` are not the wrong CRT DLLs to use for extensions compiled with Visual Studio 2015 for CPython 3.5. It looks like the "fixed" pyzmq binaries were built with `DISTUTILS_USE_SDK` set, which statically links the CRT. See the [blog of Steve Dower](http://stevedower.id.au/blog/building-for-python-3-5-part-two/) why this is not a good idea. Note that the pyzmq binaries for CPython 2.7 and 3.4 also depend on compiler specific CRT DLLs, `MSVCR*.DLL` and `MSVCP*.DLL`.

**Comment by nonZero** [comment]
Please bump the version as well.

**Comment by minrk** [comment]
Thanks for the info, @cgohlke, I'll try to figure out what step is missing in the AppVeyor builds. For now, at least, the wheels work as they always have. 

@nonzero the Windows wheels have been bumped with a "local" version suffix according to the versioning pep. I'll do a 15.3.1 when I figure out the build fix.

**Comment by takluyver** [comment]
The conda-forge packages for pyzmq and matplotlib appear to have a similar issue, going by [failures on our Jenkins build](https://jenkins.jupyter.org/job/windows-multi/684/testReport/). I've gone back to the 'defaults' channel for now on Jenkins, which seems to make the tests pass.

**Comment by takluyver** [comment]
(Pinging @pelson in relation to that)

**Comment by pelson** [comment]
@takluyver - would you mind raising an issue at https://github.com/conda-forge/pyzmq-feedstock/issues? (and if necessary, the matplotlib feedstock also)

Thanks,

**Comment by takluyver** [comment]
Done:

* conda-forge/pyzmq-feedstock#9
* conda-forge/matplotlib-feedstock#47

**Comment by minrk** [comment]
@cgohlke where is the code that bundles the DLLs on Windows for matplotlib or another package? I can't seem to find it.

**Comment by cgohlke** [comment]
See https://github.com/matplotlib/matplotlib/pull/5348. It's up to the builder to copy required DLLs to the matplotlib directory as part of the build process, e.g.
```CMD
copy /Y /B "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\MSVCP140.DLL" lib\matplotlib\
copy /Y /B "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x64\Microsoft.VC140.CRT\CONCRT140.DLL" lib\matplotlib\
C:\Python35\python.exe setup.py bdist_wheel
del /S /Q lib\matplotlib\*.dll
```

**Comment by minrk** [comment]
So this is only done manually, there's no code anywhere that gets the right DLLs based on the current compiler?

**Comment by minrk** [comment]
#870 bundles MSVCP, CONCRT

**Comment by PolarNick239** [comment]
Hm, seems that it still depends on VS 2015 redist.

Steps to reproduce:
 - Launch clean Windows 7 without updates (or at least without ```KB2999226```)
 - Don't install python, but copy it from somewhere (already unpacked)
 - ```pip install pyzmq``` (15.4.0 or 16.0.2)
 - ```import zmq``` - fails

If you will install python with installer - it will also implicitly install VS 2015 redist (you could see ```KB2999226``` installed in ```Event Viewer```->```Windows Logs```->```Setup```).

I am writing this for two reasons:
 - May be bundling of DLLs has no effects, and so they should be removed?
 - Somebody like me may be want to bundle python embedded in their application, in such case I think the only way is to bundle VS 2015 redist with their application installer (keywords: merge module)
