### ISSUE TITLE
numpy array alignment issue with buffer/memoryview

### ISSUE THREAD

**Issue by bmcfee** [zeromq/pyzmq#864]
[documenting this after speaking with @minrk yesterday]

I'm hitting a problem with sending numpy ndarrays over zmq sockets without copying, and reconstructing them on the receiving side while maintaining alignment and contiguity.

In python 3 with `memoryview`, it works perfectly.

In python 2, `np.frombuffer` fails on `memoryview` (no `__buffer__` method), so I use `buffer` instead.  This fails to maintain alignment.

[This gist](https://gist.github.com/f4beb69e63a77b92d8fd3825949cb38d) implements a producer/consumer process and illustrates the failure or success under different kernels.

Is this just not possible in python 2?  Or should I not be using `np.frombuffer` for this at all?  Or is it a bug?

**Comment by minrk** [comment]
Closing some old issues since Python 2 support is dropped
