### ISSUE TITLE
ssh.select_random_ports keeps increasing size of _random_ports forever

### ISSUE THREAD

**Issue by donatwork** [zeromq/pyzmq#876]
I have an application that periodically calls ssh.tunnel_connection in a long running service and after a few days will hang due to a high CPU load on the threads that call tunnel_connection. I've traced the code and noticed that for every call to ssh.tunnel_connection the internal select_random_ports call adds a new socket to the internal set, _random_ports. Eventually I've seen that the set (python-2.7.9-14.1.x86_64) tops out at size 28228 and the calling threads go into a high CPU spin. I never see the set size decreasing nor where the list of unused local ports is cleaned up.

I'm currently using python-pyzmq-14.0.0-2.13.x86_64 distributed via SLES12 but I just checked the code in master and the problem seems to still be in master. 

I'd also like to know if the pyzmq library is thread safe.

The problem is easy to reproduce by either calling select_random_ports in a loop (one or more threads to speed things up) or calling the exported tunnel_connection to open a tunnel over a longer period of time.

**Comment by donatwork** [comment]
AA simpler solutions which has less housekeeping and still has the same risk as the kernel reusing a port as the current code is this:

```
def select_random_ports(n):
    """Selects and return n random ports that are available."""
    ports = []
    for i in range(n):
        sock = socket.socket()
        sock.bind(('', 0))
        ports.append(sock.getsockname()[1])
        sock.close()
    return ports
```
I've run simulations by calling this routine multiple thousands of times with multiple threads and the kernel will not immediately reuse the same port number.

**Comment by minrk** [comment]
I've removed the long-running port history in #877, which should fix this.

> I'd also like to know if the pyzmq library is thread safe.

In general, zmq sockets are not threadsafe, but zmq contexts are.
