### ISSUE TITLE
bundled stdint.h causes build to fail on 64-bit VS2010 compile

### ISSUE THREAD

**Issue by joachimmetz** [zeromq/pyzmq#885]
The bundled stdint.h (buildutils/include_win32/stdint.h) is preferred over the default stdint.h (due to the include path order) which causes a 64-bit VS2010 build to fail because uint8_t is not defined in include/zmq.h (since buildutils/include_win32/stdint.h is included and not the VS provided stdint.h).

**Comment by minrk** [comment]
Hm, I'm building pyzmq on every commit at appveyor, and it appears to be working properly on all tested versions of Python. What version of Python, and how did you install it (Python.org, anaconda, custom built, etc.)?

**Comment by joachimmetz** [comment]
Python 2.7.12 64-bit version from python.org, installed via MSI
Visual Studio Express 2010, with Windows 7 SDK

The issue is mainly with the default include header search path, manually removing buildutils/include_win32/stdint.h solves the issue for me. My suggestion would be not to ship stdint.h but have a pyzmq/libzmq specific that defines the missing types if stdint.h is missing e.g. https://github.com/libyal/libevtx/blob/master/include/libevtx/types.h.in

**Comment by minrk** [comment]
Python 2.7 must build either with the SDK or VS 2008, as I understand it. Does it build correctly if you do `set DISTUTILS_USE_SDK=1`?

**Comment by joachimmetz** [comment]
> Does it build correctly if you do set DISTUTILS_USE_SDK=1?

Makes no difference, build still fails.

**Comment by minrk** [comment]
I've verified that it does build correctly with DISTUTILS_USE_SDK=1 and the [Windows SDK 7](https://www.microsoft.com/en-us/download/details.aspx?id=8279) (not 7.1). VS2010 shouldn't be involved if building for Python 2.7, so if it is some configuration is amiss.

**Comment by joachimmetz** [comment]
Agree, the configuration issue is with the include path order, which you'll have no guarantee that it in the order you currently need it to be. Hence I would request not to have a solution that relies on the include path order, but have an approach that works without relying on it. Thanks in advance.

**Comment by minrk** [comment]
Windows builds have been greatly improved. This shouldn't be an issue anymore.
