### ISSUE TITLE
Make use of zmq.green.eventloop.IOLoop less baffling

### ISSUE THREAD

**Issue by chadrik** [zeromq/pyzmq#889]
I tried to use `zmq.green.eventloop.IOLoop` and could not figure out why `IOLoop.start` was blocking my other greenlets.  Here's the code I was using:

```python
import zmq.green as zmq
from zmq.green.eventloop.ioloop import IOLoop
from zmq.green.eventloop.zmqstream import ZMQStream

# server
context = zmq.Context()
server_socket = context.socket(zmq.PULL)
server_socket.connect("tcp://localhost:5560")
loop = IOLoop.current()

def serve():
    print "starting server loop"
    loop.start()

def other_task():
    print "starting other task"
    for i in range(10):
        print "running", i
        gevent.sleep(1)


server_thread = gevent.spawn(serve)
print "spawned server"
gevent.spawn(other_task).join()
print "spawned other"
```

It turns out that this was the problem:

```python
isinstance(zmq.green.eventloop.IOLoop.instance(), zmq.green.eventloop.IOLoop) is False
```

That is pretty confusing, to say the least. 

After some experimentation, I found that I have to call `IOLoop().install()` to ensure that the gevent-compatible `IOLoop` is used.  This was particularly confusing to me because I expected the singleton would be established the first time that I called `instance()` or `current()` and not prior to that.  i.e. if the first time that I call `instance()` is from `zmq.green.eventloop.IOLoop`, then I expect the singleton instance to be an instance of `zmq.green.eventloop.IOLoop`.  Moreover, I would expect an error if this was not the case.

It would be nice if some of the following existed:
- documentation on this
- an example of this
- a warning or error when the result of calling `.instance()` is not an instance of the class it's being called from.
- basing the `IOLoop` singleton on the class used the first time `instance()` or current()` is called.
- automatic installation of `zmq.green.eventloop.IOLoop` when importing `zmq.green`

Thanks!

**Comment by minrk** [comment]
#896 should fix this, add tests, and provide a warning in the no-longer-likely event of the class mismatch.

**Comment by minrk** [comment]
BTW, the tornado-idiomatic way to use a custom poll implementation would be:

```python
from tornado.ioloop import IOLoop
import zmq.green.eventloop.ioloop as green_ioloop
IOLoop.configure(green_ioloop.IOLoop)

loop = IOLoop.current()
```

That would not rely on zmq's implicit call to configure if you call `.instance` or `.current` on the subclasses.

**Comment by chadrik** [comment]
Thanks for the fast fix!
