### ISSUE TITLE
Returning a Future when using asyncio?

### ISSUE THREAD

**Issue by jo-sm** [zeromq/pyzmq#897]
Currently, there's no way to handle waiting for a connection in `zmq` when using the `asyncio` methods, which means the only semi-reliable way to wait until something has connected is to use `asyncio.sleep`. 

Is there any way to make `socket.connect` return a Future when using the `asyncio` code, so that you can `await` it?

**Comment by minrk** [comment]
There's nothing to await with connect, so no way to resolve that Future. As far as the zmq API is concerned, connect resolves immediately.

**Comment by jo-sm** [comment]
But couldn't you return from this method? https://github.com/zeromq/pyzmq/blob/master/zmq/backend/cython/socket.pyx#L527

**Comment by minrk** [comment]
That is what happens right now. `zmq_connect` has completed before `Socket.connect` returns. So if it returned a Future, it would be already resolved.

**Comment by jo-sm** [comment]
Ah I see, sorry for the issue!
