### ISSUE TITLE
Update setup.py for Cython 25

### ISSUE THREAD

**Issue by minrk** [zeromq/pyzmq#910]
build_ext is changing in Cython 25. #909 points to backward-compatible `old_build_ext` to keep master building, but we should be able to update setup.py to work with the new one.

**Comment by jdemeyer** [comment]
From https://github.com/cython/cython/pull/1456 it seems that Cython would welcome feedback about their new `build_ext`.

PS: Cython 0.25, not Cython 25

**Comment by jdemeyer** [comment]
FYI: Cython has just made an alpha version of the upcoming 0.25 release: https://pypi.python.org/pypi/Cython/0.25a0

I would be good to have a new pyzmq release before Cython 0.25 comes out.

**Comment by minrk** [comment]
I'll make sure to do that.

**Comment by minrk** [comment]
Released pyzmq 16, which works with Cython master.
