### ISSUE TITLE
pyzmq-16.0.0 fails to build on AIX: 1540-0274 (S) The name lookup for "SOCK_CLOEXEC" did not find a declaration.

### ISSUE THREAD

**Issue by aixtools** [zeromq/pyzmq#932]
This is using bundled libraries:
root@x064:[/data/prj/aixtools/saltstack/pyzmq-16.0.0]python setup.py configure
running configure

---

Using bundled libzmq
already have bundled/zeromq
already have platform.hpp

---

checking for timer_create
cc -c /tmp/timer_createnBNrdh.c -o build/temp.aix-5.3-2.7/tmp/timer_createnBNrdh.o
cc build/temp.aix-5.3-2.7/tmp/timer_createnBNrdh.o -o build/temp.aix-5.3-2.7/a.out
ok

---

root@x064:[/data/prj/aixtools/saltstack/pyzmq-16.0.0]pip list
pip (8.1.1)
setuptools (20.10.1)
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@x064:[/data/prj/aixtools/saltstack/pyzmq-16.0.0]python --version
Python 2.7.12

root@x064:[/data/prj/aixtools/saltstack/pyzmq-16.0.0]oslevel -r
5300-07
root@x064:[/data/prj/aixtools/saltstack/pyzmq-16.0.0]xlc -qversion
IBM XL C/C++ for AIX, V11.1 (5724-X13)
Version: 11.01.0000.0020

Final message:
xlc_r -I/opt/include -O3 -qmaxmem=-1 -qarch=pwr5 -q64 -I/opt/buildaix/includes -DNDEBUG -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_POLL=1 -Ibundled/zeromq/include -Ibundled/zeromq/tweetnacl/src -Ibundled/zeromq/tweetnacl/contrib/randombytes -Ibundled -I/opt/include -I/opt/include/python2.7 -c bundled/zeromq/src/ip.cpp -o build/temp.aix-5.3-2.7/bundled/zeromq/src/ip.o
"bundled/zeromq/src/ip.cpp", line 54.14: 1540-0274 (S) The name lookup for "SOCK_CLOEXEC" did not find a declaration.
error: command 'xlc_r' failed with exit status 1

Comments:
it does not seem to be any complaint about the source file ending in .cpp as several others compiled successfully.

On AIX 5.3 the command: "grep SOCK_ /usr/include/_.h /usr/include/sys/_.h" returns:
root@x064:[/data/prj/aixtools/saltstack/pyzmq-16.0.0]grep SOCK_ /usr/include/_.h
/usr/include/netdb.h:        int              ai_socktype;   /_ SOCK_xxx _/
root@x064:[/data/prj/aixtools/saltstack/pyzmq-16.0.0]grep SOCK_ /usr/include/_.h /usr/include/sys/_.h
/usr/include/netdb.h:        int              ai_socktype;   /_ SOCK_xxx _/
/usr/include/sys/aacct.h:#define TRP_LSOCK_IO   8
/usr/include/sys/aacct.h:#define TRP_RSOCK_IO   9
/usr/include/sys/atmsock.h:#ifndef H_ATMSOCK_H
/usr/include/sys/atmsock.h:#define H_ATMSOCK_H
/usr/include/sys/lockname.h:#define ATMSOCK_LOCK            450     /_ ATMSOC _/
/usr/include/sys/lockname.h:#define ATMSOCK_USRREQ_LOCK     451     /_ ATMSOC _/
/usr/include/sys/socket.h:#define SOCK_STREAM     1               /_ stream socket _/
/usr/include/sys/socket.h:#define SOCK_DGRAM      2               /_ datagram socket _/
/usr/include/sys/socket.h:#define SOCK_RAW        3               /_ raw-protocol interface _/
/usr/include/sys/socket.h:#define SOCK_RDM        4               /_ reliably-delivered message _/
/usr/include/sys/socket.h:#define SOCK_SEQPACKET  5               /_ sequenced packet stream _/
/usr/include/sys/socket.h:#define SOCK_CONN_DGRAM 6               /_ connection datagram */
/usr/include/sys/socketvar.h:#define FREE_SOCK_HASH_SZ 103
/usr/include/sys/socketvar.h:#define FREE_SOCK_HASH(so)      (((ulong)(so)) % FREE_SOCK_HASH_SZ)
/usr/include/sys/socketvar.h:#define FREE_SOCK_LOCK_INIT() {                                                                 \
/usr/include/sys/socketvar.h:        for (_free_sock_index = 0; _free_sock_index < FREE_SOCK_HASH_SZ; _free_sock_index++) {  \
/usr/include/sys/socketvar.h:#define FREE_SOCK_LOCK(index)   free_sock_hash_table[(index)].fsh_intrlvl =             \
/usr/include/sys/socketvar.h:#define FREE_SOCK_UNLOCK(index) unlock_enable(free_sock_hash_table[(index)].fsh_intrlvl,        \
/usr/include/sys/socketvar.h:#define FREE_SOCK_ISLOCKED(lp)  lock_mine(lp)
/usr/include/sys/socketvar.h:#define FREE_SOCK_ISLOCKED(lp)  1

On AIX 6.1 the same command returns:
michael@x071:[/home/michael]grep SOCK_ /usr/include/_.h /usr/include/sys/_.h
/usr/include/ha_emcommon.h:#define HA_EM_CL_TO_D_SOCK_FMT       "/var/ha/soc/em.clsrv.%s"
/usr/include/ha_emcommon.h:#define HA_EM_RM_TO_D_SOCK_FMT       "/var/ha/soc/em.rmsrv.%s"
/usr/include/ha_emcommon.h:#define HA_EM_D_TO_RM_SOCK_FMT       "/var/ha/soc/haem/em.RM%s.%d.%s"
/usr/include/ha_gs.h:    HA_GS_SOCK_CREATE_FAILED,           /\* 17 _/
/usr/include/ha_gs.h:    HA_GS_SOCK_INIT_FAILED,             /_ 18 _/
/usr/include/ha_gs.h:    HA_GS_WRITE_SOCK_ERROR              /_ 34 _/
/usr/include/netdb.h:        int              ai_socktype;   /_ SOCK_xxx _/
/usr/include/nim_interface.h:#define SOCK_PTR(a) (((a).addrtype == NIM_ADDR_TYPE_IPv4) ? \
/usr/include/nim_interface.h:#define SOCK_LEN(a) (((a).addrtype == NIM_ADDR_TYPE_IPv4) ? \
/usr/include/sys/aacct.h:#define TRP_LSOCK_IO   8
/usr/include/sys/aacct.h:#define TRP_RSOCK_IO   9
/usr/include/sys/atmsock.h:#ifndef H_ATMSOCK_H
/usr/include/sys/atmsock.h:#define H_ATMSOCK_H
/usr/include/sys/fdinfo.h:#define FDINFO_SOCK_DELETE            12
/usr/include/sys/fdinfo.h:#define FDINFO_USOCK_CONNECT          13
/usr/include/sys/fdinfo.h:#define FDINFO_USOCK_INFLT_GET                14
/usr/include/sys/fdinfo.h:#define FDINFO_USOCK_INFLT_PUT                15
/usr/include/sys/fdinfo.h:      FDTYPE_ISOCK_DGRAM,             /_ inet dgram socket    _/
/usr/include/sys/fdinfo.h:      FDTYPE_ISOCK_STREAM,            /_ inet stream socket   _/
/usr/include/sys/fdinfo.h:      FDTYPE_USOCK_DGRAM,             /_ unix dgram socket    _/
/usr/include/sys/fdinfo.h:      FDTYPE_USOCK_STREAM,            /_ unix stream socket   _/
/usr/include/sys/fdinfo.h:      FDTYPE_I6SOCK_DGRAM,            /_ inet6 dgram socket   _/
/usr/include/sys/fdinfo.h:      FDTYPE_I6SOCK_STREAM,           /_ inet6 stream socket  _/
/usr/include/sys/fdinfo.h:      FDTYPE_ISOCK_RAW,               /_ inet raw socket      _/
/usr/include/sys/fdinfo.h:      FDTYPE_I6SOCK_RAW,              /_ inet6 raw socket     _/
/usr/include/sys/lockname.h:#define ATMSOCK_LOCK            450     /_ ATMSOC _/
/usr/include/sys/lockname.h:#define ATMSOCK_USRREQ_LOCK     451     /_ ATMSOC _/
/usr/include/sys/sock_api.h:#ifndef _SOCK_API_H
/usr/include/sys/sock_api.h:#define _SOCK_API_H
/usr/include/sys/socket.h:#define SOCK_STREAM     1               /_ stream socket _/
/usr/include/sys/socket.h:#define SOCK_DGRAM      2               /_ datagram socket _/
/usr/include/sys/socket.h:#define SOCK_RAW        3               /_ raw-protocol interface _/
/usr/include/sys/socket.h:#define SOCK_RDM        4               /_ reliably-delivered message _/
/usr/include/sys/socket.h:#define SOCK_SEQPACKET  5               /_ sequenced packet stream _/
/usr/include/sys/socket.h:#define SOCK_CONN_DGRAM 6               /_ connection datagram */
/usr/include/sys/socketvar.h:#define FREE_SOCK_HASH_SZ 103
/usr/include/sys/socketvar.h:#define FREE_SOCK_HASH(so)      (((ulong)(so)) % FREE_SOCK_HASH_SZ)
/usr/include/sys/socketvar.h:#define FREE_SOCK_LOCK_INIT() {                                                                 \
/usr/include/sys/socketvar.h:        for (_free_sock_index = 0; _free_sock_index < FREE_SOCK_HASH_SZ; _free_sock_index++) {  \
/usr/include/sys/socketvar.h:#define FREE_SOCK_LOCK(index)   free_sock_hash_table[(index)].fsh_intrlvl =             \
/usr/include/sys/socketvar.h:#define FREE_SOCK_UNLOCK(index) unlock_enable(free_sock_hash_table[(index)].fsh_intrlvl,        \
/usr/include/sys/socketvar.h:#define FREE_SOCK_ISLOCKED(lp)  lock_mine(lp)
/usr/include/sys/socketvar.h:#define FREE_SOCK_ISLOCKED(lp)  1
/usr/include/sys/socketvar.h:#define soisrds(so)    ((so)->so_proto->pr_type == SOCK_SEQPACKET && \

So, I do not expect to find a solution by changing to AIX 6.1 (AIX 5.3 is chosen to support more platforms from one package).

**Comment by minrk** [comment]
The lookup for SOCK_CLOEXEC is no longer skipped when bundling libzmq, so this should work now.
