### ISSUE TITLE
Support curio

### ISSUE THREAD

**Issue by tcwalther** [zeromq/pyzmq#936]
Is support for the async library [curio](https://curio.readthedocs.io/en/latest/tutorial.html) present or planned in pyzmq?

**Comment by minrk** [comment]
I haven't planned on it, but I suspect it could be done.

**Comment by tcwalther** [comment]
Thank you for your swift reply, that's nice to hear. I'm currently using `asyncio` with pyzmq, and it's working okay. That being said, I (and other people) find the [learning curve for `asyncio` quite steep](http://lucumr.pocoo.org/2016/10/30/i-dont-understand-asyncio/), and a lot of people in the Python community seem to think that `curio` is a [cleaner and simpler approach](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/).

I don't know how much effort would be involved in adding support for curio, but it might be worth keeping it on your radar if curio keeps gaining momentum.

**Comment by minrk** [comment]
I've only learned recently about curio, and it sounds attractive.

I should say that pyzmq doesn't need to support it, one can always write a curio-compatible wrapper in a separate package as has been done in aiozmq. I can then merge it upstream if it seems standard enough, or just leave it as its own project.

**Comment by jkbbwr** [comment]
Bump. Is this still a possibility?

**Comment by minrk** [comment]
It's always a possibility, but I'm not planning to work on it soon. Integration with eventloops doesn't need to be done in pyzmq itself. It can always be done as a separate package (it's already that way effectively in pyzmq, they just happen to be bundled together). If anyone is interested in doing this, making a package that makes zmq sockets available to curio (following aiozmq's example) would be great.

**Comment by kawing-chiu** [comment]
It seems the author of curio has already written [a wrapper](https://github.com/dabeaz/curio/blob/master/curio/zmq.py) for pyzmq. Don't know whether it is finished or not.

**Comment by minrk** [comment]
Closing some old issues. I don't think this should be _in_ pyzmq, since it can be in an external package that extends FutureSocket.
