### ISSUE TITLE
question: 16.0.1

### ISSUE THREAD

**Issue by wesyoung** [zeromq/pyzmq#938]
curious if it'd be really hard to do a 16.0.1 release? i'm doing some work with czmq and zyre using pyzmq to re-cast sockets (via shadow) and running into some odd crash bugs, which i think are related to:

https://github.com/zeromq/pyzmq/commit/f37052960e1dc510ea2c1d2e69a32d727afa9d69

the work-around isn't too much of a stretch, just using pip to install pyzmq including that commit, but harder to release stuff into pypi that requires pyzmq>16.0

if the answer is "when we get to it" that's OK, figured i'd ask... thanks for all you do!

**Comment by minrk** [comment]
Yes, I hope to do it this week.

**Comment by wesyoung** [comment]
cool beans. if there's anything you need help with, let me know. appreciate it!

**Comment by wesyoung** [comment]
so, it appears that there's still an issue buried within libzmq 4.1.6, 16.0.1+4.1.5 works OK, soon as you go to 4.1.6, something aborts somewhere...

```
$ zyre-chat -i eth1
2016-11-14 12:40:22,617 - INFO - root[30] - setting up node: Bianca Shone
2016-11-14 12:40:22,617 - INFO - root[70] - staring node...
2016-11-14 12:40:22,618 - INFO - root[73] - joining: ZYRE
Socket operation on non-socket (src/signaler.cpp:301)
Aborted (core dumped)
```

i'm gonna dig around a little, but i guess it might have more to do with libzmq than pyzmq at this stage... (technically speaking).

fwiw...

**Comment by wesyoung** [comment]
actually; i think it might be because the pyzmq-16.0.1-cp27-cp27mu-manylinux1_x86_64.whl wheel doesn't appear to contain a pre-built libzmq.so object? but does have .libs/libzmq-feeff037.so.5.0.1 ? which seems to function OK in and of itself... but not when you're trying to do more "shadow" like stuff... does this make sense?

**Comment by minrk** [comment]
Do you have some code to reproduce issues? It could have to do with the bundled libzmq in that maybe multiple libzmqs are getting loaded? The manylinux 16.0.1 wheels still include 4.1.5 unlike OS X / Windows, because I forgot to update them.

Can you try installing with `--no-binary pyzmq` to skip the wheel?

**Comment by wesyoung** [comment]
```
$ pip install pyzyre
$ zyre-chat -i eth0 -d
````

(i'm taking czmq sockets and shadowing them as pyzmq sockets, easier to work with atm)

https://github.com/wesyoung/pyzyre/blob/master/pyzyre/chat.py#L162

if i build and install pyzmq locally with pip (after you install pyzyre):

```
$ pip install https://github.com/zeromq/pyzmq/archive/f37052960e1dc510ea2c1d2e69a32d727afa9d69.tar.gz#egg=pyzmq>16.0.1
```

everything works kosher (because it's building the binary from scratch and embedding it as zmq/libzmq.so).

*HOWEVER* pyzyre also builds it's own version of czmq/libzmq.so and embeds it (the same way pyzmq does, thanks for that btw!) along with czmq/libczmq.so and zyre/libzyre.so (the zproject generated ctypes auto figure this out and loads it properly). so i'm wondering if what's found in .lib via the wheel is colliding with libzmq.so in czmq/libzmq.so ? but when it's compiled from scratch as zmq/libzmq.so it loads ok? 

if you ```pip install pyzyre``` you'll see czmq, zyre directories in the python packages path along with the embedded .so files..

does that make sense?

**Comment by minrk** [comment]
I bet that's it. I'll need to dig into how the manylinux stuff is working, but I'm guessing the two bundled libzmqs have a different name, which is what allows both to load and get confused. If they had the same name, I think only one would load. But that could be completely wrong.

@matthew-brett do you recall exactly what we need to do for two libraries to bundle the same DLL and be happy? This is Linux using a manylinux wheel that pulls in libzmq.

**Comment by matthew-brett** [comment]
I'm sorry, I'm not a Linux link expert - paging @njs.

The auditwheel tool renames the built library by appending some characters from the hash of the library, or order to make it unique - hence (above) `.libs/libzmq-feeff037.so.5.0.1 `.  Your question is whether loading this library, and another with the same symbols, is going to cause a clash.

**Comment by wesyoung** [comment]
i can do more digging two, sounds like i'm headed down the right path. worst-case i can probably bundle pyzmq in with pyzyre and manipulate things from there (which is ok too). since the symbol's are already being loaded, i'd probably only need the python code..
