### ISSUE TITLE
How to use more io_threads in device

### ISSUE THREAD

**Issue by xvsfekcn** [zeromq/pyzmq#939]
I want use more io_threads number in the device, How can i set the io_threads params in ProcessDevice or ThreadDevice, thanks

**Comment by minrk** [comment]
Sorry for missing this ancient question, but `Device` has a `context_factory` attribute, which is `zmq.Context.instance` by default.

This can be any callable that returns a context, e.g.

```python
dev = ProcessDevice()
...
def context_with_threads():
    return zmq.Context(io_threads=5)

dev.context_factory = context_with_threads
dev.start()
