### ISSUE TITLE
requires tornado >= 4.0

### ISSUE THREAD

**Issue by mrvn** [zeromq/pyzmq#945]
zmq/eventloop/future.py uses ZMQIOLoop.call_later, which was only added in tornado 4.0.

Would be nice to fall back to ZMQIOLoop.add_timeout for tornado < 4.0.

**Comment by mrvn** [comment]
I'm working from the Debian source so I can't just send a pull request but here is the diff I use to work around this issue:

<pre>
--- pyzmq-15.4.0.orig/zmq/eventloop/ioloop.py
+++ pyzmq-15.4.0/zmq/eventloop/ioloop.py
@@ -175,6 +175,16 @@ if (3, 0) <= tornado_version < (3, 1):
         return mini_loop.close.__get__(self)(all_fds)
     ZMQIOLoop.close = backport_close

+if (3, 0) <= tornado_version < (4, 0):
+    def backport_call_later(self, delay, callback, *args, **kwargs):
+        """backport IOLoop.call_later to 3.0 from 4.0"""
+        return self.call_at(self.time() + delay, callback, *args, **kwargs)
+    ZMQIOLoop.call_later = backport_call_later
+
+    def backport_call_at(self, when, callback, *args, **kwargs):
+        """backport IOLoop.call_at to 3.0 from 4.0"""
+        return self.add_timeout(when, callback, *args, **kwargs)
+    ZMQIOLoop.call_at = backport_call_at

 # public API name
 IOLoop = ZMQIOLoop
</pre>

**Comment by minrk** [comment]
I'm more inclined to put an explicit check that requires actual tornado 4.0 in `zmq.eventloop.future`. Would that work for you?

**Comment by mrvn** [comment]
If it falls back to the minitornado in that case then that's fine for me.

**Comment by mrvn** [comment]
As a side node: With tornado 4.x and the above patch some tests still fail but work without patch. Is the `if (3, 0) <= tornado_version < (4, 0)` actually working to detect a tornado version between the two limits? Or does it simply always use the backport? (Asking because of backport_close)
