### ISSUE TITLE
A great run-time problem of pyzmq 16.0.0 on CentOS 6

### ISSUE THREAD

**Issue by rhuab** [zeromq/pyzmq#946]
First I type "pip install pyzmq==16.0.0 "(pip version is 9.0.1) and pip tells me pyzmq is successfully installed.
Second when I try to run my python script I would get a run-time error as following:
 
```
File "/root/.local/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/root/.local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/root/.local/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/root/.local/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/root/.local/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /root/.local/lib/python2.7/site-packages/zmq/backend/cython/error.so: undefined symbol: zmq_strerror
```

I thought I did not install libzmq-devel but after I installed it the problem still exists.
BTW, on Ubuntu 12.04 and Ubuntu 14.04 pip install pyzmq==16.0.0 can successfully install pyzmq and no run-time error. Also on Ubuntu when I type "pip install pyzmq==16.0.0 --only-binary :all:" , pip will download a .whl file first and install pyzmq successfully but on CentOS "pip install pyzmq==16.0.0 --only-binary :all:" will tell me "no matching distributions" something like that. It seems that pyzmq 16.0.0 does not have a binary distribution on CentOS.

**Comment by minrk** [comment]
There is no separate binary for CentOS, it should use the same wheels as any Linux, but even so, it should work if it's compiling itself. There were some changes in 16.x for how it builds, and that's probably related.

What do you get from:

    python -c 'import pprint,pip.pep425tags; pprint.pprint(pip.pep425tags.get_supported())'

**Comment by rhuab** [comment]
When I type 'pip install pyzmq' or 'pip download pyzmq' on CentOS 6, no matter what version it is I always get a .tar.gz file not a .whl file I get on Ubuntu. Moreover when I type 'pip install pyzmq==16.x' (the newset version is 16.0.2) pip would tell me installation is successful but I still get a run-time error that I mentioned before.
And I type the code you suggested in the terminal I got following info:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pip.pep425tags

The version I install is 16.0.2.

**Comment by minrk** [comment]
Oh, I thought you had pip 9.0.1, which has this module. What do you get from `pip --version` and `which -a pip`?

**Comment by rhuab** [comment]
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

/usr/local/bin/pip

**Comment by minrk** [comment]
That's odd, because pip 9.0.1 does have this module, so `import pip` doesn't appear to be giving you pip 9. What's `head -n 1 $(which pip)` and `which -a python`?

**Comment by rhuab** [comment]
#!/usr/local/bin/python2.7

/usr/bin/python

**Comment by minrk** [comment]
And `ls /usr/local/lib/python2.7/site-packages/pip`?

**Comment by rhuab** [comment]
basecommand.py   compat          __init__.py    operations        vcs
basecommand.pyc  download.py     __init__.pyc   pep425tags.py     _vendor
baseparser.py    download.pyc    locations.py   pep425tags.pyc    wheel.py
baseparser.pyc   exceptions.py   locations.pyc  req               wheel.pyc
cmdoptions.py    exceptions.pyc  __main__.py    status_codes.py
cmdoptions.pyc   index.py        __main__.pyc   status_codes.pyc
commands         index.pyc       models         utils

**Comment by minrk** [comment]
Weird, so you do have `pip.pep425tags`, but can't import it? Can you try importing it again and showing `pep425tags.get_supported()`? If import fails again, double-check `pip.__file__`.

**Comment by rhuab** [comment]
I miss an important detail: 'python' in my CentOS refers to /usr/bin/python2.4 and my python2.7 is installed in /usr/local/bin and my pip is based on python2.7 so I type the following commands and the result is:
python2.7 -c 'import pprint,pip.pep425tags; pprint.pprint(pip.pep425tags.get_supported())'
[('cp27', 'cp27m', 'manylinux1_x86_64'),
 ('cp27', 'cp27m', 'linux_x86_64'),
 ('cp27', 'none', 'manylinux1_x86_64'),
 ('cp27', 'none', 'linux_x86_64'),
 ('py2', 'none', 'manylinux1_x86_64'),
 ('py2', 'none', 'linux_x86_64'),
 ('cp27', 'none', 'any'),
 ('cp2', 'none', 'any'),
 ('py27', 'none', 'any'),
 ('py2', 'none', 'any'),
 ('py26', 'none', 'any'),
 ('py25', 'none', 'any'),
 ('py24', 'none', 'any'),
 ('py23', 'none', 'any'),
 ('py22', 'none', 'any'),
 ('py21', 'none', 'any'),
 ('py20', 'none', 'any')]
[root@12838f5ced08 /]# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
[root@12838f5ced08 /]# which -a pip
/usr/local/bin/pip
[root@12838f5ced08 /]# head -n 1 $(which pip)
#!/usr/local/bin/python2.7
[root@12838f5ced08 /]# which -a python
/usr/bin/python
[root@12838f5ced08 /]# which -a python2.7
/usr/local/bin/python2.7
[root@12838f5ced08 /]#  ls /usr/local/lib/python2.7/site-packages/pip 
basecommand.py   compat          __init__.py    operations        vcs
basecommand.pyc  download.py     __init__.pyc   pep425tags.py     _vendor
baseparser.py    download.pyc    locations.py   pep425tags.pyc    wheel.py
baseparser.pyc   exceptions.py   locations.pyc  req               wheel.pyc
cmdoptions.py    exceptions.pyc  __main__.py    status_codes.py
cmdoptions.pyc   index.py        __main__.pyc   status_codes.pyc
commands         index.pyc       models         utils

**Comment by minrk** [comment]
Aha. From reading the [manylinux doc](https://github.com/pypa/manylinux), I've only made 'wide' pyzmq wheels for py27 (`cp27mu`), while your Python is 'narrow' (`cp27m`), so the existing wheels are rightly rejected.

How did you install Python? I'm trying to reproduce the error, but I can't seem to get anything to not work. What do you see in `ls -l /root/.local/lib/python2.7/site-packages/zmq/`?

I've tried [this Dockerfile](https://gist.github.com/ca8c3407a1ab33bdbb9d84ed23294f26), but can't get it to misbehave. Can you tell if libzmq was found on the system or bundled in pyzmq? pyzmq prints this quite verbosely, but pip generally hides all output of successful installations. You can see it with `pip install -v pyzmq`.

**Comment by rhuab** [comment]
First I type 'pip install -v pyzmq' and the result is in the attachment.
Second I type  'ls -l /root/.local/lib/python2.7/site-packages/zmq/' and the result is no such directory because pyzmq is not installed with --user, so I uninstall pyzmq and 'pip install --user pyzmq' and ls again:
[root@92d701f5343c setuptools-1.4.2]#  ls -l /root/.local/lib/python2.7/site-packages/zmq/
total 6472
drwxr-xr-x 2 root root    4096 Nov 29 13:12 auth
drwxr-xr-x 4 root root    4096 Nov 29 13:12 backend
-rw-r--r-- 1 root root    5242 Nov 29 13:12 decorators.py
-rw-r--r-- 1 root root    6275 Nov 29 13:12 decorators.pyc
drwxr-xr-x 2 root root    4096 Nov 29 13:12 devices
-rw-r--r-- 1 root root    5268 Nov 29 13:12 error.py
-rw-r--r-- 1 root root    7038 Nov 29 13:12 error.pyc
drwxr-xr-x 3 root root    4096 Nov 29 13:12 eventloop
drwxr-xr-x 3 root root    4096 Nov 29 13:12 green
drwxr-xr-x 2 root root    4096 Nov 29 13:12 include
-rw-r--r-- 1 root root    1851 Nov 29 13:12 __init__.py
-rw-r--r-- 1 root root    2140 Nov 29 13:12 __init__.pyc
-rwxr-xr-x 1 root root 6537472 Nov 29 13:12 libzmq.so
drwxr-xr-x 2 root root    4096 Nov 29 13:12 log
drwxr-xr-x 2 root root    4096 Nov 29 13:12 ssh
drwxr-xr-x 2 root root    4096 Nov 29 13:12 sugar
drwxr-xr-x 2 root root    4096 Nov 29 13:12 tests
drwxr-xr-x 2 root root    4096 Nov 29 13:12 utils
[a.txt](https://github.com/zeromq/pyzmq/files/619048/a.txt)

**Comment by andre-merzky** [comment]
FWIW, I also stumble over this problem, on Titan@ORNL.  The compute nodes show:

```
$ python -c 'import pprint,pip.pep425tags; pprint.pprint(pip.pep425tags.get_supported())'

[('cp27', 'cp27m', 'manylinux1_x86_64'),
 ('cp27', 'cp27m', 'linux_x86_64'),
 ('cp27', 'none', 'manylinux1_x86_64'),
 ('cp27', 'none', 'linux_x86_64'),
 ('py2', 'none', 'manylinux1_x86_64'),
 ('py2', 'none', 'linux_x86_64'),
 ('cp27', 'none', 'any'),
 ('cp2', 'none', 'any'),
 ('py27', 'none', 'any'),
 ('py2', 'none', 'any'),
 ('py26', 'none', 'any'),
 ('py25', 'none', 'any'),
 ('py24', 'none', 'any'),
 ('py23', 'none', 'any'),
 ('py22', 'none', 'any'),
 ('py21', 'none', 'any'),
 ('py20', 'none', 'any')]
```

and a naive `pip install pyzmq` results in an unusable module

```
$ python -c 'import zmq'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve.ornl.titan_aprun.0.46/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve.ornl.titan_aprun.0.46/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve.ornl.titan_aprun.0.46/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve.ornl.titan_aprun.0.46/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve.ornl.titan_aprun.0.46/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /lustre/atlas2/csc230/scratch/merzky1/radical.pilot.sandbox/ve.ornl.titan_aprun.0.46/lib/python2.7/site-packages/zmq/backend/cython/error.so: undefined symbol: zmq_strerror
```

Advice would be appreciated.
Thanks, Andre.

**Comment by sPyOpenSource** [comment]
I have the same problem. I'm running on docker alphine. $ python -c 'import pprint,pip.pep425tags; pprint.pprint(pip.pep425tags.get_supported())' show:
`[('cp27', 'cp27mu', 'linux_x86_64'),
 ('cp27', 'none', 'linux_x86_64'),
 ('py2', 'none', 'linux_x86_64'),
 ('cp27', 'none', 'any'),
 ('cp2', 'none', 'any'),
 ('py27', 'none', 'any'),
 ('py2', 'none', 'any'),
 ('py26', 'none', 'any'),
 ('py25', 'none', 'any'),
 ('py24', 'none', 'any'),
 ('py23', 'none', 'any'),
 ('py22', 'none', 'any'),
 ('py21', 'none', 'any'),
 ('py20', 'none', 'any')]`

**Comment by andre-merzky** [comment]
We meanwhile found a workaround on Titan: `export LD_PRELOAD=/lib64/librt.so.1`.  I have no idea how that would translate to other environments...

**Comment by sPyOpenSource** [comment]
The problem is that I have removed g++ package after install pyzmq. Therefore librt.so.1 is gone in my docker container. I fixed this problem by reinstall g++ package. Thanks andre-merzky.
