### ISSUE TITLE
keepalive settings should default to OS defaults

### ISSUE THREAD

**Issue by moio** [zeromq/pyzmq#948]
According to [the zeromq API](http://api.zeromq.org/3-2:zmq-setsockopt#toc25) keepalive settings should default to the OS defaults if they are not explicitly set.

This does not seem to be the case at least with my configuration as not setting any keepalive option results in a socket with keepalive turned off, instead of the Linux default of 7200 seconds.

This [small reproducer](https://gist.github.com/moio/13030dbf575f998cdd6bcc430da6c4fe) opens a socket, outputs the value of `TCP_KEEPALIVE` and then checks the actual keepalive status via `netstat`. It is expected to be `on` both with and without setting `TCP_KEEPALIVE`, but actually it is `off` unless such option is specified:

```
# python keepalive_test.py 
libzmq-4.0.4
pyzmq-14.0.0
Python-2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
TCP_KEEPALIVE value: -1
tcp        0      0 proxy.tf.local:54796    suma3pg.tf.local:4505   ESTABLISHED root       36862      7687/python         off (0.00/0/0)
TCP_KEEPALIVE value: 300
tcp        0     28 proxy.tf.local:54797    suma3pg.tf.local:4505   ESTABLISHED root       36949      7687/python         on (0,19/0/0)
```

I am not sure whether this is a pyzmq bug or a generic libzmq issue - I apologize in advance in the latter case as I am not able to determine it myself at this point.

Thanks in advance!

**Comment by minrk** [comment]
pyzmq doesn't touch any of these things itself, so it sounds like a libzmq issue to me. You might also check with the latest libzmq-4.1.6 and/or 4.2.0, since it might be fixed already.
