### ISSUE TITLE
Is there support for socket option `ZMQ_CONNECT_TIMEOUT` from libzmq 4.2.0?

### ISSUE THREAD

**Issue by dougthor42** [zeromq/pyzmq#949]
I'm sure this is already being worked on. When can we expect a release that's bundled with libzmq 4.2.0 and all the nice socket options that go along with it?

I'm most interested in `ZMQ_CONNECT_TIMEOUT` myself.

Thanks,

**Comment by jimrthy** [comment]
Along these same lines, has anyone started thinking about supporting the new socket types? (Thinking "let's wait until the API is settled and they're no longer DRAFT" seems like a perfectly reasonable answer, although I'd really like access to CLISRV). Thanks!

**Comment by minrk** [comment]
If build with DRAFT_API enabled, all of 4.2.0 draft APIs should already be supported in pyzmq 16.

**Comment by minrk** [comment]
options like this work in pzymq 16 if `ZMQ_BUILD_DRAFT_API` is defined and easier to expose in pyzmq 17 with `--enable-drafts`
