### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. in python 3.6.0

### ISSUE THREAD

**Issue by INFINI7** [zeromq/pyzmq#954]
when i pip install pyzmq, it showed that error. but it's perfect in python 3.5.2.
how can I install it? or could u fix it with a update?
Thanks very much. Waiting for answer

**Comment by minrk** [comment]
I need to upload wheels for Python 3.6, but haven't yet. I will do it this week.

**Comment by minrk** [comment]
I've uploaded the 3.6 wheels, so it should work, now.

**Comment by Sarmed-armis** [comment]
hi guys, i had same issue  when install mysql-python module 
kindly, to share the solution here .
