### ISSUE TITLE
Tornado Context keeps old IOLoop

### ISSUE THREAD

**Issue by pitrou** [zeromq/pyzmq#962]
The Tornado `Context` class stores the IOLoop current instance at the time of instantiation, and then forces all sockets to use that loop. This breaks any use where the current loop is closed and replaced with another one (it's common to have a distinct IO loop per unit test, for example).

**Comment by minrk** [comment]
Indeed it does. Contexts are a bit like IOLoops in that way, and are also generally cleaned up after each unit test as well.
