### ISSUE TITLE
asyncio: memory leak when events never arrive

### ISSUE THREAD

**Issue by RojavaCrypto** [zeromq/pyzmq#968]
Installed using `pip3 install pyzmq`, at latest version of 16.0.2 on Ubuntu 16.04.

Running this script just consumes more and more memory indefinitely:

```
import asyncio
import zmq
import zmq.asyncio

loop = zmq.asyncio.ZMQEventLoop()
asyncio.set_event_loop(loop)

async def main():
    context = zmq.asyncio.Context()
    socket = context.socket(zmq.DEALER)
    socket.connect("tcp://localhost:8181")

    poller = zmq.asyncio.Poller()
    poller.register(socket, zmq.POLLIN)

    while True:
        events = await poller.poll(timeout=0.1)
        for socket, mask in events:
            print("foo")

    loop.create_task(poll())

if __name__ == '__main__':
    loop.run_until_complete(main())
```

After a short time:
```
$ pdb3.5 async_test.py
> /.../async_test.py(1)<module>()
-> import asyncio
(Pdb) r
<CTRL-C>
(Pdb) import objgraph
(Pdb) objgraph.show_most_common_types(limit=20)
dict                       117798
list                       116306
Future                     115773
_FutureEvent               115773
function                   4464
tuple                      2039
weakref                    1213
wrapper_descriptor         1146
method_descriptor          953
builtin_function_or_method 930
getset_descriptor          734
type                       599
set                        427
member_descriptor          367
property                   260
module                     236
ModuleSpec                 233
SourceFileLoader           171
WeakSet                    168
classmethod                123
```

After 2 minutes, memory consumption is now ~650+ Mb.
```
dict                       854641
list                       853144
Future                     852619
_FutureEvent               852619
function                   4464
tuple                      1829
weakref                    1213
wrapper_descriptor         1146
method_descriptor          953
builtin_function_or_method 930
getset_descriptor          734
type                       599
set                        427
member_descriptor          367
property                   260
module                     236
ModuleSpec                 233
SourceFileLoader           171
WeakSet                    168
classmethod                123
```

```
(Pdb) obj = objgraph.by_type('_FutureEvent')[0]
(Pdb) objgraph.show_backrefs([obj], max_depth=10)
```

This seems to be the main culprit (the 850k references to ZMQEventLoop).

![selection_002](https://cloud.githubusercontent.com/assets/19536664/21888380/ee934106-d8bb-11e6-9be3-e5a775637e48.png)

If I query those leaked dicts with `random.choice(objgraph.by_type('dict'))` then I get `{'_loop': <ZMQEventLoop running=False closed=False debug=False>, '_log_traceback': False, '_result': None, '_state': 'FINISHED', '_callbacks': []}` every single time.

**Comment by RojavaCrypto** [comment]
I think that in `eventloop/future.py`, `_AsyncSocket._recv_futures` is expanding indefinitely.

**Comment by RojavaCrypto** [comment]
Funny enough I forgot to await the `recv()` call in this code and also the memory keeps increasing, but the dicts are different.
```
import asyncio
import zmq
import zmq.asyncio

loop = zmq.asyncio.ZMQEventLoop()
asyncio.set_event_loop(loop)

async def main():
    context = zmq.asyncio.Context()
    socket = context.socket(zmq.DEALER)
    socket.connect("tcp://localhost:8181")

    while True:
        socket.recv()

if __name__ == '__main__':
    loop.run_until_complete(main())
```

The dicts are `{'_callbacks': [], '_loop': <ZMQEventLoop running=False closed=False debug=False>}` instead.

**Comment by minrk** [comment]
> I think that in eventloop/future.py, _AsyncSocket._recv_futures is expanding indefinitely.

Exactly right - the recv_futures would get cleaned up if any recv event ever arrived, but since no recv event ever arrives, the cleanup never happens. #969 fixes that.

The latter example with missing awaits *should* leak, as it's allocating and never awaiting Futures that will never resolve. Constantly allocating and storing those Futures seems like the expected behavior there.

**Comment by RojavaCrypto** [comment]
Thank you for this bug fix and your work in general.
