### ISSUE TITLE
inproc on Windows fails with some patterns

### ISSUE THREAD

**Issue by chancyk** [zeromq/pyzmq#971]
The `inproc://` transport seems to not work on Windows with some patterns, for instance in [this threaded version](https://gist.github.com/chancyk/41f1028cb444a9ffed404c5fc9fe33c3) of the lbbroker example found in the ZeroMQ guide [here](http://zguide.zeromq.org/py:lbbroker). Uncommeting line 14 in that gist will switch to the `inproc://` transport, which just blocks indefinitely for me. The TCP version works fine.

However the [serial socket](https://github.com/zeromq/pyzmq/blob/d7e1b867f87eac7aff7b24b90bc48a7fcaa40ad2/examples/serialization/serialsocket.py) example included with PyZMQ works fine with `inproc://`.

Windows 7 64-bit
Python 3.5.2 64-bit
PyZMQ 16.0.2

**Comment by minrk** [comment]
closing as not a pyzmq issue. Anything to do with transports and platforms would be a libzmq question.
