### ISSUE TITLE
assert when running the test suite on windows

### ISSUE THREAD

**Issue by cournape** [zeromq/pyzmq#972]
I noticed this w/ our pyzmq build on windows, and can reproduce it w/ Gholke wheels:

* python 2.7.12 from python.org
* pyzmq 16.0.2 from gholke webiste
* run the tests with the latest pytest

The crash happens within the `test_large_send` in `test_socket.py`:

``` bash
$ pytest ...site-packages\zmq -vs
...
test_large_send: Assertion failed: No Buffer space available (bundle/zeromq/src/tcp.cpp:176)
```

Let me know if there is something we can do to help

**Comment by minrk** [comment]
closing some old issues. Tests seem more reliable on Windows now.
