### ISSUE TITLE
Numerous crashes when running the test suite on windows for python 3.6

### ISSUE THREAD

**Issue by cournape** [zeromq/pyzmq#973]
I am seeing crashes when running the test suite on python 3.6 for pyzmq 16.0.2.

While I can reproduce the crashes almost every time, unfortunately, the crash location is not always the same. I have been able to reproduce the crash fairly regularly in test_context:test_destroy if I only run tests for test_auth.py and test_context.py.

I see that appveyor does not run tests at all ATM. Would you be interested in PRs that blacklist test failing on windows ?

**Comment by minrk** [comment]
> I see that appveyor does not run tests at all ATM. Would you be interested in PRs that blacklist test failing on windows ?

Absolutely! Maybe start with just context and socket tests.
