### ISSUE TITLE
router to one dealer will appear mutil connect

### ISSUE THREAD

**Issue by bill68551632** [zeromq/pyzmq#977]
server  router poll              debian8 pyzmq14.7.0
client   delear   connect    win7       pyzmq14.7.0
for example
server 192.168.1.10
client   192.168.1.100

first   server client have one connect,
192.168.1.10:192.168.1.100:52980
all run normal
for quite a time，router server will appear to two connect，debian netstat
192.168.1.10:192.168.1.100:52980
192.168.1.10:192.168.1.100:54680
 
but delear client ，win7 netstat
192.168.1.10:192.168.1.100:54680

router server listen the connect is
192.168.1.10:192.168.1.100:52980
only process this connect，but client not send as 52980，send use 54680，have problem

i do not know why? i do not known how to slove this problem

**Comment by minrk** [comment]
Is it a problem? What are the consequences of a reconnect? There generally isn't anything pyzmq can do about underlying libzmq behavior.

**Comment by bill68551632** [comment]
after a reconnect，the  router  can not respond to the new connect，respond to the old connect，but client  only have new connect.  how to use the router？is the libzmq reconnect problem？

**Comment by minrk** [comment]
zmq generally attempts to hide connect events, so reconnects shouldn't be an issue.

**Comment by bill68551632** [comment]
the github can not upload the cut picture,  I copy the problem content,  
tcp        0      0 172.16.21.56:6905       192.168.33.54:63805     ESTABLISHED -
tcp        0      0 172.16.21.56:6905       192.168.33.54:49176     ESTABLISHED -

router server 6905, client delear  have only one connect
when I use pyzmq，have this problem，
can you help me to rosolve?

**Comment by minrk** [comment]
Do you have test code that shows the problem? Generally libzmq hides reconnects, so they shouldn't be noticed by application code at all.

**Comment by bill68551632** [comment]
to the router, I set ZMQ_ROUTER_HANDOVER to 1

that is ok,   thank you for your answer!
