### ISSUE TITLE
Does this package support Python 3?

### ISSUE THREAD

**Issue by cclauss** [zeromq/pyzmq#982]
On 19 February 2017, Python 3 will be 3,000 days old!  We are interested to see if we can get **at least 50%** of the [Top 5,000 PyPI packages](http://python3wos.mybluemix.net/5000) to compatible with Python 3 by that date.  We are *really* close and given that this package is in the PyPI Top 5,000, we seek your assistance in pushing us over that threshold.

  So, if this package *already supports Python 3* then please consider adding an appropriate [trove classifier](https://pypi.python.org/pypi?%3Aaction=list_classifiers) "*Programming Language :: Python :: 3*" to this package's PyPI page so that tools can automaticly determine its Python 3 compatibility.

**Comment by minrk** [comment]
Yes, this package does support Python 3 and does have the Python 3 trove classifier, and has since early 2011. If these messages are automated, it might be worth double-checking the criteria.

**Comment by cclauss** [comment]
You are correct @minrk ...  I got messed up by https://pypi.python.org/pypi/pyzmq-static
