### ISSUE TITLE
Running zmq.SUB in multiprocessing.Process

### ISSUE THREAD

**Issue by cubranic** [zeromq/pyzmq#983]
I have come across a strange behaviour when I create a zmq.SUB listener socket (i.e., `socket.bind`) from multiprocessing.Process. The subprocess receives messages fine, but when it ends and closes the socket, and I then start another Process from the same Python session, the second instance doesn’t receive any messages from clients. It binds to the socket,  starts listening and is even shown by `netstat` as owning the socket, but it never returns from `socket.recv`. 

This happens on both Linux and OSX, Python 2.7 and 3.6, and with both ipc and TCP sockets.

Pyzmq 16.0.2 and zmq 4.1.6.

Code to reproduce:

```python
import os
import zmq
import time
from multiprocessing import Process as Process

addr = 'tcp://127.0.0.1:2344'
# addr = 'ipc://foo'
# addr = 'ipc://@foo'
def server(addr):
    print("Start server")
    print('parent process: %d' % os.getppid())
    print('process id: %d' % os.getpid())
    context = zmq.Context.instance()
    sub = context.socket(zmq.SUB)
    sub.linger = 0
    sub.subscribe('')
    sub.bind(addr)
    time.sleep(.1)
    print(sub.recv())
    sub.close()
    print("Server done")

def client(addr, msg):
    print("Start client")
    context = zmq.Context.instance()
    sub = context.socket(zmq.PUB)
    sub.linger = 0
    sub.connect(addr)
    print("Connected...")
    time.sleep(1)
    sub.send(msg)
    print("Closing client...")
    sub.close()

listener = Process(target = server, args = (addr, ))
listener.start()
time.sleep(.2)

client(addr, b"hello there!")
listener.join()
time.sleep(3)

print("Start again")
listener = Process(target = server, args = (addr, ))
listener.start()
time.sleep(.2)

client(addr, b"hello again!")

listener.join()
print("Done")
```

**Comment by GarlandM** [comment]
Did you ever solve this? Having a similar issue.

**Comment by cubranic** [comment]
IIRC, I had to create a new `Context` instead of using the `Context.instance()` for the subprocess (here, in the `server` function).

**Comment by minrk** [comment]
Yup, zmq Contexts and Sockets cannot be used across the fork boundary. You must create new Contexts when creating new processes.

**Comment by cubranic** [comment]
I think this issue can be closed then.

**Comment by bytesofmyself** [comment]
Woo, thank you. 

Could not understand why recv() was hanging in Linux but not Windows in my multiprocessing code. Switching Context.instance() to Context() did the job. Using Python 2.7.14 and 16.0.4

Presumably this is due to the different natures of python multiprocessing on different platforms, forking (linux) vs spawning (win).  My existing logging objects worked without any extra hassle in Linux but are alive yet inert in Windows, which makes some sense because Linux does allow some shared resource space while Windows does not.
