### ISSUE TITLE
How to set socket options `ZMQ_HEARTBEAT_IVL`, `ZMQ_HEARTBEAT_TIMEOUT`?

### ISSUE THREAD

**Issue by lovesh** [zeromq/pyzmq#990]
I can use some other socket options like `LINGER` by using `zmq.LINGER` but cannot use `zmq.HEARTBEAT_IVL` or `zmq.HEARTBEAT_TIMEOUT`, I see they are defined in `backend/cython/constants.pxi` but there is no numeric value defined for them in `include/zmq.h`? Is there any other way to use them except defining them in the header file and rebuilidng? Thanks

**Comment by minrk** [comment]
@lovesh what's `zmq.zmq_version()`? These options will only be defined if they are available in the currently linked version of libzmq.

**Comment by lovesh** [comment]
@minrk Its `4.1.6`

**Comment by minrk** [comment]
Those constants are part of a draft implementation only available on libzmq >= 4.2.

**Comment by bluca** [comment]
Just a note that those options are no longer draft, they are declared stable since 4.2.0

**Comment by minrk** [comment]
Thanks, @bluca!
