### ISSUE TITLE
Context.term hangs but Context.destroy does not

### ISSUE THREAD

**Issue by lovesh** [zeromq/pyzmq#991]
I have some sockets in a context and have a `LINGER` time of 5 ms. I have closed all the sockets. But when i call the `term` method on the context it blocks and the code does not move ahead. But when i call the `destroy` method the code does not block. And after calling destroy i can call term and the it does not block now. But `destroy` is deprecated in favour of `term` so i think i should not be using it. Any ideas what i am missing, i am on `pyzmq==16.0.2`.

**Comment by minrk** [comment]
Where do you see that context.destroy is deprecated? destroy closes sockets and then calls term. term just terminates the context, which will block until the sockets are closed. So if term is blocking, that means there are still open sockets somewhere waiting to be closed.

**Comment by lovesh** [comment]
@minrk But LINGER time is set to 5 ms, so in after 5 ms the term should not block even after there are pending sockets. And here it mentions that destroy is deprecated by zmq_ctx_term, http://api.zeromq.org/4-2:zmq-ctx-destroy. There is a code snippet that has 2 sockets, one acts as a listener and the other a sender, and if i dont close any of those sockets, then term hangs, but destroy does not

```
def test1():
    print('On zmq_version {}'.format(zmq.zmq_version()))
    print('On zmq.__version__ {}'.format(zmq.__version__))
    port = 8876
    ctx = zmq.Context.instance()
    sock1 = ctx.socket(zmq.ROUTER)
    sock1.setsockopt(zmq.LINGER, 1)
    sock1.bind('tcp://*:{}'.format(port))
    sock2 = ctx.socket(zmq.DEALER)
    sock2.setsockopt(zmq.LINGER, 1)
    sock2.connect('tcp://127.0.0.1:{}'.format(port))
    sock2.send(b'm_1')
    sock2.send(b'm_2')
    print(sock1.recv())
    print(sock1.recv())
    sock1.close()
    sock2.close()
    ctx.term()
    print('going down')

test1()
```
 
Now if i comment you any one of  `sock1.close()` or `sock2.close()`, `ctx.term()` will hang and you will not see `going down` printed. Here is my output,
```
On zmq_version 4.1.6
On zmq.__version__ 16.0.2
b'\x00k\x8bEg'
b'm_1'
going down
```

**Comment by minrk** [comment]
LINGER governs discarding messages after sockets are closed, not closing sockets. Term will always block until all sockets are closed.

**Comment by lovesh** [comment]
@minrk Thanks for the explanation, looks like i was missing closing a socket in my original code and since destroy is deprecated, i'll go find out which socket is not closed. Thanks again.

**Comment by lovesh** [comment]
I was creating new context in multiple objects in the same process so was getting the same context. So when i closed all sockets of the object and called context's `term`, it froze because there were other objects which had socket bound to the same context which were open. So for now i will take of closing the sockets and let the context termination be handled by the library

**Comment by minrk** [comment]
@lovesh where do you see that destroy is deprecated?

**Comment by lovesh** [comment]
http://api.zeromq.org/4-2:zmq-ctx-destroy

**Comment by minrk** [comment]
Ah, that's confusing. pyzmq added a destroy method before zeromq. It was added as a convenience method for closing sockets and terminating the context (it does more than just term). Then zeromq decided to add an alias for zmq_term as zmq_ctx_destroy, which does the exact same thing a term. The deprecated destroy is the alternate name for term in libzmq that has been reconsidered, but the pyzmq method is not deprecated.

I guess I should give the pyzmq method a new name (perhaps `Context.close_and_term()`).
