### ISSUE TITLE
asyncio.auth module not working

### ISSUE THREAD

**Issue by subiol** [zeromq/pyzmq#992]
I tried the asyncio authentication module and it would not work, no matter how many examples I followed. So I made a test run using the thread authenticator in a non asyncio test program and it worked as expected.

The only modification in both programs is using AsyncioAuthenticator for ThreadAuthenticator, the rest of the code I am using to set up passwords and activate is the same. When the asyncio authentication is activated the socket will not connect, no matter if the passwords are correct.

I have also tried using ThreadAuthenticator in the asyncio programs but when I combine an asyncio context with a ThreadAuthenticator I get error on initialization so I'm guessing they are not compatible.

So I am not 100% sure if the AsyncioAuthenticator needs some special configuration that I have not found in my examples or it is not working. I can provide the test code if it would help.

**Comment by minrk** [comment]
Sorry for missing this! I'm closing some stale issues. Feel free to open a new Issue if this still comes up, but I'm guessing the relevant asyncio loop wasn't running.
