### ISSUE TITLE
Need binary for python 2.5

### ISSUE THREAD

**Issue by francescpuig7** [zeromq/pyzmq#994]
I need help installing zmq in python 2.5. I see that since 2.1.x you have removed support for py25, but installing those previous versions gives problems. Even configuring the python setup.py configure --zmq=/lib/site-packages/zmq. I try with pip and with easy_install. Different versions, and also getting installers from: 
[ZeroMQ downloads](https://github.com/zeromq/pyzmq/downloads)
Please need if someone has the executable or msi for python 2.5

Thx!

**Comment by minrk** [comment]
Supporting Python 2.5 may be difficult, but if you download the source for the old version and install with `--zmq=/usr/local`, it should work. Note that it will require old libzmq as well (2.x, I believe).

**Comment by francescpuig7** [comment]
Thx!
