### ISSUE TITLE
poller.poll() no longer returns when interrupted by signal and restarts timeout

### ISSUE THREAD

**Issue by mrvn** [zeromq/pyzmq#996]
The code below polls for activity on a socket for 5 seconds and sets up an alarm to interrupt it after 1 second. What used to happen was that poller.poll() would raise zmq.AGAIN after the signal handler returned. With libzmq 4.2.2 and pyzmq 16.0.2 poller.poll() restarts the poll with the initial timeout. The effect of this is that poller.poll() will never timeout in this example.

    #!/usr/bin/python3

    import logging
    import signal
    import zmq

    # enable logging output
    numeric_log_level = getattr(logging, "INFO", None)
    logging.basicConfig(level=numeric_log_level)

    # set up a alarm heartbeat once a second
    def on_alarm(signalnum, frame):
        logging.info("on_alarm()")
        signal.alarm(1)
    signal.signal(signal.SIGALRM, on_alarm)
    signal.alarm(1)

    # create and connect socket
    ctx = zmq.Context()
    socket = ctx.socket(zmq.DEALER)
    socket.connect("inproc://test")
    poller = zmq.Poller()
    poller.register(socket, zmq.POLLIN)

    # poll socket for 5 seconds
    logging.info("polling for 5 seconds")
    poller.poll(5000);
    logging.info("polling done")

    # cleanup
    socket.close()
    ctx.destroy()

**Comment by mrvn** [comment]
Note: this makes it impossible to interrupt a poller.poll(-1) with a signal

**Comment by minrk** [comment]
> the timeout isn't honored which mightr cause timing problems in surrounding code

This is a bug in pyzmq, where the poll deadline is not updated when starting the retry.

> how to abort the poll early?

If you want a signal to trigger an exception, raise an Exception in the signal handler:

```python
def on_alarm(signalnum, frame):
    logging.info("on_alarm()")
    # on alarm, interrupt main
    raise KeyboardInterrupt()
```

Previously, it was impossible to register signal handlers that prevent interrupting zmq calls. Now it is possible, and the signal handler gets to decide if the zmq call should be interrupted - raise an Exception if one should be raised, don't if not. This makes zmq calls more similar to other Python calls.

**Comment by mrvn** [comment]
Yeah, I saw that (raising an exception in the signal handler) upon closer look at the pep-0475. Seems to work fine. So only computing the timeout on restart remains as actual issue.

Problem for me is that I still need to support python 3.2 for a little while and monotonic clock was only added in python 3.3. Makes it hard to work with timestamps for the timeout that don't break when ntp resets the time during boot.

There is a python monotonic module for python 2 and <3.3 that aliases to pythons monotonic for >= 3.3. Is that the way to go here?

**Comment by minrk** [comment]
Depending on an external C dependency probably isn't going to fly, especially for such a tiny thing. I'll make sure to handle the case where `end < start`, which should be good enough for legacy Python versions.
