### ISSUE TITLE
XPUB_WELCOME_MSG issue

### ISSUE THREAD

**Issue by geopars** [zeromq/pyzmq#998]
I have a problem setting up the XPUB_WELCOME_MSG option on a XPUB socket. The following line of code 
`self.socket_publisher.setsockopt(zmq.XPUB_WELCOME_MSG, b"Hello")`

returns AttributeError: module 'zmq' has no attribute 'XPUB_WELCOME_MSG'

I would appreciate any help!

**Comment by davidia** [comment]
I've also ran into this problem. Can anyone shed some light on how to fix this?

**Comment by guidog** [comment]
This option is new in libzmq 4.2, the libzmq deployed w/ pyzmq 16.0.2 is 4.1.6. Seems you have to change the underlying libzmq for your needs.
